### ISSUE TITLE
Investigate handling currencies with 0 or 3 decimal places

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1012]
Currently, all prices are stored using two decimal places. When handling tax, quantization is currently set to two decimal places as well. We should investigate if we can better support for currencies that have 0 or 3 decimal places.

Was spotted in #994.

**Comment by mbertheau** [comment]
I think we can just use 8 decimal places in the database everywhere and display and calculate with less than that depending on the currency.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
