### ISSUE TITLE
Bootstrap 3 Migration

### ISSUE THREAD

**Issue by timjacobi** [django-oscar/django-oscar#1014]
I would like to read some opinions about whether migrating to Bootstrap 3 is something we should have a look into. Also if you have any interesting links that cover the topic please post them here.

Here are some links to start with
- [Bootstrap 3 for IE7 (Beta)](https://github.com/coliff/bootstrap-ie7)
- [Bootstrap 3 migration guide](http://bootply.com/bootstrap-3-migration-guide)
- [Bootstrap 3 Showcase](http://lovebootstrap.com/)

**Comment by mvantellingen** [comment]
Both the frontend and backend are now using bootstrap 3.2.0. So I'll close this then :-)
