### ISSUE TITLE
Drop IE7 support

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1032]
This ticket serves as a collection of libraries we've kept at non-current versions to keep IE7 support. IE7 is at <0.5% worldwide usage now and should be dropped for 0.7.

- Bootstrap (#1014)?
- Select2 (#1026)

Not sure about:
- jQuery?
- WYSIWYG editor
- What else?

**Comment by mvantellingen** [comment]
Closing since we already switched to bootstrap 3
