### ISSUE TITLE
Allow custom rendering of product classes in basket

### ISSUE THREAD

**Issue by izidormatusov** [django-oscar/django-oscar#1038]
At the moment Oscar allows overriding product detail pages for different product clases (Product page for a book can look completely differently than a page for clothes)

We're missing similar feature for rendering basket lines. It is especially important when you have a product with line options:

![2013-12-02_11 02 33](https://f.cloud.github.com/assets/98588/1654010/b59d85fa-5b41-11e3-84da-1ab2f4a9b35e.png)

Make it easy to create custom basket line rendering.

**Comment by sasha0** [comment]
That would be actually, custom basket line formset rendering, since each row is the form.

I'm uncertain in feasibility of this and didn't have necessity to customize this on my projects. WDYT @solarissmoke @craigloftus @mvantellingen ?

**Comment by craigloftus** [comment]
This isn't something we have done, but I can see the use case and I do think it is feasible.

The forms are rendered 'manually' in the template at the moment, and we have the information in the context to swap out partials based on the class, so it could be done; perhaps with a template tag or a method on the line and then just an `{% include %}`.

I think its a case of "PRs welcome" though?

**Comment by sasha0** [comment]
Right, but the case is more than 4 years old and PR is not likely to be provided considering lack of activity around the issue and the fact is has not been submitted until now.

We haven't done this on our projects as well - but rather built the whole basket management within the reactive UI and API.

**Comment by specialunderwear** [comment]
fixed in #3795
