### ISSUE TITLE
Use a custom StockInfo class for variants

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1085]
As noted in #481, it might be better to have a custom `StockInfo` class for variants that includes the min and max price of an item.

Some research required...

**Comment by sasha0** [comment]
It indeed will allow to indicate variant prices appropriately. WDYT @django-oscar/core ?

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
