### ISSUE TITLE
Rethink handling of category slugs/full_name fields 

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1119]
full_name and slug, respectively and can quickly hit the limit of 255
characters. Increasing the limit beyond that is not really feasible, at
least with MySQL.
#929 reported this and attempted a fix by increasing the limit beyond 255 chars, but that breaks with MySQL. The limit is somewhere around 760 bytes, but as with Unicode we never actually know how many bytes are consumed, we can't considerably increase beyond 255 chars.

I've also attempted moving to TextFields, but similar issues crop up; MySQL can't have an index on TextFields even with a max_length set: http://stackoverflow.com/questions/11129309/how-do-i-specify-an-index-for-a-textfield-in-django-with-a-mysql-backend

As we're thinking about how to translate category URLs, this should be given a proper think for a good solution.

**Comment by specialunderwear** [comment]
this was solved in #1674
