### ISSUE TITLE
Review splitting user's names & title choices

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1135]
Assumptions about names and being able to split them into a first name and last name quickly fall apart outside of English speaking countries. [[1]](http://www.w3.org/International/questions/qa-personal-names) [[2]](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)

Personally, I'd make a case for doing the right thing and having our `AbstractUser` defaulting to a reasonably long name field.

I'd also like to review our use of the "treatment pronouns" and see if they can be made more inclusive, and configurable via a setting.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
