### ISSUE TITLE
Provide an easy way to disable the wishlists feature

### ISSUE THREAD

**Issue by c00lz3r0** [django-oscar/django-oscar#1143]
This is along the lines of https://github.com/tangentlabs/django-oscar/pull/673

It appears that the work for wishlists was not done during the work stream above. As https://github.com/tangentlabs/django-oscar/blob/master/oscar/defaults.py#L86 suggests that this is supportted and it would indeed be a very nice feature, I'm documenting it here.

**Comment by sasha0** [comment]
@c00lz3r0 @maikhoepfel Done, PR #1782.

**Comment by LennyLip** [comment]
But how do disable wish list? Does not found in settings http://django-oscar.readthedocs.io/en/latest/ref/settings.html

**Comment by slav0nic** [comment]
@LennyLip https://github.com/django-oscar/django-oscar/blob/739ab701789de3baae45ac0ed9eb0627b14be941/src/oscar/defaults.py#L95

**Comment by sasha0** [comment]
Closing, since it's already available to disable wishlists by the `OSCAR_HIDDEN_FEATURES` setting.

**Comment by SalahAdDin** [comment]
@sasha0, thiese option isn't in the official documentation.

**Comment by sasha0** [comment]
Yes, but this already logged into another issue #2194.
