### ISSUE TITLE
Improvements to shipping

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1147]
There are various things that need attention within the shipping app. :ship
- The `OrderAndItemCharges` model should be deprecated and removed.  It doesn't handle tax in a flexible way and is quite specific to how the UK and AU operates.  The class also charges if all items in the basket don't require shipping.
- Is `NoShippingRequired` really required? Seems a bit hacky to me.
- Rework shipping methods to be thread safe. This will require using a template tag to pass the basket in for calculation
- Can we rework the shipping method view in checkout to use a form so we can get validation out of the view? (#808)
- Add a dashboard for the weight-based shipping method.

Related tickets: #812, #1043, #1158, #1198

:shipit: :shipit: :shipit:

**Comment by sasha0** [comment]
> The OrderAndItemCharges model should be deprecated and removed. It doesn't handle tax in a flexible way and is quite specific to how the UK and AU operates. The class also charges if all items in the basket don't require shipping.

Perhaps we can distinguish prices fields into tax-exclusive and tax-inclusive fields, but we certainly should not deprecate and remove it.

> Is NoShippingRequired really required? Seems a bit hacky to me.

Yes, has served well so far. I don't see enough reasons to revise.

> Rework shipping methods to be thread safe. This will require using a template tag to pass the basket in for calculation

Addressed in terms of #812.

> Can we rework the shipping method view in checkout to use a form so we can get validation out of the view?

To be addressed in the task #808.

> Add a dashboard for the weight-based shipping method.

Already implemented.

**Comment by sasha0** [comment]
As per comment above, all should has been already addressed.
