### ISSUE TITLE
Sensibly handle attribute values of type image, file, date

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1152]
#1132 and #1149 raised the issue that handling of Rich Text attributes is lacking. While this is being fixed right now, we should add sensible defaults for the other more exotic attribute values. This means adding `$type_as_html` and `$type_as_text` properties on `AbstractProductAttributeValue`.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
