### ISSUE TITLE
Allow easy adding of shipping details (e.g. preferred shipping date and time) page to checkout process

### ISSUE THREAD

**Issue by zuck** [django-oscar/django-oscar#1158]
In my store, I don't want to skip the shipping method selection page when only one shipping method is available.

The reason is that I want to render a form where the user should insert more details about shipping method (i.e. preferred shipping date and time).

This is currently possible, but requires too much hacking in custom views, because the skip policy is hard-coded in core **checkout.views.ShippingMethodView.get** method.

I see two ways:
1. Provide a **"should_skip_shipping_method_selection"** method which could be overridden in custom views.
2. Add a settings flag which could be disabled.

The first one, I think, is the best one because allows much more customization.

(Title originally was: Skipping shipping method page when there's only one method should be optional)

**Comment by mbertheau** [comment]
This should be relatively straightforward with #1423.

**Comment by sasha0** [comment]
I think more consistent improvement could be to move conditions application to the methods, which would allow to override them, as 1) suggests.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
