### ISSUE TITLE
Improve ValidationError wording for product attributes

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1165]
https://github.com/tangentlabs/django-oscar/blob/master/oscar/apps/catalogue/abstract_models.py#L790 and https://github.com/tangentlabs/django-oscar/blob/master/oscar/apps/catalogue/abstract_models.py#L793 are probably hard to understand for the general public.

**Comment by sasha0** [comment]
All `ValidationError` messages looks clear now. Closing.
