### ISSUE TITLE
Review use of GET parameters outside of form handling

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1195]
#1181 alerted me to the fact that there's a few places in Oscar where we pass around GET parameters without validation, mostly to do sorting of things.

While #1181 has no security implications, I think it's not a very good practice. Personally, I think they belong should be processed by Django forms if at all possible.

Other examples helpfully collected by @mbertheau include
- https://github.com/tangentlabs/django-oscar/blob/master/oscar/templates/oscar/dashboard/catalogue/product_list.html#L128
- https://github.com/tangentlabs/django-oscar/blob/master/oscar/templates/oscar/dashboard/catalogue/product_update.html#L32

**Comment by sasha0** [comment]
Second one was brought by PR #507 and I currently don't see reason why we should keep it - product update view does not accept GET params. Although it allows to redirect with provided params.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
