### ISSUE TITLE
Possible race condition when submitting basket at same time

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1198]
The `build_submission` method in the `PaymentDetails` view loads a shipping method in order to calculate the order total.  It's possible for the `get_shipping_method` to return `None` if two identical submissions are submitted at the same time.  This leads to a 500 as the shipping method has been removed from the session by the first submission.

We need a little more checking within the checkout submission process.

**Comment by daniel-butler** [comment]
It looks like this was accidentally reopened. In the merged PR `shipping_method` is checked for `None`

This is the closest link I could grab. The check is at line 171 https://github.com/django-oscar/django-oscar/blob/a63c7a7a7e8b4ab175fa918b6c53efde5b1861e7/oscar/apps/checkout/session.py

**Comment by specialunderwear** [comment]
closing because this was fixed according to @daniel-butler
