### ISSUE TITLE
Can't browse product range that includes categories or product classes

### ISSUE THREAD

**Issue by grakic** [django-oscar/django-oscar#1219]
Create a new product range including some categories and set this range to public. Try browsing it, no products are shown.

The issue is caused by using only Range.included_products to create a queryset while the Range can be defined using included_categories.

Included product classes and exclusion are also not supported but that can be a non-issue as there are no dashboard forms to create such ranges.

This also affects conditional offers.

There should probably be a new products() method in the Range class, following the contains(), that returns queryset with all products in the range.

Checking for OSCAR_OFFER_BLACKLIST_PRODUCT should be moved to conditional offer just like is_discounted filter, as products listed in OSCAR_OFFER_BLACKLIST_PRODUCT can belong to a range but can not have offers applied.

**Comment by sasha0** [comment]
Should has already fixed by e5ab94012c3b99a67e2f44ac195a7257cb9c0335 and `OSCAR_OFFER_BLACKLIST_PRODUCT` setting already removed.
