### ISSUE TITLE
Fresh install of oscar fails in Err 500 

### ISSUE THREAD

**Issue by alex-leonhardt** [django-oscar/django-oscar#1226]
Hi,

I did the manual install of django-oscar today and I got to the point of getting into the django /admin/ interface, however, when i just go "/" - i get this : 
# Error

Request Method: GET
Request URL: http://localhost:8000/

Django Version: 1.6.2
Python Version: 2.6.6
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.flatpages',
 'django.contrib.admin',
 'south',
 'compressor',
 'oscar',
 'oscar.apps.analytics',
 'oscar.apps.checkout',
 'oscar.apps.address',
 'oscar.apps.shipping',
 'oscar.apps.catalogue',
 'oscar.apps.catalogue.reviews',
 'oscar.apps.partner',
 'oscar.apps.basket',
 'oscar.apps.payment',
 'oscar.apps.offer',
 'oscar.apps.order',
 'oscar.apps.customer',
 'oscar.apps.promotions',
 'oscar.apps.search',
 'oscar.apps.voucher',
 'oscar.apps.wishlists',
 'oscar.apps.dashboard',
 'oscar.apps.dashboard.reports',
 'oscar.apps.dashboard.users',
 'oscar.apps.dashboard.orders',
 'oscar.apps.dashboard.promotions',
 'oscar.apps.dashboard.catalogue',
 'oscar.apps.dashboard.offers',
 'oscar.apps.dashboard.partners',
 'oscar.apps.dashboard.pages',
 'oscar.apps.dashboard.ranges',
 'oscar.apps.dashboard.reviews',
 'oscar.apps.dashboard.vouchers',
 'oscar.apps.dashboard.communications',
 'haystack',
 'treebeard',
 'sorl.thumbnail']
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware')

Template error:
In template #removed#/oscar/lib/python2.6/site-packages/oscar/templates/oscar/partials/mini_basket.html, error at line 10
   (Could not get exception message)
# Error Line

   10 :          {{ request.basket.total_excl_tax|currency:request.basket.currency }} 
# Trace

File "#removed#/oscar/lib/python2.6/site-packages/django/template/debug.py" in render
1.             output = self.filter_expression.resolve(context)
   File "#removed#/oscar/lib/python2.6/site-packages/django/template/base.py" in resolve
2.                     arg_vals.append(arg.resolve(context))
   File "#removed#/oscar/lib/python2.6/site-packages/django/template/base.py" in resolve
3.             value = self._resolve_lookup(context)
   File "#removed#/oscar/lib/python2.6/site-packages/django/template/base.py" in _resolve_lookup
4.                                                        (bit, current))  # missing attribute

Exception Type: VariableDoesNotExist at /
Exception Value: Failed lookup for key [basket] in u"<WSGIRequest\npath:/,\nGET:<QueryDict: {}>,\nPOST:<QueryDict: {}>,\nCOOKIES:{'csrftoken': 'rI07EEFoy5u6Z4O1yS8l1mr4duBuJA1Q',\n 'org.cups.sid': '6fabde3497ea232a1b3daea3dfd9089d',\n 'sessionid':

**Comment by pouemo** [comment]
Thanks
