### ISSUE TITLE
Order status and line status can't be translated

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1232]
The status pipelines relies on strings to work. I just marked them translatable, but got an import error for that file - I presume marked strings can't be used as dictionary keys. That makes it hard to translate the order status and line status.

**Comment by sasha0** [comment]
@maikhoepfel @mvantellingen done in PR #1783

**Comment by sasha0** [comment]
We decided to try `django-fsm` as proper solution for the issue.

**Comment by Arussil** [comment]
Are there some news on this issue?

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
