### ISSUE TITLE
Translation: Double strings are created with the only difference being a single upper or lowercase letter

### ISSUE THREAD

**Issue by renemulder** [django-oscar/django-oscar#1240]
In my translation file there are multiple examples of strings that factually communicate the same, but only differ in the use of upper and lower case. I don't know if this is a design choice, but it makes for a lot of duplicate strings. I can see the point of varying between upper and lower case for the first word in the string, but in a lot of strings this is not the case.

Examples:
- Email Address
- Email address
- Date Uploaded
- Date uploaded
- Date created
- Date Created
  (Actually also has a variant 'Date of creation', which is pretty much saying the same thing)
- Save for Later
- Save for later
- Payment Events
- Payment events

I guess a lot of these can be cleaned up? It is also something to keep in mind with future strings.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
