### ISSUE TITLE
First page of checkout process could be avoided to increase conversions

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1244]
Currently, the gateway page (anonymous checkout vs logging in vs registering) is the first thing that the users sees when checking out. It's a difficult question that will have an impact on conversions. We really should just ask for the email address together with the shipping address, and then maybe provide helpful hints if a customer already has that email address. 

Needs more spec'ing, but added as an issue to keep track of it.

**Comment by DmytroLitvinov** [comment]
Hey @maikhoepfel 

I think we can add something like `OSCAR_OMIT_GATEWAY_ORDERING_PAGE` and inside IndexView in `get` method add checking for this variable and redirect to success URL.

What do you think?

**Comment by maikhoepfel** [comment]
Hey @DmytroLitvino If I'm not mistaken, we can't just simply omit the gateway page - we'd still need to handle both guest and registered accounts. But please discuss this with the current maintainers - I'm  I'm afraid I currently don't have time to work much on Oscar.

**Comment by sasha0** [comment]
> Hey @DmytroLitvino If I'm not mistaken, we can't just simply omit the gateway page - we'd still need to handle both guest and registered accounts.

Indeed we can't.

I personally don't think there's both proper and modern solution, based on the merging all checkout forms/views/templates into the one.

**Comment by DmytroLitvinov** [comment]
Yeah, during the internal work, found that it will be not easy.
So everyone depends on their project could remove it.
Thanks for reply

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
