### ISSUE TITLE
Allow product attributes to be customised

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1290]
Re https://groups.google.com/d/msgid/django-oscar/687fcc5c-6b62-4a50-9089-9bc597983c3d%40googlegroups.com

We should investigate making it easier to customise product attributes. Eg adding new field types - that kind of thing.

**Comment by michaelkuty** [comment]
+ 1
For example now I want to make some attributes hidden etc..

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
