### ISSUE TITLE
Please copy/symlink the 'missing image' image

### ISSUE THREAD

**Issue by natea** [django-oscar/django-oscar#1314]
when I try to deploy an Oscar-based site to Heroku, I get this error:

```
Please copy/symlink the 'missing image' image at /app/slstore/slstore/public/media/image_not_found.jpg into your MEDIA_ROOT at /app/slstore/slstore/public/media. This exception was raised because Oscar was unable to symlink it for you.
```

I would think that running the collectstatic command would create the public and media dirs and put this file in the media dir. Is that not the case?

**Comment by davidmarquis** [comment]
I confirm @rayrrr 's solution works with S3. Thanks!

**Comment by TarasTarasTaras** [comment]
@rayrrr Thanks!

**Comment by Dihfahsih1** [comment]
@rayrrr  your answer was on absolute help to fixing that bug in my code. Thanks

**Comment by omoz01** [comment]
Thank you @rayrrr for the solution
