### ISSUE TITLE
Allow user basket to be accessed via cookie

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1317]
At the moment, when a user logs in, we remove their basket cookie and tie their basket to their user ID, meaning they can only access it when the sign in. A more sophisticated approach would be to allow a user to keep their basket cookie so that if they return to the site and they're not logged in, they still have access to their basket and signing in will not change the basket.

This would be a better experience for the customer and prevent surprises when they sign in and their basket gets merged with an older one.

**Comment by sasha0** [comment]
I think if we introduce settings which will allow to enable/disable baskets merge in the middleware, this might improve user experience. WDYT @django-oscar/core ?

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
