### ISSUE TITLE
Add a cached basket middleware

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1329]
V0.8 of Oscar will have a slightly modified basket middleware that allows the basket hash to be computed lazily. This provides the hook to write cached basket middleware. It's mildly tricky as you need to serialise the basket, lines and discounts (which Django's cache framework won't do automatically) and then deserialise into instantiated objects.

Here's a skeleton:

``` python
class CachedBasketMiddleware(BasketMiddleware):

    def process_request(self, request):
        key = request.basket_hash

        super(CachedBasketMiddleware, self).process_request(request)

        def load_cached_basket():    
            basket_data = cache.get(key)
            if basket_data is None:
                # TODO: serialise basket into format that can be cached
                basket_data = self.serialize(request.uncached_basket)
                cache.set(key, basket_data)
                basket = request.uncached_basket
            else:
                # TODO: deserialise basket
                basket = self.deserialize(basket_data)
            return basket

        # Replace basket attribute with cached loader
        request.uncached_basket = request.basket
        request.basket = SimpleLazyObject(load_cached_basket)

        # TODO If POST, then flush cache
```

We'll also need a global basket cache flush that can be called from offline processes.

**Comment by sasha0** [comment]
In general, it could be feasible performance improvement, although I can see several complex and tricky parts, except serialization/deserialization - discount applications, a lot of places of basket lines queryset related code etc.
