### ISSUE TITLE
Applying multiple benefits per basket line

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1398]
(#1414 is the corresponding PR)
## Requirements

We need multiple benefits per basket line for our implementation. Two offers we want to combine are:
1. a usually time-based offer like "If Germany wins, next day 15% off all products"
2. a custom offer where every user gets a 50% discount up to 150 Euros per year paid by his employer

On our site it is so common that people buy only quantity 1 of one product that we will skip the UI
part of the basket functionality. Both offers should apply to the same product. For example if a
product costs 100 Euros and Germany won yesterday (which it did!) the first offer is active and the
price is 85 Euros. Then the other offer applies and the user gets a discount of 50% on the remaining
price. The end price is then 42,50 Euros.
### Additional requirements
- https://groups.google.com/d/msg/django-oscar/83-KLHQwSfE/CQkgQvzxwU0J
- https://groups.google.com/forum/#!topic/django-oscar/wQLsQqK-qF8
## Current situation in Oscar

To implement offers oscar has the concept of conditions and benefits. An example condition is "buy
two products from category A". An example benefit is "get 50% off a product from category B".

Oscar takes care to consume the products mentioned in the condition and in the benefit so that
1. the same two products from category A don't allow a discount for a second product from category B
2. the two products from category A can't be discounted
3. the same product from category B that was discounted cannot be discounted again
4. the product from category B cannot be used as a condition for another benefit

It does so by using `Line._affected_quantity` to track what quantity of the line was used in
conditions (`Line.consume()`) or benefits (`Line.discount()`). Both methods use the same counter.

When testing a condition oscar looks in the basket whether there are lines that weren't used in
another condition or discounted by a benefit by comparing `Line.quantity` and
`Line._affected_quantity`.
### Shortcomings
- Mixing the tracking of condition-consumed and benefit-consumed items leads to problems such as
  https://groups.google.com/forum/#!topic/django-oscar/vceEpy889O4.
- `CountCondition` and `CoverageCondition` consume lines inconsistently. `CountCondition` discards
  lines with a zero price, `CoverageCondition` does not.
## The plan

In order to fix the shortcomings of the current implementation and also realize the new requirements
I intend to
1. (Refactoring) Separately track which line items were used in which condition and which were used
   in which benefit. Details on semantics below.
   1. Use an extra data structure instead of basket lines to track that (anticipating
      https://groups.google.com/forum/#!topic/django-oscar/nr5QFw5tPII).
   2. Don't use lines that were used in a condition or in a benefit to satisfy another condition.
   3. Don't use lines that were used in a condition or in a benefit for another benefit.
   4. `CountCondition`: mark random N items from the range
   5. `CoverageCondition`: mark a quantity of one for random N items from the range
   6. `ValueCondition`: mark random items from the range in increments of quantity one until the
      condition value has been reached or surpassed
   7. Benefits mark all items that have received a discount
   8. Remove tracking infrastructure from `Line`.
2. (Feature) Support multiple benefits per line
   1. Add a field `conflicts_with_other_benefits` (better naming ideas very welcome!) to Benefit with
      default True.
   2. When looking for lines a benefit can be applied to make sure that for every line there is at
      most one benefit with `conflicts_with_other_benefits == True`.
   3. Benefits to the same line are applied in order on descending priority of their
      `ConditionalOffer` according to the following rules:
      1. Percentage benefits are calculated from the resulting discounted price of
         any earlier benefits.
      2. A fixed price benefit is applied if it results in a lower price than the
         resulting discounted price of any earlier benefits.
      3. Multibuy benefits result in a discounted price of 0.
3. (Feature) Apply offers in order of desecending `ConditionalOffer.priority`.
### Open questions
1. Can products with `is_discountable == False` be used to satisfy offer conditions? Currently they cannot, but maybe they should.
## The revised plan

The original plan turned out to be too time-consuming given that we require only percentage benefits and no conditions. I followed the revised plan instead:
1. Rip out all conditions and all benefits except for `PercentageDiscountBenefit` and add `NoneCondition`.
2. (Refactoring) Separately track which line items were used in which benefit. Details on semantics below.
   1. Use an extra data structure instead of basket lines to track that (anticipating
      https://groups.google.com/forum/#!topic/django-oscar/nr5QFw5tPII).
   2. Don't use lines that were used in a benefit for another benefit.
   3. Benefits mark all items that have received a discount
   4. Remove tracking infrastructure from `Line`.
3. (Feature) Support multiple benefits per line
   1. Add a field `can_apply_with_other_benefits` (better naming ideas very welcome!) to Benefit with
      default `False`.
   2. When looking for lines a benefit can be applied to make sure that for every line there is at
      most one benefit with `can_apply_with_other_benefits == False`.
   3. Benefits to the same line are applied in order on descending priority of their
      `ConditionalOffer` according to the following rules:
      1. Percentage benefits are calculated from the resulting discounted price of
         any earlier benefits.
4. (Feature) Apply offers in order of desecending `ConditionalOffer.priority`.

(I cross-posted this to the mailing list at
https://groups.google.com/forum/#!topic/django-oscar/83-KLHQwSfE. I use this issue to keep track of
the latest discussion outcome.)

**Comment by solarissmoke** [comment]
I think the use case described here is addressed in #2410, so am closing this. If there is additional functionality that is missing then we can address it separately.
