### ISSUE TITLE
Sorry its sold - basket messages - improve user experience

### ISSUE THREAD

**Issue by michaelhjulskov** [django-oscar/django-oscar#1404]
example :
if you have 2 x mountainbike in basket and they are sold to someone else, you'll discover this at the checkout.

I'd like Oscar to 
1. warn the customer earlier in the process (as soon as possible)
2. say something user friendly like "Oops! We just sold the last mountainbike to someone else, so unfortunately we had to remove it from Your basket. Please forgive us! Maybe You'd like to sign up and get an alert when its back in stock, or take a look at these alternative products." (alternative products could be a link to other variants of mountainbike, or a link to the mountainbikes category)

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.
