### ISSUE TITLE
Drop jQuery UI and jquery-ui-datepicker

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1462]
#1457 replaced the dashboard's datetimepicker with a much nicer Bootstrap-themed one. While reviewing that, I realised that the customer order list page in the frontend also uses the replaced ``jquery-ui-datepicker``. If I'm not mistaken, that is also the only reason we keep the ``jquery-mousewheel`` and jQuery UI dependencies. 

We should move the order list page to use the new datetime picker, and drop all unneeded dependencies.

**Comment by sasha0** [comment]
@maikhoepfel `jquery-mousewheel` being used by new datetimepicker and `select2` plugin.
