### ISSUE TITLE
Use proper search in dashboard product list

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#1463]
This is a leftover of #693. We should use the search backend to perform searches in the dashboard product list, instead of `_icontains` hacks.

**Comment by sasha0** [comment]
Not necessarily to replicate frontend search, but rather implement dashboard full-text search backend for products and orders. I implemented similar backend on one of the projects and it worked pretty conveniently. WDYT @solarissmoke?

**Comment by solarissmoke** [comment]
I definitely think we need to use the search backend for the dashboard - `icontains` has its limitations and becomes unwieldy and slow for large catalogues. We should look at this as part of the search refactoring and decide whether a separate backend is required for the dashboard.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.
