### ISSUE TITLE
Forking "partners" dashboard app without replacing "partner" base app

### ISSUE THREAD

**Issue by zuck** [django-oscar/django-oscar#1473]
It seems replacing/forking the **oscar.apps.dashboard.partners** dashboard app without also replacing its "base" app (**oscar.apps.partner**) is not possible at the moment, due to an issue with custom permission creation (_dashboard_access_).

A simple way to reproduce the bug is the following:
- Fork Oscar's default "partners" dashboard app.
- Replace it in INSTALLED_APPS: e.g. "my.apps.dashboard.partners"
- Sync the DB and launch the server.
- Go to _Fullfilment > Partners > partner_name > Link existing user_
- Try to link a user.

An error regarding the absence of "**partner.dashboard_access**" permission will be raised.

BUT, if you replace ALSO the base "partner" app (e.g. "my.apps.partner"), simply including the standard Oscar's models ("from oscar.apps.partner.models import *") the problem goes away.

**Comment by sasha0** [comment]
Does not seem to occur any more - `dashboard_access` custom permission is listed in the `Partner` model meta, thus created on initial migrations run.
