### ISSUE TITLE
Switch from excluding to explicitly including form fields in ModelForms

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1499]
It's [discouraged](https://docs.djangoproject.com/en/dev/topics/forms/modelforms/#selecting-the-fields-to-use) to use ``exclude = `` instead of explicitly including available fields in ModelForms. Especially in Oscar we should always use the explicit white-listing approach, because a custom deployment might override the model and inadvertently make a new field available.

We have been switching to the preferred syntax when we stumbled upon the old syntax. But it just caused an issue in my work, and there's not many forms left, so let's get that sorted by switching to the white-list syntax with ``fields = ``.

**Comment by mvantellingen** [comment]
Implemented in PR #1682

**Comment by maikhoepfel** [comment]
PR is merged.
