### ISSUE TITLE
FED house-keeping

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1505]
This is a bucket ticket to capture a load of minor FED issues.
### Catalogue browsing pages

Too much whitespace around facet boxes

![image](https://cloud.githubusercontent.com/assets/80975/4504960/8544cda4-4aed-11e4-8460-282573a3d869.png)

Prices and availability messages don't line up

![image](https://cloud.githubusercontent.com/assets/80975/4504965/a1ab23b2-4aed-11e4-83e8-f0c22f05d435.png)

Needs a little footer (or some gray space) at the bottom of the page:

![image](https://cloud.githubusercontent.com/assets/80975/4504983/d5e41c74-4aed-11e4-9453-32ce2003a45a.png)
### Basket page

I think the totals need to be much bigger. There's also a wide mix of font sizes and weights that could be simplified.

![image](https://cloud.githubusercontent.com/assets/80975/4505017/71c2747e-4aee-11e4-94da-7ff3b9ad4484.png)
### Address book in checkout

Long addresses clash with select button

![image](https://cloud.githubusercontent.com/assets/80975/4544474/946b7604-4e33-11e4-938d-9a4bc5e0b099.png)
### Default forms have text inputs and textareas which aren't the right size

Eg, the review form:

![image](https://cloud.githubusercontent.com/assets/80975/4545315/f7fe8660-4e39-11e4-8e03-569ecb9a4394.png)

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.
