### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1506]
The responsiveness of some pages needs some work.
### Catalogue browsing pages

The "browse store" dropdown doesn't seem very touch-screen friendly (as it uses hover effects)

![image](https://cloud.githubusercontent.com/assets/80975/4505050/13819e52-4aef-11e4-97a3-5b3100bf3069.png)

The rendering of a product could do with being improved. Seems like some things need centre justification.

![image](https://cloud.githubusercontent.com/assets/80975/4505053/1d13e39e-4aef-11e4-9b74-ca7d9392fedb.png)
### Basket page

The basket line rendering is a little odd in narrow viewports

![image](https://cloud.githubusercontent.com/assets/80975/4505059/442fa300-4aef-11e4-80ee-fc1cebcf5e62.png)

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.
