### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1514]
# Motivation
We try to specify version ranges, to not force our users onto a certain version of a library. But frequently enough, we need to limit those versions any way because we need a certain version, or even a specific fork. That forces a user to use that version as well.

# Idea
We should copy Django's approach and vendor the libraries. E.g. ``oscar.vendors.`` namespace (Django mostly uses ``django.utils``, but has non-vendored libraries in there as well). 

# Problems
- Does this even work for libraries that need to be part of ``INSTALLED_APPS``? I'm thinking static files, template tags, etc.
- How would we manage updates, etc.? Would we include the entire repo with ``git subtree`` or suchlike, or have a process to include the Python package?
- How would we handle licences? Where would we display them?

**Comment by mvantellingen** [comment]
Closing for now. The situation is much better these days and vendoring leads to extra maintenance.
