### ISSUE TITLE
Allow prices to vary according to product options

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1515]
This is common in the world of print where there's a load of options that go with each product. For example:
- Paper type
- Print quantity (eg box of 100)
- Lamination

Each combination can have a different price. 

Oscar needs a change to the strategy interface to allow this as the options aren't passed around at the moment. Here's one place to change:
https://github.com/tangentlabs/django-oscar/blob/master/oscar/apps/basket/abstract_models.py#L176

**Comment by mvantellingen** [comment]
This is something we also need for most projects. Currently we keep re-implemeting it in each project so I would like to work getting this in Oscar.

We have the following requirements:
 - Options which have the same price for all products
 - Options which have a different price per product (e.g. an installation fee).

We currently achieve this by setting a default price on the Option model and create a separate model (`OptionPrice`) which overrides the default price for a specific option/product combination.

The selected options are then passed to Strategy.fetch_for_product() where the strategy can calculate the combined price. 

This doesn't allow a different option price per partner or a stock for an option, but this can be achieved the same way I believe.

Let me know if this is something we would like to see in Oscar.

**Comment by qnub** [comment]
Extremely required function. Must use LFS instead Oscar because of that :(

**Comment by jlmadurga** [comment]
For customizable products with multiple Options is extremely useful.

**Comment by maikhoepfel** [comment]
@mvantellingen definitely would like to see this. I think it requires careful redesign of the Strategy interface. If you get the time, please grab us for discussing the interface changes before submitting a PR.

**Comment by mvantellingen** [comment]
So I think we can first implement some relative simple changes to the Strategy interface which allows varying prices based on the selected options. In a later phase we can extend this based on experiences learned.

The idea is to pass a dict with the selected options to the `pricing_policy` and `parent_pricing_policy` methods. This requires us to also add the options to the `fetch_for_product` method.

The dict can be as simple as:

```python
options = [
    {
        'code': 'my_option',
        'value': 'my option value',
    },
]
```

**Comment by johnmckown** [comment]
We are going to be looking into upgrading our ecommerc system from ColdFusion to Django. Basically re-writing it. This feature (option-based price deltas) is critical. We solved this a decade ago, but we would be looking for similar functionality from Oscar if it is to be taken seriously as an ecommerce solution. 
Imagine selling an Apple Watch, where the band that select changes the overall price - very common scenario.
Here is how we handled it in our legacy platform: 

![screen shot 2015-05-23 at 1 27 29 pm](https://cloud.githubusercontent.com/assets/12212119/7785498/8be7f60e-014f-11e5-8779-70ec4d25de45.png)

**Comment by lionaneesh** [comment]
Is there any documentation on how to do this yet?

**Comment by msalahz** [comment]
Any updates ?

**Comment by AlexDev1** [comment]
Good day!
Has anyone implemented this?
How can I set the price for an Option?

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have open PR's attached.

**Comment by piyushjoshi1016** [comment]
I am new to Django-Oscar. I am trying to achieve the exactly the following. And as this discussion is quite old and seems like the solution is already merged with Oscar, But I could not find any way to set the price varying as per the options selection. Can anyone please help?

This is common in the world of print where there's a load of options that go with each product. For example:

    Paper type
    Print quantity (eg box of 100)
    Lamination

Each combination can have a different price.
