### ISSUE TITLE
Allow checkout to place multiple orders from the same basket

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#1519]
Re: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/django-oscar/Hk-xtz6Yzw8/VDRdwmV0iY8J

Oscar currently assumes that submitting a basket only leads to one order. We can change this assumption by re-working the checkout slightly and perhaps changing how orders and payments are modelled.

**Comment by seyannselasie** [comment]
Any updates on this aspect? In the meantime, how are current implementations finding solid  workarounds so far?

Thanks.

**Comment by sasha0** [comment]
As per the topic above from the mailing list, purpose of the change is to customize Oscar into multi-vendor marketplace.

After implementing few similar projects I should admit that this is not achievable with this slight change and requires in any case, to alter Oscar architecture significantly (baskets, checkout, payments etc). For the generic shops this change might not be very useful as well.

Facilitation of the per-partner checkout process implementation is outside of the scope of this task, so as soon we ready to start to move in this direction, we can open a new one.
