### ISSUE TITLE
Customizable Products with Catalogue.Options

### ISSUE THREAD

**Issue by jlmadurga** [django-oscar/django-oscar#1527]
This functionality is focused in adding  not only CharField  _Catalogue.Options_ to Products. This is a key functionality for shops selling customizable Products.
In order to fulfill this requirement just follow the schema and the idea of _ProductAttributes_ which only defines the type of the field and then other instance _ProductAttributeValue_ handles the value. Forms generates fields dynamically (_dashboard/catalogue/forms:ProductForm_)

My proposal:
- catalogue:
  - abstract_models: _AbstractOption_ modify type attr to chose the type of field add required attr to handle actual required/not_required choice field 
- basket
  - forms: _addToBasket_ modify _add_option_field to generate form field dynamically (already done in _dashboard/catalogue/forms:ProductForm_)
  - abstract_models: _AbstractLineAttribute_ modify value attr not to just handle CharField. Follow _ProductAttributeValue_ logic keep an eye to line_reference generation (slug) 
- order
  - abstract_models: _AbstractLineAttribute_ remove type attr set value attr as it is done in _Basket.AttributeLineAttribute_

The same scheme model is repeated in _Basket.LineAttribute_, _Order.LineAttribute_ and _Catalogue.ProductAttributeValue_. We should consider DRY:
- forms/fields.py: Add _FIELD_FACTORIES_ defined in _dashboard/catalogue/forms_
- models/???:  Add _models.Model_ abstract class or mixin to define dynamically value as it is done already in _Catalogue.ProductAttributeValue_

Waiting for your feedback.

**Comment by Remiz** [comment]
Bumping this issue for interest...

I saw that your commits haven't been integrated to the project, is there is any update on that? I like your approach, I too feel that charfield is too limited for product options...

**Comment by jlmadurga** [comment]
Hi Remiz,

I am using those changes in production for oscar 0.7. I know those changes where not integrated. The solution is not as clean as it should be but it works.
If i get time I don't mind to refactor not having same logic solution in three places.
