### ISSUE TITLE
Translatability issues in orders dashboard

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1530]
The issue is (as so often) where we concatenate strings, which doesn't work for some languages. The offending block is here: https://github.com/tangentlabs/django-oscar/blob/master/oscar/apps/dashboard/orders/views.py#L144-L211

It was reported in Transifex here: https://www.transifex.com/projects/p/django-oscar/translate/#eu/oscar/19718168 

The fix is to have full translation strings for each choice.

**Comment by sasha0** [comment]
The issue does seem to exist any more - dashboard order list filters translated separately and concatenated afterwards, which works fine.
