### ISSUE TITLE
Some CSS changes

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1533]
There are some changes in our css-changes branch at https://github.com/machtfit/django-oscar/commits/css-changes that might be suitable for merging into oscar proper:

- [ ] af2490152c432e2c0a3b4d8c032e1fd446b88d1c
- [ ] 4e9f3acec5c240f279a3f8b4545635d967669c10
- [ ] 34b2074b00f16e6783f846a1667df8351718aef6
- [ ] ed6a139059fae47779ccca926d7c41065bc98a88

border color changes as undone in 2714123ef31545f95a99bdc70f3fce7675ac8074 should probably be made by modifying the corresponding bootstrap variable.

**Comment by mvantellingen** [comment]
Is this still relevant since the move to bootstrap 3? Otherwise we might want to close this one
