### ISSUE TITLE
Overriding the search handler used for product listings should be easier.

### ISSUE THREAD

**Issue by pipermerriam** [django-oscar/django-oscar#1566]
Currently, if you want to override the handler returned by `get_search_handler` on the various product listing views in the `catalogue` app, you can do one of the following things.
1. Subclass the view.
2. override `catalogue.search_handlers.get_product_search_handler_class`
3. override `catalogue.search_handlers.SimpleProductSearchHandler` or `catalogue.search_handlers.ProductSearchHandler`.
- **Option 1**  seems heavy, and it isn't _DRY_ if you want to override the handler globally.
- **Option 2** is relatively clean but seems awkward in the case that you just want to override what it returns.
- **Option 3** has to pay attention to what the return value of `get_product_search_handler_class` will be based on the return value of `is_solr_supported` in order to override the right class.

I think a new option would be helpful for those who have this use case.
- Add a setting `OSCAR_PRODUCT_SEARCH_HANDLER` which defaults to `None`.  When this value is set, the `catalogue.search_handlers.get_product_search_handler_class` function import and return the object at this path.
- Add a new search handler to be used when the `Elasticsearch` backend is in place for haystack, that uses the following code to narrow based on categories. (technically a separate feature so I'm happy to PR this in separately if you prefer)

``` python
class ElasticsearchProductSearchHandler(SearchHandler):
    form_class = BrowseCategoryForm
    model_whitelist = [Product]
    paginate_by = settings.OSCAR_PRODUCTS_PER_PAGE

    def __init__(self, request_data, full_path, categories=None):
        self.categories = categories
        super(ElasticsearchProductSearchHandler, self).__init__(request_data, full_path)

    def get_search_queryset(self):
        sqs = super(ElasticsearchProductSearchHandler, self).get_search_queryset()
        if self.categories:
            for category in self.categories:
                sqs = sqs.filter_or(category=category.full_name)
        return sqs
```

Is this a modification you would be open to me submitted a pull request for?

**Comment by sasha0** [comment]
Fixed by #1572.
