### ISSUE TITLE
Use gulp to build JS and CSS

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1570]
We previously used django-compressor to compile LESS to CSS and also to minify our JS. Django-compressor was removed in #1568. Currently we don't process JS in any way and use a simple Makefile for compiling LESS. The objective is make our CSS/JS process more powerful, while keeping it completely optional if you don't want to touch the JS/CSS.

Requirements:
* no new runtime requirements - this means, all generated JS/CSS files must be committed to the repository in the correct locations
* minified versions for production deployment
* sourcemap support for development

**Comment by sasha0** [comment]
Closing issue, since we already switch to gulp and removed django-compressor.
