### ISSUE TITLE
order statistics status link loses date range

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1579]
1. In /dashboard/orders/statistics/ apply a date filter.
   - the order statuses now count only orders within the given period
2. Click on one of the order statuses

_Actual_: A list with all orders with that status is shown.

_Expected_: A list with orders within the given period and with that status is shown.

**Comment by sasha0** [comment]
This also require changes in the order list filters, since there's only shortcut query filter for order status.
