### ISSUE TITLE
Event handling / EventHandler documentation

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1581]
The documentation is missing some obvious sections.

> Most Oscar shops will want to customise the EventHandler class from the order app. This is class is intended to handle all events and perform the appropriate actions. The main public API is 

> Many helper methods are also provided: 

Looks like somebody set up a skeleton here but never filled in the necessary details.

https://github.com/django-oscar/django-oscar/blob/master/docs/source/howto/how_to_set_up_order_processing.rst#event-handling

**Comment by sasha0** [comment]
Documentation contains sphinx `autoclass` directives after both of these paragraphs, thus generated documentation has all necessary information - http://django-oscar.readthedocs.io/en/latest/howto/how_to_set_up_order_processing.html#event-handling.

If you think anything else is missing in the events documentation - please re-open this issue with the feedback.

Thanks.

**Comment by john-parton** [comment]
Looks like I just missed the autoclass directives. I'll try to make sure to test the generated documentation before opening a ticket next time.
