### ISSUE TITLE
Trying to edit content blocks on / gives 404

### ISSUE THREAD

**Issue by m4l** [django-oscar/django-oscar#1587]
django-oscar==1.0
I wanted to add content blocks to my start page (url '/') which worked fine. But trying to get to the edit page where I can change the order gives me a 404, I guess due to the 2 trailing slashes.

```
.../dashboard/content-blocks/page//
```

It works in development server but not with nginx/gunicorn in production. Changing the url pattern to use the page id instead of the path might be a solution. Unless I'm doing something not supposed to.

**Comment by szuprefix** [comment]
I also had this problem, But I don't use proxy_pass, What should I do to solve it ?
As my nginx configuration followed:

        location /static/ {
            root /www/cooltatu/;
         }

        location /media/ {
            root /www/;
         }

        location / {
         fastcgi_pass 127.0.0.1:8081;
            fastcgi_param PATH_INFO $fastcgi_script_name;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param CONTENT_TYPE $content_type;
            fastcgi_param CONTENT_LENGTH $content_length;
            fastcgi_param REMOTE_ADDR $remote_addr;
            fastcgi_param SERVER_PROTOCOL $server_protocol;
            fastcgi_param SERVER_PORT $server_port;
            fastcgi_param SERVER_NAME $server_name;
            fastcgi_pass_header Authorization;
            fastcgi_intercept_errors off;
        }
