### ISSUE TITLE
Country's name field should be blank=True

### ISSUE THREAD

**Issue by m4l** [django-oscar/django-oscar#1589]
pycountries does not have an official name for every country, so many get populated with an empty string:

```
Country.objects.filter(name='').count()      # 77
```

When you then try to edit one of them via django admin you will get an error on save when leaving the "official name" field blank since it does not have blank=True.

**Comment by sasha0** [comment]
@mvantellingen finally got to implement this using your suggestion. Added support of updating countries as well.

**Comment by sasha0** [comment]
Since now countries update support, empty names for existing countries could fixed just by executing `oscar_populate_countries` command, initial population was fixed as well in 68bc575c3082002be7c1b32e097d3589c4227f22.
