### ISSUE TITLE
Problem with oscar.core.loading._import_module() in debug mode in Eclipse + PyDev

### ISSUE THREAD

**Issue by martymcmahon** [django-oscar/django-oscar#1593]
I'm porting a Oscar v0.8 project across to v1.0 from scratch and have hit a problem when running the debugger in Eclipse and PyDev that seems to stem from `oscar.core.loading._import_module()`.

I am extending the catalogue app and when run from the normal Eclipse Run it goes fine but when run using Eclipse Debug I get

```
ImportError: No module named signals
```

I have not extended `myshop.catalogue.signals` (I've only added some fields to `models.py`).

The problem comes about in `oscar.core.loading._import_module()`

```
__, __, exc_traceback = sys.exc_info()
frames = traceback.extract_tb(exc_traceback)
if len(frames) > 1:
    raise
```

with PyDev running in debug mode `frames` contains:

```
[('/Users/<user>/.virtualenvs/myshop/lib/python2.7/site-packages/oscar/core/loading.py', 159, '_import_module', 'return __import__(module_label, fromlist=classnames)'), ('/Applications/eclipse-kepler/plugins/org.python.pydev_3.9.0.201411111611/pysrc/_pydev_imps/_pydev_pluginbase.py', 445, 'plugin_import', 'fromlist, level)')]
```

so it triggers the second condition detailed in the comments for `_import_module()`.

The quick fix is to set 

```
if len(frames) > 2:
```

and to just be aware that import errors may occur from inside the overridden module.  
I'm not sure if this is only peculiar to my development setup, but I just wanted to flag it here in case someone else was experiencing this issue.

**Comment by bgryszko** [comment]
It won't fix for me. In my case there are 8 elements in the traceback. They appears while debugging using PyCharm 4 (PyCharm 3.4 is OK). Maybe it has something to do with https://github.com/mitsuhiko/pluginbase that was absent in previous versions of https://github.com/fabioz/PyDev.Debugger

**Comment by sasha0** [comment]
Closing since issue is outdated and does not seem to be relevant any more. Please re-open in case of new questions/issues. Thanks!

**Comment by esupoff** [comment]
Still relevant! PyCharm's remote pydev debugger is affected:
```
[<FrameSummary file /usr/local/lib/python3.7/site-packages/oscar/core/loading.py, line 182 in _import_module>,
<FrameSummary file /root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py, line 19 in do_import>]
```
