### ISSUE TITLE
Why use custom wizard for creating offers instead of SessionWizardView?

### ISSUE THREAD

**Issue by twil** [django-oscar/django-oscar#1601]
Hi,

Current implementation has a bit hacky way of dealing with ForeignKey's and doesn't support FileField at all. So I wonder is there a design decision behind the implementation or it's just pre Django 1.3?

May be it is a good idea of rewriting it using SessionWizardView?

**Comment by sasha0** [comment]
Closing since the issue is quite outdated and I couldn't find any references of `SessionWizardView`.
