### ISSUE TITLE
English (United States) Localization

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1608]
There are a few instances where GB word use sounds awkward to the US ear.

Some examples:

"Basket" vs. "Cart"
"Voucher" vs. "Coupon"
"Offer" vs. "Deal"

There are also many instances where the GB spelling differs from the US spelling. "Catalogue" vs "Catalog" is one that jumps out at me.

I was going to fix it in my app, but I thought it might make more sense to have a localization for en_US? I realize this is a minor annoyance, but it seems like something that should be configurable out of the box. 

Thoughts?

Thanks,
John

**Comment by john-parton** [comment]
I submitted this: https://www.transifex.com/p/django-oscar/language/en_US/

Right now the only changes I made are "Basket" to "Cart" and "Voucher" to "Coupon". 

Anyone have thoughts on "Offer" vs "Deal"? Anything else?

**Comment by john-parton** [comment]
Looks like the URL is now here: https://www.transifex.com/codeinthehole/django-oscar/language/en_US/

I updated the strings to bring it back to 100%.

**Comment by john-parton** [comment]
Strings should still be at 100%. Is there anything else I need to do to get this ticket closed?

**Comment by sasha0** [comment]
Locale is already in place. Thanks John!
