### ISSUE TITLE
Customizing apps.address.forms.UserAddressForm and apps.checkout.forms.ShippingAddressForm

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1609]
The US demo site customizes `apps.checkout.forms.ShippingAddressForm` to include a select widget for US State, as well as modifying a label and help_text.

But those changes are only for the checkout form, and not the `UserAddressForm`. Once the user has saved the address, if they got to change it at` /checkout/user-address/edit/<id>/`, then those customizations are gone.

The simplest solution is to just do all of the customizations again for `UserAddressForm`, but it would be slightly nicer if we could customize `apps.address.forms.AbstractAddressForm` directly.

**Comment by sasha0** [comment]
@john-parton what's pending here?

**Comment by john-parton** [comment]
I think it can be closed.

I also posted a mixin for this: https://github.com/django-oscar/django-oscar/pull/1610#issuecomment-76762025

**Comment by sasha0** [comment]
@codeinthehole @maikhoepfel @monikasulik please close the issue. Thanks.
