### ISSUE TITLE
Overriding SearchHandler doesnt works.

### ISSUE THREAD

**Issue by ddc67cd** [django-oscar/django-oscar#1614]
Class loader does not play nice when loading SearchHandler class. 
```get_class('search.search_handlers', 'SearchHandler')``` always returns ```<module 'oscar.apps.search.search_handlers' ...>```, regardless of whether there is a local search application or not.
This is because the loader replaces all occurrences of the 'search' in 'search.search_handlers'. As a result, it looks for a module '_handlers', what is wrong.

**Comment by codeinthehole** [comment]
Thanks for the report. We'll get that fixed for the next release.
