### ISSUE TITLE
BasketMiddleware.merge_baskets and checkout process

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1615]
Under some circumstances, baskets are merged together, where it would actually make sense for a more recent basket to replace older baskets.

Here's an example for when it is (almost certainly) inappropriate to merge two baskets together:
- A logged in user adds an item to their basket
- The user logs out (or uses a different computer)
- User adds a different item to their basket
- Basket now shows only the 2nd item
- User proceeds to checkout (Obviously if a user presses the checkout button at this point, they intend to checkout with the basket in its current state.)
- User is prompted to log in
- User logs in and is redirected to first step of checkout process
- BasketMiddleware has merged the two baskets together, so now there is a basket with both items in it.
- User fills out shipping information, billing information, etc.
- Only then is the user presented with this new basket that has (surprise) both items in it

Instead of silently merging the two carts, maybe the user should be notified that there are two carts, and be prompted to pick one or somehow at least draw attention to the fact that they have been merged. If the first cart is quite old, it might be safe to discard the first cart silently.

Some discussion elsewhere:
http://stackoverflow.com/questions/11942764/is-it-appropriate-to-merge-guest-user-cart-items-with-items-in-the-cart-when-a-u
http://ux.stackexchange.com/questions/52785/should-shopping-carts-from-different-sessions-be-merged-or-not

**Comment by mvantellingen** [comment]
I've had the same issue on a project I was working on. We chose to always use cookie-based baskets, which also solved the same problem.

See also #1317

**Comment by john-parton** [comment]
@mvantellingen Can you provide me with some more information regarding the cookie-based baskets? I'm having a hard time finding info about it in the docs.

Thanks.

**Comment by sasha0** [comment]
Fixed by PR #1871.
