### ISSUE TITLE
Download selected orders as CSV is broken

### ISSUE THREAD

**Issue by lijoantony** [django-oscar/django-oscar#1621]
When the Download button is used to download the selected orders as CSV at orders dashboard, the resulting CSV file doesn't contain any data, instead has the keys in place of values. CSV file downloaded for one order in the sandbox site has the below content,

Order number,Order value,Date of purchase,Number of items,Order status,Customer email address,Deliver to name,Bill to name
number,value,date,num_items,status,customer,shipping_address_name,billing_address_name

**Comment by maikhoepfel** [comment]
Thank you for taking the time to report. I'm not sure who else found it, but it's been fixed already. Please see #1622.
