### ISSUE TITLE
Sandbox: Advanced Search in dashboard/orders with date range results in attribute error

### ISSUE THREAD

**Issue by lijoantony** [django-oscar/django-oscar#1625]
1. Click on Advanced Search link next to Search button in /dashboard/orders
2. Enter date range 9/9/2014 - 12/12/2014
3. Click search
4. Django error page with below information is returned.

AttributeError at /en-gb/dashboard/orders/
'datetime.date' object has no attribute 'tzinfo'
Request Method:	GET
Request URL:	http://127.0.0.1:5000/en-gb/dashboard/orders/?csrfmiddlewaretoken=13ipHmklGCwrfxXksC5k6MjBjxeqJBuy&order_number=&name=&product_title=&upc=&partner_sku=&status=&date_from=9%2F9%2F2014&date_to=12%2F12%2F2014&voucher=&payment_method=&response_format=html
Django Version:	1.7.1
Exception Type:	AttributeError
Exception Value:	
'datetime.date' object has no attribute 'tzinfo'
Exception Location:	/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/utils/timezone.py in is_naive, line 349

TRACEBACK
===========
Environment:

Request Method: GET
Request URL: http://127.0.0.1:5000/en-gb/dashboard/orders/?csrfmiddlewaretoken=13ipHmklGCwrfxXksC5k6MjBjxeqJBuy&order_number=&name=&product_title=&upc=&partner_sku=&status=&date_from=9%2F9%2F2014&date_to=12%2F12%2F2014&voucher=&payment_method=&response_format=html

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.flatpages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django_extensions',
 'debug_toolbar',
 'template_timings_panel',
 'compressor',
 'apps.gateway',
 'widget_tweaks',
 'oscar',
 'oscar.apps.analytics',
 'oscar.apps.checkout',
 'oscar.apps.address',
 'oscar.apps.shipping',
 'oscar.apps.catalogue',
 'oscar.apps.catalogue.reviews',
 'oscar.apps.partner',
 'oscar.apps.basket',
 'oscar.apps.payment',
 'oscar.apps.offer',
 'oscar.apps.order',
 'oscar.apps.customer',
 'oscar.apps.promotions',
 'oscar.apps.search',
 'oscar.apps.voucher',
 'oscar.apps.wishlists',
 'oscar.apps.dashboard',
 'oscar.apps.dashboard.reports',
 'oscar.apps.dashboard.users',
 'oscar.apps.dashboard.orders',
 'oscar.apps.dashboard.promotions',
 'oscar.apps.dashboard.catalogue',
 'oscar.apps.dashboard.offers',
 'oscar.apps.dashboard.partners',
 'oscar.apps.dashboard.pages',
 'oscar.apps.dashboard.ranges',
 'oscar.apps.dashboard.reviews',
 'oscar.apps.dashboard.vouchers',
 'oscar.apps.dashboard.communications',
 'haystack',
 'treebeard',
 'sorl.thumbnail',
 'django_tables2']
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.transaction.TransactionMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'oscar.apps.basket.middleware.BasketMiddleware')

Traceback:
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/db/transaction.py" in inner
  394.                 return func(*args, **kwargs)
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/lijo/project/opensource/django-oscar/src/oscar/apps/dashboard/orders/views.py" in dispatch
  128.         return super(OrderListView, self).dispatch(request, *args, **kwargs)
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/home/lijo/project/opensource/django-oscar/src/oscar/apps/dashboard/orders/views.py" in get
  142.         return super(OrderListView, self).get(request, *args, **kwargs)
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/views/generic/list.py" in get
  145.         self.object_list = self.get_queryset()
File "/home/lijo/project/opensource/django-oscar/src/oscar/apps/dashboard/orders/views.py" in get_queryset
  297.         self.description = self.desc_template % self.get_desc_context(data)
File "/home/lijo/project/opensource/django-oscar/src/oscar/apps/dashboard/orders/views.py" in get_desc_context
  191.                 % {'start_date': format_datetime(data['date_from']),
File "/home/lijo/project/opensource/django-oscar/src/oscar/core/utils.py" in format_datetime
  79.     if is_naive(dt):
File "/home/lijo/.virtualenvs/eshop1/local/lib/python2.7/site-packages/django/utils/timezone.py" in is_naive
  349.     return value.tzinfo is None or value.tzinfo.utcoffset(value) is None

Exception Type: AttributeError at /en-gb/dashboard/orders/
Exception Value: 'datetime.date' object has no attribute 'tzinfo'

**Comment by codeinthehole** [comment]
I can replicate this. That advanced search is something that hasn't seen much attention for a long time.

**Comment by mvantellingen** [comment]
Fixed with #1626
