### ISSUE TITLE
Reverse for set_language not found

### ISSUE THREAD

**Issue by pwalsh** [django-oscar/django-oscar#1628]
New install of django-oscar 1.0.1 on Python 3.4.

Directly follow instructions here:

https://django-oscar.readthedocs.org/en/releases-1.0/internals/getting_started.html

Get to here to run the server:

https://django-oscar.readthedocs.org/en/releases-1.0/internals/getting_started.html#create-database

Error:

```
Template error:
In template /Users/paulwalsh/code/environments/hamigdalor/lib/python3.4/site-packages/oscar/templates/oscar/partials/nav_accounts.html, error at line 16
   Reverse for 'set_language' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

I solved the error by doing the following (which I don't need):

* Adding a LANGUAGES setting
* Enabling the i18n urls

Not that only adding a LANGUAGES setting does not help - I had to do both.

**Comment by codeinthehole** [comment]
Good spot - will get this cleared up for 1.1

**Comment by codeinthehole** [comment]
@pwalsh The [docs do specify](https://django-oscar.readthedocs.org/en/releases-1.0/internals/getting_started.html#urls) that the i18n URLs need to be included. I checked and things do work even if a `LANGUAGES` settings isn't set. Am I missing something?

**Comment by pwalsh** [comment]
The docs say: "If you have more than one language set your Django settings for LANGUAGES, you will also need to include Django’s i18n URLs:"

Which implies that if you do not have LANGUAGES at all (it is not set by default with startproject), then you *do not* need to include the i18n urls, no?

**Comment by mvantellingen** [comment]
Actually, Django sets LANGUAGES by default, see: https://github.com/django/django/blob/master/django/conf/global_settings.py#L50

So i'm closing this for now. If you don't agree, then please be free to re-open :-)
