### ISSUE TITLE
Validate if message is set in AccountAuthView

### ISSUE THREAD

**Issue by mikedingjan** [django-oscar/django-oscar#1629]
Hi,

We're using the messages framework throughout our oscar application however the "welcome back" notice when a user logs in isn't one we would like to display.

Is it possible to have the view function check if a message is set before actually setting the message this way we can use the get_login_success_message to return False. 

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/customer/views.py#L161

**Comment by sasha0** [comment]
Closing since related PR already merged.
