### ISSUE TITLE
demo change language error

### ISSUE THREAD

**Issue by yeesuu** [django-oscar/django-oscar#1636]
![oscar1](https://cloud.githubusercontent.com/assets/6366499/5831380/a119ac72-a16c-11e4-89ce-f803d89b3eb4.jpg)

![oscar2](https://cloud.githubusercontent.com/assets/6366499/5831367/6b051414-a16c-11e4-9796-0b355264945a.jpg)

**Comment by codeinthehole** [comment]
Yow. How strange - I will fix.

**Comment by mvantellingen** [comment]
I'm not able to reproduce this. Is this still an issue?
