### ISSUE TITLE
Fix #1638 Will Brake Orders Placed and Offer Performance Reports

### ISSUE THREAD

**Issue by halfnibble** [django-oscar/django-oscar#1640]
Note: accepting my fix for #1638 will break two of the reports if you attempt to generate them without a date range specified. (Technically, they are already broken)

I believe this is because these two reports incorrectly use their custom `generate()` method to filter via dates instead of the more robust `ReportGenerator.filter_with_date_range()`.

I will attempt to create a pull request for these two reports tomorrow.

Reports:
1. https://github.com/django-oscar/django-oscar/blob/1.0.1/oscar/apps/order/reports.py#L54
2. https://github.com/django-oscar/django-oscar/blob/1.0.1/oscar/apps/offer/reports.py#L45

**Comment by mvantellingen** [comment]
Fixed in 1c76fb9
