### ISSUE TITLE
PaymentDetails view- UnableToTakePayment- Paypal Express

### ISSUE THREAD

**Issue by jlmadurga** [django-oscar/django-oscar#1651]
When Paypal returns an error placing order (i.e. incorrect credit card) PaymentDetails view raises UnableToTakePayment. It redirects to "render_payment_details"  to introduce again payment details.
When checking out with paypal from basket this makes no sense.
Redirecting to basket with the error might be a solution but I don't know if it fits all scenarios.

**Comment by codeinthehole** [comment]
Moved to https://github.com/django-oscar/django-oscar-paypal/issues/92
