### ISSUE TITLE
Dashboard email preview crashes on email templates with hyphen in code

### ISSUE THREAD

**Issue by jvkersch** [django-oscar/django-oscar#1653]
To reproduce, add a `CommunicationEventType` instance through the admin page with a hyphen in its code field (e.g. `TEST-DASH`). Open the dashboard and navigate to Content > Email Templates; an internal server error occurs.

Probably a good fix would be to add validation to the `code` field to ensure that it matches `\w+` as the regular expression in https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/dashboard/communications/app.py#L17 suggests.

**Comment by codeinthehole** [comment]
Thanks for the report - I'll take a butchers.
