### ISSUE TITLE
Cannot easily order facets

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1655]
There isn't a convenient way to order the facets, because the facets are loaded into a `dict`. I have a partial fix for this already and will submit it here soon.

**Comment by maikhoepfel** [comment]
I agree about the issue. We now have support for ordering fields and queries, but can't mix the two.

**Comment by sasha0** [comment]
@maikhoepfel @john-parton PR already merged. What's pending in the issue? Thanks.

**Comment by john-parton** [comment]
Like I said, this is only a partial fix. The change allows you to order fields as well as ordering queries, but you cannot specify an arbitrary ordering of fields and queries.

**Comment by solarissmoke** [comment]
Closing this in favour of #2539.
