### ISSUE TITLE
translation files aren't updated for thank_you.html

### ISSUE THREAD

**Issue by armutcu** [django-oscar/django-oscar#1669]
translation files aren't updated for thank_you.html; should be as follows

#: templates/oscar/checkout/thank_you.html:13
msgid ""
"\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Order %(number)s: confirmation\n"
"&nbsp;&nbsp;&nbsp;&nbsp;"
msgstr ""

#: templates/oscar/checkout/thank_you.html:25
#, python-format
msgid ""
"\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your order has been placed and a confirmation email has been sent - your order number is\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;strong&gt;%(number)s&lt;/strong&gt;.\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
msgstr ""

**Comment by maikhoepfel** [comment]
@armutcu, thank you for reporting this. Am I correct in assuming you were working with a version of Oscar of the master branch? We only commit ``makemessages`` changes before a release to not clutter the commit history with i18n commits. So this is as expected; you should be able to run it yourself to get an up-to-date version of the translation files.

Please re-open the ticket if I'm guessing wrongly.
