### ISSUE TITLE
image upload option with django-oscar dashboard tinyMCE

### ISSUE THREAD

**Issue by jijin-github** [django-oscar/django-oscar#1679]
How can I genarate django-oscar dashbosrd text editor (tinyMCE) with image upload option. 

OR

How to integrate ckeditor instead of django-oscar dashbosrd text editor (tinyMCE) .

**Comment by maikhoepfel** [comment]
Advice like this is better suited for discussion on our mailing list. Please post there. As far as I know, nothing in Oscar is stopping you from implementing this, but there's no support for it at the moment.
