### ISSUE TITLE
Arbitrary model instance as a product

### ISSUE THREAD

**Issue by raratiru** [django-oscar/django-oscar#1681]
I have an application where I can "build" cds in the admin interface through inlines and model relations:

models.py
```
class Label(models.model):
    label_name=models.CharField(max_length=63)

class CD(models.model):
    title=models.CharField(max_length=63)
    unique_id=models.PositiveIntegerField()
    label_key=models.ForeignKey(Label)

class Composer(models.model):
    cd_key=models.ForeignKey(CD)
    composer_name=models.CharField(max_length=63)

class Musician(models.model):
    cd_key=models.ForeignKey(CD)
    musician_name=models.CharField(max_length=63)

```

Is it possible to have django-oscar consider the first instance of the CD model and its relations as my first product?

The documentation discusses the use of the ```entity``` attribute type, but I cannot understand the example provided.

**Comment by maikhoepfel** [comment]
Hi George,

I think replacing the ``Product`` model would be a tall (and unnecessary) order. There's two simpler solutions I can think of:
- Add a foreign key/one to one field to your custom Product model (inheriting from Oscar's Product model)
- Add an attribute of type ``entity`` to each product's ``attributes``. 

Both should be quite straightforward. Please post to the mailing list if you run into any trouble.

Cheers, M.

**Comment by raratiru** [comment]
Thank you!

I will search the source to find out how ```entity``` could work, and alternatively I will go with the first solution.

**Comment by raratiru** [comment]
Indeed, the documentation is not correct. I have opened a[ new issue][1].

[1]: https://github.com/django-oscar/django-oscar/issues/1686
