### ISSUE TITLE
Documentation error in the chapter "Product Attributes"

### ISSUE THREAD

**Issue by raratiru** [django-oscar/django-oscar#1686]
The code exposed to the chapter "[Product Attributes][1]" needs the following correction:

```
> ProductAttribute.objects.create(product_class=klass, name='admin user', code='admin_user')
```
Should read:

```
> ProductAttribute.objects.create(product_class=klass, name='admin user', code='admin_user', type='entity')
```

[1]: http://django-oscar.readthedocs.org/en/latest/topics/modelling_your_catalogue.html?highlight=entity#product-attributes

**Comment by maikhoepfel** [comment]
Thanks George. I fixed the docs as you suggested. If you find anything else, a pull request is most welcome!

**Comment by raratiru** [comment]
Thank you for this great application. 

Now, I know where I can find the docs in the github directory!
