### ISSUE TITLE
Extended fields in category model do not appear in dashboard

### ISSUE THREAD

**Issue by aef-** [django-oscar/django-oscar#1692]
I want to add a few more image fields to the category model. I forked the app and extended the abstract model and while what I did works with 1.0.2, the fields do not show up in the dashboard on master. I found the following snippet to be the culprit.

```
# apps/dashboard/catalogue/forms.py
CategoryForm = movenodeform_factory(
     Category,
     fields=['name', 'description', 'image'])
```

**Comment by maikhoepfel** [comment]
Adrian, if I don't misunderstand, that is intended behaviour. We think it's a better practice to explicitly have to override the forms (and force the dev to think about how to handle things) than potentially accidentally exposing the fields.Please override the form and set fields accordingly.

**Comment by aef-** [comment]
Makes sense, thanks!
