### ISSUE TITLE
upgrade to treebeard 3.0 

### ISSUE THREAD

**Issue by anentropic** [django-oscar/django-oscar#1695]
Current treebeard 2.0 generates a bunch of noisy deprecation warnings in Django 1.7

treebeard 3.0 was recently released and should fix this:
https://tabo.pe/jenkins/job/django-treebeard/

**Comment by Azd325** [comment]
Hey  @anentropic,
I think this was already discussed and merged in #1644

**Comment by anentropic** [comment]
sweet!
