### ISSUE TITLE
Range can never include child products

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1698]
There is no good way to apply a discount to a child product.

Here's a scenario: You run a bookstore and want to discount hard cover books, but not paperbacks. Your catalog is set up so that paperback and hardcovers are children. You want to discount hardcovers but not paperbacks. One approach would be to create a new `Range` and add all the hard covers to the new `Range`, but ranges are always associated with parents or standalone products.

`Range.contains_product` has the following lines:

```python
# Child products are never part of the range, but the parent may be.
if product.is_child:
    product = product.parent
```

**Comment by monikasulik** [comment]
The pull request was merged so this issue can be closed

**Comment by mvantellingen** [comment]
Yeah sorry forgot to close it.
