### ISSUE TITLE
Checking multiple facet / possible misuse of checkboxes

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1701]
If you're on the search page, and you click on multiple checkboxes for facets, you're directed to a new page with only the last facet that you selected active.

The expected behavior would be to have all of the facets that you clicked on selected.

One thing we could do would be to just remove the checkboxes.  This would remove the user's expectation that they're interacting with a form or a widget, so the "link" behavior would be less surprising.

Another solution might be to hide the sidebar or search area with a spinner or other indicator so that the user knows that some action is being taken immediately after they click.

**Comment by john-parton** [comment]
Another solution might be to hide the sidebar or search area with a spinner or other indicator so that the user knows that some action is being taken immediately after they click.

**Comment by sasha0** [comment]
When you select new facet - it reloads page with new search results. If you select multiple facets one by one - the all will be selected.

**Comment by john-parton** [comment]
If you click a facet, and then click a second facet *before the page has reloaded* then the page will reload with only the first facet that you selected. (On a slow connection, this is quite easy to do.)

This is expected behavior for *links* but not the expected behavior for *form elements*, however the links are presented as if they were form elements. This mismatch of expectations is potentially confusing.

**Comment by sasha0** [comment]
Right. As a possible solution, as you proposed, we can hide search form and/or sidebar under overlay and display spinner right after checkbox has selected.
@maikhoepfel @mvantellingen @codeinthehole what do you think guys?

**Comment by solarissmoke** [comment]
This will be completely refactored in #2539, so closing.
