### ISSUE TITLE
basket/abstract_models.py: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by foadnh** [django-oscar/django-oscar#1708]
In description function of AbstractLine class, in this line:
```python
d = "%s (%s)" % (d.decode('utf-8'), ", ".join(ops))
```
.decode('utf-8') should be dropped. It is not compatible with python 3.

This bug appeared since Django 1.8!
Django Version:       1.8.0
Python Version: 	3.3.5
Oscar Version:        1.0.2

Error message and backtrack:
https://gist.github.com/foadnh/b69fcb91daf7cccf2cfc

**Comment by codeinthehole** [comment]
Thanks for the report - I've linked this to the Django 1.8 support PR.
