### ISSUE TITLE
Adding django 1.8 support

### ISSUE THREAD

**Issue by auvipy** [django-oscar/django-oscar#1710]

**Comment by krzysztofp** [comment]
+1

**Comment by karol-gruszczyk** [comment]
+1

**Comment by blager** [comment]
+1

**Comment by tpro** [comment]
+1

**Comment by bartlomiejborzucki** [comment]
+1

**Comment by mvantellingen** [comment]
Yup, if no one beats me to it i'll look at it this weekend

**Comment by auvipy** [comment]
while changes between 1.6 and 1.7 were not trivial, changes between 1.7 and 1.8 should not be that difficult to support togather.

**Comment by mvantellingen** [comment]
Well one of the issues is that not all our dependencies support 1.8 yet. And we also need to decide if we integrate this in Oscar 1.1.0 (which will include Bootstrap 3) or release it as a 1.0.4 (thus make it an easier upgrade path). I'll leave this decision to @maikhoepfel and @codeinthehole

**Comment by maikhoepfel** [comment]
Hi all, I'm happy to announce I just merged #1711. Django 1.8 is now supported on the master branch. A client of mine is using Oscar and wants to move to Django 1.8 pretty soon, so I'm hopeful I'll get time to package Oscar 1.1 soon.

**Comment by maikhoepfel** [comment]
We do have some work left to do: https://github.com/django-oscar/django-oscar/issues/1728
