### ISSUE TITLE
docs for overriding product template for upc or product class wrong

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1715]
Docs talk about `catalogue/partials/product/upc-%s.html`, code uses `catalogue/detail-for-upc-%s.html`.

Docs: https://github.com/django-oscar/django-oscar/blob/dc437aaeec45b0005c0630808f3bdda1a09ace5e/docs/source/howto/how_to_customise_templates.rst#overriding-individual-products-partials
Code: https://github.com/django-oscar/django-oscar/blob/dc437aaeec45b0005c0630808f3bdda1a09ace5e/src/oscar/apps/catalogue/views.py#L109

**Comment by sasha0** [comment]
Fixed in e71576a1815c6710920860ca73b450ab98a2c765.
