### ISSUE TITLE
Required fields aren't enforced when first saving a partner

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1723]
From the [mailing list](https://groups.google.com/d/msgid/django-oscar/9be77593-40f9-4eff-b39d-0b95f3cb76d8%40googlegroups.com?utm_medium=email&utm_source=footer):

> I'm a bit lost as to how to edit Oscar to make it so that when an Administrator of the site goes to enter a new Partner via the Dashboard, when they click "New Partner", they shouldn't be able to save a blank partner at all. Now, I know I can make the "Name" part required, but the address gets much trickier. It doesn't seem to matter how I extend the address models, no matter what I do, I cannot make it so that certain fields in the address form are required for the very first save of the partner. If a save occurs, and the partner is edited after the fact, THEN the requirements kick in but there must be a way of requiring them in the inline form or the PartnerAddressFormSet, right?

**Comment by mvantellingen** [comment]
I'm not really sure what to do with this. It seems that #1206 made the partner name optional. If the address data is required when creating a new partner then that should be easy.

**Comment by maikhoepfel** [comment]
I made the Partner.name *form* field required in https://github.com/django-oscar/django-oscar/commit/4b72a16cc8f735f518513812699eaf5592c5b9d2, because I agree that's confusing.

I'll respond on the mailing list with ideas how to get the desired behaviour. But that is a non-standard Oscar behaviour, so not really something we need to address.
