### ISSUE TITLE
Remaining work for Django 1.8 support

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1728]
I merged #1712 which should add Django 1.8 support for Oscar, but there's some work remaining:

- [x] We currently need to run against an unreleased version of `tables2`. See https://github.com/django-oscar/django-oscar/commit/90c05e18f30458ef4bda5cc85e9bb7f7a48ae717 and https://github.com/bradleyayers/django-tables2/pull/245
- [x] ``sites/demo/manage.py migrate`` currently fails: https://travis-ci.org/django-oscar/django-oscar/jobs/61158307
- [ ] ``./manage.py migrate`` creates migrations both for the demo and sandbox site. Likely Oscar itself is missing some.

**Comment by maikhoepfel** [comment]
We do need to think about how we handle migrations that Django adds: Django 1.8 added some migrations. By creating migrations with Django 1.8, we force them upon our users, also the ones with Django 1.7. That could lead to issues as they might require matching code in Django, which a user of Django 1.7 wouldn't have.

**Comment by mbertheau** [comment]
A possibility is to support only one Django release with every Oscar release.

**Comment by mvantellingen** [comment]
# By creating migrations with Django 1.8, we force them upon our users, also the ones with Django 1.7. 

I'm not sure I understand this. Migrations should be compatible between 1.8 and 1.7 right? Otherwise this is a problem for the complete Django app ecosystem.

**Comment by mvantellingen** [comment]
The demo migrations error is due to the fact that django-stores is not yet compatible with Django >= 1.7.

I've created a PR to fix this issue: https://github.com/django-oscar/django-oscar-stores/pull/77

**Comment by maikhoepfel** [comment]
@mvantellingen: Thanks for doing the stores PR. Much appreciated!
Migration should be compatible, yes. The issue is a different one. Django 1.8 [shipped with a few migrations](https://docs.djangoproject.com/en/1.8/releases/1.8/#default-emailfield-max-length-increased-to-254). For example, the default length of an `EmailField` increased, and `User.last_login` can now be `None`. Because we have models using an `EmailField`, `makemigrations` will pick up those changes when switching to Django 1.8. But if we bundle those created migrations with Oscar, they will be fed to all Oscar users, including Django 1.7.

The scenarios I can imagine are:
-  Bundle migrations of highest supported Django version. Then we might run into a situation where a lower Django version doesn't have the matching code changes (e.g. be unable to deal with `User.last_login` being `None).
- Bundle migrations of lowest supported Django version. When running with a higher Django version, the user will see model changes that aren't reflected in migrations. I think if then running `makemigrations`, they would be created inside the virtualenv, which wouldn't persist across deployments, leading to a messy situation for the user.
- Bundle migrations of highest supported Django version, wrap in a `if django.VERSION < (1,8)`. I'm not entirely sure of the consequences, but it's worth investigating.
- Ship no migrations. Are they even necessary? Can't we generally ask the user to run `makemigrations`, even for non-customised apps?
- Any other approach.

**Comment by mvantellingen** [comment]
Ok thanks for the explanation. I think we are required to ship migrations since we might sometimes have datamigrations which can't be automatically generated. I'm wondering how other projects handle this.

**Comment by john-parton** [comment]
If we only supported one Django release, how do we decide which version to support? Only the latest release? Or only the latest LTS release?

Either way, some users are going to be left out in the cold, and in general, I think it makes upgrading more difficult.

We could subclass `EmailField` and add the changes introduced in Django 1.8 manually. Then we wouldn't have to worry about there being a difference between Django versions.

Maybe have some module like `oscar.core.compatability`?

This wouldn't automatically fix the `User` model, unfortunately.

**Comment by codeinthehole** [comment]
In #1764, I've set the `max_length` back to 75 to side-step this issue. When we drop support for Django 1.6 we can remove these and fall back to the 254 set in Django.
