### ISSUE TITLE
Carousel styles for multiple product images are broken

### ISSUE THREAD

**Issue by simplylizz** [django-oscar/django-oscar#1731]
The problem appears in the current development version of oscar. It looks like carousel was styled for bootstrap v2 and this styles arn't acceptable for bootstrap v3.

http://postimg.org/image/v0ufjrarr/ - there is a screenshot of the problem.

**Comment by mvantellingen** [comment]
So I have no real css skills but now it at least doesn't look completely borked. I'll try to get someone else to look at it for more improvements :-)

**Comment by sasha0** [comment]
Since slider was already fixed in 435a30a8c7e504ec2b191277e7fafdc1a54169b6, I think we could close this issue and open new one if we want to improve styling in the future. What do you think @mvantellingen ?

**Comment by sasha0** [comment]
Already fixed per comment above.
