### ISSUE TITLE
How to pass a queryset for each different field Admin Inlines

### ISSUE THREAD

**Issue by unehub** [django-oscar/django-oscar#1743]
Pretend to have in the Django admin, 4 forms inlines, Each with a pair of fields choices, "Attributes" and "Value Option". We have the first pair, which initialize the field one with a value, for example color and other field you must have a queryset the choices.

*Check images please*
![enter image description here][1]

As you can see I need to filter each pair with their default values, if Color should show only white, black and blue.

    class ProductAttributeValueForm(forms.ModelForm):
        attribute = forms.ModelChoiceField(label=_('Attribute'),
            widget=forms.Select(attrs={'disabled': 'True'}),
            queryset=ProductAttribute.objects.all(), required=False)

    class ProductAttributeValueFormSet(BaseInlineFormSet):

        def __init__(self, *args, **kwargs):
            super(ProductAttributeValueFormSet, self).__init__(*args, **kwargs)
            # This return initial [{'attribute' initial}, {..}, {..}]
            self.initial = [{'attribute': a} for a in obj.category.attributes.all()]
            # Now we need to make a queryset to each field of each form inline
            self.queryset = [{'value_option' .. }, { .. }]

What I do is initialize each attribute with a value, for example, Color and passed a queryset to value_option with their respective values, white, blue and black.
I have tried to do this two days ago and I have not accomplished anything, not if the solution is on the forms or in any function of admin

  [1]: http://i.stack.imgur.com/kk1xQ.png

**Comment by john-parton** [comment]
Generally, you want to edit products through the `/dashboard/`.

Is there a particular reason you're trying to edit it through the admin?

**Comment by unehub** [comment]
@john-parton yes, more security, less code to maintain, although complicated to accomplish certain things. But in general I like the Django admin and try to make everything work there.

**Comment by john-parton** [comment]
I definitely sympathize with your situation.

Here's a work around:

```python
from django import forms
from django.contrib import admin
from django.core.exceptions import ObjectDoesNotExist

from oscar.apps.catalogue import admin as catalogue_admin

# This is a custom model form that limits the value_option queryset based on the instance's attribute
class ProductAttributeValueForm(forms.ModelForm):
    class Meta:
        model = catalogue.ProductAttributeValue
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductAttributeValueForm, self).__init__(*args, **kwargs)
        try:
            self.fields['value_option'].queryset = self.instance.attribute.option_group.options.all()
        except (AttributeError, ObjectDoesNotExist):
            pass

# We subclass the existing oscar inline, but substitute our new custom form
class AttributeInline(catalogue_admin.AttributeInline):
    form = ProductAttributeValueForm

# This is our custom product admin class
class ProductAdmin(catalogue_admin.ProductAdmin):
    # Here we tell the admin which inlines to use
    # use our new custom inline as well as the stock category inline
    inlines = [AttributeInline, catalogue_admin.CategoryInline]
    # add in any other customizations here
    # list_filters, date_hierarchy, extra actions... whatever you need

# We first have to tell django to NOT use the previously registered admin class (the one Oscar enables by default)
admin.site.unregister(catalogue_admin.Product)

# And then let it know that we actually want to use this one
admin.site.register(catalogue_admin.Product, ProductAdmin)
```

The value option field will initially show all the options, but if you select the attribute and then hit "save and continue editing" it should update to only show the correct options.

Honestly, this is pretty reasonable default behavior and could probably be included in Oscar by default. Let me know if this works and I might consider submitting a PR.

**Comment by unehub** [comment]
Consider two things: A product is whether or ATTRIBUTES own, Color, Size, etc .. then initialize these attributes without being able to edit and then a queryset is done to show in their choices value_option.

    class ProductAttributeValueForm(forms.ModelForm):
        attribute = forms.ModelChoiceField(label=_('Attribute'), widget=forms.Select(attrs={'disabled': 'True'}), queryset=None, required=False)

        class Meta:
            model = ProductAttributeValue
            fields = '__all__'

        def clean(self):
            ....

    class ProductAttributeValueFormSet(BaseInlineFormSet):
        def __init__(self, *args, **kwargs):
            super(ProductAttributeValueFormSet, self).__init__(*args, **kwargs)
            self.initial = [{'attribute': Colors}, {'attribute': Sizes}, ...]

    class AttributeInline(admin.TabularInline):
        form = ProductAttributeValueForm
        formset = ProductAttributeValueFormSet
        model = Product.attributes.through

        def get_min_num(self, request, obj=None, **kwargs):
            """calculate min_num inlines forms"""

        def get_max_num(self, request, obj=None, **kwargs):
            """calculate max_num inline forms."""
            return self.get_inline_num(obj)

**Comment by unehub** [comment]
Second, we have all the attributes loaded in the forms, now what? well now you need to make a value_option queryset each attribute will match the initially charged.

**Comment by john-parton** [comment]
I'm sorry, but I'm having trouble understanding you.

You have to pick a value (any value) and then save it. Then it will actually filter it down to the correct queryset.

I realize this is not perfect, but it seems to be a limitation of the django admin. You could probably come up with something slightly better if you override the template and put some custom javascript on the page.

**Comment by john-parton** [comment]
Okay, I looked more closely at your code and I sort of understand what you're going for.

Basically, you need to make sure that the value_option.queryset is set when a form is initialized. I'm not 100% sure how to do that, unfortunately.
