### ISSUE TITLE
hola necesito ayuda para un pequeño proyecto con django-oscar

### ISSUE THREAD

**Issue by halbertt** [django-oscar/django-oscar#1744]
Hola, me gustaría saber si es posibles modificar alguna de las tiendas que te dan hechas, ya que lo que necesito es muy parecido a la versión Sandbox que nos ofrecen.
Gracias.

**Comment by unehub** [comment]
Hola @halbertt, lamentablemente aqui no ofrecemos soporte en español, pero te responderé.

Si así es, de hecho django-oscar es muy configurable y puedes extender o modificar cualquier parte que requieras, si esta todo lo que necesitas en la version master, para que quieres cambiar algo ?

**Comment by maikhoepfel** [comment]
@unehub Thanks for replying. I can only agree.

@halbertt, for future queries, please post to our mailing list: https://groups.google.com/forum/?fromgroups#!forum/django-oscar. Thanks!
