### ISSUE TITLE
StockAlert date_closed not saved

### ISSUE THREAD

**Issue by jlmadurga** [django-oscar/django-oscar#1747]
When StockAlert is closed no date for date_closed field is provided

**Comment by monikasulik** [comment]
Could you make a pull request for this? :)

**Comment by sasha0** [comment]
@monikasulik I've already made.

**Comment by sasha0** [comment]
@codeinthehole @maikhoepfel please take a look. Thanks.

**Comment by mvantellingen** [comment]
I'm neither of them but looks good to me :-) 
Thanks
