### ISSUE TITLE
Access to admin dashboard

### ISSUE THREAD

**Issue by genxstylez** [django-oscar/django-oscar#1750]
Hi, I want to have a play with the admin interface.

Is it accessible on the demo site?

**Comment by digicase** [comment]
I think this is something more suitable for [the user group](https://groups.google.com/forum/#!forum/django-oscar). However I'll point you to the page where you can try creating a dashboard user for the sandbox:

http://latest.oscarcommerce.com/en-gb/gateway/

**Comment by genxstylez** [comment]
thanks!
