### ISSUE TITLE
Offer pagination is hardcoded

### ISSUE THREAD

**Issue by sandino** [django-oscar/django-oscar#1753]
Hi,

Offer pagination currently is [hardcoded in OfferDetailView](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/views.py#L25), and it would be nice to be able to control this with its own setting other than OSCAR_PRODUCTS_PER_PAGE.

**Comment by john-parton** [comment]
There are quite a few `paginate_by` attributes that are hard coded. I'm not sure how big of an issue this really is, though.

Search the src tree for `paginate_by = \d+` to find them all.

**Comment by zuck** [comment]
It would be great to let the user to paginate all this views according to her own preference, with a front-end tool. BTW I agree a default value should be configured in `settings.py`.

**Comment by codeinthehole** [comment]
Thanks for this. I'm going to use this as a base to make all the pagination attributes controlled by settings.
