### ISSUE TITLE
Product Structure and Attributes

### ISSUE THREAD

**Issue by jakobholmelund** [django-oscar/django-oscar#1756]
Hi all

I've now been hard at work implementing our new shop in django oscar. Sadly django-oscar isn't very good at product variations and attributes. I'm considering how to fix this, and would like some input from the community.

Imo the best and simplest implementation would be to have every product be a variation, even if it's a standalone product. This greatly simplifies working with products all around the framework, and would make product editing in the dashboard more intuitive. You could even change the layout in the dashboard if only a single variation is created.

I've made a little list of things that the variation system should be able to handle.
- Variant generation from attributes set in product class
- No duplicate variants should be allowed
- Multi inline editing of variants
- Image on variants (for automatic image switching on product page)

Regarding Attributes i have some ideas as well. First order of business would be to unify Options and Attributes. It's confusing that these are 2 separate entities. This would entail removing the AbstractOption model, this is already confusing since the only way to add options is through django admin. There should be a global entry to manage attributes. Looking through the current models, it seems like much of this can be implemented right away, with a few modifications.  

and here is a list of the thing attributes should able to handle
- Attributes should have it's own global management, and then be attached to product classes
- Swatch type on the ProductAttributeValue (for handling frontend representation e.g. Color, Image etc.)

There's probably more stuff that i forgot in this writeup, so please let me know if missed anything and if you are interested in helping out implementing. Obviously much of the work will be in the frontend, and i think i read somewhere that the dashboard was about to be rewritten, so if anyone has information on this i would be glad to have it. 

Cheers

**Comment by john-parton** [comment]
There's already an open issue that covers most of this: https://github.com/django-oscar/django-oscar/issues/675 Swatches are specifically mentioned.

There definitely is room for improvement.

Here's my PR for per-variant image support: https://github.com/django-oscar/django-oscar/pull/1643

I have an application that I've developed that solves pretty much all of these issues, but I'm waiting for feedback on some of my smaller pull requests before I attempt to submit larger pull requests.

**Comment by john-parton** [comment]
There would be some difficulty to removing Options. We would first have to deprecate it and let everybody know that it's going to be removed, and ideally push out a migration.

You're right that attributes and parent/child relationships don't mix very well. Stuff you can do out-of-the-box that doesn't make a lot of sense:

* You can add conflicting attributes to both the parent and a child. Which is correct?
* You can have two identical products, but one has a bunch of attributes on the parent, while others have a bunch on the children. Because there is no canonical representation, it makes comparing products and finding duplicates tricky

You're also right that it's confusing to be able to have a standalone product, as well as having a product with a single child. These are functionally identical, but again, there's no canonical representation.

I think the rationale for having the two separate structures is that if you have standalone products, it's straightforward to have an "add to basket" button directly on the product thumbnail (in search results or whatever), and while it's technically possible to have an "add to basket" button on a parent with a single child, the logic for checking that can be somewhat tricky.

Could probably open several tickets just for these issues.

**Comment by john-parton** [comment]
I've implemented a grab-bag of utilities to help mitigate some of these issues:

* A function that canonizes attribute values
    * If all of the children have an identical attribute value, it's hoisted to the parent
* A function that converts a standalone product into a parent-only-child product, as well as a function that does the opposite
* A function that merges multiple products
* A function that splits a product-children structure into multiple standalone products

Once you start dealing with thousands of products, these things become pretty much requisite.

**Comment by digicase** [comment]
It would be great if all the changes and features you mentioned could be added to Oscar. I'm starting a new project using Oscar for a clothing website, and it could hugely benefit from better product variation handling. I'd be interested to help if I could.

To add to the discussion I think stock handling for product and variations could be improved. Right now I don't think stock levels for variants are taken into account for each variation as well as it could be. I will need customers to be able to subscribe and receive stock alerts for each variation of a product. So for example receive an alert when a the small size of a t-shirt is restocked. Multi inline editing of variants would be useful for quickly viewing and editing stock levels for all variations at once. 

I also think that variations should be added to the search index, and then you could create search facets for attributes such as sizes, and possibly use stock levels here too. If all products were variations I would expect that this would happen. Then use filtering or a model manager to display only the relevant parent products when customers are browsing or searching the shop.

**Comment by jakobholmelund** [comment]
Great to see, that there are some interest here :) I've implemented all of these features before on a proprietary platform, but that doesn't really help oscar, though it was also in python. Heres a screenshot of how variant management could look like.

![snapshot1](https://cloud.githubusercontent.com/assets/244930/7897289/138545d0-06d7-11e5-8cbb-2f85f75f7ed1.png)
 

@john-parton 
I'll have a look at your pull request for the image pr variant. Actually when i think about it, it could also make sense to have multiple images pr variant. The project i work on now could actually use that.

I don't think it would be too bad to deprecate AbstractOption in the next version. It's not good for a platform to have too much legacy stuff going around, and it muddles feature creation with more edge cases. And now that Django 1.8 is here, it would seem that we have to do some breaking changes anyways ?

The case for cleaning this up, would be coherence. It will be much easier to develop plugins and features if you are targeting a single structure. The specific usecase you mentioned with add_to_basket in lists (search etc.) already supports variants and standalone products but the implementation would be much cleaner if it didn't had to include 2 structures. 

You are definitely right that this is multiple tickets in one.

I would like to do some project management on this, and this is probably not the right place to do it :) I also have a plan to make the dashboard a single page app in angularjs and bootstrap, since the current workflow in the dashboard are tedious and would fit a single page app better. As i said earlier i have already developed a full blown e-commerce platform before, but would like to share my work this time around and of course also benefit from having a community.

@digicase 
Would love to have more people working on this. What is your skills ? We will need both frontend and backend to finish this, so i definitely think you would be able to help somewhere.

You are right regarding stock handling the low stock threshold should trigger on individual variants. And multi inline editing for variants is a must on a modern e-commerce platform

Regarding search, there's also much work to be done ! Faceted search would definitely be really nice, and is especially important for clothing. It should be possible to make nice faceted search capabilities with Elastic Search, Solr and Postgres. But it will be hard work.

**Comment by unehub** [comment]
Hello, this can help manage variants (children) of any structure, both the admin and forms.

[Proxy models](https://docs.djangoproject.com/en/1.8/topics/db/models/#proxy-models)

**Comment by john-parton** [comment]
I'm on my phone, so I'll be terse.

@digicase Variants and search is a huge can of worms. I completely rewrote the search app to fix some problems.

You can read a little about that here: https://groups.google.com/forum/m/#!topic/django-oscar/Sl3_jq4KBBc

@jakobholmelund My PR adds a m2m relationship for variant images.

**Comment by jakobholmelund** [comment]
After looking through most of the code, i'm beginning to think that a fork is the best way. The changes i wan't to make is kind of huge. So it will all depend on how willing the core team is to make big changes. All i know right now, is that the product structure and attributes are a total mess right now, and that need to change.

**Comment by unehub** [comment]
@jakobholmelund I support a new fork, +1.

changes are required, the idea is also to make the most natural and friendly called models, there is much code "junk" can be omitted and have a more clean and clear code.

**Comment by digicase** [comment]
@jakobholmelund I'd probably be best at helping with user interface design for managing products and variants. I agree a fork sounds like the best way forward. The core team seems relatively quiet as regards to Oscar changes and maintenance recently.

@john-parton your Elasticsearch implementation sounds very interesting. Would you be able to commit any code for this to an Oscar fork? I'm guessing no if the legal reasons you mentioned are still valid.

**Comment by jakobholmelund** [comment]
Ok. I've started the fork. And for now, it will reside here https://github.com/sonofatailor/django-oscar . I've added a dependency for wq.db(https://github.com/wq/wq.db.git) to handle the api generation, so unless you install the dependencies for that, you won't be able to run the project. I'll be looking in to including dependency installation via the make-file but haven't had time to fix that yet.

**Comment by mvantellingen** [comment]
To be honest I think it's a bit harsh to call it a 'total mess'. I think we can all agree that there are definitely improvements possible. I've implemented it myself using solr and field-collapsing (which seems to be the same as elasticsearch aggregations) and only indexing variants and stand-alone products.

I think we need to define the features we want and then go from there. But if you have can submit a PR we will certainly appreciate it.

**Comment by jakobholmelund** [comment]
Sorry for the hard wording @mvantellingen . Obviously it's not a TOTAL mess ;) Don't get me wrong, i think that Oscar is a great framework, and i'm building my company's website in it. The reason i'm making a fork is because it's not very approachable, i kind of feel like i'm extending the framework to do very basic stuff that i feel should be there out of the box.

I'm currently in the process of rebuilding the catalogue app and you can follow it here https://github.com/sonofatailor/django-oscar . If there's any of the ideas you like i'd be happy to make a pull request. But i'm making some rather big changes to product structure which will probably trickle out to some other apps than Catalogue, the Partners App comes to mind.

**Comment by sasha0** [comment]
@mvantellingen @jakobholmelund is there any feature requests to be discussed? If they are going to be implemented in the fork, maybe we can close the issue? Thanks.

**Comment by john-parton** [comment]
I think we can close this. There are some good ideas in here, but we should probably open up separate issues for each feature or bug (referencing this issue, of course).

**Comment by unehub** [comment]
@sasha0 @john-parton I do not think that the solution is close, if not to seek to solve all the problems raised here.

**Comment by john-parton** [comment]
@unehub I suggest that you open tickets for each problem raised here, referencing this one. I already had a ticket open that covers "Image on variants (for automatic image switching on product page)" and I opened one for deprecating AbstractOption.

Basically, small tickets that cover a specific issue are more likely to get addressed.

**Comment by taedori81** [comment]
@jakobholmelund Have you completed Product structure job?
If yes, How can I use it?

**Comment by jakobholmelund** [comment]
Hi @taedori81 

I never totally completed the new product structure. my efforts can be seen in this branch  https://github.com/sonofatailor/django-oscar/tree/structuralchanges

I had to move on since i had to get some actual work done. I would recommend to keep django-oscar as is, and then build your own system around that by forking.

**Comment by SalahAdDin** [comment]
@jakobholmelund Have you beated with this?

**Comment by jakobholmelund** [comment]
@SalahAdDin Nope. i never got the time to finish it.

**Comment by SalahAdDin** [comment]
So, what are missing in this for finish it ?

**Comment by SalahAdDin** [comment]
@jakobholmelund , what's about it?
