### ISSUE TITLE
API and Dashboard

### ISSUE THREAD

**Issue by jakobholmelund** [django-oscar/django-oscar#1757]
Hi guys

The dashboard could really need some love. I was thinking that it would be awesome if the dashboard was a SPA. To really make this possible, Oscar would need an API. I'm aware of the django-oscar-api . But it's targeting the frontend, and there isn't much activity in the repo. Imo the API should be part of the core. This would make Oscar more modern and appealing to new developers. I would love to hear some input on this idea.

Cheers

**Comment by mvantellingen** [comment]
Yeah the dashboard needs some improvements but i'm not a fan of making it a SPA. We should keep it simple and easily extendable, and if you go the SPA route then it's not possible to simply add additional functionality since you need to add additional frontend code.

So personally i'm -1 on this.

**Comment by jakobholmelund** [comment]
If Oscar had full API coverage it would be easy to make the dashboard SPA so that you could extend or fork that instead. I think it's very limiting for a dashboard to be django-templates only.

In my own fork i'm testing out the wq.db library for api generation, and merging that with the current django-oscar-api project should get it pretty far.

**Comment by maikhoepfel** [comment]
@jakobholmelund Thank you for your thoughts and input. I can see the appeal of making the dashboard a SPA. But I have to agree with @mvantellingen: Making the dashboard a SPA would mean more code when trying to modify it. So I don't think we'll have it in core. But an extension would definitely be welcome.

Furthermore, any work towards improving what is available over the API is most welcome!

This has turned more into a mailing list subject, so if we continue the discussion, let's continue there.
