### ISSUE TITLE
Update customising oscar docs

### ISSUE THREAD

**Issue by mostafa-anm** [django-oscar/django-oscar#1760]
Customising oscar section is confusing. In "Fork the Oscar app" section
http://django-oscar.readthedocs.org/en/releases-1.0/topics/customisation.html

It is currently.

$ ./manage.py oscar_fork_app order yourproject/

It should rather be: 

$ ./manage.py oscar_fork_app order yourappsfolder/

**Comment by sasha0** [comment]
@codeinthehole @maikhoepfel can we merge this PR? Thanks.

**Comment by codeinthehole** [comment]
Done
