### ISSUE TITLE
A translation string error (typo) and a translation string inconsistency

### ISSUE THREAD

**Issue by renemulder** [django-oscar/django-oscar#1777]
On line 99 in core/validators.py it reads:

"This field is invalid as its valud is forbidden"

I suspect this should be: "This field is invalid as its value is forbidden"

In apps/catalogue/abstract_models.py:787 and apps/customer/abstract_models.py:149 you will find this line:

"Code can only contain the letters a-z, A-Z, digits, and underscores, and can't start with a digit."

However in one of them it does not end with the period, thus creating 2 translation strings, rather than a single one. I think in these cases, both need to have the period, or not have the period.

**Comment by sasha0** [comment]
@renemulder submitted PR with fix for typo. Could you please explain issue with translation string? Sinc it's been translated correctly.

**Comment by Bashar** [comment]
@sasha0 the source is typed as valud I saw it on transifex too

**Comment by sasha0** [comment]
@Bashar right, that's for the tip. Updated PR.

**Comment by mvantellingen** [comment]
Merged the fix from @sasha0
