### ISSUE TITLE
Implement hash navigation in dashboard

### ISSUE THREAD

**Issue by jakobholmelund** [django-oscar/django-oscar#1778]
It's really annoying that you can't navigate the dashboard properly. Every time you hit back, you are reset to the default tab position.

For example:

I'm looking at an order, i go to the shipping tap, i press edit, i regret for a moment and press back/cancel/breadcrumb. When i get back the Order contents tap is now active

This is just one example, variant editing comes to mind as another pain point in this regard

**Comment by john-parton** [comment]
This would be nice to have. I have a hack that adds some history in, but specifically only for variant editing.

**Comment by maikhoepfel** [comment]
I totally agree. We're using Bootstrap's tabs, I'm not sure if they support it? Any way, a PR is most welcome!

**Comment by bmihelac** [comment]
Added PR fot this, let me know if needs any change.

**Comment by sasha0** [comment]
Fixed by f6d16fc53e3c0d8012890bda04e1267957982b04.
