### ISSUE TITLE
use Django 1.7 migrations instead of south 

### ISSUE THREAD

**Issue by renlinx007** [django-oscar/django-oscar#1784]
Still using south for migration :/

**Comment by sasha0** [comment]
@renlinx007 what version of Django do you use in your project?

**Comment by renlinx007** [comment]
Its 1.8 & why still use south for migration ?

**Comment by mvantellingen** [comment]
Version 1.0 and 1.1 both have Django 1.7+ migrations. 1.0 also included south migrations since Django 1.6 was supported, these were removed in oscar 1.1
