### ISSUE TITLE
Signature of Repository.get_shipping_methods

### ISSUE THREAD

**Issue by st8st8** [django-oscar/django-oscar#1794]
Line 447 of paypal/express/views.py calls repo.get_shipping_methods with the signature:

def get_shipping_methods(self, user, basket, shipping_address):
    repo = Repository()
    return repo.get_shipping_methods(
        user, basket, shipping_addr=shipping_address)

But in oscar/apps/shipping/repository.py it's given as:

\# API
def get_shipping_methods(self, basket, shipping_addr=None, **kwargs):

ie with no "user" argument. I'm not sure which is correct?

**Comment by sasha0** [comment]
@st8st8 this issue is relevant to django-oscar-paypal application, please report it to corresponding repository issue tracker. Thanks.

**Comment by st8st8** [comment]
I did, three weeks before I filed this one, I'm still awaiting a response...
https://github.com/django-oscar/django-oscar-paypal/issues/99

**Comment by maikhoepfel** [comment]
I'm looking at this issue in `django-oscar-paypal` now, thanks.
