### ISSUE TITLE
Problem with ProductCategory and ProductImage

### ISSUE THREAD

**Issue by Ekivor** [django-oscar/django-oscar#1801]
Hello i try to create an app but i have a problem. I create a product , how can i use ProductCategory?
I mean i don't know how to use this class.

My second problem is how django-oscar manage image ?

Thank's for any help

**Comment by jlmadurga** [comment]
A Product belongs to ProductCategories an the purpose of these categories is for visualization. 
Imagine you have clothes accessories shop. You can divide the products in Ties and Socks.
Category: Accessories
Subcategory: Ties
Subcategory: Socks
Using CategoryView it only shows the products which belongs to the category.

**Comment by Ekivor** [comment]
Thank's for you answer but i don't know how to use it with code. I know why this class exist and this goal but not how to create. I mean how to initializate them.

**Comment by maikhoepfel** [comment]
Hey @Ekivor, thanks for getting in touch. But I feel like this is a generic Django question, and might be best directed to Django support channels. It doesn't sound like an Oscar issue to me; please use the mailing list for general support.
