### ISSUE TITLE
currency filter fails if there's no active translation

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1803]
```python
AttributeError: 'NoneType' object has no attribute 'find'
```

This is because Django 1.7 used to return LANGUAGE_CODE if there's no active translation. Modify line 25 in `templatetags.currency_filters` to restore old behavior:
```python
        'locale': to_locale(get_language() or settings.LANGUAGE_CODE),
```

**Comment by maikhoepfel** [comment]
Sounds about right, John. Thanks for finding this; and feel free to submit a PR and ping me.
