### ISSUE TITLE
Squashing basket migrations raises CircularDependencyError

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1808]
Steps to reproduce:
1. Build the sandbox as described here: http://django-oscar.readthedocs.org/en/latest/internals/sandbox.html#run-the-sandbox-locally
2. Run `sites/sandbox/manage.py squashmigrations basket 0005`
3. Try to start the server back up `sites/sandbox/manage.py runserver`

As far as I can tell, it's because `basket.Basket` has a `ManyToManyField` to `voucher.Voucher`; `voucher.VoucherApplication` has a `ForeignKey` to `voucher.Voucher` and `order.Order`; and `order.Order` has a `ForeignKey` to `basket.Basket`.

I'm not sure how big of an issue this is, but it seems like there is a lot of complicated interdependence between those 3 apps at the model level.

I'll submit a PR with a proposed fix.

``` python
Traceback (most recent call last):
  File "sites/sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
...
django.db.migrations.graph.CircularDependencyError: order.0001_initial, basket.0001_squashed_0005_auto_20150604_1450, voucher.0001_initial
```

**Comment by solarissmoke** [comment]
Closing this based on the discussion in #1809.
