### ISSUE TITLE
Django oscar database

### ISSUE THREAD

**Issue by Ekivor** [django-oscar/django-oscar#1812]
I want to change my database in a json file. But I want to know if someone knows where is the Django-oscar code of the connection to the database and the research in this database. Because I have a lot of difficulty to find it.

**Comment by john-parton** [comment]
Could you please be more specific with your issue? Do you just need help configuring a database connection?

You might want to look at the documentation for django settings, specifically on databases: https://docs.djangoproject.com/en/1.8/ref/settings/#databases

**Comment by Ekivor** [comment]
In fact, I use Django-Oscar. 
But I want to change the code witch access in the database. Not because I have a problem with my database connection, I just want to try to ask Django-Oscar to take data in a file. But I find the specific class:  django.db.utils.ConnectionHandler

Thank you for your answer.

**Comment by john-parton** [comment]
I'm sorry, I think I'm having trouble understanding exactly what you're trying to do.

Are you trying to load data from a JSON file into the database?

**Comment by Ekivor** [comment]
No, i want to made my json file the database. 
I mean i want that django-oscar take the data from json file.

**Comment by john-parton** [comment]
Django is (more or less) built on top of relational databases. There's not really support for using something like a JSON file as the database.

**Comment by iraycd** [comment]
@Ekivor 
1. Do you mean you want to connect it with MongoDB like database?
2. Just some import feature, like from JSON -> DB?

Ans: 
1. It's pretty impossible with present oscar.
2. You should take a look at, [CatalogueImporter](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/partner/importers.py#L21) or  [DemoSiteImporter](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/partner/importers.py#L148). Which can be modified to support JSON. Just inherit it and use it carefully as it's not meant to be used in production.

**Comment by Ekivor** [comment]
Thank you for you answer.
I did it. It's take me a lot of time but now my product are take from json file.
