### ISSUE TITLE
oscar.dashboard.orders.initFilterToggle is not a function

### ISSUE THREAD

**Issue by cdicosmo** [django-oscar/django-oscar#1813]
Hi,

when accessing the orders list in the dashboard the browser console is showing this error:
Uncaught TypeError: oscar.dashboard.orders.initFilterToggle is not a function 

We have experienced the error in our project, but also the oscar sandbox is affected. From the code seems that the orders_list.html template initialize this:

    {% block onbodyload %}
        {{ block.super }}
        oscar.dashboard.orders.initTable();
        oscar.dashboard.orders.initFilterToggle();
        oscar.dashboard.search.init();
        {% if form.errors %}
        $('#SearchModal').modal('show');
        {% endif %}
    {% endblock onbodyload %}

But there is actually no function initFilterToggle() in dashboard.js

**Comment by sasha0** [comment]
@cdicosmo thanks for the report. I'll take a look.

**Comment by maikhoepfel** [comment]
I just merged #1862. Thanks for the excellent bug report @cdicosmo, and thank you for fixing it @sasha0 .
