### ISSUE TITLE
Custom reports

### ISSUE THREAD

**Issue by jakobholmelund** [django-oscar/django-oscar#1818]
Is there an easy way to add custom reports ? It seems that forking the dashboard reports app isn't as straight forward as i hoped.

All i could find, was this old issue https://github.com/django-oscar/django-oscar/issues/32 and it seems like it was never implemented.

**Comment by jakobholmelund** [comment]
Figured it out.. closing..

**Comment by ismaeelsameed** [comment]
jakobholmelund now i'm facing the same issue can you help me figure out the way?

**Comment by jakobholmelund** [comment]
Sure :)

Have tried forking other apps than the dashboard ?

**Comment by ismaeelsameed** [comment]
Got it, thank you @jakobholmelund

**Comment by Prill** [comment]
I've forked another app and I'm not sure what I am missing.
