### ISSUE TITLE
`Line#category` shouldn't return `None` by default

### ISSUE THREAD

**Issue by monokrome** [django-oscar/django-oscar#1819]
I think that this is maybe intended to be overridden on a per-app basis, but it's a bit confusing to try to get the `Category` for a `Line` and see `None` come back.

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/order/abstract_models.py#L545-L551

**Comment by john-parton** [comment]
The comment says it's used by Google analytics, so I wonder if has to be a Google product category: https://support.google.com/merchants/answer/160081?hl=en

Otherwise, here's a basic implementation:

```python
@property
def category(self):
    if self.product:
        return self.product.get_categories()[0]
```

**Comment by monokrome** [comment]
We've solved this in another way internally, but I felt like this may be an issue in the core codebase and wanted to contribute back to see what everyone else thinks.

**Comment by solarissmoke** [comment]
I've just removed this property completely as it isn't doing anything.
