### ISSUE TITLE
Problem with filtering vouchers in dashboard.

### ISSUE THREAD

**Issue by wieslawgorniewski** [django-oscar/django-oscar#1820]
Hi,

Trying to filter vouchers in dashboard gives this error:

"FieldError: Cannot resolve keyword 'start_date' into field. Choices are: applications, basket, code, date_created, end_datetime, id, name, num_basket_additions, num_orders, offers, start_datetime, total_discount, usage, users"

I'm gussing that this line:

`qs = qs.filter(start_date__lte=today, end_date__gte=today)`
should be:
`qs = qs.filter(start_datetime__lte=today, end_datetime__gte=today)`

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/dashboard/vouchers/views.py#L62

At some point Voucher model fields `start_date` and `end_date` were renamed to `start_datetime` and `end_datetime`.

Cheers,
Wieslaw

**Comment by john-parton** [comment]
Looks like this is fixed in master. Here's the commit: https://github.com/django-oscar/django-oscar/commit/b1b224e5286f8e9e84d5adde6c1f8fc7b35bd5e0

**Comment by sasha0** [comment]
@wieslawgorniewski @john-parton I re-checked too, this is fixed.

**Comment by calosth** [comment]
I'm having the same error. If I install it from PyPI.

**Comment by sasha0** [comment]
Should have been already fixed in 1.2. Closing.
