### ISSUE TITLE
Add ability to create/edit 'option groups' from dashboard

### ISSUE THREAD

**Issue by aleprovencio** [django-oscar/django-oscar#1823]
On the dashboard interface, there's no plus sign as the one from the admin (admin/catalogue/productclass/) so I still can't model my catalogue from there or even edit those items as Oscar 1.1 promises.

**Comment by john-parton** [comment]
You can do it through the admin at `/admin/catalogue/attributeoptiongroup/`.

I'm not totally sure that we even need to be able to do this through the dashboard. The admin is 100% working in this case, and I don't see how we could improve on it in the dashboard.

However, I do think that we should document how you actually go about adding option groups.

Here's a related question on the Google group: https://groups.google.com/forum/#!topic/django-oscar/t16xY52If3s

**Comment by aleprovencio** [comment]
Hello @john-parton, I know this is available through the admin, thats the way I model the catalogue since I started to use Oscar.

What I'm saying is that since Oscar 1.1, the dashboard already provides a very good interface for this intent that is very close to be usable, but still it's not because it lacks something as simple as this 'plus sign' I mention.

Also the 1.1 [changelog](https://django-oscar.readthedocs.org/en/releases-1.1/releases/v1.1.html) states that "Product class options and attributes can now be edited in the dashboard.", so even not being a full done job, this makes me think there's a movement towards moving these things from admin to dashboard.

**Comment by john-parton** [comment]
@aleprovencio, Oscar has two different models with very similar names: ["Options"](http://django-oscar.readthedocs.org/en/latest/ref/apps/catalogue.html#oscar.apps.catalogue.abstract_models.AbstractOption) and ["attribute options"](http://django-oscar.readthedocs.org/en/latest/ref/apps/catalogue.html#oscar.apps.catalogue.abstract_models.AbstractAttributeOption).

You can add options to a product class at the dashboard (It's at `/dashboard/catalogue/product-type/1/update/` under the "Product Class details" tab.) This is what was referenced in the changelog. But, as far as I know, you cannot add attribute options or attribute option groups in the dashboard.

Personally, I think folding more stuff into the dashboard is a little silly. If the admin already offers a totally functional interface for a model, _especially_ if the model is infrequently modified, why bother folding it into the dashboard?

Let me know if you have any questions.

**Comment by aleprovencio** [comment]
Alright I got it.

I'm fine with doing stuff from the admin instead of the dashboard.

IMHO keeping the dashboard incomplete the way it is and having to go back and forth to the admin to do things like setting "Options" here "Attribute Options" there, feels somehow confusing.

So maybe if the dashboard development is not aiming to be a more complete solution I think it should be leaner than it is on Oscar 1.1, concerning the catalogue modeling, for clarity sake.

Anyways, it's just my take on it, with all respect for yours and other Oscar dev's awesome job.

**Comment by T4m** [comment]
@john-parton I'm confused by your comment. It contradict the documentation: http://django-oscar.readthedocs.io/en/latest/internals/getting_started.html

> It is important to note that the Django admin site is not supported. It may or may not work and is only included in the sandbox for developer’s convenience.

**Comment by SalahAdDin** [comment]
@aleprovencio any PR is welcome.

**Comment by jonathanmeier5** [comment]
I've just encountered this problem myself. I don't mind rolling my own solution, and will post when/if I do. It seems counter-intuitive to not include something like this in the dashboard UI.

**Comment by iuliuscaesar92** [comment]
@jonathanmeier5 it would be nice if you share your work here, for future use... i think not only you and me faced this problem.

**Comment by iuliuscaesar92** [comment]
btw, i've found a ready to use solution - https://github.com/williamc/django-oscar-modified/tree/master/src/oscar , but i've not tested it yet. Feel free to try if you want :)

**Comment by SalahAdDin** [comment]
I think the same.

**Comment by jwayodi** [comment]
I am working on this, in pull request #2448.

**Comment by solarissmoke** [comment]
Fixed in #2448
