### ISSUE TITLE
Is it bug? Empty image container for product item

### ISSUE THREAD

**Issue by feado** [django-oscar/django-oscar#1831]
Description: I faced random issue when image container for product can be empty
Steps: 
1) Add new product with image in dashboard
2) Save it 
3) Go to the shop
Expected result: I see image for product
Actual result: There isn't image for this product
Workaround: upload this image against
1) there is issue when product item preview doesn't contain image
See below example for product Italian coffee cremoso:

![missed_image](https://cloud.githubusercontent.com/assets/13540228/9461612/75fe247c-4b18-11e5-89b7-4a3a8fe6cb8c.jpg)
![product_view_missed_image](https://cloud.githubusercontent.com/assets/13540228/9461636/8d37f0d2-4b18-11e5-863b-11aa98700c16.jpg)
![coffee_cremoso_dashboard](https://cloud.githubusercontent.com/assets/13540228/9461645/965b7594-4b18-11e5-9fd5-fd257bacf218.jpg)

And please see similar issue when product view item contains image
![missed_image_thumbnail](https://cloud.githubusercontent.com/assets/13540228/9461662/b44f0a98-4b18-11e5-96ca-70d904809e28.jpg)
![Uploading product_view.jpg…]()

Requirements:
django-admin-enhancer==1.0.0
django-appconf==1.0.1
django-bootstrap-form==3.2
django-classy-tags==0.6.2
django-cms==3.1.2
django-compressor==1.5
django-email-extras==0.3.1
django-emailit==0.2.2
django-extra-views==0.6.4
django-filer==0.9.11
django-haystack==2.3.1
django-ipware==1.1.0
django-localflavor==1.1
django-meta==0.3.1
django-meta-mixin==0.1.1
django-mptt==0.7.4
django-oscar==1.1
django-oscar-paypal==0.9.5
django-parler==1.5
django-polymorphic==0.7.1
django-reversion==1.8.5
django-robots==1.1
django-sekizai==0.8.2
django-simple-captcha==0.4.5
django-sizefield==0.7
django-smart-load-tag==0.3.2
django-tables2==1.0.4
django-tablib==3.1.1
django-taggit==0.16.2
django-taggit-autosuggest==0.2.7
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==3.0
django-widget-tweaks==1.3
djangocms-admin-style==0.2.7
djangocms-blog==0.4.0
-e git+https://github.com/jrief/djangocms-cascade.git@173731aa6f14b403c4f9a3b4e5626337a92f2320#egg=djangocms_cascade-master
djangocms-column==1.5
djangocms-flash==0.2.0
djangocms-forms==0.1.5
djangocms-googlemap==0.3
djangocms-inherit==0.1
djangocms-installer==0.7.8
djangocms-link==1.6.2
djangocms-oscar==0.1
djangocms-style==1.5
djangocms-text-ckeditor==2.5.3
easy-thumbnails==2.2
factory-boy==2.4.1
future==0.9.0
html5lib==0.999
jsonfield==1.0.3
lxml==3.4.4
mock==1.0.1
phonenumbers==6.3.0
premailer==2.9.2
psycopg2==2.6.1
purl==1.1
pycountry==1.13
python-gnupg==0.3.7
pytz==2015.4
requests==2.7.0
six==1.9.0
solid-i18n==1.1.0
sorl-thumbnail==12.2
sphinx-me==0.3
tablib==0.10.0
tzlocal==1.2
wsgiref==0.1.2

**Comment by travisjwarren** [comment]
I am having a similar issue but images are not rendering in the product images.

<img width="1280" alt="screen shot 2015-09-29 at 8 47 11 pm" src="https://cloud.githubusercontent.com/assets/233899/10162039/9652ee58-66eb-11e5-8a77-299b29f45cc9.png">

I'm pretty sure my MEDIA_ROOT is correct as my catalogue images serve.

<img width="1280" alt="screen shot 2015-09-29 at 8 48 26 pm" src="https://cloud.githubusercontent.com/assets/233899/10162033/8a4ba6e0-66eb-11e5-97c8-a0cedea408c1.png">

<img width="1280" alt="screen shot 2015-09-29 at 8 48 21 pm" src="https://cloud.githubusercontent.com/assets/233899/10162045/9fc3a86a-66eb-11e5-81d3-c7ff5356afca.png">
<img width="1280" alt="screen shot 2015-09-29 at 8 47 42 pm" src="https://cloud.githubusercontent.com/assets/233899/10162047/a2e9bd18-66eb-11e5-9580-bb396ddbdda2.png">

**Comment by MasterKale** [comment]
I'm having this exact same issue on a brand new install of the latest Oscar. 

### Catalog View:
![screenshot_2015-12-14_16-32-47](https://cloud.githubusercontent.com/assets/5166470/11798523/6c83dd6e-a280-11e5-9d72-ab91dbd4506b.png)

### Dashboard View:
![screenshot_2015-12-14_16-33-03](https://cloud.githubusercontent.com/assets/5166470/11798525/7058e86c-a280-11e5-8a0d-8487df3368aa.png)

And strangely enough I see two Upload Image squares, next to a white square that should display the product image. When I click any of the squares, I get the file upload popup as though I'm attaching a product image:

![screenshot_2015-12-14_16-35-16](https://cloud.githubusercontent.com/assets/5166470/11798553/bcd81104-a280-11e5-83bc-5195f04358d9.png)

After selecting an image, I can see it within my MEDIA_ROOT folder but it never appears on the website. I also never see the `image_not_found.jpg` file that I copy-pasted from `oscar/static/oscar/img/` into my MEDIA_ROOT.

Any idea what might be going on?

**Comment by EddyVelazquez** [comment]
you have to  make this table in your db 

this is from sorl package.thumbnail


**thumbnail_kvstore**

```

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from sorl.thumbnail.conf import settings

@python_2_unicode_compatible
class KVStore(models.Model):
    key = models.CharField(
        max_length=200, primary_key=True,
        db_column=settings.THUMBNAIL_KEY_DBCOLUMN
    )
    value = models.TextField()

    def __str__(self):
        return self.key
```

![image](https://cloud.githubusercontent.com/assets/15119993/16035836/d219e81a-31de-11e6-96e8-cd95fc8d9f44.png)

----------------------------------------------------------------- 

well this worked for me

**Comment by sasha0** [comment]
Closing since it's does not seem to be relevant any more. Please re-open in case of new questions/issues. Thanks!
