### ISSUE TITLE
Random item appears in the basket after registration/login 0.7.2

### ISSUE THREAD

**Issue by wzrd-clss** [django-oscar/django-oscar#1836]
Does anyone know what might cause a random item or items to appear in the basket after registration/login? this issue occurs intermittently for me

**Comment by jlmadurga** [comment]
Check basket middleware when it merges baskets.

**Comment by wzrd-clss** [comment]
it was a merge issue. Im guessing this happened after switching over to a custom user model. any new user id would have then been lesser than any existing owner_id
