### ISSUE TITLE
ImportError: No module named 'custom_apps\\promotions'

### ISSUE THREAD

**Issue by aznnoh** [django-oscar/django-oscar#1838]
Hi, 

After forking app, It is giving this error:

ImportError: No module named 'custom_apps\promotions'

What I have done:

python manage.py oscar_fork_app promotions custom_apps

Creating package custom_apps\promotions

Creating admin.py

Creating app config

Creating models.py

Creating migrations folder

The final step is to add 'custom_apps\promotions' to INSTALLED_APPS
(replacing the equivalent Oscar app). This can be achieved using
Oscar's get_core_apps function - e.g.:

  # settings.py
  ...
  INSTALLED_APPS = [
      'django.contrib.auth',
      ...
  ]
  from oscar import get_core_apps
  INSTALLED_APPS = INSTALLED_APPS + get_core_apps(
      ['custom_apps\promotions'])

INSTALLED_APPS = [

```
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.sites',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.flatpages',
'compressor',
"django.contrib.admin",
'widget_tweaks',
"paypal",
```

] + get_core_apps(['custom_apps.promotions'])

**Comment by sasha0** [comment]
@aznnoh why there's backslash in the application path?

**Comment by solarissmoke** [comment]
Closing due to no response from OP (looks like that backslash is the problem anyway).
