### ISSUE TITLE
NameError in OrderPlacementMixin.save_payment_events()

### ISSUE THREAD

**Issue by webtweakers** [django-oscar/django-oscar#1840]
Just wondering, but shouldn't these lines be indented:

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/checkout/mixins.py#L207-L209

'event' is now out of scope.

**Comment by anentropic** [comment]
I don't know the intent of the code but it might be correct

after the `for` loop above it finishes `event` will still have the value it had in the last iteration of the loop

the comment says `# We assume all lines are involved in the initial payment event` so... if `self._payment_events` is ordered from last to first then the code would agree with the comment

**Comment by mvantellingen** [comment]
It indeed can cause errors  if `self._payment_events` is an empty list.

PS. 'bug?' is a bit to generic title for a bug report :-)

**Comment by solarissmoke** [comment]
Fixed in https://github.com/django-oscar/django-oscar/commit/8b19afc746bfa24557aacc53f58138b37ee58420
