### ISSUE TITLE
Override offers.Benefits and change TYPE_CHOICES

### ISSUE THREAD

**Issue by carn1x** [django-oscar/django-oscar#1843]
Is there a conventional way to tackle this? My override model looks like:

```
class Benefit(AbstractBenefit):
    """
    Override Benefit model so we can inject our own Discount choice and model
    """

    # Benefit types
    MEMBERSHIP_DISCOUNT = (
        "Membership Discount")
    TYPE_CHOICES = (
        (MEMBERSHIP_DISCOUNT, ugettext("Discount is as specified by the product's merchant membership settings")),
    )
```

The problem is that setting the TYPE_CHOICES on the subclass is too late.

I can't override the `type` field directly lest I run into `django.core.exceptions.FieldError: Local field 'type' in class 'Benefit' clashes with field of similar name from base class 'AbstractBenefit'`

I've also tried the following solutions to no effect:

```
    def __init__(self, args, **kwargs):
        type_field = self._meta.get_field_by_name("type")[0]
        type_field.choices = self.TYPE_CHOICES
        super(Benefit, self).__init__(*args, **kwargs)
```

and

```
class Benefit:
   ...
Benefit._meta.get_field('type').choices = Benefit.TYPE_CHOICES
```

But both produce errors and I get the feeling they aren't the right solution here.

**Comment by sasha0** [comment]
@carn1x firstly, what MEMBERSHIP_DISCOUNT intended for? Is it configurable percentage or absolute value benefit?

**Comment by carn1x** [comment]
It's a percentage associated with a Partner and whether current user has a membership in relation to the Partner associated with each Product.

**Comment by sasha0** [comment]
@carn1x then you don't need custom benefit type. Did you try to create custom benefit inherited from percentage benefit model?

**Comment by sasha0** [comment]
Closing since it's lacking feedback for too long and does not seem to be relevant any more. Please re-open in case of new questions/issues. Thanks!
