### ISSUE TITLE
Adding product to Range by SKU broken for duplicate SKUs

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1847]
Steps to duplicate:
- Create two stock records on different products with the same SKU but with different partners
- Add the SKU to a `Range` using `/dashboard/ranges/1/products/`

Result:
- Both products are added to the range without notifying the user that more than one product was added

**Comment by sasha0** [comment]
@john-parton maybe in case of duplication, we could show user list of selected products with checkboxes and ask to confirm selection?

**Comment by sasha0** [comment]
Still think this is the best approach to fix this. Any other ideas? Thanks.

**Comment by sasha0** [comment]
Decided to just show warning message. Fixed in 6169826571e68d2634717bd4e824145a2d9333a9.
