### ISSUE TITLE
ShippingAddressView.get_initial <Country: XXX> is not JSON serializable

### ISSUE THREAD

**Issue by Bogh** [django-oscar/django-oscar#1865]
If you are to return back to the shipping address after you've reached further into the checkout process and you selected a country from the list, doing a GET request to the address /checkout/shipping-address/ would result in the following error:

`TypeError at /shop/checkout/shipping-address/ <Country: XXXXX> is not JSON serializable`

The issue is in here https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/checkout/views.py#L140

Modifying the initial dictionary in this function modifies the same reference that is going to be stored in the session.

**Comment by brunifrancesco** [comment]
Di it work for you? Not for me.

**Comment by Bogh** [comment]
Yes. It worked. You still get the error?
