### ISSUE TITLE
Basket Line Reference with already encoded utf-8 options

### ISSUE THREAD

**Issue by jlmadurga** [django-oscar/django-oscar#1868]
In an ecommerce model with Options a Basket Line Reference is created by its options representation encoded as utf-8. It raises a problem when option value is already encoded in utf-8. 

```python
    def _create_line_reference(self, product, stockrecord, options):
        """
        Returns a reference string for a line based on the item
        and its options.
        """
        base = '%s_%s' % (product.id, stockrecord.id)
        if not options:
            return base
        return "%s_%s" % (base, zlib.crc32(repr(options).encode('utf8')))
```

I imagine this encoding is done because only basket.AttributeLine value supported is charField. In extended models with more rich Attribute values it is a problem.

**Comment by jlmadurga** [comment]
Sorry forgot python3 bytes enconding

**Comment by sasha0** [comment]
I suppose the issue can be closed, since related PR was merged.

**Comment by sasha0** [comment]
Closed since related PR already merged.
