### ISSUE TITLE
ImportError at /admin/products/productimage/9/ No module named PIL

### ISSUE THREAD

**Issue by cristiantoong** [django-oscar/django-oscar#1870]
I successfully run my project in Pythonanywhere but when I tried to upload image in admin

Im getting this error:

ImportError at /admin/products/productimage/9/
No module named PIL
Request Method:	POST
Request URL:	http://djangotest4010.pythonanywhere.com/admin/products/productimage/9/
Django Version:	1.8.4
Exception Type:	ImportError
Exception Value:	
No module named PIL
Exception Location:	/home/djangotest4010/.virtualenvs/env/local/lib/python2.7/site-packages/django/forms/fields.py in to_python, line 674
Python Executable:	/usr/local/bin/uwsgi
Python Version:	2.7.6
Python Path:	
['/var/www',
 '.',
 '',
 '/var/www',
 '/home/djangotest4010/.virtualenvs/env/lib/python2.7',
 '/home/djangotest4010/.virtualenvs/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/djangotest4010/.virtualenvs/env/lib/python2.7/lib-tk',
 '/home/djangotest4010/.virtualenvs/env/lib/python2.7/lib-old',
 '/home/djangotest4010/.virtualenvs/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/djangotest4010/.virtualenvs/env/local/lib/python2.7/site-packages',
 '/home/djangotest4010/.virtualenvs/env/lib/python2.7/site-packages',
 '/home/djangotest4010/src']
Server time:	Tue, 13 Oct 2015 20:44:00 +0000

**Comment by john-parton** [comment]
This sounds like an issue with PythonAnywhere. I'm not familiar with that service, but you might try their forums.

https://www.pythonanywhere.com/forums/topic/217/

**Comment by mvantellingen** [comment]
Hi @cristiantoong, it indeed seems to be a problem with your python install so I'm closing this for now.
