### ISSUE TITLE
Search results sorting returns results in wrong order

### ISSUE THREAD

**Issue by bharling** [django-oscar/django-oscar#1872]
I'm having lots of problems with all types of sorting of search results. First off I'm using the haystack backend. Sorting by price gives me results ordered by the first digit in the price eg: £7.30 consistently comes before £12.30 in a descending search. Also title search seems to be reversed. I'm using oscar 1.2. 

We have a custom Strategy and pricing policy in place, but they differ very little from the default implementation. My search indexes are up to date. 

Has anyone else hit this ?

**Comment by bharling** [comment]
Just finished setting up SOLR in my dev environment and sorting magically working fine. I think the docs could be clearer that actually SOLR is the only search engine of any use with oscar ?

**Comment by john-parton** [comment]
What backend were you using first? Whoosh?

Generally, elasticsearch is "as good" as solr.

**Comment by bharling** [comment]
I had tried whoosh and elasticsearch, both with the same result when it came to ordering of search results. Solr is working great for me at the moment, but is quite a lot more painful to configure than the other options ( spent a good portion of today configuring staging and production environments with it :( )

I guess this could be closed really, but I'd still suggest that the docs could be clearer that you're going to get a lot better results with solr than other options.

**Comment by digicase** [comment]
I tried elasticsearch first of all and had trouble with the search facets - they basically didn't work at all. As soon as I switched to solr the faceting worked. So I don't think elasticsearch can be considered "as good" as solr when it comes to Oscar support. It would be nice if elasticsearch was better supported by Oscar, as I found the same as @bharling that solr was harder to set up.

**Comment by john-parton** [comment]
Elasticsearch works fine. It's just that Oscar and Haystack "out of the box" don't really take full advantage of it.

I use elastic as my backend, but I had to [almost] completely replace the search app. I used [elasticsearch-dsl-py](https://github.com/elastic/elasticsearch-dsl-py) to actually generate the elastic queries, and a bunch of custom classes to glue it all together. More info on the google group: https://groups.google.com/forum/#!msg/django-oscar/Sl3_jq4KBBc/QPfFgEY_BCYJ

You can try it out [here](https://pillowcentral.com/search/) if you would like.

**Comment by Mohl** [comment]
This is a known issue for almost 5 years now - https://github.com/django-haystack/django-haystack/issues/398

**Comment by digicase** [comment]
Thanks @Mohl that worked for me with Solr 4.10.4 and Haystack 2.4.1

In case anyone else finds this, there is a small typo in your comment. It should read `FloatField` instead of `Floatfield`. Here is my adapted function for preparing the price.

    def prepare_price(self, obj):
        result = None
        if obj.is_parent:
            result = strategy.fetch_for_parent(obj)
        elif obj.has_stockrecords:
            result = strategy.fetch_for_product(obj)

        if result:
            if result.price.is_tax_known:
                return result.price.incl_tax
            return result.price.excl_tax
        else:
            return float(0.0)

**Comment by SalahAdDin** [comment]
Where use you this?

Can you make a pull request?

**Comment by vaskinyy** [comment]
Sorting by title with elasticsearch backend doesn't work in Oscar. Because title is stored as an eged ngram in the elasticsearch index, sorting doesn't work for this type of items in elasticsearch index with standard settings. I just create another title item in the index, that is just a CharFiled, and sort by it. I'll do a pull requesto on that

**Comment by SalahAdDin** [comment]
@vaskinyy We have use old elasticsearch version, right?

**Comment by vaskinyy** [comment]
Yes, 1.7.*

**Comment by sasha0** [comment]
Fixed by PR #2226.
