### ISSUE TITLE
Include the lessc binary so that `make css` is the same across environments

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1877]
... exactly what it says in the title.

This would make pull requests that make simple less changes cleaner, fixing the issue if the contributor has a different version of less that causes minor differences in css output.

**Comment by mvantellingen** [comment]
Did you mean to add the lessc binary to the oscar repository? I don't think that is the way to go :-)
We should probably just add npm / gulp ala wagtail

**Comment by john-parton** [comment]
Is there any current work to add npm or gulp? Can you point me in the right direction so I can start work on it?

Thanks.

**Comment by maikhoepfel** [comment]
Hi John, what do you use the binary for? I just added the on-the-fly pre-processor in https://github.com/django-oscar/django-oscar/pull/1890, maybe that's enough?

**Comment by john-parton** [comment]
When you call `make css` it uses your system's binary. https://github.com/django-oscar/django-oscar/blob/master/Makefile#L95-L101

If you happen to have a different version of LESS installed, you might get slightly different output, which makes diffs hard to read.
