### ISSUE TITLE
include import OSCAR_MAIN_TEMPLATE_DIR in docs

### ISSUE THREAD

**Issue by dhruvnarang** [django-oscar/django-oscar#1880]
I was going through the docs and in templates dircs, OSCAR_MAIN_TEMPLATE_DIR was used which was not found. Inlucde 

```
from oscar import OSCAR_MAIN_TEMPLATE_DIR 
```

in docs before defining templates in settings.py .

**Comment by john-parton** [comment]
I think this is covered in the docs here: http://django-oscar.readthedocs.org/en/latest/howto/how_to_customise_templates.html#method-2-subclass-parent-but-use-same-template-path

Unless there's something else missing?

**Comment by sasha0** [comment]
Right, documentation per link above is clear about usage of the setting, thanks John.
