### ISSUE TITLE
Email templates incorrectly escape product names

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1885]
If you have a product that has a quote `"` character, it's rendered as `&quot;` in the emails.

The simplest solution is to use a `|safe`. Wrapping the entire body or subject in `{% autoescape off %}` is another option, but that could have other effects.

**Comment by aleprovencio** [comment]
Hello @john-parton, unfortunately for my product titles to show up correctly (not empty) on the alert emails I have to take the `|safe` out from it. What can be wrong?
