### ISSUE TITLE
messages.error outputs `alert-error` class instead of `alert-danger`

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1895]
This results in the alert having black text with a transparent background, instead of the expected red.

Some discussion on how it might be fixed: https://github.com/django-oscar/django-oscar/pull/1887#issuecomment-151642361

![screenshot from 2015-10-27 16 07 26](https://cloud.githubusercontent.com/assets/2071543/10772605/f6c84b54-7cc4-11e5-9d28-678e826474e8.png)

**Comment by sasha0** [comment]
Fixed in ea28ecfcf63565816e1b26ba068943d6f179a6e8.
