### ISSUE TITLE
Point demo.oscarcommerce.com at correct server

### ISSUE THREAD

**Issue by chrismckinnel** [django-oscar/django-oscar#1896]
At the moment it's a dead-end.

I reckon you could point it at 54.77.234.211 (the box that latest.oscarcommerce.com points to)

**Comment by pajooh** [comment]
why the demo is not alive for a while?

**Comment by mvantellingen** [comment]
The demo site isn't kept up-to-date with the recent oscar changes due to time constraints. So the current plan is to remove the demo site from the repository and move it to a separate repo.

**Comment by mvantellingen** [comment]
The demo site is removed from the repository (see #1911). It might be cool to get it back in a separate repository but we need some help with that.

**Comment by chrismckinnel** [comment]
Nice one!
