### ISSUE TITLE
skip condition in checkout causes internal server error

### ISSUE THREAD

**Issue by Rodrockz** [django-oscar/django-oscar#1899]
in `oscar/apps/checkout/session.py`, line 235:
`shipping_charge = D('0.00')`

In the next line shipping charge is passed to `get_order_totals`, which passes shipping charge to the `OrderTotalCalculator`. 

The `OrderTotalCalculator` tries to access the attribute `shipping_charge.excl_tax`, which does not work for decimal objects.

`shipping_charge`cannot be a decimal object.

**Comment by sasha0** [comment]
@Rodrockz fixed in @1af7b40bc591c2f9d1637884ebed5dab836124ad. Thanks for the report.
