### ISSUE TITLE
Recommended Products have no order

### ISSUE THREAD

**Issue by dimka665** [django-oscar/django-oscar#1901]
We can see ranking on Recommended products in Dashboard only.
There are no ordering on Product detail page.

Oscar master, Django 1.8

**Comment by dimka665** [comment]
To implement this we need something like https://github.com/gregmuellegger/django-sortedm2m

**Comment by sasha0** [comment]
Apart from that, noticed formset styling issues locally, recommended product dropdowns have different width and not aligned:
![2015-11-22 11 27 36](https://cloud.githubusercontent.com/assets/673711/11324587/646340be-913e-11e5-8e3c-f659b29cd756.png)
And initially dropdown is too narrow:
![2015-11-22 11 27 51](https://cloud.githubusercontent.com/assets/673711/11324589/681d1432-913e-11e5-931a-c1544ddc13ec.png)

Did you experience that too locally @dimka665 @mvantellingen @john-parton ?

**Comment by john-parton** [comment]
@sasha0 I don't use the recommend products feature, so I really don't know. 

I actually search my elasticsearch backend with a "more like this" query.
