### ISSUE TITLE
Add option product attribute to a product.

### ISSUE THREAD

**Issue by vkaracic** [django-oscar/django-oscar#1903]
I cannot find anywhere an example how to add an options ProductAttribute to a Product object.
A code example like this one for entity here would be great:
http://django-oscar.readthedocs.org/en/latest/topics/modelling_your_catalogue.html#product-attributes

**Comment by onewaytoconnect** [comment]
you can add product attribute in product type from catalogue menu

example above depicts same

**Comment by vkaracic** [comment]
Thanks but I am not looking for any UI based solutions. I want to do this via code. I found out how to do it in the meanwhile, I'll create a PR for the documentation to add that as well.
