### ISSUE TITLE
Long rendered page when a lot of categories products

### ISSUE THREAD

**Issue by amirrpp** [django-oscar/django-oscar#1910]
_Sorry for my english._

When we have a lot of categories (and subcategories) the list of products render a long time because Django search products in all subcategories of current category.
#### I have:
- 1,100 Categories and subcategories
- 40,000 products
- The average depth of 4 categories
- In the navbar need to show categories first and second level of nesting. In this category you need to show only those that have products (at least one of the subcategories). Therefore, it is necessary to once again pass through the tree categories. Navbar appear on each page.
- On pages /catalogue/\* it is necessary to show the sidebar (the children of the currently selected category), the logic of both the navbar.
#### Possible solution cache search at a template. But:
- In the category affected by external factors
- Sidebar for each of your categories
- A list of products will be formed is still a long
### The best decision:

Show products only selected category. When we create the product and choose him a category, it must be added that the goods in the category-parents.
For example like this:

``` python
class AbstractProduct(models.Model):

    def save(self, *args, **kwargs):
        super(AbstractProduct, self).save(*args, **kwargs)
        product_categories = ProductCategory.objects.filter(product=self)
        for product_category in product_categories:
            product_category.save()


class AbstractProductCategory(models.Model):

    def save(self, *args, **kwargs):
        super(AbstractProductCategory, self).save(*args, **kwargs)
        product = self.product
        category = self.category
        parent = category.get_parent()
        if not parent:
            return
        ProductCategory.objects.update_or_create(product=product, category=parent)
```

Of course this has its problems.

What do you think?

**Comment by mvantellingen** [comment]
Hi, this might be related to #1828 I've promised @maikhoepfel to make a test case for this issue

**Comment by maikhoepfel** [comment]
And I promised to help fix this instead of reverting to the old code. I'm happy to leave this open until the issue resolved. @amirrpp, thank you for the detailed write-up. This helps us think about the issue.

**Comment by shimulch** [comment]
Hi,

I have experienced same issue with v1.5. It was due to ```get_ancestors()``` call while ```get_absolute_url()``` has got called. So I have done a hack in my overriden Category class as following -

```python
    def _get_ancestors_cache_key(self):
        paths = [
            self.path[0:pos]
            for pos in range(0, len(self.path), self.steplen)[1:]
        ]
        key = str(paths)
        return key.replace(',', '').replace('\'', '').replace('[','N').replace(']','N').replace(' ', '')

    def get_ancestors(self):
        key = self._get_ancestors_cache_key()
        cached_val = cache.get(key)
        if cached_val is not None:
            # print("Found cache for %s", str(paths))
            return cached_val

        result = super(AbstractCategory, self).get_ancestors()
        cache.set(key, result)

        return result
```
I think there might be better way to do this. Also need to invalidate cache while category gets updated from dashboard. I will probably do that by overriding save method.

Hope it helps someone else. Or if you find an issue with this hack, would be nice to learn.
