### ISSUE TITLE
Exceptions when price_excl_tax is unset

### ISSUE THREAD

**Issue by mafrosis** [django-oscar/django-oscar#1912]
The Oscar product admin allows the `price_excl_tax` field to be left unset, however an exception occurs when adding a product to the basket if this field is empty.

Similarly, if I have a product in my cart, and then clear the `price_excl_tax` field, an exception occurs when I try to view my basket.

Bottom line: `price_excl_tax` needs to be mandatory.

**Comment by sasha0** [comment]
Stock record could import price from external service or etc and that could be the case that price is updated yet - for this case it might be an option to prohibit product adding to busket if `price_excl_tax`.
What do you think @john-parton @mvantellingen ?
