### ISSUE TITLE
Multilingual not working on 127.0.0.1:8000/xx-xx/catalogue/category/some-item

### ISSUE THREAD

**Issue by ctchanac** [django-oscar/django-oscar#1925]
I have two languages.
In the settings.py:
`LANGUAGES = (
    ('en', gettext_noop('English')),
    ('zh-cn', gettext_noop('Simplified Chinese')),
)
`
When i go to http://127.0.0.1:8000/zh-cn/catalogue/category/some-item,
the page will redirect to http://127.0.0.1:8000/en/catalogue/category/some-item
And the status code of the request is 301 MOVED PERMANENTLY (from cache)

Everything seems working normally except the category page.
All these pages can display Chinese language.
http://127.0.0.1:8000/zh-cn/offers/
http://127.0.0.1:8000/zh-cn/catalogue/
http://127.0.0.1:8000/zh-cn/catalogue/some-item/
http://127.0.0.1:8000/zh-cn/dashboard/

**Comment by mvantellingen** [comment]
Yup, can reproduce it here. Thanks for the report

**Comment by ctchanac** [comment]
Thanks.
I think i solved this problem by deleting `cache.set(cache_key, url)` in catalogue/abstract_model.py
class AbstractCategory:
```
def get_absolute_url(self):
        """
        Our URL scheme means we have to look up the category's ancestors. As
        that is a bit more expensive, we cache the generated URL. That is
        safe even for a stale cache, as the default implementation of
        ProductCategoryView does the lookup via primary key anyway. But if
        you change that logic, you'll have to reconsider the caching
        approach.
        """
        cache_key = 'CATEGORY_URL_%s' % self.pk
        url = cache.get(cache_key)
        if not url:
            url = reverse(
                'catalogue:category',
                kwargs={'category_slug': self.full_slug, 'pk': self.pk})
            #cache.set(cache_key, url)
        return url
```

**Comment by sasha0** [comment]
@ctchanac @mvantellingen I've prepared pull request.

**Comment by maikhoepfel** [comment]
Thanks for the fix, @sasha0!
