### ISSUE TITLE
How to use dynamic pricing?

### ISSUE THREAD

**Issue by kapil019** [django-oscar/django-oscar#1927]
https://github.com/django-oscar/django-oscar/issues/599
How i can use dynamic pricing?

**Comment by sasha0** [comment]
Please describe what you actually want to implement using dynamic pricing.

**Comment by kapil019** [comment]
I am having some forms, User fill data in fields like age, Then i am to offer dynamic price of product (On base of age)

Example
Age: 20, Product A (Price 100)
Age: 30, Product A (Price 120)

**Comment by kapil019** [comment]
@sasha0 Any support for this type of problem? I really need this,

**Comment by sasha0** [comment]
Please explain why there's one product for different types of customers.

**Comment by kapil019** [comment]
@sasha0 This is a problem of policy, There are some plans those have different  premium for different age groups,

**Comment by kapil019** [comment]
@sasha0 Any solution for this?

**Comment by mvantellingen** [comment]
Hi @kapil019, you can use the mailinglist to ask these kind of questions. But it should be possible with a custom strategy class in combination with some logic in the pricing policy
