### ISSUE TITLE
Difficult to customize basket message logic (offer gained, offer lost, new total)

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1929]
`apps.basket.views.get_messages` and `apps.basket.views.apply_messages` aren't customizable. It's possible to change the messages by overriding the templates, but if you want to pass in some additional context or disable a message completely, there's no good way to do that.

One simple solution would be to move `get_messages` and `apply_messages` to a class and then load in the class with `get_class`.

**Comment by maikhoepfel** [comment]
Fixed by https://github.com/django-oscar/django-oscar/issues/1930

**Comment by mvantellingen** [comment]
I assume we can close this then? Otherwise please re-open :-)
