### ISSUE TITLE
Re-ordering from order history assumes order numbers are ints

### ISSUE THREAD

**Issue by bharling** [django-oscar/django-oscar#1931]
It seems in most of oscar Order numbers are assumed to be strings rather than ints, but in the OrderLineView do_reorder assumes an int.

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/customer/views.py#L565-L567

Is this the correct behaviour, since overriding order generation is encouraged, and doesn't explicitly say the numbers generated should be ints ?

**Comment by mvantellingen** [comment]
Good catch. Order numbers are indeed allowed to be strings so we should use natural sorting for this.

**Comment by mvantellingen** [comment]
Fixed, and ignore my natural sorting remark (no idea what I was thinking) :-)

**Comment by bharling** [comment]
Thanks! :)
