### ISSUE TITLE
nvalid template library specified. ImportError raised when trying to load 'treebeard.templatetags.admin_tree': No module named util

### ISSUE THREAD

**Issue by zhljen** [django-oscar/django-oscar#1932]
The issue happens on Mac. Try to install the oscar on Mac, the issue happens when executing make sandbox.
..i/Projects/other/django-oscar/oscar/lib/python2.7/site-packages/django/template/backends/django.py", line 148, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'treebeard.templatetags.admin_tree': No module named util
make: *** [build_sandbox] Error 1

**Comment by mvantellingen** [comment]
Hi,

This is a duplicate of #1928

**Comment by zhljen** [comment]
Thank you!
