### ISSUE TITLE
ImportError raised when trying to load 'treebeard.templatetags.admin_tree': No module named util

### ISSUE THREAD

**Issue by zhljen** [django-oscar/django-oscar#1933]
On MAC during the make sandbox
site-packages/django/template/backends/django.py", line 148, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'treebeard.templatetags.admin_tree': No module named util
make: *** [build_sandbox] Error 1

**Comment by redaelli** [comment]
I think that this problem is related to django 1.9, try this:
```bash
pip uninstall django
```
than
```bash
pip install "django<1.9"
```

**Comment by a115** [comment]
@redaelli How is this a solution??

**Comment by maerteijn** [comment]
@a115, well for now it is until the dependencies are correct or until it's compatible with djang 1.9

**Comment by mvantellingen** [comment]
1.3 will be compatible with django 1.9
