### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by rogueleaderr** [django-oscar/django-oscar#1938]
Showing nginx splash page. Hopefully just needs a server reset!

![welcome_to_nginx_](https://cloud.githubusercontent.com/assets/1051233/11703134/43d44fc2-9e91-11e5-9760-9075738459df.png)

**Comment by maerteijn** [comment]
This is also true for "browse the sandbox" (http://latest.oscarcommerce.com). Should be better to drop the navigation items on the site or to fix this (I would be happy to help).

**Comment by mvantellingen** [comment]
The demo site was removed in #1911 because it was out of date. If there are still reference to the demo site then we should probably remove them (thought i removed them all)

Regarding the sandbox we will need to ask @codeinthehole

**Comment by maerteijn** [comment]
The demosite is still referenced on the homepage of http://oscarcommerce.com

**Comment by rogueleaderr** [comment]
@mvantellingen I'd just like to say that having a demo site is very helpful for people like me. I'm evaluating eCommerce frameworks and haven't done an eCommerce project before. Django-oscar's documentation is great but it's large and it's a lot to take in. Being able to see the system working before committing to installing it is very helpful in deciding whether it suits my requirements.

**Comment by mazulo** [comment]
I totally agree @rogueleaderr +1

**Comment by mvantellingen** [comment]
@rogueleaderr I think that the sandbox gives a much better demo experience. It is also kept up-to-date with all the changes in Oscar.

I've just created a new repository with the old demo code for history purposes (https://github.com/django-oscar/django-oscar-demo), although if people want to work on making it compatible with the latest oscar release again that would be great.
