### ISSUE TITLE
Repository.get_default_shipping_method should has a confusing name.

### ISSUE THREAD

**Issue by monokrome** [django-oscar/django-oscar#1939]
It looks like `get_default_shipping_method` is actually supposed to return the shipping method for the current checkout session. This is very confusing, because it is named in a way that implies that it is only expected to give the default shipping method.

I would like to rename it to `get_current_shipping_method` with a fallback to the name `get_default_shipping_method` for legacy support. I will be happy to create a pull request if this seems reasonable, but would like to get others' thoughts on this issue.

**Comment by sasha0** [comment]
I think by default we just select first available shipping methods from list of all shipping methods. Thus,  if `Repository.get_available_shipping_methods` is not overridden, shipping method returned by `Repository.get_default_shipping_method` won't vary per checkout session.

Anyway, on my point of view I would have thought about `get_current_shipping_method` as a name for method that returns already selected shipping method during current checkout session.

**Comment by monokrome** [comment]
If that is the case then I think it makes sense, and maybe it's related to us being on an older version of Oscar - but it's returning the current session's shipping methods for us.

Also, it thinks to take things like the basket into account since it functionally inherits `get_shipping_methods` here:

https://github.com/django-oscar/django-oscar/blob/481c61f0ff24c93608c0eafaff927f61e456b421/src/oscar/apps/shipping/repository.py#L38-L52

Since `get_shipping_methods` functionally inherits `get_available_shipping_methods`:

https://github.com/django-oscar/django-oscar/blob/481c61f0ff24c93608c0eafaff927f61e456b421/src/oscar/apps/shipping/repository.py#L32-L33

So, it seems to be based on a particular user session since it uses `get_available_shipping_methods` and it's also inherently based on a specific basket. The confusion that my team ran into was that the name implies that it's a default, not that it's based on the current session.

**Comment by sasha0** [comment]
Indeed - I reviewed this again and method naming might be confusing, since we get default shipping method for the current basket. Although, would it make more sense to introduce method which return default standalone shipping method, unrelated with the current session?

What do you think @solarissmoke @mvantellingen ?

**Comment by solarissmoke** [comment]
> Would it make more sense to introduce method which return default standalone shipping method, unrelated with the current session?

I don't think there is such a thing :-). All the repository methods take a `basket` argument and it is quite possible to have projects where the concept of a default doesn't make sense (i.e., where it really depends on the basket).  

I guess I have the same view about `get_default_shipping_method` - like all the repository methods it takes a basket argument so it seems fine to me it is basket-specific. Maybe we just need some documentation to highlight this.
