### ISSUE TITLE
Basket quantity value isn't visible if 'Update' button label has length > 8 (translated versions)

### ISSUE THREAD

**Issue by slava-mitin** [django-oscar/django-oscar#1949]
![oscar-basket-screenshot](https://cloud.githubusercontent.com/assets/16369255/11917444/2a399984-a718-11e5-870f-81f48b5b05fe.jpg)

**Comment by sasha0** [comment]
@slava-mitin could you please check in browser element inspector which element width is enough to display quantity control correctly? Thanks.

**Comment by slava-mitin** [comment]
I don't know which width is enough for all languages. 

The way you can reproduce the issue:
- open file templates/oscar/basket/partials/basket_content.html
- find row 66 "button class="btn btn-default" type="submit" data-loading-text="{% trans 'Updating...' %}" {% trans "Update" %} /button"
- replace {% trans "Update" %} with "Update01"

**Comment by slava-mitin** [comment]
If you are going to fix it only for Russian language you could set other translation for 'Update' in this context - 'Задать' instead of 'Обновить'
