### ISSUE TITLE
TinyMCE moved, hence editing in dashboard broken

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1950]
We load TinyMCE in [dashboard/layout.html](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/dashboard/layout.html#L158). The URL we use (tinymce.cachefly.net/4.0/tinymce.min.js) seems to time out. TinyMCE [documents](https://www.tinymce.com/download/) a different URL, so I'm guessing we need to update. 

I'm guessing this means dashboard editing of rich-text fields is broken at the moment.

Unfortunately, I don't have time to dig further into this. Our docstring mentions something about dynamically loading, and I'm not sure about the jQuery integration, so I hope somebody can have a look and properly test it before fixing.

**Comment by sasha0** [comment]
@maikhoepfel I'll look into it.

**Comment by sasha0** [comment]
@maikhoepfel despite old ULR loads fine for me, I have upgraded TinyMCE to latest version.
Please check.
