### ISSUE TITLE
Django-Oscar: Error extending base class “AbstractShippingAddress” from the app “address”

### ISSUE THREAD

**Issue by hugosalas91** [django-oscar/django-oscar#1952]
Hello I have a problem that makes me crazy. I want to add one field "company" to the class ShippingAddress. I do the next:

Forking the app order of django-oscar.
In the file models.py of the order app I write the next code:

```
from oscar.apps.address.abstract_models import AbstractShippingAddress
 
class ShippingAddress(AbstractShippingAddress):
    company = models.CharField("Empresa", max_length=255)

from oscar.apps.order.models import *  # noqa*
```
I get the next error:
```
...lib/python3.3/site-packages/django/apps/registry.py", line 221, in register_model
(model_name, app_label, app_models[model_name], model))
RuntimeError: Conflicting 'shippingaddress' models in application 'order': <class 'oscar.apps.order.models.ShippingAddress'> and <class 'apps.order.models.ShippingAddress'>.
```

I'm using Django==1.8.6, django-oscar==1.1.1 and python 3.3.

If you can help me I will be so grateful.

**Comment by maerteijn** [comment]
My first guess is that you should fork the `address` app, not the `order` app (the model is defined in `address`)

**Comment by hugosalas91** [comment]
Thanks for your quick response maerteijn, but that was my first solution and it neither didn't work.

**Comment by maerteijn** [comment]
Can you show me your INSTALLED_APPS section of your settings.py?

**Comment by hugosalas91** [comment]
Of course maerteijn, you have here:

```
DEFAULT_APPS = [
	'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
]

THIRDPARTY_APPS = [
    'compressor',
    'widget_tweaks',
]

LOCAL_APPS = [
	'apps.manipulados_papel', 
	'apps.user', 
]

INSTALLED_APPS = DEFAULT_APPS + THIRDPARTY_APPS + LOCAL_APPS + get_core_apps(['apps.customer', 'apps.partner', 'apps.shipping', 'apps.basket', 'apps.checkout', 'apps.address', 'apps.order'])
```

**Comment by hugosalas91** [comment]
The remaining base classes I can inherit them without problems, I only have problems inheriting AbstractShippingAddress.

**Comment by maerteijn** [comment]
I suspect a circular import (you maybe imported `ShippingAddress` in one of your other apps), so try to adjust your `settings.py` adding apps on by another (start with just adding `get_core_apps(['apps.order'])`.

I tried a sandbox oscar with python-2.7 and 3.5. I customized exactly what you did and executed `./manage.py makemigrations && ./manage.py migrate` which did the job:
```
Migrations for 'order':
  0004_shippingaddress_company.py:
    - Add field company to shippingaddress 
```
And I could see your defined field in the admin:
![django](https://cloud.githubusercontent.com/assets/121401/11942049/321a2bba-a834-11e5-82e3-ecfb3f8948bc.png)

(PS the line `from django.db import models` from your `models.py`, is not there, but I assume that you would already figured that out :) )

**Comment by hugosalas91** [comment]
I'm very grateful to you maerteijn, my error was very silly. In my app manipulados_papel in the file models.py I had writting:

```
# yourproject/order/models.py

# your custom models go here

from oscar.apps.order.models import *
```
It was an error in copy paste. I only had that delete the line `from oscar.apps.order.models import *`.

**Comment by maikhoepfel** [comment]
@hugosalas91 sounds like this is resolved? :) @maerteijn, thanks for helping out. I'll close the issue then.
