### ISSUE TITLE
Sandbox Instructions Reference Missing Make Targets.

### ISSUE THREAD

**Issue by kphretiq** [django-oscar/django-oscar#1953]
Attempting some of the demos. In particular the us_site.

    http://django-oscar.readthedocs.org/en/releases-1.1/internals/sandbox.html#the-us-site

It appears neither "us_site" nor "demo" are actually targets in the Makefile.

    (oscar)user@mokk:~/django-oscar$ make us_site
    make: *** No rule to make target 'us_site'.  Stop.
    (oscar)user@mokk:~/django-oscar$ make demo
    make: *** No rule to make target 'demo'.  Stop.
    (oscar)user@mokk:~/django-oscar$ make me_dance_like_a_monkey
    make: *** No rule to make target 'me_dance_like_a_monkey'.  Stop.

Am I missing something really basic, here?

Sorry to be a pain, I'm wanting a glance at the us_site shipping methods to help get my head around what needs to be done.

**Comment by maerteijn** [comment]
The demosite has been removed as it was out of date, https://github.com/django-oscar/django-oscar/commit/51980c748463d14f82295b6ad349f8cfa47580f2 (So this means the documentation needs to be updated).

You could try a released version (for example https://github.com/django-oscar/django-oscar/tree/releases/1.1) where it's still in there.

**Comment by beckastar** [comment]
Are there any example sites to look at?
