### ISSUE TITLE
Can't install it!

### ISSUE THREAD

**Issue by boopr** [django-oscar/django-oscar#1955]
Hello,

When I run :   
`pip3 install django-oscar`

I've this error :  
```
Downloading/unpacking django<1.9,>=1.7.8 (from django-oscar)
  Could not find any downloads that satisfy the requirement django<1.9,>=1.7.8 (from django-oscar)
Cleaning up...
No distributions at all found for django<1.9,>=1.7.8 (from django-oscar)
```

Why? I'm running inside a virtualenv (Python 3). And I don't have any problem with Django usally...

Thanks for your help!

**Comment by ashwin31** [comment]
I got different issue when i tried to install it

 pip install django-oscar
Downloading/unpacking django-oscar
  Downloading django_oscar-1.1.1-py2.py3-none-any.whl (4.9MB): 4.9MB downloaded
Downloading/unpacking django-tables2<1.1,>=1.0.4 (from django-oscar)
  Downloading django-tables2-1.0.5.tar.gz (981kB): 981kB downloaded
  Running setup.py (path:/tmp/pip-build-RsiJU6/django-tables2/setup.py) egg_info for package django-tables2
    
Downloading/unpacking phonenumbers<7.0.0,>=6.3.0 (from django-oscar)
  Downloading phonenumbers-6.3.0.tar.gz (2.1MB): 2.1MB downloaded
  Running setup.py (path:/tmp/pip-build-RsiJU6/phonenumbers/setup.py) egg_info for package phonenumbers
    
    warning: no files found matching 'MANIFEST'
    warning: no previously-included files found matching '.*ignore'
Downloading/unpacking django-compressor>=1.4 (from django-oscar)
  Could not find any downloads that satisfy the requirement django-compressor>=1.4 (from django-oscar)
Cleaning up...
No distributions at all found for django-compressor>=1.4 (from django-oscar)
Storing debug log for failure in /home/ashwin/.pip/pip.log

**Comment by maerteijn** [comment]
I suspect some glitches with pypi. I tried `pip install django-oscar` with python3.5 and python2.7 and both install fine.

@boopr what happens when you install Django first in your virtualenv? (`pip install Django==1.8.7`)
@ashwin31: what if you try to install django-compressor first? (`pip install django-compressor>=1.4`)

**Comment by mvantellingen** [comment]
@boopr and @ashwin31  what is the output of `pip --version` ?

**Comment by ashwin31** [comment]
@mvantellingen its installing now. I guess, it was some pypi issue. You can close this issue.

**Comment by mvantellingen** [comment]
Ok, thanks for the report :+1:
