### ISSUE TITLE
Compress not found

### ISSUE THREAD

**Issue by Gigha** [django-oscar/django-oscar#1961]
Hello,

I was just starting to look into Django-Oscar, and by doing that I cloned the repo and tried to start running it.

However when I set up the sandbox site I get the following error:
```
TemplateSyntaxError at /en-gb/
'compress' is not a valid tag library: Template library compress not found, tried django.templatetags.compress,django.contrib.admin.templatetags.compress,django.contrib.flatpages.templatetags.compress,django.contrib.staticfiles.templatetags.compress,django_extensions.templatetags.compress,compress.templatetags.compress,debug_toolbar.templatetags.compress,widget_tweaks.templatetags.compress,oscar.templatetags.compress,haystack.templatetags.compress,treebeard.templatetags.compress,sorl.thumbnail.templatetags.compress,django_tables2.templatetags.compress
```

And the error is located in
In template /Documents/Django/django-oscar/oscar/lib/python2.7/site-packages/oscar/templates/oscar/layout.html, error at line 3

Would be great if someone can fix this so I can start looking into Django Oscar :+1: 

Thanks in advance!

**Comment by maerteijn** [comment]
``django-compressor`` has been removed a while ago from the dependencies of oscar, including the load tag in the templates (see 838f0866fd939fd727bab18ace2b7c281599391b) so it's strange that you get this error. Can you please specify how you installed django-oscar and the sandbox? (did you use a virtualenv while installing it?)

**Comment by Gigha** [comment]
I cloned the original repository, created a virtualenv and installed everything using pip -r requirements.txt. I used the same repository as described in the sandbox tutorial on the official django oscar site

**Comment by maerteijn** [comment]
My guess now is that you have an older version of ``django-oscar`` already installed, so this is probably version 1.x which still uses ``django-compressor`` (the error message id from ``django-oscar/oscar/lib/python2.7/site-packages/oscar/templates/oscar`` which means you already installed django oscar using pip)

Can you try the following to make sure you will have a clean environment:
```
mkvirtualenv new-django-oscar (or virtualenv new-django-oscar && source ./new-django-oscar/bin/activate)
git clone https://github.com/django-oscar/django-oscar.git
cd django-oscar
make sandbox
./sites/sandbox/manage.py runserver
```

**Comment by Gigha** [comment]
I think you're right, it's working now with your new instructions!
Thanks a lot!
