### ISSUE TITLE
doc: DeferredTax/CheckoutSessionMixin example no longer works

### ISSUE THREAD

**Issue by fghaas** [django-oscar/django-oscar#1966]
The example for deferred taxes (http://django-oscar.readthedocs.org/en/releases-1.1/howto/how_to_handle_us_taxes.html) no longer works, and a working example was removed in bcbbd053f90b08a9fbfa7c6ec7c5eb34af55ce26 along with the rest of the "US" sandbox site.

**Comment by maikhoepfel** [comment]
Should be fixed by https://github.com/django-oscar/django-oscar/pull/1967

**Comment by fghaas** [comment]
Funny, this one should have auto-closed when you merged #1967. Thanks for merging!
