### ISSUE TITLE
Bucket list of model fields we should probably delete

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1968]
This ticket is becoming the bucket list for model fields that I'd like to see removed. In Oscar, it's always harder to change existing fields than add new ones, so IMHO anything that provides no or little value should be removed. Feel free to suggest more fields.
- `StockRecord.price_retail` and `StockRecord.cost_price`. Not used, and make it harder to understand how pricing works, because there's already quite a few fields and methods with "price" in it.
- `order.Line.est_dispatch_date`: It is displayed when set, but not set anywhere in default Oscar. While I get it's purpose, I haven't actually seen it used in a project. I can be convinced to not delete this. 
- `order.Line.line_price_incl_tax`: The docstring already suggests those fields are redundant. This should be investigated with a bit of care, but in the spirit of normalisation, it sounds like they should be removed.

**Comment by mafrosis** [comment]
FWIW I agree on `est_dispatch_date`. I spent some time investigating the point of the field, before realising it's not used. At this point it's just noise.

**Comment by Nathre2501** [comment]
"est_dispatch_date" could help you if you have set delivery dates per product. I'm using this field to let the user choose a date to receive the package.

**Comment by sasha0** [comment]
For now I don't see motivation to make clean up soon. We could probably deprecate fields until Oscar 2.0. 
Since I don't have problem having these fields for a while, I'd like to see opinions of other developers until we proceed. @django-oscar/api-team @django-oscar/developers @craigloftus please share your thoughts. Thanks.

**Comment by inopia** [comment]
I've been using `StockRecord.price_retail` for manufacturer's suggested retail price (MSRP) and `StockRecord.cost_price` for the price the product actually costs from the supplier. These are useful for when creating sales and calculating profit margins. The fields could have better names but I feel they are useful for what they do. I'd just add them back locally if they were removed.

**Comment by pwalsh** [comment]
I strongly agree with the sentiment expressed by @maikhoepfel in the original post. Fields that are not used, and which are not explicitly hooks for customisation, should be removed, and sooner rather than later.

I'd advocate for immediate deprecation, and removal in Oscar 2.

**Comment by crgwbr** [comment]
We don't use `StockRecord.cost_price`, but we do use `StockRecord.price_retail` to display strike-through MSRP pricing to the customer. But, as long as we can add them back in in our own apps, if they're not used in core, it makes sense to drop them.

**Comment by solarissmoke** [comment]
This has largely been addressed in #3019. There is still `line_price_incl_tax`, which is more difficult to unpick and I will look into it when I have time.
