### ISSUE TITLE
Define ordering for models

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1970]
I've been thinking about ordering of model instances a bit lately (#1963, https://github.com/django-oscar/django-oscar/pull/1969). I think we might be relying on the implicit order of instances returned by the database a bit too often. From the [PostgreSQL docs](http://www.postgresql.org/docs/9.1/static/queries-order.html): 

> If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on. A particular output ordering can only be guaranteed if the sort step is explicitly chosen.

We should make a pass over our models and define a default ordering where it makes sense. I think many times we assume "order of creation", but that is not guaranteed.

**Comment by maikhoepfel** [comment]
I made this PR because in a client's project, the order of lines changed between the basket and the order. The changes in this PR fixed that issue. 

I created https://github.com/django-oscar/django-oscar/issues/1970 to track the underlying issue. But this PR should be quite safe to merge.

**Comment by cowlicks** [comment]
@maikhoepfel this seems like a good starter issue, except that the linked PR's don't include tests.

Is there developer documentation on testing somewhere?

**Comment by SameeranB** [comment]
Hey there, I would like to take this issue up. I'm not sure if this is still a relevant issue though because there hasn't been any activity since 2017. This would be my very first contribution to an open-source project... I was hoping I could get a little guidance if that's okay.

As far as I understand it, we would need to add a Meta class to our models and set the ordering. As @maikhoepfel mentioned in the description, we would need to add the ordering where it makes sense. I was hoping to give it a shot and see if I can give appropriate orderings to the models.

**Comment by solarissmoke** [comment]
@SameeranB yes, help is welcome on this, and it's a good starter issue. 

I would suggest you review all the models and make a list here of those whose ordering you think needs setting, and what ordering they should have. We can then review this before you make a PR with changes to implement that?

**Comment by SameeranB** [comment]
Sounds good. Thank you so much, I'll make the list and put it up here...

**Comment by SameeranB** [comment]
@solarissmoke, after reviewing the models, I was able to come up with the following table. I have suggested the fields which could be used for ordering, but in some of the models it's not apparant as to which one would be the best suited. I have listed out possible fields for those. I have also assigned Model Numbers, those are just for reference.
| Model Number | App             | Model                            | Model Description                                                                                                                                                                                                           | Ordering Fields                                                                           |
|--------------|-----------------|----------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| 1            | `address`       | `AbstractAddress`                | This is subclassed and extended to provide models for user, shipping and billing addresses.                                                                                                                                 | `title`, `first_name` or `postcode`                                                       |
| 2            | `address`       | `AbstractCountry`                | ISO 3166 Country Codes <https://www.iso.org/iso-3166-country-codes.html>                                                                                                                                                    | Already Ordered (`'-display_order', 'printable_name'`)                                    |
| 3            | `address`       | `AbstractShippingAddress`        | A shipping address.                                                                                                                                                                                                         | Order of Creation (Missing Field)                                                         |
| 4            | `address`       | `AbstractUserAddress`            | A user's address.  A user can have many of these and together they form an 'address book' of sorts for the user.                                                                                                            | Already Ordered (`-num_orders_as_shipping_address`)                                       |
| 5            | `address`       | `AbstractBillingAddress`         | No Description                                                                                                                                                                                                              | Not Required as Orders are sorted.                                                        |
| 6            | `address`       | `AbstractPartnerAddress`         | A partner can have one or more addresses. This can be useful e.g. when determining US tax which depends on the origin of the shipment.                                                                                      | Not Required as partner.Partner is sorted.                                                |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 7            | `analytics`     | `AbstractProductRecord`          | A record of how popular a product is. This used be auto-merchandising to display the most popular products.                                                                                                                 | Already Ordered (`'-num_purchases'`)                                                      |
| 8            | `analytics`     | `AbstractUserRecord`             | A record of a user's activity.                                                                                                                                                                                              | Order of Creation (Missing Field)                                                         |
| 9            | `analytics`     | `AbstractUserProductView`        | No Description                                                                                                                                                                                                              | `date_created`                                                                            |
| 10           | `analytics`     | `AbstractUserSearch`             | No Description                                                                                                                                                                                                              | `date_created`                                                                            |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 11           | `basket`        | `AbstractBasket`                 | Basket object                                                                                                                                                                                                               | `date_created`                                                                            |
| 12           | `basket`        | `AbstractLine`                   | A line of a basket (product and a quantity)                                                                                                                                                                                 | Already Ordered (`'date_created', 'pk'`)                                                  |
| 13           | `basket`        | `AbstractLineAttribute`          | An attribute of a basket line                                                                                                                                                                                               | Not Required as Lines are sorted.                                                         |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 14           | `catalogue`     | `AbstractProductClass`           | Used for defining options and attributes for a subset of products. E.g. Books, DVDs and Toys. A product can only belong to one product class.                                                                               | Already Ordered (`'name'`)                                                                |
| 15           | `catalogue`     | `AbstractProductCategory`        | Joining model between products and categories. Exists to allow customising.                                                                                                                                                 | Already Ordered (`'product', 'category'`)                                                 |
| 16           | `catalogue`     | `AbstractProduct`                | The base product object                                                                                                                                                                                                     | Already Ordered (`'-date_created'`)                                                       |
| 17           | `catalogue`     | `AbstractProductRecommendation`  | 'Through' model for product recommendations                                                                                                                                                                                 | Already Ordered (`'primary', '-ranking'`)                                                 |
| 18           | `catalogue`     | `AbstractProductAttribute`       | Defines an attribute for a product class. (For example, number_of_pages for a 'book' class)                                                                                                                                 | Already Ordered (`'code'`)                                                                |
| 19           | `catalogue`     | `AbstractProductAttributeValue`  | The "through" model for the m2m relationship between :py:class:`Product <.AbstractProduct>` and :py:class:`ProductAttribute <.AbstractProductAttribute>` This specifies the value of the attribute for a particular product | `product`                                                                                 |
| 20           | `catalogue`     | `AbstractAttributeOptionGroup`   | Defines a group of options that collectively may be used as an attribute type                                                                                                                                               | Not Required.                                                                             |
| 21           | `catalogue`     | `AbstractAttributeOption`        | Provides an option within an option group for an attribute type Examples: In a Language group, English, Greek, French                                                                                                       | Not Required.                                                                             |
| 22           | `catalogue`     | `AbstractOption`                 | An option that can be selected for a particular item when the product is added to the basket.                                                                                                                               | `name`                                                                                    |
| 23           | `catalogue`     | `MissingProductImage`            | Mimics a Django file field by having a name property.                                                                                                                                                                       | Not Required.                                                                             |
| 24           | `catalogue`     | `AbstractProductImage`           | An image of a product                                                                                                                                                                                                       | Already Ordered (`display_order`). I believe it should be (`'product'`,`'display_order'`) |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 25           | `communication` | `AbstractEmail`                  | This is a record of an email sent to a customer.                                                                                                                                                                            | `user`                                                                                    |
| 26           | `communication` | `AbstractCommunicationEventType` | A 'type' of communication.  Like an order confirmation email.                                                                                                                                                               | (`'user'`,`'date_updated'`,`'date_created'`)                                              |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 27           | `customer`      | `AbstractUser`                   | An abstract base user suitable for use in Oscar projects.                                                                                                                                                                   | `'pk'`                                                                                    |
| 28           | `customer`      | `AbstractProductAlert`           | An alert for when a product comes back in stock                                                                                                                                                                             | (`'product'`,`'status'`)                                                                  |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 29           | `offer`         | `BaseOfferMixin`                 | No Description                                                                                                                                                                                                              | Not Required.                                                                             |
| 30           | `offer`         | `AbstractConditionalOffer`       | A conditional offer (e.g. buy 1, get 10% off)                                                                                                                                                                               | `'status'`                                                                                |
| 31           | `offer`         | `AbstractBenefit`                | No Description                                                                                                                                                                                                              | Not Required                                                                              |
| 32           | `offer`         | `AbstractCondition`              | A condition for an offer to be applied. You can either specify a custom proxy class, or need to specify a type, range and value.                                                                                            | Not Required                                                                              |
| 33           | `offer`         | `AbstractRange`                  | Represents a range of products that can be used within an offer.                                                                                                                                                            | `'slug'`                                                                                  |
| 34           | `offer`         | `AbstractRangeProduct`           | Allow ordering products inside ranges                                                                                                                                                                                       | (`'range'`,`'display_order'`)                                                             |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 35           | `order`         | `AbstractOrder`                  | The main order model                                                                                                                                                                                                        | Already Ordered (`'-date_placed'`). Should be changed to  (`'-date_placed'`, `'user'`)    |
| 36           | `order`         | `AbstractOrderNote`              | This is often used for audit purposes too.  IE, whenever an admin makes a change to an order, we create a note to record what happened.                                                                                     | (`'date_updated'`)                                                                        |
| 37           | `order`         | `AbstractOrderStatusChange`      | No Description                                                                                                                                                                                                              | Already Ordered (`'-date_created'`)                                                       |
| 38           | `order`         | `AbstractCommunicationEvent`     | An order-level event involving communication to the customer, such as a confirmation email being sent.                                                                                                                      | Already Ordered (`'-date_created'`). Should be changed to  (`'order'`, `'-date_created'`) |
| 39           | `order`         | `AbstractLine`                   | No Description                                                                                                                                                                                                              | Already Ordered (`'pk'`). Should be changed to  (`'order'`)                               |
| 40           | `order`         | `AbstractLineAttribute`          | An attribute of a line                                                                                                                                                                                                      | `'line'`                                                                                  |
| 41           | `order`         | `AbstractLinePrice`              | For tracking the prices paid for each unit within a line.                                                                                                                                                                   | Already Ordered (`'id'`). Should be changed to  (`'line'`)                                |
| 42           | `order`         | `AbstractPaymentEventType`       | Payment event types are things like 'Paid', 'Failed', 'Refunded'.                                                                                                                                                           | Already Ordered (`'name'`)                                                                |
| 43           | `order`         | `AbstractPaymentEvent`           | A payment event for an order                                                                                                                                                                                                | Already Ordered (`'-date_created'`).                                                      |
| 44           | `order`         | `PaymentEventQuantity`           | A "through" model linking lines to payment events                                                                                                                                                                           | `'event'`                                                                                 |
| 45           | `order`         | `AbstractShippingEvent`          | An event is something which happens to a group of lines such as 1 item being dispatched.                                                                                                                                    | Already Ordered (`'-date_created'`)                                                       |
| 46           | `order`         | `ShippingEventQuantity`          | A "through" model linking lines to shipping events.                                                                                                                                                                         | `'event'`                                                                                 |
| 47           | `order`         | `AbstractShippingEventType`      | A type of shipping/fulfilment event                                                                                                                                                                                         | Already Ordered (`'name'`)                                                                |
| 48           | `order`         | `AbstractOrderDiscount`          | A discount against an order.                                                                                                                                                                                                | `'category'`                                                                              |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 49           | `partner`       | `AbstractPartner`                | A fulfilment partner. An individual or company who can fulfil products. E.g. for physical goods, somebody with a warehouse and means of delivery.                                                                           | Already Ordered (`'name'`,`'code'`)                                                       |
| 50           | `partner`       | `AbstractStockRecord`            | A stock record.                                                                                                                                                                                                             | `'partner'`                                                                               |
| 51           | `partner`       | `AbstractStockAlert`             | A stock alert. E.g. used to notify users when a product is 'back in stock'.                                                                                                                                                 | Already Ordered (`'-date_created'`)                                                       |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 52           | `payment`       | `AbstractTransaction`            | A transaction for a particular payment source.                                                                                                                                                                              | Already Ordered (`'-date_created'`)                                                       |
| 53           | `payment`       | `AbstractSource`                 | A source of payment for an order.                                                                                                                                                                                           | Unsure. Possible: source_type, order.                                                     |
| 54           | `payment`       | `AbstractSourceType`             | A type of payment source.                                                                                                                                                                                                   | `'name'`                                                                                  |
| 55           | `payment`       | `AbstractBankcard`               | Model representing a user's bankcard.  This is used for two purposes:                                                                                                                                                       | `'user'`                                                                                  |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 56           | `shipping`      | `AbstractBase`                   | Implements the interface declared by shipping.base.Base                                                                                                                                                                     | Already Ordered (`'name'`)                                                                |
| 57           | `shipping`      | `AbstractOrderAndItemCharges`    | Standard shipping method                                                                                                                                                                                                    | Not Required                                                                              |
| 58           | `shipping`      | `AbstractWeightBand`             | Represents a weight band which are used by the WeightBasedShipping method.                                                                                                                                                  | Not Required                                                                              |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 59           | `voucher`       | `AbstractVoucherSet`             | A collection of vouchers (potentially auto-generated)                                                                                                                                                                       | `'-date_created'`                                                                         |
| 60           | `voucher`       | `AbstractVoucher`                |  A voucher.  This is simply a link to a collection of offers.                                                                                                                                                               | `'-date_created'`                                                                         |
| 61           | `voucher`       | `AbstractVoucherApplication`     | For tracking how often a voucher has been used in an order.                                                                                                                                                                 | `'-date_created'`                                                                         |
|              | ****            | ****                             | ****                                                                                                                                                                                                                        | ****                                                                                      |
| 62           | `voucher`       | `AbstractWishList`               | Represents a user's wish lists of products.                                                                                                                                                                                 | Already Ordered (`'owner'`,`'-date_created'`)                                             |
| 63           | `voucher`       | `AbstractLine`                   | One entry in a wish list. Similar to order lines or basket lines.                                                                                                                                                           | Already Ordered (`'pk'`)                                                                  |
|              |                 |                                  |



There were a lot of models and the interactions were quite complex. I have tried my best to make sense of them. Please do let me know if I missed anything or if anything needs to be changed.

**Comment by solarissmoke** [comment]
Wow, that was a thorough review. 

I am somewhat short on time, so my feedback is brief, but here is a table where I've removed everything that doesn't need a comment. What remains is the rows either where ordering needs to be changed/added, or I've disagreed with your proposal and have left a comment explaining why. I've added a new column ("Ordering change") to indicate what change I propose in response to your suggestions.

This leaves about 15 places where I think changes are needed.



| #            |      App      |             Model              |                                  Proposed                                           | Ordering change |                                                                              Comments                                                                              |
|--------------|---------------|--------------------------------|-------------------------------------------------------------------------------------|-----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|            1 | address       | AbstractAddress                | title, first_name or postcode                                                       | (no change)     | This is not a concrete model. Ordering is applied on subclasses.                                                                                                   |
|            3 | address       | AbstractShippingAddress        | Order of Creation (Missing Field)                                                   | (no change)     | This is not a concrete model. Ordering is applied on subclasses.                                                                                                   |
|            8 | analytics     | AbstractUserRecord             | Order of Creation (Missing Field)                                                   | (no change)     | Not queried in bulk, don't think ordering is needed                                                                                                                |
|            9 | analytics     | AbstractUserProductView        | date_created                                                                        | date_created    |                                                                                                                                                                    |
|           10 | analytics     | AbstractUserSearch             | date_created                                                                        | date_created    |                                                                                                                                                                    |
|           11 | basket        | AbstractBasket                 | date_created                                                                        | date_created    |                                                                                                                                                                    |
|           19 | catalogue     | AbstractProductAttributeValue  | product                                                                             | (no change)     | Doesn't make sense to sort by product - you would only every query these for a particular product anyway. This is a through model, don't think ordering is needed. |
|           22 | catalogue     | AbstractOption                 | name                                                                                | name            |                                                                                                                                                                    |
|           24 | catalogue     | AbstractProductImage           | Already Ordered (display_order). I believe it should be ('product','display_order') | (no change)     | These are only queried with respect to a product - so no change required.                                                                                          |
|           25 | communication | AbstractEmail                  | user                                                                                | date_sent       | This needs to be sorted by date. It is filtered on user in most queries anyway.                                                                                    |
|           26 | communication | AbstractCommunicationEventType | ('user','date_updated','date_created')                                              | name            | This model doesn't have any of the fields you've suggested.                                                                                                        |
|           27 | customer      | AbstractUser                   | pk                                                                                  | (no change)     | Think this is best left to projects to override.                                                                                                                   |
|           28 | customer      | AbstractProductAlert           | ('product','status')                                                                | date_created    | We should order by date. Filtering on product/status happens in most views.                                                                                        |
|           30 | offer         | AbstractConditionalOffer       | status'                                                                             | (no change)     | This is already ordered by priority, pk                                                                                                                            |
|           33 | offer         | AbstractRange                  | slug                                                                                | name            | Slug is not visible in dashboard views, so lets order by name.                                                                                                     |
|           34 | offer         | AbstractRangeProduct           | ('range','display_order')                                                           | (no change)     | This is a through model, no ordering needed.                                                                                                                       |
|           35 | order         | AbstractOrder                  | Already Ordered ('-date_placed'). Should be changed to ('-date_placed', 'user')     | (no change)     | Current ordering is fine - I don't see any need to order by user as well.                                                                                          |
|           36 | order         | AbstractOrderNote              | ('date_updated')                                                                    | -date_updated   |                                                                                                                                                                    |
|           38 | order         | AbstractCommunicationEvent     | Already Ordered ('-date_created'). Should be changed to ('order', '-date_created')  | (no change)     | Current ordering is fine - these are filtered on order when used.                                                                                                  |
|           39 | order         | AbstractLine                   | Already Ordered ('pk'). Should be changed to ('order')                              | (no change)     | You would only query these in the context of an order - doesn't make sense to sort on order.                                                                       |
|           40 | order         | AbstractLineAttribute          | line                                                                                | (no change)     | You would only query these in the context of a line - doesn't make sense to sort on line.                                                                          |
|           41 | order         | AbstractLinePrice              | Already Ordered ('id'). Should be changed to ('line')                               | (no change)     | You would only query these in the context of a line - doesn't make sense to sort on line.                                                                          |
|           44 | order         | PaymentEventQuantity           | event                                                                               | (no change)     | This is a through model - rely on ordering of relations.                                                                                                           |
|           46 | order         | ShippingEventQuantity          | event                                                                               | (no change)     | This is a through model - rely on ordering of relations.                                                                                                           |
|           48 | order         | AbstractOrderDiscount          | category                                                                            | pk              | Suggest we order in the order these are created.                                                                                                                   |
|           50 | partner       | AbstractStockRecord            | partner                                                                             | (no change)     | This would be an arbitrary ordering - don't think it is required.                                                                                                  |
|           53 | payment       | AbstractSource                 | Unsure. Possible: source_type, order.                                               | pk              | Suggest we order in the order these are created.                                                                                                                   |
|           54 | payment       | AbstractSourceType             | name                                                                                | name            |                                                                                                                                                                    |
|           55 | payment       | AbstractBankcard               | user                                                                                | (no change)     | You would only query these in the context of a user. No change required.                                                                                           |
|           59 | voucher       | AbstractVoucherSet             | -date_created                                                                       | -date_created   |                                                                                                                                                                    |
|           60 | voucher       | AbstractVoucher                | -date_created                                                                       | -date_created   |                                                                                                                                                                    |
|           61 | voucher       | AbstractVoucherApplication     | -date_created                                                                       | -date_created   |                                                                                                                                                                    |

**Comment by SameeranB** [comment]
Sounds good.... I'll finalize a table based on your comments and share them here.

**Comment by SameeranB** [comment]
The following table consists of the 15 models whose ordering needs to be changed. I'm not entirely sure what my next steps should be... should I fork the repo and create a PR?


|    |               |                                |                 |
|----|---------------|--------------------------------|-----------------|
| #  | App           | Model                          | Ordering Change |
| 1  | analytics     | AbstractUserProductView        | date_created    |
| 2  | analytics     | AbstractUserSearch             | date_created    |
| 3  | basket        | AbstractBasket                 | date_created    |
| 4  | catalogue     | AbstractOption                 | name            |
| 5  | communication | AbstractEmail                  | date_sent       |
| 6  | communication | AbstractCommunicationEventType | name            |
| 7  | customer      | AbstractProductAlert           | date_created    |
| 8  | offer         | AbstractRange                  | name            |
| 9  | order         | AbstractOrderNote              | -date_updated   |
| 10 | order         | AbstractOrderDiscount          | pk              |
| 11 | payment       | AbstractSource                 | pk              |
| 12 | payment       | AbstractSourceType             | name            |
| 13 | voucher       | AbstractVoucherSet             | -date_created   |
| 14 | voucher       | AbstractVoucher                | -date_created   |
| 15 | voucher       | AbstractVoucherApplication     | -date_created   |

**Comment by solarissmoke** [comment]
Yes please, if you can. You will also need to make sure that we have indexes defined for the fields we're ordering by. I have updated the table above just to tweak the ascending/descending order definition of some rows.

**Comment by SameeranB** [comment]
Alright sure... I've actually never indexed my fields before. I just want to confirm if this is the right way to do it :

`added = models.DateTimeField(db_index=True, auto_now_add=True)`

**Comment by solarissmoke** [comment]
Yes (`db_index=True`).

**Comment by SameeranB** [comment]
Alright, thank you so much 😊. I'll get started on the PR.

**Comment by SameeranB** [comment]
This is probably not the right place to ask this question but I have been searching for an answer for two days now. I'm unable to make migrations. According to the docs, I must run:

`sites/sandbox/manage.py schemamigration $YOURAPP --auto`

There is no directory called `sites` and the manage.py inside of sandbox has no subcommand `schemamigration`. I'm almost done with the changes, I just need to figure this out. Where should I look for help?

**Comment by solarissmoke** [comment]
The docs for that are out of date - it should be `sandbox/manage.py makemigrations` and then `sandbox/manage.py migrate` to apply them. I'll make a separate issue to fix the docs.

**Comment by SameeranB** [comment]
Thank you so much. I'll continue working on the PR.

**Comment by SameeranB** [comment]
@solarissmoke, I have successfully created a PR. 

[https://github.com/django-oscar/django-oscar/pull/3364](url).

Please let me know if there are any changes that need to be made.

**Comment by SameeranB** [comment]
@solarissmoke, I have made the necessary changes. If there is anything else to change, do let me know.
