### ISSUE TITLE
ImportError: No module named 'django.utils.importlib'

### ISSUE THREAD

**Issue by auspi** [django-oscar/django-oscar#1972]
Django 1.9.1 compatibility issue in following files : 
in file /oscar/apps/catalogue/abstract_models.py (line 20):
from django.contrib.contenttypes.generic import GenericForeignKey
should be 
from django.contrib.contenttypes.fields import GenericForeignKey

And in file /oscar/apps/offer/utils.py (line 3) : 
from django.utils.importlib import import_module
should be 
from importlib import import_module

  File "/home/deepak/Documents/pyves/py34dj191/lib/python3.4/site-packages/oscar/apps/offer/models.py", line 5, in <module>
    from oscar.apps.offer.abstract_models import (
  File "/home/deepak/Documents/pyves/py34dj191/lib/python3.4/site-packages/oscar/apps/offer/abstract_models.py", line 18, in <module>
    from oscar.apps.offer import results, utils
  File "/home/deepak/Documents/pyves/py34dj191/lib/python3.4/site-packages/oscar/apps/offer/utils.py", line 3, in <module>
    from django.utils.importlib import import_module
ImportError: No module named 'django.utils.importlib'

**Comment by maikhoepfel** [comment]
@auspi Thank you for reporting this. What version of Oscar did you run? I would guess you're not running a version from master. master has 1.9 support; but we haven't been able to release a version with it yet.

As the errors you're reporting sound like basic and loud import errors, I'm guessing you're not running against master, and closing this issue. Please re-open if I'm mistaken! We hope to have a release soon.
