### ISSUE TITLE
Hosted sandbox site returns 404 on all media images

### ISSUE THREAD

**Issue by fghaas** [django-oscar/django-oscar#1974]
http://latest.oscarcommerce.com is currently being bitten by a solr-thumbnail issue that makes all images in the catalogue return a 404.

Users have been hit by the same thing as well:
https://groups.google.com/d/msgid/django-oscar/e0de9142-3d66-4fe1-9538-294c9b868396%40googlegroups.com

Looks like this issue is resolvable by `./manage.py thumbnail cleanup` followed by `./manage.py syncdb`, but maybe there's a smarter way to fix this.

**Comment by fghaas** [comment]
@maikhoepfel, is this possibly something you could look into as I guess you have control over the sandbox site?

**Comment by maikhoepfel** [comment]
Thanks for reporting this.

I'm afraid the bus factor on the hosted sites is too low. @codeinthehole is the only one who can fix this. Next month, I'll likely be able to sufficiently annoy him to fix it. ;)

**Comment by sasha0** [comment]
@mvantellingen let's re-check after sandbox site is fixed.

**Comment by sasha0** [comment]
Fixed in f708b2467304e16ad99d5c6314cb164797c9c1ad.

@fghaas thanks for the report and fix suggestion.
