### ISSUE TITLE
List display for product with options is broken in sandbox

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#1976]
![image](https://cloud.githubusercontent.com/assets/509427/12413594/55e4d064-be90-11e5-8e83-2034bf6168cb.png)

For a shop I'm doing, I have products with options. In [product.html](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/catalogue/partials/product.html), the `AddToBasketForm` only gets included when the product is not a parent product. But we should also exclude it if the product has options. Or maybe the `basket_form` template tag shouldn't return a form if the product has options and `simple` was specified. 

We also need to be careful to not incur too many new database queries; we want to avoid querying for options for each product.

**Comment by sasha0** [comment]
To avoid additional queries, we can add `has_options` field to the product model and update it with the `post_save` signal. Hence, in the template, similar to parent products, we won't show basket form:
```django
{% if not product.is_parent or not product.has_options %}
    {% include "catalogue/partials/add_to_basket_form_compact.html" %}
{% endif %}
```
If we deprecate product options in favor of attribute options in terms of #1776, we can slightly change this code and still indicate presence or absence of option attributes in this field.

WDYT @mvantellingen @solarissmoke ?

**Comment by solarissmoke** [comment]
> We can add `has_options` field to the product model.

Sounds OK to me. The template logic would be `and not` rather than `or not`.

As per my comments in #1776 I think there are separate use cases for attributes vs options.

**Comment by specialunderwear** [comment]
Why is this considered a bug?

**Comment by specialunderwear** [comment]
I'm just saying, that form works it just looks like shit ...

**Comment by sasha0** [comment]
@specialunderwear the issue not in the form look, but in the fact that it's not possible to provide option value for non-parent products.
