### ISSUE TITLE
sandbox syntax errors

### ISSUE THREAD

**Issue by andreas-roehler** [django-oscar/django-oscar#1985]
Messages from command "make sandbox" display the following:

Compiling /tmp/pip-build-Mixix_/django/django/conf/app_template/apps.py ...
  File "/tmp/pip-build-Mixix_/django/django/conf/app_template/apps.py", line 1
    {{ unicode_literals }}from django.apps import AppConfig
                             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-Mixix_/django/django/conf/app_template/models.py ...
  File "/tmp/pip-build-Mixix_/django/django/conf/app_template/models.py", line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax

**Comment by maerteijn** [comment]
Can you specify which version of pip you use? (`pip --version`)

**Comment by andreas-roehler** [comment]
Okay, thanks. Version is pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
As you are aware of it, think it deserves being closed.

**Comment by maerteijn** [comment]
@andreas-roehler Did it work for you with a newer of pip?

**Comment by sasha0** [comment]
Should work on the latest pip version (8.1.2). 

@andreas-roehler please confirm, so we could close the ticket.

Thanks.

**Comment by sasha0** [comment]
As noted above, should be already fixed. Please re-open in case of new questions/issues. Thanks!
