### ISSUE TITLE
migrate falied

### ISSUE THREAD

**Issue by Tedcon** [django-oscar/django-oscar#1987]
order.Order.site: (fields.E300) Field defines a relation with model 'sites.Site', which is either not installed, or is abstract.

when i init the project,use 'python mnage.py migrate '

**Comment by sasha0** [comment]
Please paste whole traceback.

**Comment by Tedcon** [comment]
python manage.py  migrate
/Users/Azure/.virtualenvs/gmrz/lib/python2.7/site-packages/haystack/utils/__init__.py:12: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

/Users/Azure/.virtualenvs/gmrz/lib/python2.7/site-packages/oscar/apps/catalogue/abstract_models.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericForeignKey

/Users/Azure/.virtualenvs/gmrz/lib/python2.7/site-packages/django/utils/translation/__init__.py:146: RemovedInDjango19Warning: The use of the language code 'zh-cn' is deprecated. Please use the 'zh-hans' translation instead.
  return _trans.activate(language)

SystemCheckError: System check identified some issues:

ERRORS:
order.Order.site: (fields.E300) Field defines a relation with model 'sites.Site', which is either not installed, or is abstract.

**Comment by vinamelody** [comment]
Check your settings.py to be like this (using [ ] and not ( ) )
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'compressor',
    'widget_tweaks',
] + get_core_apps()
```

**Comment by Anlim** [comment]
when i init the project,use 'python mnage.py migrate '

SystemCheckError: System check identified some issues:

ERRORS:
order.Order.site: (fields.E300) Field defines a relation with model 'sites.Site', which is either not installed, or is abstract.

**Comment by sasha0** [comment]
I believe this issue could be caused by not plugged `django.contrib.sites` application, which provides `Site` model.

**Comment by sasha0** [comment]
Feel free to reopen, if the issue is still relevant. Thanks.
