### ISSUE TITLE
tests/_site/templates/layout.html omits {% block content_wrapper %}

### ISSUE THREAD

**Issue by zbmott** [django-oscar/django-oscar#1991]
I have recently been working on improving `OSCAR_HIDDEN_FEATURES` so that it supports the `"wishlists"` and `"alerts"` keys.  One facet of my effort was to hide the "Wish Lists" link on `/accounts/profile` when the `"wishlists"` feature is hidden.

My test plan for this particular modification is very simple:
1. Render `/accounts/profile` and verify that a link to `/accounts/wishlists` is present.
2. Use a context manager to temporarily add `"wishlists"` to `OSCAR_HIDDEN_FEATURES`, render `/accounts/profile`, and verify that a link to `/accounts/wishlists` is **not** present.

The following test case implements this plan:

``` python
from django.core.urlresolvers import reverse

from oscar.test.testcases import WebTestCase


class TestProfilePage(WebTestCase):
    is_anonymous = False

    def test_wishlists_link_exists(self):
        account_page = self.get(reverse('customer:profile-view'))

        html = account_page.content.decode('utf-8')
        self.assertTrue(reverse('customer:wishlists-list') in html)

    def test_wishlists_link_does_not_exist(self):
        with self.settings(OSCAR_HIDDEN_FEATURES=['wishlists']):
            account_page = self.get(reverse('customer:profile-view'))

        html = account_page.content.decode('utf-8')
        self.assertFalse(reverse('customer:wishlists-list') in html)  
```

Unfortunately, `TestProfilePage.test_wishlists_link_exists` fails.

I have investigated the source of this failure and determined that it arises from the differences between `src/oscar/templates/oscar/layout.html` and `tests/_site/templates/layout.html`.  The former defines `{% block content_wrapper %}`, while the latter does not.  This is significant because `templates/oscar/customer/baseaccountpage.html` extends `templates/oscar/layout_2col.html` and renders the left navigation (where I expect the link to appear) into `{% block column_left %}`.  `{% block column_left %}` is defined by `layout_2col.html` within `{% block content_wrapper %}`.

Thus, because `tests/_site/templates/layout.html` does not define `{% block content_wrapper %}`, `{% block column_left %}` is not rendered, and `TestProfilePage.test_wishlists_link_exists` fails.

I suspect that `tests/_site/templates/layout.html` has been simplified to avoid rendering unnecessary HTML during tests.  This issue documents a case where rendering the full `layout.html` could contribute to improved test coverage.

**Comment by sasha0** [comment]
During the latest review I had a closer look on feature disable functionality and found out that wishlists URL is not hidden yet on the account page, when feature is disabled, simply because it's not wrapped with `{% iffeature "wishlists" %}{% endiffeature %}` tag.

@zbmott you were right regarding the test template - not having `{% content_wrapper %}` block prevented from proper testing of account navigation, so I added it in PR #2522.
