### ISSUE TITLE
username attribute in UserFactory model

### ISSUE THREAD

**Issue by mafrosis** [django-oscar/django-oscar#1999]
As far as I can tell, the `username` attribute in the `UserFactory` model should be removed:

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/test/factories/customer.py#L19

The `User` model in Oscar does not include a field called `username` - and even includes a comment saying `username` has been removed:

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/customer/abstract_models.py#L49

When using the `UserFactory` in our tests, it causes an exception in factory_boy when trying to instantiate a `User` model. I had to copy the factory into our project and remove the `username` attribute to get it working.

**Comment by sasha0** [comment]
@mafrosis please provide traceback of exception in the tests in your project. Thanks.

**Comment by mafrosis** [comment]
I no longer work with Oscar, so please close this if it's you can't recreate.
