### ISSUE TITLE
Email template preview with guest checkout potentially misleading

### ISSUE THREAD

**Issue by bufke** [django-oscar/django-oscar#2004]
I think this is a bug, let me know if it's intended. Adding `{{ user.get_full_name }}` in an email template using the email dashboard will result in the currently logged in user's name going there when used with a guest checkout order. This could be misleading to a developer trying to edit an email template. Not sure how "user" is getting into the context like that. I could look into this more if desired.

**Comment by sasha0** [comment]
`user` instance automatically added to the template context by `auth` context processor -
 https://docs.djangoproject.com/en/2.0/ref/templates/api/#django-contrib-auth-context-processors-auth.
