### ISSUE TITLE
Setting up django-oscar with Django 1.9

### ISSUE THREAD

**Issue by fegul** [django-oscar/django-oscar#2005]
When going through the "Getting Started" I get the following error:

`ImportError: No module named 'django.contrib.contenttypes.generic'`

It seems that in Django 1.9, [this module has been deprecated](https://docs.djangoproject.com/en/1.9/internals/deprecation/#deprecation-removed-in-1-9)

Are there any fixes to allow users to upgrade to Django 1.9?

**Comment by maerteijn** [comment]
Do you use the current release? (1.1.1). This release is not compatible with django 1.9. Try installing the latest development release ('pip install git+https://github.com/django-oscar/django-oscar.git')

**Comment by fegul** [comment]
Ah, OK. Yes, I'm using 1.1.1
