### ISSUE TITLE
BankcardNumberField.clean raises AttributeError instead of ValidationError

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#2006]
If you pass `None` as a value to `BankcardNumberField` instead of `''`, it raises an `AttributeError` instead of raising a `ValidationError`.

This occurred because I was trying to make an optional bank card field.

I'll submit a PR briefly.

**Comment by sasha0** [comment]
Fixed in 6b9ae9e702391030b670ecdaee58cd8de49d4882.
