### ISSUE TITLE
ExpiryMonthField.clean raises AttributeError inappropriately

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#2008]
Similar to https://github.com/django-oscar/django-oscar/issues/2006

If you create an `ExpiryMonthField` with `required=False` you can get into a situation where an `AttributeError` is raised where no error should be raised.

I'll submit a PR briefly.

**Comment by sasha0** [comment]
Just wondering about the use-case, when expiry month field is not mandatory.

**Comment by sasha0** [comment]
Within your case with saved card, I'm wondering what fields remained mandatory? Thanks.

**Comment by john-parton** [comment]
The mandatory fields I have in my app are `number`, `expiry_month`, and `ccv`. All other fields can be optional.

**Comment by sasha0** [comment]
Ok, thanks for the clarification. Closing since #2009 merged.
