### ISSUE TITLE
how to fork order apps in oscar?

### ISSUE THREAD

**Issue by anthony1110** [django-oscar/django-oscar#2011]
Hi

I have the issue below when I try to fork oscar.order application. I don't have any problem when I fork other applications such as checkout, shiipping etc. Can you tell me what is the proper way to fork order applications?

ERRORS:
payment.Source.order: (fields.E300) Field defines a relation with model 'order.Order', which is either not installed, or is abstract.
voucher.VoucherApplication.order: (fields.E300) Field defines a relation with model 'order.Order', which is either not installed, or is abstract.

Thanks,
Kah Fai

**Comment by spacediver** [comment]
@anthony1110, could you please show example of your code that does not work?

**Comment by anthony1110** [comment]
Hi @spacediver , 

Thanks for your response. I just figured it out today. I guess I missed out the models.py file inside my forked order application. I only put __init.py and config.py files previously. After I include models.py, then it dont have the error above. I need to be more careful next time. 

models.py
from oscar.apps.order.models import *  


Thanks
Kah Fai

**Comment by spacediver** [comment]
If you forked apps before, you could probably know of `oscar_fork_app` management command, that automates much of what you need to do =)

**Comment by anthony1110** [comment]
oh yea.... thanks for remind...
i forgot to use that command!!! i fork it myself...   =.=
I will remember to use that command from now... 
Thanks again!
