### ISSUE TITLE
Allow site override in /apps/order/utils.py:OrderCreator.create_order_model

### ISSUE THREAD

**Issue by mattdrayer** [django-oscar/django-oscar#2013]
Hi there!

I'm running into a site-related issue with the OrderCreator.  We are trying to pass in a site entity as an override, but the current implementation appears to ignore any provided value in favor of the Site's get_current() workflow.  Typically this wouldn't be an issue, however this is a multi-host scenario and we'd like to be able to indicate the site as part of the request to this class.  See here:

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/order/utils.py#L104

I'd like to propose that the setting of the "site" key be moved from its current location to after the "if extra_order_fields..." conditional on line 120.  We would perform a quick check to see if the site key had not been set via extra_order_fields -- if not we'd execute Site._default_manager.get_current() as is currently happening.

I am happy to make this change and submit a pull request to the django-oscar project if that's the best way to move forward?  If you could let me know that would be great.

Thanks!

Matt

**Comment by sasha0** [comment]
Closing since related PRs #2014 and #2080 already merged.
