### ISSUE TITLE
Unable to override ProductImage and ProductImageForm classes

### ISSUE THREAD

**Issue by jordanmkoncz** [django-oscar/django-oscar#2016]
I have been trying to override the `ProductImage` and `ProductImageForm` classes but I've run into an issue and can't figure out how to achieve this (or whether it's even possible). I've already successfully overridden the `Product` and `ProductForm` classes so I assumed I would be able to do something similar for `ProductImage` and `ProductImageForm`.

I wanted to make significant changes to the `ProductImage` class, so I've overridden this class and **not** inherited from `AbstractProductImage`, and this _seems_ to be working. My problem is that now I'm trying to override the `ProductImageForm` class so make it compatible with my new `ProductImage` class, and I keep getting the following error:

```
FieldError at /oscar-admin/dashboard/catalogue/products/1/
Unknown field(s) (caption, original) specified for ProductImage
```

This error comes from `class ProductImageForm(forms.ModelForm)` in `venv/lib/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py`, which seems to imply that my customised `ProductImageForm` class is being ignored, but I have no idea why, especially since I am successfully overriding `ProductForm` in the very same file that I'm attempting to override `ProductImageForm`.

I'm using Django Oscar 1.1.1 and Django 1.8.9.

All the relevant code can be viewed here: https://gist.github.com/jordanmkoncz/9fe171eacc34ee83e996

**Comment by lindleywhite** [comment]
Looks like you haven't based your ProductImage model after AbstractProductImage. You can find it here: [http://django-oscar.readthedocs.org/en/latest/_modules/oscar/apps/catalogue/abstract_models.html#AbstractProductImage](AbstractProductImage)

**Comment by sasha0** [comment]
Please re-open if the issue is still relevant. Thanks.
