### ISSUE TITLE
Prices and availability (documentation)

### ISSUE THREAD

**Issue by martinsam** [django-oscar/django-oscar#2023]
Example : 
```
>>> product = Product.objects.get(id=1)
>>> product.price
Decimal('17.99')
```

It doesn't work (from sandbox)

`AttributeError: 'Product' object has no attribute 'price'`

http://django-oscar.readthedocs.org/en/releases-1.1/topics/prices_and_availability.html

**Comment by amirrpp** [comment]
Its an example of how other ecommerce frameworks are work (not django-oscar)

**Comment by robmoorman** [comment]
This exemplary piece of instructions are indeed for other e-ccommerce frameworks, it doesn't indicate it's for Django Oscar.
