### ISSUE TITLE
404 : http://django-oscar.readthedocs.org/fr/releases-1.1/

### ISSUE THREAD

**Issue by martinsam** [django-oscar/django-oscar#2024]
404 Not Found
nginx/1.4.6 (Ubuntu)

-> 

The server sends a personalised 404 Not found error page (Source : http://checklists.opquast.com/oqs-v3/criteria/le-serveur-envoie-une-page-derreur-404-personnalisee)

**Comment by mvantellingen** [comment]
Not sure what you mean here. Is the french documentation missing (that is correct since there is only english documentation) or do you mean something else?
