### ISSUE TITLE
Straight discount on products.

### ISSUE THREAD

**Issue by Warun26** [django-oscar/django-oscar#2028]
The shop I am trying to build needs a new kind of offer or promotion. Every month some of the products in the catalogue will be sold at a discounted price(Sometimes for occasions like Christmas or Thanksgiving).  Everybody will be eligible for the discount.

I was wondering if this feature is already available is Oscar. If not, what is the best way to go about this? I did read the discussion [here](https://groups.google.com/forum/#!searchin/django-oscar/discount$20products/django-oscar/c-npC-krnP0/jIbjhEJ4zdoJ). Just wanted to know if there is other ways to achieve what I want.

**Comment by sasha0** [comment]
>  Every month some of the products in the catalogue will be sold at a discounted price

E.g. regular price would be overridden instead of applying fixed or percentage discount?

**Comment by SalahAdDin** [comment]
@Warun26 Man, why did you close this issue?
Also, if you want, use mailing list.
