### ISSUE TITLE
Customize some code

### ISSUE THREAD

**Issue by alexkos** [django-oscar/django-oscar#2029]
I would like to ask. Is it ok if I'll move oscar code inside my project and will make changes directly in oscar code?

Thanks

**Comment by digicase** [comment]
Hello @alexkos,

Please read the documentation on [customising oscar](https://django-oscar.readthedocs.org/en/releases-1.1/topics/customisation.html).

Also this isn't the place to be asking these types of questions, you should direct them to the [django-oscar Google group](https://groups.google.com/forum/#!forum/django-oscar).

**Comment by alexkos** [comment]
Thank you very much
