### ISSUE TITLE
Basket threshold not consistently enforced

### ISSUE THREAD

**Issue by anziem** [django-oscar/django-oscar#2031]
oscar's is_quantity_allowed bases its answer on the basket's num_items before an update and the quantity in the proposed update. This is flawed because if you're updating the quantity for a line, it is double-counting the previous quantity for the line.

Steps to reproduce bug:
0) Set OSCAR_MAX_BASKET_QUANTITY_THRESHOLD in your settings to any number - say, 10.
1) add a single item to your cart.
2) update the quantity to be something less than the threshold, say 5
3) try to update the quantity to something more than threshold - current quantity - say, 6
Result:
Quantity: 6
Error message: "Due to technical limitations we are not able to ship more than 10 items in an order."

Relevant code: 

        if basket_threshold:
            total_basket_quantity = self.num_items
            max_allowed = basket_threshold - total_basket_quantity
            if qty > max_allowed:
                return False, _(
                    "Due to technical limitations we are not able "
                    "to ship more than %(threshold)d items in one order.") \
                    % {'threshold': basket_threshold}

in oscar/apps/basket/abstract_models.py
![basket___flyshop_-_welcome_to_surround_video_](https://cloud.githubusercontent.com/assets/15231879/14157409/dd1edfda-f698-11e5-85b4-fd066cfef05d.png)

**Comment by anziem** [comment]
Fix:

In basket/models, change is_quantity_allowed to also take a line argument and use that to calculate the correct limit:
    def is_quantity_allowed(self, qty, line):
        """
        Test whether the passed quantity of items can be added to the basket
        """
        # We enfore a max threshold to prevent a DOS attack via the offers
        # system.
        basket_threshold = settings.OSCAR_MAX_BASKET_QUANTITY_THRESHOLD
        if basket_threshold:
            total_basket_quantity = self.num_items
            max_allowed = basket_threshold - total_basket_quantity + line.quantity

In basket/forms, change check_max_allowed_quantity to supply the line:
    def check_max_allowed_quantity(self, qty):
        is_allowed, reason = self.instance.basket.is_quantity_allowed(qty, self.instance)

**Comment by anziem** [comment]
You also need to update do_reorder in customer/views:

        for line in lines_to_add:
            is_quantity_allowed, reason = basket.is_quantity_allowed(
                line.quantity, line)
            if not is_quantity_allowed:
                messages.warning(self.request, reason)
                self.response = redirect('customer:order-list')
                return

**Comment by anziem** [comment]
Actually, the fix for do_reorder will have to be a little more complicated than that.

**Comment by mvantellingen** [comment]
Cool, thanks. Can you supply a PR with an unittest?

**Comment by mvantellingen** [comment]
Fixed by @sasha0
