### ISSUE TITLE
MultipleObjectsReturned is possible when logging in with duplicate email

### ISSUE THREAD

**Issue by bufke** [django-oscar/django-oscar#2040]
Related to #295 but that was marked fixed so maybe this is a regression. Same issue as before. Can be reproduced by
1. Create 2 users with the same email in django admin
2. Log in using /store/accounts/login/

```
MultipleObjectsReturned: There are multiple users with the given email address and password
  File "django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "oscar/apps/customer/views.py", line 125, in post
    return self.validate_login_form()
  File "oscar/apps/customer/views.py", line 152, in validate_login_form
    if form.is_valid():
  File "django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "django/forms/forms.py", line 393, in full_clean
    self._clean_form()
  File "django/forms/forms.py", line 417, in _clean_form
    cleaned_data = self.clean()
  File "django/contrib/auth/forms.py", line 157, in clean
    password=password)
  File "django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "oscar/apps/customer/auth_backends.py", line 54, in authenticate
    "There are multiple users with the given email address and "
```

**Comment by maerteijn** [comment]
I can confirm this one

**Comment by bufke** [comment]
I ended up working around this with some monkey patching auth.User to make the email field unique and force lower caps. The only clean way I could think to do it would be replacing the user model outright - which is a ton of code for a very small change. 

Not sure the best solution here. Minimally Oscar could document the issue and suggest some work-arounds.

**Comment by mvantellingen** [comment]
PR welcome

**Comment by sasha0** [comment]
I neither don't see so far better option as to document this. Enforcing custom user model is not backwards compatible with existing Oscar installations. Besides, using generic Oscar user creation flow it's not available to create multiple users with the same email address.

**Comment by sasha0** [comment]
The only other option I have in mind is to override user admin with the custom model form which will enforce email address uniqueness. WDYT @solarissmoke @mvantellingen ?

**Comment by solarissmoke** [comment]
I've added to the documentation in #2354 to state that Oscar assumes a unique `email` field. Not sure whether it is feasible to do anything to fix this at the code level - the assumption of uniquess is baked pretty hard into Oscar.

**Comment by sasha0** [comment]
Agree. Closing.
