### ISSUE TITLE
check_basket_is_valid recalculates purchase info of a basket Line

### ISSUE THREAD

**Issue by mblayman** [django-oscar/django-oscar#2044]
I work on an application where price calculation is dynamic and expense computationally. While trying to optimize my application code, I found that `check_basket_is_valid` does not use the cached `purchase_info` property available for basket lines. Because of this, I have certain Django views that are doing redundant work.

Since it calls `fetch_for_line` directly, it bypasses the proxying work and cache that `Line.purchase_info` provides.

**Comment by mvantellingen** [comment]
Can you supply a PR for this? Thanks :-)

**Comment by sasha0** [comment]
This won't work since `availability` and `stockrecord` will be cached, and then, if we allocate remaining number of the stock record and it becomes unavailable - `check_basket_is_valid` would still pass.

I added tests to verify this.

**Comment by sasha0** [comment]
Closing since my test proofs appropriateness of current implementation. If you have other suggestion for performance improvement - please open a new issue. Thanks!
