### ISSUE TITLE
Incorrect results for product category

### ISSUE THREAD

**Issue by 5w0rdf15h** [django-oscar/django-oscar#2046]
Hello.

I have few categories for each product, for example there is a Banquette which might be in

Home > Chairs > Banquette
Hotels > Chairs
Bedroom > Chairs

The problem appears when I open "Hotels > Chairs" category. There are chairs and banquettes listed in this category which is not correct. Only chairs should be listed in this category. I tried to change oscar/apps/search/search_indexes.py, class ProductIndex and change 

`category = indexes.MultiValueField(null=True, faceted=True)`

to 

`category = indexes.MultiValueField(null=True, faceted=True, indexed=False)`

to prevent elasticsearch fulltext analyzer work for that field. It did not help, so I rebuild index manually and add my own mappings to Elastic.

```
"category": {
    "type": "string",
    "index": "not_analyzed"
},
```

But after reindexing elastic all products failed to appear in any category, so I had to rebuild schema using python manage.py rebuild_index and I return my problem again. 

Is there any way to fix this problem?

**Comment by amirrpp** [comment]
change [this](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/views.py#L221)
to
`return [self.category]`

**Comment by sb83** [comment]
> change this to return [self.category]

Unfortunately it did not help :(
Haystack query is as follows (output from haystack_panel):
Query String
`category:(Hotels AND > AND Chairs)`

**Comment by anentropic** [comment]
Are the categories structured hierarchically in the db? Or the catgoery name is the string `"Home > Chairs > Banquette"` ?

If the latter then maybe you can find a way to use exact matching: http://django-haystack.readthedocs.io/en/v2.4.1/inputtypes.html#exact

**Comment by sasha0** [comment]
Closing due to pending feedback for a while. During my latest tests on ES and ES2 product category filter worked fine so I suspect reported problem was rather local.

For support issues please use mailing list or Slack. Thanks.
