### ISSUE TITLE
Duplicate ID in template/catalogue/partials/gallery.html

### ISSUE THREAD

**Issue by quakig** [django-oscar/django-oscar#2048]
Found duplicate id ` <div id="product_gallery" ...>` in the file 

> template/catalogue/partials/gallery.html

**Comment by jjanssen** [comment]
It's in the template twice due to a difference between having a single product image and multiple product images and they have different additional CSS-classes. The ID is being wrapped within a if-else and doesn't render twice in in the page.

**Comment by vdboor** [comment]
Thanks @jjanssen for clearing this up!
