### ISSUE TITLE
category images not showing

### ISSUE THREAD

**Issue by Nuruddinjr** [django-oscar/django-oscar#2059]
```python
{% category_tree depth=2 as tree_categories %}
{% for category, info in tree_categories %}
    {% if info.level == 0 %}
        <li><a href="{{ category.get_absolute_url }}"><i
                class="fa fa-{{ category.icon }} dropdown-menu-category-icon"></i>{{ category.name }} </a>
            {% if info.has_children %}
                . . .
    {% category_tree depth=1 parent=category as sub_categories %}
    {% for sub_category, info in sub_categories %}
    <div class="col-md-4">
        <a href="{{ sub_category.get_absolute_url }}">
            <h5 class="dropdown-menu-category-title">
                {#here only the first category is shown with image, the rest is without image#}
                {% thumbnail sub_category.image "100x100" upscale=False as thumb %}
                    <img
                            src="{{ thumb.url }}"
                            alt="{{ sub_category.name }}"
                            title="{{ sub_category.name }}"
                    />
                {% endthumbnail %}
                {{ sub_category.name }}

            </h5>
        </a>
            <ul class="dropdown-menu-category-list">
                {% category_tree depth=1 parent=sub_category as sub_sub_categories %}
                {% for ss_category, info in sub_sub_categories %}
                    <li>
                        <a href="{{ ss_category.get_absolute_url }}">{{ ss_category.name }}</a>
                        <p>{{ ss_category.description|safe }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
                ...
                {% if info.level == 0 %}   {# Here image is shown  #}
                    {% thumbnail category.image "300x300" upscale=False as thumb %}
                        <img class="dropdown-menu-category-section-theme-img"
                             src="{{ thumb.url }}"
                             alt="{{ category.name }}" title="{{ category.name }}"
                             style="right: 10px;"/>
                    {% endthumbnail %}
                {% endif %}
                </div>
                </div>
            {% endif %}
        </li>

    {% endif %}
{% endfor %} ```

**Comment by LennyLip** [comment]
also in demo does not shown 
http://latest.oscarcommerce.com/media/cache/59/d3/59d3d8c74e03cbba3aed4051c18d6a8c.jpg

**Comment by Nuruddinjr** [comment]
@LennyLip  why do you think this issue happening?
I can't still find the issue
interesting thing is the first image is shown in the for loop the rest is not shown....

**Comment by LennyLip** [comment]
@Nuruddinjr i think, i found reason. I try to install oscar locally. And get [follow error](http://stackoverflow.com/a/35143733/1271271), when try to get image by url like a an /media/cache, etc. problem in sorl-thumbnail v12.3 in a PyPI , that the package doesn't contain any migrations (and last django 1.9 does not suppor syncdb).  So i change sorl version to 12.4a1 in requirements.txt, reinstall it and run migrations.
And all work for me  now.

**Comment by Nuruddinjr** [comment]
Thanks, i will try for sure, don't u know why when i give size for sorl, it doesn't resize it

**Comment by mvantellingen** [comment]
So the current setup.py in master requires sorl-thumbnail>=12.4a1 so it should be all good there right? Closing for now since this will be available in 1.3 then. If i'm wrong then let use know

**Comment by LennyLip** [comment]
@mvantellingen but demo images does steel does not work http://latest.oscarcommerce.com/en-gb/catalogue/ 
![oscar-demo](https://cloud.githubusercontent.com/assets/955994/16818889/b09d6afa-4952-11e6-9d06-41579c62e572.png)

**Comment by MR612** [comment]
i'm using django-oscar, and i faced the same issue.
i installed sorl thumbnail 12.4a1, but it didn't fixed the problem.
any ideas? or new solutions?
thanks  a lot.

**Comment by SalahAdDin** [comment]
Can you provide a traceback?

**Comment by SalahAdDin** [comment]
You can see in browser content, or use `django-debug-toolbar` or the old but trustable `print()`.

**Comment by alientt-tony** [comment]
any updates here?
I'm trying django-oscar with lightsail + nginx and i can't also see the images.
Any help here?

Thanks.
