### ISSUE TITLE
Content Blocks deletion is not working

### ISSUE THREAD

**Issue by CoffeeNight** [django-oscar/django-oscar#2064]
1. Go to Oscar Dashboard
2. Create a new content block RawHTML
3. Try to delete it

TypeError at /oscar/dashboard/content-blocks/delete/rawhtml/1/
argument of type 'bool' is not iterable
Request Method:	GET
Request URL:	http://pollux.local:8000/oscar/dashboard/content-blocks/delete/rawhtml/1/
Django Version:	1.9.7
Exception Type:	TypeError
Exception Value:	
argument of type 'bool' is not iterable
Exception Location:	/home/radevil/virtualenvs/pollux/lib/python3.4/site-packages/django/templatetags/i18n.py in render_value, line 162
Python Executable:	/home/radevil/virtualenvs/pollux/bin/python
Python Version:	3.4.3

**Comment by CoffeeNight** [comment]
The bug is not present in Django 1.8.13

**Comment by CoffeeNight** [comment]
Bug seems to be fixed in Django 1.9.8

**Comment by mvantellingen** [comment]
Interesting. So 1.9.8 works and 1.9.7 fails? Don't see any relevant fix in the changelog.

**Comment by CoffeeNight** [comment]
It is possible that the problem was in any of the dependencies and when I upgraded it, it fixed. I am still uncertain, have you been able to replicate it?. Probably it was just in my set up.

**Comment by sasha0** [comment]
@CoffeeNight what is `string_if_invalid` settings in your project?

Since this issue occurred on this line - https://github.com/django/django/blob/1.9.7/django/templatetags/i18n.py#L162, I could reproduce it with boolean value of this setting.

**Comment by CoffeeNight** [comment]
@sasha0 That's correct!!, when it is set to True I get the error.

**Comment by sasha0** [comment]
@CoffeeNight I think this option value of `string_if_invalid` intended to be string type. If you don't need this option - you could just remove it, since it has default value as empty string.
