### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2085]
Hi guys, 

I'm working in my project and test some scripts with `shell_plus` and `ipython`.

Creating a partner i get this warning.
```pyhon
we = Partner.objects.create(name='')
/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/oscar/models/fields/autoslugfield.py:89: RemovedInDjango110Warning: 'get_fields_with_model is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
  for field, model in model_cls._meta.get_fields_with_model():
```

Thanks for your great work.

**Comment by mvantellingen** [comment]
There are various efforts underway to make oscar 1.10 compatible.

**Comment by SalahAdDin** [comment]
@mvantellingen  Ok man, Did something list this warning for take in these efforts?
