### ISSUE TITLE
custom ModelForm no longer works after 1.8 -> 1.9 upgrade

### ISSUE THREAD

**Issue by birophilo** [django-oscar/django-oscar#2086]
Hi sorry to post here as I feel like this more likely to be general to the Django 1.8 -> 1.9 upgrade process than Oscar-specific, but I'm using django-oscar together with my own subscription app and was seeing if I could upgrade Django 1.8 to 1.9 before deploying. But after upgrading Django, my own ModelForm for AbstractAddress no longer works, saying that Country cannot be loaded (into the fields list in Meta class). I've posted on Stackoverflow - I was wondering if anyone can shed light on why this works with oscar in Django 1.8 but not 1.9, or if anyone else has experienced similar. Would be grateful for any input - otherwise I guess I'll just stick with 1.8. 

http://stackoverflow.com/questions/38833608/cannot-create-form-field-for-country-yet-because-its-related-model-address-c

Thanks, and many thanks for this great project,
Andrew

**Comment by mvantellingen** [comment]
Did you try this with 1.2 or with 1.3rc2?

**Comment by birophilo** [comment]
Hi there, it's 1.2.1.

**Comment by mvantellingen** [comment]
Ok, 1.2 is not compatible with Django 1.9. Try 1.3rc2. The final 1.3 is released end of this week i hope

**Comment by birophilo** [comment]
Ah OK, I should have checked, thanks a lot!
