### ISSUE TITLE
Add username to oscar's user forms

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2087]
Hi guys, i'm working in two projects with Oscar and i'm testing all features.

Creating a partner i have to link users but creating they, the create user form, as register form, put email and password fields but username.

![seleccion_144](https://cloud.githubusercontent.com/assets/5034215/17502593/d3585bb6-5dae-11e6-85a6-0f68afdd766a.png)
I went to `Partners` admin module and i found the partner's linked users and i found this horrible thing.

![seleccion_143](https://cloud.githubusercontent.com/assets/5034215/17502592/d31879b0-5dae-11e6-89e0-bcb2fbc86b8d.png)
So, i want see the user list and i found this horrible thing: Oscar's register form create a random username for the new users.

![seleccion_146](https://cloud.githubusercontent.com/assets/5034215/17502595/d3a74b9a-5dae-11e6-9a2c-94f3a447e085.png)
I tried to edit the account profile and i couldn't found the username field.

![seleccion_145](https://cloud.githubusercontent.com/assets/5034215/17502594/d37f4866-5dae-11e6-874b-01daba622e86.png)
I verified the register name thinking that i could forgot put the username when i register that user, but, in register form username doesn't exist.

I created two users with username and i could create they, so, i think that Oscar doesn't restrict the user back end.

So, Have you thinking about add username to forms?

**Comment by sasha0** [comment]
Partner management in the dashboard allows to link existing user or to create new one and link it. Allows to search by email and does not use username field.

**Comment by SalahAdDin** [comment]
Yes yes, i know this, but creating a new user we can not create a user name for it.

I think that will be better add this field or, default, backend give a username joining the full name or split the email and give the @ preview part.

For example:
First Name: _Pepito_ 
Last Name: _Perez Perenzejano_
Usersanem: _PepitoPerez_

Or:
email: _pepitoperez22@example.com_
username: _pepitoperez22_

**Comment by SalahAdDin** [comment]
Creating my custom user model based your models i can see that `username` field isn't in `user` model, at least in my case, but in `django-oscar` model is, at least i can see in the admin site.

Why?

**Comment by sasha0** [comment]
Oscar use email and password fields for auth, username being randomly generated, if it's used in the user model. If you need to generate username in other way or allow user to fill it in - you can override user forms and/or user model.

Thanks.

**Comment by SalahAdDin** [comment]
Which form or user model?

**Comment by sasha0** [comment]
The point it, if you need a readable username for user model repr, you can override `oscar.apps.customer.forms.EmailUserCreationForm` locally and implement your own username generation https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/customer/forms.py#L181, as a concatenation of first and last name or etc.

Otherwise, there's no reason to add this field to the forms, since `email` field used as a username field.

Thanks.

**Comment by arafay993** [comment]
Adding a username is easier than you expect. You need to override the customer app of Django oscar by following command:
python manage.py oscar_fork_app customer project_name
After that create a form.py file in the newly customer module located in project_name folder. And append the following code onto the file:
`from oscar.apps.customer.forms import EmailUserCreationForm as CoreEmailUserCreationForm
from django import forms
from django.utils.translation import gettext_lazy as _
from oscar.core.compat import (
existing_user_fields, get_user_model)

User = get_user_model()

class EmailUserCreationForm(CoreEmailUserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'username',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])

        if 'username' in [f.name for f in User._meta.fields]:
            user.username = self.cleaned_data['username']

        if commit:
            user.save()
        return user`
Note: don't forgot to include your customer app in your INSTALLED_APPS in settings.py like this
'project_name.customer.apps.CustomerConfig'
![login_reg](https://user-images.githubusercontent.com/46745314/63209943-eb19ad00-c100-11e9-812b-7f84f34ac645.png)

**Comment by dante1119** [comment]
Hi, thankyou for the snippet but, it does not help in using 'username' for authentication ... 
it looks like oscar has 'hardcoded' the email in the customer app and I suppose to be enforced to rewrite the whole app
Do you know a way to override the email with a different username (django AUTH_USER_MODEL = 'customapp.MyUser')?
Thankyou for any help
