### ISSUE TITLE
Sorl-thumbnail features unnused.

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2088]
Hi guys

I worked in a news website using `sorl-thumbnail` package for handle images and i can remember use an admin mixin for improve the admin.

``` bash
from sorl.thumbnail.admin import AdminImageMixin

class MyModelAdmin(AdminImageMixin, admin.ModelAdmin):
    pass
```

You can read documentation about [`AdminMixin`](http://sorl-thumbnail.readthedocs.io/en/latest/examples.html#admin-examples).

This feature improve a thumbnail inside model object change form and model object list, yes, you can see the image in the change form and view a small image by each objects in the list.

So, i try use it:

``` python
class ProductImageAdmin(AdminImageMixin, admin.ModelAdmin):
    list_display = ['product', 'original', 'display_order', 'date_created']

admin.site.register(ProductImage, ProductImageAdmin)
```

But i couldn't see any change in admin view, so, i investigate in the code and i found this:

``` python

    original = models.ImageField(
        _("Original"), upload_to=settings.OSCAR_IMAGE_FOLDER, max_length=255)
```

In `ProductImage` model Oscar use a normal image field instead a `sorl-thumbnail` [Image Field](http://sorl-thumbnail.readthedocs.io/en/latest/examples.html#model-examples),  for this reason the mixin doesn't works.

But, i think that Oscar use `sorl-thumbnail` for use his Image Field, but seems isn't it.

Have you plans use full featured `sorl-thumbnail`?

Thanks.

**Comment by mvantellingen** [comment]
My personal preference is to switch to https://github.com/SmileyChris/easy-thumbnails instead

**Comment by SalahAdDin** [comment]
@mvantellingen  Why?

**Comment by sasha0** [comment]
As for the admin enhancement - it could be easily customized locally, moreover primary place for managing content in the Oscar is its own dashboard, which should be exclusively considered for the improvement, I believe.

Regarding thumbnails generating engine - it makes sense to finish implementation of thumbnails generation, not specific to the engine, started in the #1408, which would give opportunity to use any Django application for thumbnail generation of own choice, not only `easy-thumbnails` or etc and also to simplify further Oscar integration into other applications.
