### ISSUE TITLE
Payment options bar wrong styled

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2098]
Hi guys, testing the project i viewed this:
![seleccion_198](https://cloud.githubusercontent.com/assets/5034215/17656383/2f920c86-627f-11e6-8a45-9213e4e2f842.png)
Paypal buttons as checkout button are out of properly bar.

This will be a styles bug.

**Comment by sasha0** [comment]
This issue related to the `django-oscar-paypal` package, please submit it to the appropriate repository. Thanks.

**Comment by SalahAdDin** [comment]
Why are you sure about it?
