### ISSUE TITLE
Vouchers can be reused under concurrent checkout

### ISSUE THREAD

**Issue by TWarszawski** [django-oscar/django-oscar#2101]
When two customers check out concurrently using a voucher that should only be able to be used once by one customer, the voucher can be used twice.

Steps to reproduce:
1.  Start sandbox, create two customers, create/pick test product, create test voucher with usage setting “can be used once by one customer”.
2.  Both customers add the item to their baskets, apply the voucher, and perform the  checkout concurrently, making sure both customers finish checkout (click the Place Order button) as close to the same time as possible.

We have reproduced this behavior on a single machine, by performing the above steps in rapid succession with one customer in one browser window and another customer in a second browser window.

Expected Result:
Only one checkout successfully completes using the voucher.

Actual Result:
Both checkouts successfully complete using the voucher.

**Comment by sasha0** [comment]
Fixed in 8fb5ce932beeffc3df1482dce9198a0978a6855b
