### ISSUE TITLE
Datetime picker does not default to zero seconds

### ISSUE THREAD

**Issue by sasha0** [django-oscar/django-oscar#2104]
When hours selected, seconds don't default to zeros:

![2016-08-18 15 08 54](https://cloud.githubusercontent.com/assets/673711/17773203/deb02580-6555-11e6-85db-163823ee6413.png)

Found by @pwalsh

**Comment by SalahAdDin** [comment]
Interesting, have you think about implements date dropper and time dropper? Have a seem style.

**Comment by sasha0** [comment]
E.g.? Please explain.

**Comment by SalahAdDin** [comment]
Ah, no, forget it, `datedropper` and `timedropper` aren't integrate in one script, and your scrip is.
