### ISSUE TITLE
Custom Shipping admin doesn't works properly

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2106]
I created a repository  for shipping methods, so, i make the appropriate app and put this code in the admin:

``` python
from django.contrib import admin

from oscar.core.loading import get_model

OrderAndItemCharges = get_model('shipping', 'OrderAndItemCharges')
WeightBand = get_model('shipping', 'WeightBand')
WeightBased = get_model('shipping', 'WeightBased')


class OrderChargesAdmin(admin.ModelAdmin):
    filter_horizontal = [
        'countries',
    ]

    list_display = [
        'name',
        'description',
        'price_per_order',
        'price_per_item',
        'free_shipping_threshold'
    ]


class WeightBandInline(admin.TabularInline):
    model = WeightBand


class WeightBasedAdmin(admin.ModelAdmin):
    filter_horizontal = [
        'countries',
    ]

    list_display = [
        'code',
        'name',
        'default_weight'
    ]

    inlines = [WeightBandInline]


admin.site.register(OrderAndItemCharges, OrderChargesAdmin)
admin.site.register(WeightBased, WeightBasedAdmin)
```

So, i'll test the methods and i want add shipping countries for the existing methods.
![problem](https://cloud.githubusercontent.com/assets/5034215/17793654/9308b778-656e-11e6-8c2f-3f5269687817.gif)

You can see here that change the country field isn't saved by the admin module, and add other country replace the existing country. This problem isn't present with the other fields. In Partner models there aren't problem to add users to a partner.

Other case is this:
![seleccion_218](https://cloud.githubusercontent.com/assets/5034215/17795786/ead35d3e-6580-11e6-881f-a5ba9b5ed8be.png)
If a want delete one of theme, well, all are deleted,  but, again, doesn't save the change.

![out 04d](https://cloud.githubusercontent.com/assets/5034215/17793472/233cf018-656d-11e6-9b38-a7b94cc8acc1.gif)
But, when i do this changes in the dashboard module, i haven't problem for update the methods.

Can anyone help me to explain this?

**Comment by solarissmoke** [comment]
I'm not able to reproduce this issue. Feel free to reopen if you can provide steps to reproduce on master.
