### ISSUE TITLE
Other Django 1.10 warnings

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2109]
I want report other warning:
```bash
/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/oscar/apps/customer/abstract_models.py:239: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  messages[name] = template.render(Context(ctx)) if template else ''
```

Will be better make a list in a pr and mark as solved all warnings. :D

**Comment by mvantellingen** [comment]
Hi @SalahAdDin, could you please stop creating issues for each 1.10 related warning. As said before in another issue, it isn't merged yet. This is completely unhelpful and only leads to more work on our end.

Thanks.
