### ISSUE TITLE
Run tests using Docker / Docker Compose

### ISSUE THREAD

**Issue by sunsongxp** [django-oscar/django-oscar#2110]
Since this project already supported using docker-compose to run sandbox, it's reasonable to have the idea that runs all tests also using docker-compose, so that I don't have to mess with installing all the components in my Mac. I tried, but failed, so how to make it work if possible, or I just don't know how to do it, is there anybody can help on this?

**Comment by SalahAdDin** [comment]
Which error?

**Comment by sunsongxp** [comment]
No error actually, I was just wondering if you can support running tests in docker environment. It's fine if you don't support it. Please close it if not.

**Comment by sasha0** [comment]
Not supported yet.
