### ISSUE TITLE
productIndex should have a template with relative path instead of the absoute oscar path

### ISSUE THREAD

**Issue by kkx** [django-oscar/django-oscar#2114]
[ProductIndex.text: template_name field](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/search/search_indexes.py#L15) 
with relative path, it is easier to override the search index template(item_text.txt) without the need of subclassing the entire search module.
I will submit a PR.

**Comment by sasha0** [comment]
Merged. Thanks.
