### ISSUE TITLE
user search logics is wrong in dashboard.users page

### ISSUE THREAD

**Issue by kkx** [django-oscar/django-oscar#2116]
As described in [issue 1337](https://github.com/django-oscar/django-oscar/issues/1337) too, Oscar assumed that [users only have 2 parts as firsname and last name](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/dashboard/users/views.py#L85), which is not true. For example: Pablo Ruiz Picasso has 3 parts both Ruiz Picasso are his lastname, in the current version, this user would not be searched in the dashboard.
I am going to submit a PR for this fix

**Comment by sasha0** [comment]
Closing since PR #2117 already merged.
