### ISSUE TITLE
Cannot replace dashboard to my custom dashboard OSCAR_DASHBOARD_NAVIGATION

### ISSUE THREAD

**Issue by arunjoseph** [django-oscar/django-oscar#2123]
I followed [this](http://django-oscar.readthedocs.io/en/releases-1.1/howto/how_to_configure_the_dashboard_navigation.html) tutorial

But I wanted to make changes in the catalogue area so I tried to write OSCAR_DASHBOARD_NAVIGATION = [..My List..] but it doesn't work it only works with 
OSCAR_DASHBOARD_NAVIGATION += [... Extra list ...]

**Comment by sasha0** [comment]
Overriding of the whole list of the setting works fine as well as append of the extra items, just re-checked.

Make sure your all navigation items in the `MyList` has proper viewnames and permissions, since if `oscar.apps.dashboard.nav.default_access_fn` can't access it - it would skip it.

**Comment by SalahAdDin** [comment]
Or verify if links are working!

**Comment by arunjoseph** [comment]
I did it in another way by forking the dashboard app and then change the links there

**Comment by Aiky30** [comment]
Not directly related but may help if you are just adding a couple of links to the default list. The following snippet modifies the "Fulfilment" drop down to add the shipping controls that are disabled by default.

Adding the following to your settings (settings.py) will append the new link at the end of the fulfilment link. 

```
# Loop through the dashboard config and append new children
for navigation in OSCAR_DASHBOARD_NAVIGATION:
    if(navigation.get('label') == _('Fulfilment')):
        navigation.get('children').append(
            # The shipping method dashboard is disabled by default as it might
            # be confusing. Weight-based shipping methods aren't hooked into
            # the shipping repository by default (as it would make
            # customising the repository slightly more difficult).
            {
                'label': _('Shipping charges'),
                'url_name': 'dashboard:shipping-method-list',
            },
        ) 
```

The solution is a little hacky but I thought it was better than forking the entire list, now I only need to care about the word Fulfilment changing. You could add a test to test for this when updating if necessary.

**Comment by solarissmoke** [comment]
Closing this as is appears to be an implementation issue rather than a bug in Oscar. Feel free to reopen if you think there is a bug and can provide more details.
