### ISSUE TITLE
missing documentation for multicurrency support

### ISSUE THREAD

**Issue by Wingie** [django-oscar/django-oscar#2124]
#804 implies oscar has support for multiple currencies

in http://django-oscar.readthedocs.io/en/releases-1.1/topics/prices_and_availability.html
i can see a `info.price.currency` 
and also `|currency:session.price.currency` in the template

how do we decide which currency to show the user based on his locale (babel or geoIP location?)
in some places currency is implied to be basked oriented.

i am happy to submit a documentation PR on using multiple currencies and stores once i am clear about the basic concept.

**Comment by alexphelps** [comment]
Any update on how to do this or create a currency switcher like the language switcher?

I'm looking to create something like this:
![image](https://user-images.githubusercontent.com/674282/30550359-376e0844-9c65-11e7-938b-38643b32c557.png)

**Comment by sandeepimpressads** [comment]
> Any update on how to do this or create a currency switcher like the language switcher?
> 
> I'm looking to create something like this:
> ![image](https://user-images.githubusercontent.com/674282/30550359-376e0844-9c65-11e7-938b-38643b32c557.png)

Is this implemented ?

**Comment by sabuhish** [comment]
> > Any update on how to do this or create a currency switcher like the language switcher?
> > I'm looking to create something like this:
> > ![image](https://user-images.githubusercontent.com/674282/30550359-376e0844-9c65-11e7-938b-38643b32c557.png)
> 
> Is this implemented ?

+
