### ISSUE TITLE
need help in Stock and pricing section .

### ISSUE THREAD

**Issue by prabhatpankaj** [django-oscar/django-oscar#2126]
Hi I want to know how to implement Stock and pricing for products. 
I have 2 vendor partner with different stock ( 1 and 2 ) and different price ( 900 and 1000 ) .
![screen shot 2016-10-01 at 5 53 00 am](https://cloud.githubusercontent.com/assets/20439273/19010312/d58a2b8c-879b-11e6-9ae4-a88519a41527.png)
its should shows number of stock = 3 and price should be minimum of both ( here 900 ) 
but in actual it takes only 1st partner stock and price .
![screen shot 2016-10-01 at 5 53 26 am](https://cloud.githubusercontent.com/assets/20439273/19010313/d58eae0a-879b-11e6-90b1-d5315e7c12f0.png)

please provide me info how to solve this .
Thanks

**Comment by SalahAdDin** [comment]
:+1: , but i think that people will say you that user mailing list.

**Comment by maerteijn** [comment]
Oscar is using a strategy object to determine availability and pricing. See the oscar documentation here: 
http://django-oscar.readthedocs.io/en/releases-1.3/topics/prices_and_availability.html

**Comment by solarissmoke** [comment]
Closing as this is a support question - please use the mailing list for help.
