### ISSUE TITLE
Product search returns products that contain any *char* from the query

### ISSUE THREAD

**Issue by anentropic** [django-oscar/django-oscar#2127]
If I search for `red dress` I get any products with `r` or `e` or `d` or `s` in them.

I am using Elasticsearch backend.

Can anyone provide any suggestion of how to begin solving this?

I'm not even sure right now what to google for

**Comment by anentropic** [comment]
Is it the tokeniser?  I don't want to use exact matching, I want `red AND dress`

**Comment by anentropic** [comment]
yeah I think this is because of use of `EdgeNgramField` in `ProductIndex`

I assume that was needed to make auto-complete work but it stuffs up the normal search results

so I think these features should use separate fields

at the moment both `title` and `text` are using `EdgeNgramField` ...I'm not sure where autocomplete is used but maybe it's enough to just have the ngram on `title`? Then the document field `text` could just be a `CharField` so as to return sensible results from search.

I have done this successfully in my own oscar project, overriding the field on my `ProductIndex`, and it works as desired... does the current default setup make any sense?

**Comment by solarissmoke** [comment]
Fixed via #2128.
