### ISSUE TITLE
django-oscar multi vendor is not supporting i want if vendor login they want see there product they wont see other product information

### ISSUE THREAD

**Issue by manioftony** [django-oscar/django-oscar#2132]
https://django-oscar.readthedocs.io/en/releases-0.6/howto/multi_dealer_setup.html

This is not working

**Comment by manioftony** [comment]
https://django-oscar.readthedocs.io/en/releases-0.6/howto/multi_dealer_setup.html

**Comment by sasha0** [comment]
You are referring to the quite outdated and no longer relevant documentation.

Could you describe your issue with multiple partners in details? Thanks.

**Comment by solarissmoke** [comment]
Closing because no feedback - feel free to reopen if you can explain in more detail what you're trying to do.

**Comment by codingmehelp** [comment]
Hi, Does django-oscar provide multi vendor functionality to build marketplace and if so what the steps to build this in a project?

**Comment by mpiplani** [comment]
Basically i am also facing the same problem , i have a product type suppose xyz and it can be sold by multiple vendors , so how to incorporate it oscar
