### ISSUE TITLE
IntegrityError Returned when moving product to wishlist already in it

### ISSUE THREAD

**Issue by ibrmora** [django-oscar/django-oscar#2133]
IntegrityError Returned when moving product from wishlist  to another wishlist already in it.

The error can be reproduced by:
1- In "product A" page add it to "wishlist B" & "wishlist C".
2-Go to ~/accounts/wishlists page.
3- In "wishlist B" choose Move to "C" wishlist from Action for "product A".

**Comment by ibrmora** [comment]
As quick fix I removed the move to wishlist option

**Comment by sasha0** [comment]
Thanks for the report. Fixed in afc6d6b814eb0cb59ff12bd3148abd53b90f2622.
