### ISSUE TITLE
offer doesn't work as expected

### ISSUE THREAD

**Issue by ijasperyang** [django-oscar/django-oscar#2134]
hi,
I create a the following offer according to the doc. but I find it doesn't work as expected.
_offer: Buy 1 Lonely Planet books, get £5 off a Lonely Planet DVD
1. Create a range for Lonely Planet books and another for Lonely Planet DVDs
2. Use a count-based condition linking to the book range with a value of '**1**'
3. Use a fixed discount benefit that links to the DVD range and has a value of 5._
This offer only applies when I add one more product outside the Lonely Planet books range. 
it can't work even if I just add 2 products in Lonely Planet books range.
the workaround is to change the value in step 2) to '0' instead of '1', then everything goes ok.

**Comment by solarissmoke** [comment]
I'm not able to reproduce this issue on master - following the steps you describe, the discount is correctly applied if I add one product from the condition range and one product from the benefit range to the basket.

Can you confirm whether you are still seeing the issue and if so, clarify the steps to reproduce?

**Comment by solarissmoke** [comment]
Closing due to lack of feedback from OP. Feel free to reopen with steps to reproduce.
