### ISSUE TITLE
Price won't update when selecting variants.

### ISSUE THREAD

**Issue by lirlocker** [django-oscar/django-oscar#2139]
The price for a parent product is inherited from the first variant.
When a customer selects a different variant than the default, the price of the selected variant will only show in the basket and it won't update immediately in the product page.

**To make myself more clear:**
I have a product with two child products (variants).
When I choose a variant from the drop-down list (in the product page) the price of the product stays the same, although the variants have different prices.
I am able to see the price only when I check out.
@SalahAdDin

**Comment by john-parton** [comment]
This goes along with https://github.com/django-oscar/django-oscar/issues/675

Currently something I fixed in my app, but there's no consensus on a real fix.

**Comment by HerraLampila** [comment]
@john-parton can you share any details how you fixed this?

**Comment by solarissmoke** [comment]
Closing as a duplicate of #675 which covers better variant support in all respects.
