### ISSUE TITLE
Add git tag for 1.3 release

### ISSUE THREAD

**Issue by jsma** [django-oscar/django-oscar#2140]

**Comment by jsma** [comment]
Perhaps related, the docs default to 1.2 on Read the Docs. Tangential to that, is if you click 'edit on GitHub' on the docs page, the user gets a 404 error => https://github.com/django-oscar/django-oscar/blob/releases-1.2/docs/source/index.rst

**Comment by SalahAdDin** [comment]
In this case, will be 1.4 version.

**Comment by mvantellingen** [comment]
Just pushed the tag! Totally forgot
