### ISSUE TITLE
Broken link to analytics.oscarcommerce.com

### ISSUE THREAD

**Issue by jsma** [django-oscar/django-oscar#2141]
A [dashboard template](https://github.com/django-oscar/django-oscar/blob/6dfb5a2e01e60f88ef147728e4d2a9968805839a/src/oscar/templates/oscar/dashboard/layout.html#L134) calls home to //analytics.oscarcommerce.com/tracker.gif but this does not resolve. It looks like there aren't any valid CNAME or A records configured for this subdomain.

**Comment by sasha0** [comment]
Yeah, this should be removed.

Thanks for the report!
