### ISSUE TITLE
maximum number of items available is wrong when multiple stockrecords for the same product exist

### ISSUE THREAD

**Issue by tejon-melero** [django-oscar/django-oscar#2161]
I have a product with two different stockrecords (A and B). 
Stockrecord A has 2 products available (net_stock_available=2)
Stockrecord B has 15 products available (net_stock_available=15)

When a customer adds the product to his basket Stockrecord A gets selected. 
Then the customer clicks on view basket and increases the number of this products in his basket from 1 to 5.
Oscar then throws an error with the message "only two products available", although there is a stockrecord with 15 free products. 

In that case the stockrecord of the line in the basket should automatically change to the stockrecord that has sufficient capacity for the order.

**Comment by solarissmoke** [comment]
You need to implement this logic of deciding which stockrecord to select in your strategy - the default strategy logic is simply to select the first stockrecord that is available. If you want more complex handling then you need to provide a custom strategy that does what you want.

**Comment by solarissmoke** [comment]
Closing as this looks like a customisation issue. If there is a bug in Oscar itself, please feel free to reopen with details.
