### ISSUE TITLE
Not able to apply custom benefit

### ISSUE THREAD

**Issue by arunjoseph** [django-oscar/django-oscar#2163]
I followed the following [http://django-oscar.readthedocs.io/en/releases-1.2/howto/how_to_create_a_custom_benefit.html](tutorial) I did the same and tried to apply the benefit using ```create_benefit``` present in the ```oscar.apps.offer.custom``` after appling I get a recursion error and the function also warns of recursion error if not applied ```__str__ ``` but even after that I am facing the same problem. Kindly help ASAP

I am using Oscar 1.3

**Comment by CoffeeNight** [comment]
I solved it by adding my own 
@property 
def name(): and 
@property
def description()

**Comment by sasha0** [comment]
I believe we should leave a note in the docs about name property declaration when defining custom benefit.
