### ISSUE TITLE
pagination shows less than OSCAR_PRODUCTS_PER_PAGE  

### ISSUE THREAD

**Issue by Nuruddinjr** [django-oscar/django-oscar#2164]
I have defined OSCAR_PRODUCTS_PER_PAGE = 21  in the first page, but in some cases, 
it is giving me 19.
![image](https://cloud.githubusercontent.com/assets/9083431/20168544/8c9d7bf4-a744-11e6-9575-65726eb834a4.png)

**Comment by solarissmoke** [comment]
There's not enough information here to be able to help... you're counting products in Javascript so we would need to see your templating logic. Also are you sure you have more than 19 products in the result set?
