### ISSUE TITLE
Offer conditions are unwieldy to modify or extend because the proxy_class attribute is unique

### ISSUE THREAD

**Issue by ckepper** [django-oscar/django-oscar#2166]
This issue is related to #685. Just as the offer benefits the offer conditions should not require a unique proxy class. This would make writing and applying custom conditions easier as a single condition proxy class could be applied to multiple conditions.

Hacks for overwriting the AbstractCondition class as well as custom migrations don't seem like a good long term solution.

**Comment by Bogh** [comment]
+1

**Comment by crgwbr** [comment]
We sort of addressed this in https://gitlab.com/thelabnyc/django-oscar-bluelight, but it certainly would be nice to see something upstream. The whole offers system is kind of unwieldy right now.
