### ISSUE TITLE
"Please copy/symlink the 'missing image'..." exception when MEDIA_ROOT folders are not created 

### ISSUE THREAD

**Issue by vaskinyy** [django-oscar/django-oscar#2168]
I get the exception 
`Please copy/symlink the 'missing image' image at ... into your MEDIA_ROOT at .... This exception was raised because Oscar was unable to symlink it for you."
`
whenever I create a fresh environment. 

When I just create folders structure of my MEDIA_ROOT the symlink is created.
Possible solution - add folder creation code before symlink creation.

**Comment by mvantellingen** [comment]
The missing image is always creating issues, we should do better. Ideas and/or PR's welcome

**Comment by solarissmoke** [comment]
Why don't we just link to ` django-oscar/src/oscar/static/oscar/img/image_not_found.jpg ` directly instead of attempting (and often failing!) to copy it into the media root? If projects want to customise/change the image they they can just provide their own image at the same path with higher priority, or set `OSCAR_MISSING_IMAGE_URL`.

**Comment by mvantellingen** [comment]
Yeah agreed. I'm not sure why was chosen for the current solution, but going the proper Django way sounds like a good plan

**Comment by solarissmoke** [comment]
Will do a PR

**Comment by solarissmoke** [comment]
This is why it was done that way: https://github.com/django-oscar/django-oscar/pull/734 . The image has to be inside `MEDIA_ROOT` for sorl-thumbnail to work on it. Any other ideas?

**Comment by mvantellingen** [comment]
Ah yeah, had to be a good reason for this. Perhaps a management command which does this automatically? Like ``./manage.py oscar_init_media`` ?
