### ISSUE TITLE
wrong order while loading models of forked apps

### ISSUE THREAD

**Issue by fpischedda** [django-oscar/django-oscar#2170]
I have a strange problem where one of the forked apps model is loaded after the one from oscar instead other forked apps are loaded in the correct order; this is causing a RuntimeError because our app tries to register a model that is already registered.

I have checked the get_core_apps() return value and the oscar model is overridden by our custom UserAddress model.

does AbstractUserAddress require some additional work or different procedure?

for all our cusom models we have followed this guide http://django-oscar.readthedocs.io/en/releases-1.3/howto/how_to_customise_models.html but only the custom UserAddress has problems at load time.

**Comment by sasha0** [comment]
Please share whole traceback of the exception and your models module.

**Comment by fpischedda** [comment]
sorry I can't, we have taken a different route to circumvent the problem and I don't have the traceback at hand at this time; as far as I remember the exception was thrown in the django model loading code and my hypothesis is that for some reson the model is referenced somewhere with the result of it being loaded befor the custom one

if you prefere we can close this issue until I can provide more evidence

**Comment by sasha0** [comment]
Alright, closing. Feel free to re-open in case of new issues. Thanks.
