### ISSUE TITLE
ProductIndex should use FloatField instead of DecimalField

### ISSUE THREAD

**Issue by bmihelac** [django-oscar/django-oscar#2172]
Haystack stores DecimalField as a string, which prevents sorting or faceting by `price` field.

Worth noting is that previous Solr schema.xml did have `tdouble` price field type.

Relavant issues:

https://github.com/django-haystack/django-haystack/issues/398
https://github.com/django-oscar/django-oscar/issues/1872
https://groups.google.com/forum/#!topic/django-haystack/JdJubx4lZvc

**Comment by sasha0** [comment]
Fixed in 8516b752510dbbf8a00c01461fe3efd57329d9b1. Thanks for the report and the fix.

**Comment by bmihelac** [comment]
thanks for merging!
