### ISSUE TITLE
Order filter form in profile throws UnicodeEncodeError

### ISSUE THREAD

**Issue by sandino** [django-oscar/django-oscar#2176]
Hi,

Order filtering form throws UnicodeEncodeError if site is displayed in language other than English. After debug I found that [mark_safe](https://github.com/django-oscar/django-oscar/blob/1.2.1/src/oscar/forms/widgets.py#L207) should accept unicode instead of string:

    return mark_safe(u'<div class="form-inline">'
                         ...
                         .format(div=div, input=input))

**Comment by solarissmoke** [comment]
I am not able to reproduce this issue - have tried in several languages. Please can you provide more detailed steps to reproduce?

**Comment by sandino** [comment]
@solarissmoke  
Try commenting out [line 24](https://github.com/django-oscar/django-oscar/blob/1.2.1/src/oscar/templates/oscar/customer/order/order_list.html#L24) in template

    {% include "partials/form_fields.html" with form=form style='horizontal' %}

and using something like 

```
{% for field in form %}
    <div class="my-div">{% render_field field class+='my-input' placeholder=field.label %}</div>
{% endfor %}
```

I'm specifying line numbers according to django-oscar==1.2.1, but I also managed to reproduce the error on versions 1.2.2, 1.3 and 1.4.

### Solution

Of course, it cannot be considered as a solution as it doesn't translate field labels, but at least it doesn't throw exceptions:

```
from oscar.apps.customer.forms import OrderSearchForm as CoreOrderSearchForm


class OrderSearchForm(CoreOrderSearchForm):
    def __init__(self, *args, **kwargs):
        super(OrderSearchForm, self).__init__(*args, **kwargs)
        self.fields['date_from'].label = 'From'
        self.fields['date_to'].label = 'To'
```
or we need to override the widget to pass unicode instead of string

```
class DatePickerInput(DateTimeWidgetMixin, forms.DateInput):
        ...
        return mark_safe(u'<div class="form-inline">'
                         u' {div}'
                         u'  {input}'
                         u'  <span class="input-group-addon">'
                         u'   <i class="icon-calendar glyphicon-calendar"></i>'
                         u'  </span>'
                         u' </div>'
                         u'</div>'
                         .format(div=div, input=input))
```
