### ISSUE TITLE
oscar_populate_countries command doesn't work

### ISSUE THREAD

**Issue by jklapuch** [django-oscar/django-oscar#2179]
Hi,
I am newbie with oscar. But next command doesn't work to me: `./manage.py oscar_populate_countries --no-shipping`, it returns: 

```
...
File "/home/honza/workspace/.envs/oscar/local/lib/python2.7/site-packages/pycountry/db.py", line 22, in __getattr__
    raise AttributeError
AttributeError
```
I found that new version of pycountry has some new [methods](https://bitbucket.org/flyingcircus/pycountry/src/ea961348f24dfbd382f285f3307782fc34c8e370/src/pycountry/db.py?at=default&fileviewer=file-view-default) and when I try to get non-existent attribute it will return an AttributeError.

I found a problem here:
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/management/commands/oscar_populate_countries.py

For countries without  `official_name` attribute,  `name=getattr(country, 'official_name', country.name),` returns error instead of `country.name` because pycountry raise the error.

**Comment by sasha0** [comment]
What version of `pycountry` do you use?

**Comment by jklapuch** [comment]
16.11.8, the only version available from pypi.

**Comment by sasha0** [comment]
It's not the only, it's the latest version. Proper version to use is in requirements.txt and it's 1.10.

**Comment by jklapuch** [comment]
Ok, thanks.
I used yolk3k package to get a list of available versions on PyPI:

```
$ yolk -V pycountry
pycountry 16.11.8
```
This is why I think that is the only.
