### ISSUE TITLE
Duplicate option

### ISSUE THREAD

**Issue by ibrmora** [django-oscar/django-oscar#2180]
In uwsgi.ini
https://github.com/django-oscar/django-oscar/blob/master/sites/sandbox/uwsgi.ini

(die-on-term = 1)  Duplicate twice

line 13
 Handle docker stop
die-on-term = 1 

line 28 
 Handle docker stop
die-on-term = 1

**Comment by sasha0** [comment]
Indeed. Thanks for the notice!
