### ISSUE TITLE
Confusing documentation on OSCAR_INITIAL_LINE_STATUS

### ISSUE THREAD

**Issue by tiberiuichim** [django-oscar/django-oscar#2192]
This is in ref/settings.rst:

> The status assigned to a line item when it is created as part of an new order. It
has to be a status defined in ``OSCAR_ORDER_STATUS_PIPELINE``.

But ``class AbstractLine:`` has a dedicated pipeline:

    pipeline = getattr(settings, 'OSCAR_LINE_STATUS_PIPELINE', {})

**Comment by accraze** [comment]
I also ran into this issue today too... can confirm that you can set `OSCAR_INITIAL_LINE_STATUS` to a status that is defined in `OSCAR_LINE_STATUS_PIPELINE` just  fine.

**Comment by sasha0** [comment]
Good catch, thanks!

**Comment by sasha0** [comment]
Fixed by #2350.
