### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by roodie** [django-oscar/django-oscar#2196]
What is the preferred method to contribute translations? I tried to apply for a new language on Transifex in may, but nothing happened. Emailed 2 of the maintainers a couple of months ago, still nothing.

**Comment by mvantellingen** [comment]
Should be pulled in by 10505b5fbccce6da9d12d6e4ea73e21949f9e244

**Comment by sasha0** [comment]
I added all requests languages on the Transifex recently. They will be pulled right before upcoming 1.5 release. Feel free to re-open in case of new questions/issues. Thanks!
