### ISSUE TITLE
Connect repository with requires.io

### ISSUE THREAD

**Issue by tobiase** [django-oscar/django-oscar#2200]
[Requires.io](https://requires.io/) monitors project dependencies. Let's monitor Oscar's dependencies with it and include their badge in the README.rst
[Example](https://requires.io/github/tobiase/django-oscar/requirements/?branch=master)

**Comment by mvantellingen** [comment]
This was already done, see https://requires.io/github/django-oscar/django-oscar/requirements/?branch=master

I've added pyup.io as possible replacement
