### ISSUE TITLE
Need to update a sandbox

### ISSUE THREAD

**Issue by alexfromvl** [django-oscar/django-oscar#2207]
In the sandbox using an older version.
This sandbox is an example for setting up shop, and the old code results in errors. 
Update sandbox is necessary for the development of the project.

**Comment by sivictorallen** [comment]
The "Explore the Sandbox" link displays the Django error page (which means DEBUG is enabled in production):
http://latest.oscarcommerce.com/en-gb/

The "Explore the Demo Site" link goes nowhere (there does not appear to be a DNS record for it):
http://demo.oscarcommerce.com/

**Comment by alexfromvl** [comment]
By the study I found a mistake in the dev-version django-oscar (1.4). Somehow, in the Django 1.10 stopped working post requests. For example, this error goes away if you roll back to version 1.9.12.

The error does not load the catalog on the main page (promotion home), or to update the number of items in the basket. 
I think to spend more detailed analysis of the code to move to the Django 1.10

**Comment by mvantellingen** [comment]
Should all be fixed now. Note that demo.oscarcommerce.com is no longer active due to the required work to keep it up to date

**Comment by sasha0** [comment]
As per comment above - should be already fixed. Feel free to re-open in case of new issues. Thanks.
