### ISSUE TITLE
Needed documentation to ovewrite/modificate dashboard forms

### ISSUE THREAD

**Issue by meigallodixital** [django-oscar/django-oscar#2209]
For example to add fields, overwrite them or configure behaviours.

**Comment by okfish** [comment]
It is a relatevely simple task as the Oscar uses [dynamic class loading](https://django-oscar.readthedocs.io/en/latest/topics/class_loading_explained.html#dynamic-class-loading-explained), so you have to [fork](https://django-oscar.readthedocs.io/en/latest/topics/customisation.html#fork-the-oscar-app) appropriate dashboard app, and.. 

>  All you usually need to do is give it the same name and place it in a module with the same name.

Earlier versions of Oscar had contains a Demo site which was a good tutorial for that kind of tasks, try to grep over old releases :)

For example, we have customised Product model and have added several fields. And we want to show it in the form for editing. So, we create the file `apps/dashboard/catalogue/forms.py` which contains something like that:
```
from oscar.apps.dashboard.catalogue import forms as base_forms

class ProductForm(base_forms.ProductForm):

    class Meta(base_forms.ProductForm.Meta):

        fields = [
            'title', 'upc', 'on_sale', 
            'short_description', 'description',
            'out_of_stock', 'bestseller',
            'is_new', 'is_discountable', 'structure',
            'markdown', 'markdown_reason', ]
```
Restart server and... that's all, folks :)
Be sure you have told to Oscar where to find your classes ([via](https://django-oscar.readthedocs.io/en/latest/topics/customisation.html#replace-oscar-s-app-with-your-own-in-installed-apps) `get_core_apps(['apps.dashboard.catalogue'])` in the settings module)

**Comment by SalahAdDin** [comment]
@okfish, yes, is a good idea put all this things in the documentation.

**Comment by sasha0** [comment]
@okfish very nice example. Feel free to create a PR 😉
