### ISSUE TITLE
Dashboard permission

### ISSUE THREAD

**Issue by sammirza3** [django-oscar/django-oscar#2214]
How to change the dashboard permissions according to dashboard users

**Comment by cmwaura** [comment]
is this for the partners?

**Comment by solarissmoke** [comment]
@sammirza3 it's not very clear what you are asking - perhaps you can explain what you are trying to achieve?

**Comment by sammirza3** [comment]
Yes I am asking for partners

**Comment by solarissmoke** [comment]
Closing as it's not clear what you are asking here. You may be able to get help on the mailing list.
