### ISSUE TITLE
Extract oscar.apps.promotions into a separate package

### ISSUE THREAD

**Issue by sephii** [django-oscar/django-oscar#2215]
Providing the flatpages features makes it more difficult to integrate Oscar in a CMS since it causes a duplication of features and forces to enable a potentially useless app for Oscar to work (flatpages), as well as to hack around to hide this feature from the dashboard.

I think it would be better to provide this feature as a separate package.

**Comment by mvantellingen** [comment]
Yup agreed. The combination of for example wagtail and oscar is really nice, see https://github.com/LabD/django-oscar-wagtail

**Comment by mvantellingen** [comment]
BTW, you are talking about the promotions app right?

**Comment by sephii** [comment]
Exactly.

**Comment by sasha0** [comment]
We can extract promotion app into `django-oscar-promotion` package, but might require promotion models refactoring, attempted in PR #1036 and #1567.

**Comment by sasha0** [comment]
If we move promotion app out of the Oscar, what would we use for the home page? Mb redirection to the catalogue index?

**Comment by khink** [comment]
Disclaimer: I have worked on only 2 Oscar sites so far. There might be people out there using this feature, it would be good to hear from them. 

Also, @sephii 's could you update this issue's title? Flatpages appear to be a django.contrib thing but you mean Promotions (oscar.apps.promotions).

That said, we use Wagtail (also via django-oscar-wagtail) in the one project where we have CMS stuff, and i think we would do so again the next time around. In conclusion: to me, the proposal to remove flatpages makes sense.

And +1 on a redirect to the catalogue index.

**Comment by solarissmoke** [comment]
I think we are mixing up issues here. The original issue mentions Oscar's dependency on `django.contrib.flatpages`. We allow editing of flatpages in the dashboard, and these are used in a few [checkout](https://github.com/django-oscar/django-oscar/blob/6ce56ccbc033341a72838b0cb06935d6ba498c75/src/oscar/templates/oscar/partials/nav_checkout.html) [templates ](https://github.com/django-oscar/django-oscar/blob/6ce56ccbc033341a72838b0cb06935d6ba498c75/src/oscar/templates/oscar/checkout/layout.html).

As far as I can see there is no long between `oscar.promotions` and `flatpages`.

That being the case there are two distinct questions here:

1. Do we drop the requirement for `django.contrib.flatpages` and remove flatpage editing from the dashboard? There is

2. Do we drop the promotions app?

Both of these would be breaking changes so it would be good to get a sense of how many projects rely on either feature at present.

**Comment by pwalsh** [comment]
@sephii confirmed he is talking about the promotions app in https://github.com/django-oscar/django-oscar/issues/2215#issuecomment-277552733 so the title of the issue should be edited, as Django's flat pages is used in addition in various places.

I strongly agree on removing promotions (to separate app, or just removing) and setting default home to catalogue index.

**Comment by sasha0** [comment]
Extraction is already in progress and per PR #2623 promotions could be entirely disabled.

An old issue with promotion models customization is still relevant - https://github.com/django-oscar/django-oscar/pull/1567#issuecomment-63972537, since couple of models inherited from non-abstract ones, but probably those will be addressed after extraction completion.

**Comment by sasha0** [comment]
For backwards compatibility, we can enable promotions application by default via `get_core_apps`. Thoughts?

**Comment by sasha0** [comment]
@django-oscar/core promotions are tightly integrated into the Oscar core, so it barely feasible to add backwards compatibility within the extraction. In other words, we can extract promotions in the Oscar 2.0 and make it separate application and let users integrate it if they use this feature. Thoughts?

**Comment by solarissmoke** [comment]
I have no objection to dropping it as long as we publish a standalone app that can easily be added to achieve the same functionality.

**Comment by sasha0** [comment]
>  that can easily be added to achieve the same functionality.

Not quite. Dropping means total removal from the templates, dashboard index stats etc, so that if necessary, users can integrate it manually.

**Comment by solarissmoke** [comment]
I think we do it. The promotions app currently is not very usable, and most folks seem to be using CMSes for this sort of thing.

**Comment by sasha0** [comment]
Promotions extracted within the PR #2623 and will be available within the Oscar 2.0 release.
