### ISSUE TITLE
How to use Shopping cart in django 1.9 project.

### ISSUE THREAD

**Issue by prashante114** [django-oscar/django-oscar#2216]
Hi,

I am new to Oscar. I am trying to develop a e-marketing site with a shopping cart functionality. 
I want to use the Oscar's shopping basket plug-in in my app, but I got confused while adding it.  
Could anyone guide me on how can I add Oscar's shopping basket into my django project/app?

Expecting reply with scratch.

**Comment by mvantellingen** [comment]
Please see https://django-oscar.readthedocs.io/en/releases-1.3/

**Comment by prashante114** [comment]
Hi Michael,

Thanks for your help. I have gone through that link already, but I am not
getting proper way to add the shopping basket.

The fact is, I have created my own project in django-oscar and now I want
to add just shopping basket functionality into my project. But I don't
understand how to take only shopping basket from oscar and integrate it
with my app.

Is there any proper documentation which describes how I can add into my
app? What files needs to be added how to configure the setting files etc.

or could you please help me in this ?
