### ISSUE TITLE
Drop django-extra-views

### ISSUE THREAD

**Issue by mvantellingen** [django-oscar/django-oscar#2225]
The dependency is only used at one place (basket.views), and we can better use https://github.com/gregmuellegger/django-superform there

**Comment by sasha0** [comment]
It's been a while since the ticket logged and we can't switch to `django-superform` since it's compatible with Django <1.10.

Ultimately, I'd prefer another solution - #2972. At the meantime, we'd switch if we find another alternative.

**Comment by solarissmoke** [comment]
Closing this as django-superform isn't maintained, and extra-views works for the time being.
