### ISSUE TITLE
Unused settings feature

### ISSUE THREAD

**Issue by ibrmora** [django-oscar/django-oscar#2229]
For django-debug-toolbar 1.6 DEBUG_TOOLBAR_PATCH_SETTINGS unused.

So plz remove it from sandbox settings.py file

DEBUG_TOOLBAR_PATCH_SETTINGS = False
https://github.com/django-oscar/django-oscar/blob/master/sandbox/settings.py#L326

http://django-debug-toolbar.readthedocs.io/en/stable/changes.html?highlight=DEBUG_TOOLBAR_PATCH_SETTINGS#removed-features

**Comment by solarissmoke** [comment]
Thanks!
