### ISSUE TITLE
Cannot add a varient for a propduct in permission based dashboard of partners

### ISSUE THREAD

**Issue by albinantony2904** [django-oscar/django-oscar#2237]

**Comment by solarissmoke** [comment]
This is explicitly mentioned in the [documentation](http://django-oscar.readthedocs.io/en/releases-1.4/ref/apps/dashboard.html): 

> The permission-based dashboard currently does not support parent or child products. Supporting this requires a modelling change.

There's a ticket open (https://github.com/django-oscar/django-oscar/issues/675) to address improvements to variant handling, so closing this as a duplicate.
