### ISSUE TITLE
Render and RequestContext has been deprecated in django 1.10

### ISSUE THREAD

**Issue by cmwaura** [django-oscar/django-oscar#2242]
After investigating, I found out this two files were the offending culprits

1. templatetags/promotion_tags.py:

        ctx = RequestContext(context['request'], args)
        return template.render(ctx)
2. templatetags/product_tags.py:

       
         template_ = select_template(names)
        # Ensure the passed product is in the context as 'product'
        context['product'] = product
        return template_.render(context)

on the second one, I think its how select_template is used but on the first one is passing a Request Context to render which is no longer supported on the new version of django.

**Comment by solarissmoke** [comment]
Thanks for this - confirmed the issue in `promotion_tags` and that's easy enough to fix.

I'm not seeing any warnings from `product_tags` - please can you clarify what exactly you're seeing and how to reproduce it.

**Comment by cmwaura** [comment]
Hmm that's weird it seems to be working great  now for ` product_tags` but now everything seems to be fine. Thanks.

**Comment by solarissmoke** [comment]
Fixed in  #2243.
