### ISSUE TITLE
Voucher labels are white on white background on vouchers dashboard

### ISSUE THREAD

**Issue by aidan2129** [django-oscar/django-oscar#2249]
bootstrap.mis.css seems to have been removed from the current version causing the label text colour on the voucher section of the dashboard to be white by default.

**Comment by aidan2129** [comment]
I have fixed this on my local version by adding Oscar less styles to my static_dir, Then in the bootstrap3/labels.less i made the label class use the default background color   `background-color:@label-default-bg;`.

**Comment by sasha0** [comment]
PR would be greatly appreciated.
