### ISSUE TITLE
Unclear dependency between dashboard and frontend templates

### ISSUE THREAD

**Issue by pwalsh** [django-oscar/django-oscar#2250]
The so called ["cheeky setting" here](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/__init__.py#L23) enforces an explicit dependency between dashboard and frontend templates in Oscar sites. 

The value is dubious, ("(t)his allows Oscar's templates to be extended by templates with the same filename"), and the impact ~ hidden from users who customise their frontend templates (some important markup not in blocks, etc.).

As a user, I'm not sure what the real problem is:

1. The cheeky setting itself (what is the value of this overloading, and what problem does it solve that Django's template resolution order does not solve?).
2. The fact that at the bottom of the template stack, there is a common dependency between the dashboard and the frontend, and not all the markup can be excluded via blocks.

Is there a design pattern I am missing here?

**Comment by pwalsh** [comment]
@sasha0 @solarissmoke and anyone:

I propose:

1. remove or discourage use of this setting (i.e.: Oscar templates should be available namespaces by `oscar/`, and not pollute `/`).
2. If the above is not possible/desirable, make a break where the Oscar frontend templates do not depend on the same base template as the Oscar dashboard templates. Example: [this](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/dashboard/base.html#L1) should extend `oscar/base` and not `base`.

**Comment by solarissmoke** [comment]
I can't see what value that setting provides. It might have been because you cannot fully control the order of apps in `INSTALLED_APPS` because of Oscar's `get_core_apps` stuff - but that is tenuous too.

I would like to see both your suggestions implemented - i.e., completely separate dashboard and frontend base templates, and also namespace all of Oscar's templates and remove this setting. This will likely be a breaking change.

**Comment by solarissmoke** [comment]
Looking a bit more closely, the setting is simply a device to let us store all the templates in one directory (ass opposed to per-app directories). I don't think it does any more than that (in terms of enforcing any dependency between frontend/dashboard templates). Either way I think your suggested changes are a good idea.

**Comment by sasha0** [comment]
Interrelated with #1378

**Comment by solarissmoke** [comment]
The "cheeky setting" has been removed in #3000, which I think should address the issue that was raised here.
