### ISSUE TITLE
Dashboard navigation menu empty for staff and superuser

### ISSUE THREAD

**Issue by Wingie** [django-oscar/django-oscar#2259]
I just installed django-oscar on my Django 1.9 application
i have an existing application i.e. user model etc and everything
i have managed to get it working but only one issue is the dashboard admin navigation menu is empty.
the user i am logged in as is an admin and superuser and staff etc.

anything else i am missing?
from shell i can see that settings.OSCAR_DASHBOARD_NAVIGATION is filled with some values i.e. it is not empty?

**Comment by Wingie** [comment]
I found the issue for anybody who comes later,

in `dashboard.nav.default_access_fn`
```
url = reverse(url_name, args=url_args, kwargs=url_kwargs)
view_module = resolve(url).func.__module__
```
basically my application is mounted on a "prefix path" which is "/api/"
so url starts with "api/...." which is correctly return by 'reverse'
but the resolve function does not resolve the path correctly with /api/ in it 
a quick `.replace('api/','')` fixes the issue and the paths are appearing again.

i've had to subclass dashboard.menu and dashboard.nav in order to add that fix in my application. 
is there a cleaner fix for this issue?

**Comment by artforlife** [comment]
What did you mean by "empty?" I was doing some customizing work on Oscar's front-facing styles. In particular, I was messing with the styling of the shopping cart. As a result, all of the links in the admin menu are now rendered as "#" for me, that is, nothing in the Dashboard works. 

However, when I navigate directly to a path, it opens successfully.

**Comment by solarissmoke** [comment]
Closing as it seems like you've resolved the issue.
