### ISSUE TITLE
offers cause unorderable types: NoneType() > int() error

### ISSUE THREAD

**Issue by albinantony2904** [django-oscar/django-oscar#2273]
when I tried to create a new offer benefit with value 'None' and any choice that involves 'fixed/percentage discounts' it throws an error `unorderable types: NoneType() > int()` in oscar 1.4.

Below is my effort to create an offer 
![oscar](https://cloud.githubusercontent.com/assets/18322595/24358786/e7b468c6-131f-11e7-82ea-2fab2e65aa03.png)

This is the error encountered 
![oscar 2](https://cloud.githubusercontent.com/assets/18322595/24358882/342036a4-1320-11e7-9f27-41fc96197a51.png)

In 'oscar/apps/offer/abstract_models.py' the following method should be changed

` 

def clean_percentage(self):

        if not self.range:

            raise exceptions.ValidationError(

                _("Percentage benefits require a product range"))

        if self.value > 100:

            raise exceptions.ValidationError(

                _("Percentage discount cannot be greater than 100"))

`

Change recommended

`def clean_percentage(self):

        if not self.value:

            raise exceptions.ValidationError(

                _("A discount value is required"))

        if not self.range:

            raise exceptions.ValidationError(

                _("Percentage benefits require a product range"))

        if self.value > 100:

            raise exceptions.ValidationError(

                _("Percentage discount cannot be greater than 100"))`

**Comment by SalahAdDin** [comment]
Make a PR please.

**Comment by sasha0** [comment]
Already fixed in the master branch. Re-open if you can still re-create it. Thanks!
