### ISSUE TITLE
Country model field

### ISSUE THREAD

**Issue by ibrmora** [django-oscar/django-oscar#2277]
In url (address-create) or (address-detail).
If you input phone number but choose empty_label for country 
you will get 'NoneType' object has no attribute 'iso_3166_1_a2'
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/views/generic.py#L188
return country.iso_3166_1_a2

1- So you need to adjust the UserAddressForm
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/address/forms.py#L23
to make it like ShippingAddressForm
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/checkout/forms.py#L15

or
2- adjust  get_region_code function
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/views/generic.py#L188

I think the first solution much better!

**Comment by solarissmoke** [comment]
`country` is a required field on the `UserAddress` model - so it shouldn't be possible to submit it empty - that should raise a validation error. Have you overridden the model? If so, I think you're probably better off setting a default country or overriding the form handling logic as well.

**Comment by ibrmora** [comment]
Sorry for the delay in reply.
To produce the bug
1- add OSCAR_REQUIRED_ADDRESS_FIELDS = ('phone_number', 'country') to settings.py.
2- In page (accounts/addresses/add/) Do not choose a country & enter phone number.
3- click on save button.

the output :
AttributeError at /ar/accounts/addresses/add/
'NoneType' object has no attribute 'iso_3166_1_a2'

I think the bug happened because it starts to check the phone number before return the error flash message.

**Comment by solarissmoke** [comment]
Thanks - I can reproduce that error now.
