### ISSUE TITLE
payment view not configure for django-oscar-payu

### ISSUE THREAD

**Issue by pradeeptomer4u** [django-oscar/django-oscar#2278]
Hi,

I m new for oscar project .I have already installed and configure the payu according to documentation but shows
![screenshot from 2017-03-30 16-11-13](https://cloud.githubusercontent.com/assets/16862612/24500561/8a9292bc-1563-11e7-9393-3e24672678cb.png)
but i want to configure only payu payment method only

**Comment by SalahAdDin** [comment]
You have to implement all workflow for works, which package for payU are using you?

**Comment by pradeeptomer4u** [comment]
i have already install and configure django-oscar-payu but i m begineer in django-oscar i have no idea to configure payment detail and preview page in oscar

**Comment by SalahAdDin** [comment]
Follow tutorial documentation, first with `django-oscar `and after with `djjango-oscar-payu`.

**Comment by sasha0** [comment]
Please use [mailing list](https://groups.google.com/forum/#!forum/django-oscar) for support questions. Thanks.
