### ISSUE TITLE
ProductImage display_order is broken if images are simultaneously added and deleted from the dashboard

### ISSUE THREAD

**Issue by alainpoirier** [django-oscar/django-oscar#2289]
Using django oscar 1.1.1, I get the following error:
```
duplicate key value violates unique constraint "catalogue_productimage_product_id_1ade50c7ba4a8344_uniq"
DETAIL:  Key (product_id, display_order)=(4746, 2) already exists.
```

This happens when I try to upload an image to a product, on which I have previously deleted and uploaded an image at the same time (successfully).

**Comment by solarissmoke** [comment]
I think the approach in #2287 of dropping the `unique_together` constraint will be the best way to fix this.
