### ISSUE TITLE
possible dependancy error

### ISSUE THREAD

**Issue by adnmcq** [django-oscar/django-oscar#2291]
I was following the instructions on your readthedocs.io to install a new site

I used pip install Django-Oscar

looks like this is my version
django-oscar==1.4

when I ran python migrate.py

I get:

`  File "C:\Users\mamwo\Desktop\frobshop\venv\lib\site-packages\oscar\apps\basket\abstract_models.py", line 18, in <module>
    from oscar.templatetags.currency_filters import currency
ImportError: No module named templatetags.currency_filters`

when I look at venv/Lib/site-packages/Oscar/   I have no templatetags module

But if I look at GitHub it is there

this templatetags import is in a lot of places in the code but the template tags folder is nowhere to be found

**Comment by solarissmoke** [comment]
I can't reproduce this - did a clean install of Oscar from pypi and the templatetags module you're referring to is there. There would be a lot of people complaining if this was broken, so the most likely explanation is that your venv is corrupted...

Have you tried reinstalling the package/rebuilding the venv?

**Comment by adnmcq** [comment]
I just cloned in a different place and then moved those folders in.  Might try again on a diff comp or diff env. Sorry for false issue

**Comment by solarissmoke** [comment]
OK - feel free to reopen if you can reproduce the issue again.
