### ISSUE TITLE
Invoice generation

### ISSUE THREAD

**Issue by sasha0** [django-oscar/django-oscar#2314]
Original idea was suggested by @jowenn during Oscar sprint on the DjangoCon Europe 2017.

Initially, we can generate simple HTML invoice and integrate into checkout flow.

Feedback and basic invoice template is very welcomed.

- [x] Implement LegalEntity model, which would be configured on per-site basis.
- [x] Implement Invoice model.
- [x] Implement invoice template based on the guideline (https://github.com/wbond/vat_moss-python/blob/master/overview.md#invoices).
- [x] Allow to automatically generate invoice for the order after the checkout (could be on/off by the setting) or manually in the dashboard or admin.

**Comment by okfish** [comment]
I've made separated app for oscar, named [django-oscar-ficta](https://github.com/okfish/django-oscar-ficta) It allows to manage juristic persons and generate invoices as well as has checkout integration. But it slightly depends on local russian flavors and have to be revisioned and reworked for international use.

**Comment by sasha0** [comment]
I aim to introduce base implementation, which would follow common Oscar approach and be customizable and extensible, which could be expanded by external apps as well.

TBD:

- on behalf of whom we shall issue an invoice;
- what legal text should contain invoice template;
- at what point of checkout flow we shall send an invoice.

**Comment by sasha0** [comment]
@tobiase kindly suggested nice guideline for the invoices - https://github.com/wbond/vat_moss-python/blob/master/overview.md#invoices

**Comment by sasha0** [comment]
As for the legal entity, who'd be issuing invoice - that could defined in the settings or in the dashboard.

**Comment by okfish** [comment]
I've made a binding between Partner and legal entity, so issuer depends on basket's stockrecords. This works simply for the only partner and a bit complicated if more than one, as requires to split order into some invoices for each partner.

**Comment by SalahAdDin** [comment]
@sasha0 What's about this?

**Comment by sasha0** [comment]
After thinking about this for a while and based on feedback and experience I've came up with the next approach:
- Implement `LegalEntity` model, which would be configured on per-site basis.
- Implement invoice template based on the guideline (https://github.com/wbond/vat_moss-python/blob/master/overview.md#invoices).
- Allow to automatically generate invoice after the checkout (could be on/off by the setting) or manually in the dashboard or admin.

**Comment by tobiase** [comment]
I think, you also need an Invoice model, that stores all necessary data.
This way you're able to create invoices for deleted users or a deleted product.

**Comment by sasha0** [comment]
The question is whether to send pre-payment invoice after order placement or rather post-payment receipt. Any ideas?

**Comment by solarissmoke** [comment]
I think this depends entirely on the project workflow and am not convinced it is something that Oscar core needs to handle. Perhaps one approach is to provide the utilities for generating an invoice, but letting the project decide when to use them.

**Comment by sasha0** [comment]
Despite receipts often called invoices too, both documents are significantly different:
* invoice is list of products within the legal information about merchant, which is requesting payment from the client;
* receipt is confirmation, that products or services has been paid.

Since typically ecommerce projects have instant payment (credit card, PayPal etc) it does make sense to issue and send receipt by default and allow developer to implement invoice generation for the project purposes (payment method via wire transfer, custom accounting functionality etc).

**Comment by tobiase** [comment]
I'm not sure, if receipts are accepted by the tax office in Germany.
As far as I know, they require you to provide an invoice, even if the invoicing party already received the money. 

I send customers a mail, after the order is placed, with the transaction details and attach an invoice.
Because I chose to provide invoices for customers, I store all the invoice data denormalized.

Maybe you are right and receipt is enough for most cases, but I think it won't be enough for doing business in the european union. (Maybe I'm wrong)

**Comment by sasha0** [comment]
We have finally released it as a separate package - https://github.com/django-oscar/django-oscar-invoices or https://pypi.org/project/django-oscar-invoices/.

**Comment by SalahAdDin** [comment]
Thank you, i think you put it in the documentation. Great work.
