### ISSUE TITLE
CatalogueImportError will never being raised during catalogue import

### ISSUE THREAD

**Issue by okfish** [django-oscar/django-oscar#2319]
So, this code https://github.com/django-oscar/django-oscar/blob/master/src/oscar/management/commands/oscar_import_catalogue.py#L41 will never executed, because `CatalogueImportError` exception class didn't even imported in the `partner.importer` module. Instead of this, `ImportingError` used, but there are no places where it can be caught. 

It would be great to get explanations on this exceptions and how to use it properly.

**Comment by solarissmoke** [comment]
I think it's a mistake - it should be catching `ImportingError` there. That importer code really isn't very robust and is intended mainly for setting up the sandbox site.

**Comment by okfish** [comment]
I caught it while customising importer for remote updating when have used original as base class. And was a bit confused :)

**Comment by sasha0** [comment]
PR is very welcomed.
