### ISSUE TITLE
TinyMCE and required fields error

### ISSUE THREAD

**Issue by mightym** [django-oscar/django-oscar#2328]
There is currently a bug (I assume) in TinyMCE. 
I'm having the issue in django-oscar's dashboard. I have an additional required text field on AbstractProduct. The textarea used for it is hidden by TinyMCE and has the HTML5 attribute`required`. This causes an error in Chrome and Safari ```An invalid form control with name='textarea-name' is not focusable.```. 
I tested the latest version of TinyMCE, but same error. Even in latest FF and Opera on OSX.
I left an issue on tinymce too https://github.com/tinymce/tinymce/issues/2584#issuecomment-297503423

**Comment by mightym** [comment]
<img width="476" alt="bildschirmfoto 2017-04-26 um 21 46 13" src="https://cloud.githubusercontent.com/assets/11863/25453595/d422809c-2ac9-11e7-834e-20f9010b6868.png">

**Comment by mightym** [comment]
To reproduce: 
- Add a `models.TextField` to `AbstractProduct` and make it required. 
- modify 'oscar.apps.dashboard.catalogue.forms.ProductForm' and add the new field to Meta 
- Create a new Product in the Dasboard

**Comment by solarissmoke** [comment]
Slightly worrying that a basic bug like this hasn't been fixed in TinyMCE since 2015. Were you able to test the workarounds that people have suggested in the issue you link to?

**Comment by mightym** [comment]
Well its a bit tricky. I'm even not sure if I should call it a bug, or a bug of tinymce. It seems like this issue slowly popped up since browsers interpret the "required" HTML5 attribute. With older browsers this is not an issue. I tested old versions of chrome and safari and everythings fine there.
For Safari they actually first implemented the required attribute in the latest release March 27. 
https://bugs.webkit.org/show_bug.cgi?id=28649
That explains why many people complain about this bug since they updated to latest MacOS Sierra.

None of the workarounds solved the issue in my case. I will keep an eye on this and see if I can maybe fix this with JS.

**Comment by specialunderwear** [comment]
fixed since at least https://github.com/django-oscar/django-oscar/pull/3979
