### ISSUE TITLE
ShippingAddressView times out in Django 1.11

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2335]
The `ShippingAddressView` times out when using Django 1.11. 

To reproduce, build the sandbox and try checking out. 

The issue appears to be in the rendering of the country select in the new address form - the rendering of that widget hangs. My best guess is that it has something to do with the switch to template-based widget rendering in Django 1.11.

**Comment by solarissmoke** [comment]
If you reduce the number of countries with `is_shipping_country=True` to a small number, then it works. If you use the full list of countries then this rendering slows to a complete crawl.

**Comment by mvantellingen** [comment]
This is related to https://github.com/jazzband/django-debug-toolbar/issues/910 (just tested it by disabling the template panel).

**Comment by matthiask** [comment]
I just merged kezabelle's pull request for django-debug-toolbar, if you could test whether it fixes this problem for you that would be awesome!

**Comment by solarissmoke** [comment]
@matthiask thanks! Just tested, and it fixes this issue. 

Just FYI, I'm not able to view the template panel (allocation size overflow after the AJAX request). I assume that is a memory issue on my client.
