### ISSUE TITLE
Field error when adding product to range

### ISSUE THREAD

**Issue by Sharptsa** [django-oscar/django-oscar#2357]
Hi,

When I try to add products to one of my ranges using SKUs (with input form or with a file), I get the following error :

> FieldError at /dashboard/ranges/5/products/
Cannot resolve keyword 'stockrecords' into field. Choices are: attribute_values, attributes, basket_lines, categories, children, date_created, date_updated, description, excludes, handpickedproductlist, id, image, images, includes, is_active, is_discountable, line, name, orderedproduct, parent, parent_id, price, primary_recommendations, product, product_class, product_class_id, product_options, productalert, productcategory, productinformation, productrecommendation, rangeproduct, rating, recommended_products, reference, reviews, singleproduct, slug, stats, structure, subcategory, title, upc, userproductview, weight, wishlists_lines

The error seems to come from "oscar\apps\dashboard\ranges\forms.py", line 51.
`        existing_skus = set(products.values_list(
            'stockrecords__partner_sku', flat=True))`

I'm using oscar version 1.3.0

**Comment by solarissmoke** [comment]
I can't reproduce this issue in core - `stockrecords` is a valid reverse relationship to the `StockRecord` model. 

Have you forked the `partner` app and modified the `StockRecord` model and changed the definition of the `product` field on that model? That is the only way that this could occur. This seems likely given that you have modified the `Product` model (there are non-core fields like `is_active`, `subcategory`, `weight` in the list above).

**Comment by Sharptsa** [comment]
Nevermind... 
I picked up this project from another developer, still new to oscar, and I forgot to fork the models.py file when creating my pricing strategy.
Sorry for that dumb issue report. And thanks @solarissmoke , you helped me to point where the actual problem was coming from. 👍
