### ISSUE TITLE
how to give the permission for product variants option for partner Limited dashboard access( partner)

### ISSUE THREAD

**Issue by prabhatpankaj** [django-oscar/django-oscar#2368]
![image](https://cloud.githubusercontent.com/assets/20439273/26293003/2fe1dd20-3ed8-11e7-822b-8218ce49ce3a.png)

I want to add product variants option for partner Limited dashboard access( partner)

![image](https://cloud.githubusercontent.com/assets/20439273/26293029/5b250e9e-3ed8-11e7-845b-172f0965ae2e.png)

by default it is not available for Limited dashboard access user .

please guide me the best way to do this

**Comment by solarissmoke** [comment]
Please use the mailing list for help with customising your Oscar store.
