### ISSUE TITLE
When I search word with number, return a lot of irrelevant results 

### ISSUE THREAD

**Issue by jariberi** [django-oscar/django-oscar#2372]
Hi! For example I search `foo 1`.
In the search_indexes.py, in the ProductIndex clas, the text field is CharField.
Why is this?
Thanks!

**Comment by solarissmoke** [comment]
>  in the ProductIndex class, the text field is CharField.

What would you want it to be instead?

**Comment by solarissmoke** [comment]
Closing due to lack of feedback - please feel free to reopen if you can clarify the issue.
