### ISSUE TITLE
error with install sandbox python.2.7

### ISSUE THREAD

**Issue by officerebel** [django-oscar/django-oscar#2394]
When install sandbox I get error?

 "__Py_ZeroStruct", referenced from:
          _init_uwsgi_embedded_module in python_plugin.o
          _uwsgi_request_subhandler_wsgi in wsgi_subhandler.o
          _uwsgi_request_subhandler_web3 in web3_subhandler.o
          _py_uwsgi_is_connected in uwsgi_pymodule.o
          _py_uwsgi_is_locked in uwsgi_pymodule.o
          _py_uwsgi_mule_get_msg in uwsgi_pymodule.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    *** error linking uWSGI ***
    
    ----------------------------------------
Command "/Users/timvogt/virtualenvs/oscar/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Qw1XkI/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7sgJti-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/timvogt/virtualenvs/oscar/bin/../include/site/python2.7/uWSGI" failed with error code 1 in /private/tmp/pip-build-Qw1XkI/uWSGI/
make: *** [install] Error 1

**Comment by solarissmoke** [comment]
See https://github.com/mirumee/saleor/issues/897 and https://github.com/unbit/uwsgi/issues/600 - I think this is an issue with uwsgi on OSX.

**Comment by officerebel** [comment]
Tried the solutions but still error to install sandbox.

Command "/Users/timvogt/virtualenvs/oscar/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/r7/mzwmw_kn2px58v7clw0vxy700000gn/T/pip-build-hbKj6f/uwsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/r7/mzwmw_kn2px58v7clw0vxy700000gn/T/pip-ZBP5dN-record/install-record.txt --single-version-externally-managed --compile --install-headers 

/Users/timvogt/virtualenvs/oscar/bin/../include/site/python2.7/uwsgi" failed with error code 1 in /private/var/folders/r7/mzwmw_kn2px58v7clw0vxy700000gn/T/pip-build-hbKj6f/uwsgi/

**Comment by officerebel** [comment]
Any help?

**Comment by sasha0** [comment]
As noted @solarissmoke, this setup issue related with the uwsgi package, not Oscar.

For the support issues you can use mailing list or Slack. Thanks.
