### ISSUE TITLE
oscar's layout.html should call super for the styles block

### ISSUE THREAD

**Issue by bxm156** [django-oscar/django-oscar#2402]
There are probably more cases of this, but the "styles" block in layout.html should call ```{{ block.super }}``` at the beginning, to allow user's to override the base.html file and add their own own styles. Instead of having to override the layout.html file and copy/paste the existing entries in it.

**Comment by craigloftus** [comment]
@bxm156 [As of Django 1.9](https://docs.djangoproject.com/en/1.11/releases/1.9/#templates) you can use recursive template extending, e.g., override `layout.html` with:
```
{% extends "layout.html" %}

{% block styles %}
{{ block.super }}
<!-- My stuff -->
{% endblock %}
```

If it still irks you then PRs are always welcome.
