### ISSUE TITLE
django-oscar multi-vendor feature to build a marketplace

### ISSUE THREAD

**Issue by codingmehelp** [django-oscar/django-oscar#2403]
Hi, Does oscar provide any functionality/add-on to build multivendor website like amazon, etc? Please let me know how to build this on a project. thanks Uma

**Comment by solarissmoke** [comment]
Hi @codingmehelp - the issue tracker is for filing issues with the code base, not for asking for help. Please use the mailing list (https://groups.google.com/forum/?fromgroups#!forum/django-oscar) for help. Thanks,
