### ISSUE TITLE
The 'send_confirmation_email' in sandbox gateway app, render must be a dict not context issue with Django 1.11

### ISSUE THREAD

**Issue by gogobook** [django-oscar/django-oscar#2408]
![sandbox_error](https://user-images.githubusercontent.com/9208031/27769585-8dc4601e-5f5f-11e7-8ae1-a1d85c19f709.png)

There is the same error in other project. [Django 1.11 Must be a dict not context issue.](https://github.com/zokis/django-materialize-forms/issues/3)

**Comment by solarissmoke** [comment]
Thanks!
