### ISSUE TITLE
'Settings' object has no attribute 'TEMPLATE_DEBUG'

### ISSUE THREAD

**Issue by neermuzic** [django-oscar/django-oscar#2420]
'Settings' object has no attribute 'TEMPLATE_DEBUG'
![screen shot 2017-07-18 at 10 34 39 am](https://user-images.githubusercontent.com/30252716/28301513-bb045272-6ba4-11e7-8b27-2c4cfc90700b.png)

1 | {% load i18n %}
-- | --
{% load thumbnail %}
 
<div id="{{ image_id }}" class="image-input">
{% if image_url %}
{% thumbnail image_url "200x200" upscale=False as thumb %}
<img src="{{ thumb.url }}" alt="{% trans "thumbnail" %}" />
{% endthumbnail %}
{% else %}
<img alt="{% trans "thumbnail" %}"
onload="$('#upload_button_{{ image_id }}').hide()"
onerror="$('#upload_button_{{ image_id }}').show(); alert('{% trans 'Unrecognized image type!' %}')" />
<button class="btn btn-primary" id="upload_button_{{ image_id }}">{% trans "Upload Image" %}</button>
{% endif %}
<div class="input-field">
<input {{ input_attrs\|safe }} accept="image/*" />

**Comment by solarissmoke** [comment]
This is an issue with sorl-thumbnail - not much we can do about it until they cut a new release. See https://github.com/jazzband/sorl-thumbnail/issues/476 .

Until then the easiest fix is just to add the `TEMPLATE_DEBUG` setting to your settings file.
