### ISSUE TITLE
Templates Are Not Being Overriden 

### ISSUE THREAD

**Issue by artforlife** [django-oscar/django-oscar#2427]
I am trying to embed the Django-Oscar system into a custom HTML template. When I do that, I create a directory `templates/oscar` inside my project's root and place the new template's `base.html` there. However, I am still seeing the Oscar's original template and styles displayed in the browser.

On the other hand, if I place the very same `base.html` directly into the root of the `templates` directory, it is shown, but is missing the static files.

If it helps, here are some settings:

```
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.sites',
    
    'compressor',
    'widget_tweaks',
] + get_core_apps()

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

#This should be commented out in Development
STATICFILES_DIRS = [
  os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
```

What can I do to fix this? Does Oscar treat templates in some special way? Is this a Django bug? I am using Django 1.11.

**Comment by solarissmoke** [comment]
> On the other hand, if I place the very same base.html directly into the root of the templates directory, it is shown,

That is the right place to put it. `base.html` is not within the Oscar namespace.

> but is missing the static files.

Not sure if this is the problem, but your configuration of [`STATICFILES_DIRS`](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-STATICFILES_DIRS) is wrong - it is invalid to include the same path as `STATIC_ROOT` in that list. The former is used to provide additional locations that Django should look for static files. The latter is where Django should write the files when you run `collectstatic`.

**Comment by artforlife** [comment]
I was able to resolve this. The following code has worked.

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            
            #re-route the search for templates into this custom template directory
            os.path.join(os.path.join(BASE_DIR, 'templates'), 'tshirt-theme'),
            
            #Uncomment the line below to restore the original Oscar template
            #OSCAR_MAIN_TEMPLATE_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
                
                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.promotions.context_processors.promotions',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.apps.customer.notifications.context_processors.notifications',
                'oscar.core.context_processors.metadata',
            ],
        },
    },
]

COMPRESS_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = '/static/'

#STATIC_ROOT = os.path.join(BASE_DIR, "static")

#This should be commented out in Development
STATICFILES_DIRS = [
  os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

```

**Comment by solarissmoke** [comment]
Closing as it seems to be a local configuration issue.
