### ISSUE TITLE
Caching Error When Creating and Saving New Product

### ISSUE THREAD

**Issue by artforlife** [django-oscar/django-oscar#2428]
I have discovered some weird behavior when I try to create a product in my local developement environment. Namely, if some of the fields on the `Stock and Pricing` tab are left unfilled and the Save button is pressed, the systems attempts to save the item but them bounces one to a 404 Page which says (using Django debug info) that `media/cache/long_image_name_here.jpg` is not found. 
When one diligently fills out all of the fields, the item is created successfully. 

> Page not found (404)

> Request Method: | GET
> -- | --
> http://localhost:8000/media/cache/99/2a/992ab059225fc7d7f9f81064e64e021d.jpg
> django.views.static.serve
> "/Users/selfishman/www/sites/Playground/Django-tut/django-oscar/kindbook/media/cache/99/2a/992ab059225fc7d7f9f81064e64e021d.jpg" does not exist
> 
> You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

I believe this is simply an issue with reporting validation to the user properly and preventing the saving before all the needed fields are populated.

My dependencies on this fully stock project.

```
Babel==2.4.0
Django==1.10.7
django-appconf==1.0.2
django-compressor==2.1.1
django-extra-views==0.6.4
django-haystack==2.5.1
django-oscar==1.4
django-tables2==1.7.1
django-treebeard==4.1.1
django-widget-tweaks==1.4.1
factory-boy==2.8.1
Faker==0.7.13
mock==2.0.0
olefile==0.44
pbr==3.0.1
phonenumbers==8.5.0
Pillow==4.1.1
purl==1.3.1
pycountry==17.5.14
python-dateutil==2.6.0
pytz==2017.2
rcssmin==1.0.6
rjsmin==1.0.12
six==1.10.0
sorl-thumbnail==12.4a1
Unidecode==0.4.20
```

**Comment by solarissmoke** [comment]
It looks like you haven't configured your media URLs correctly for development - see the [relevant section of the Django documentation](https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-files-uploaded-by-a-user-during-development).

You can also refer to the Oscar [sandbox setup ](https://github.com/django-oscar/django-oscar-demo/blob/master/src/oscar_demo/urls.py#L38-L44).

**Comment by solarissmoke** [comment]
Closing doe to no feedback from OP. Feel free to reopen if there is an issue in the core (rather than a project-level configuration issue).
