### ISSUE TITLE
All Dashboard Navigation Links are Rendered as "#"

### ISSUE THREAD

**Issue by artforlife** [django-oscar/django-oscar#2433]
I was doing some customizing work on Oscar's front-facing styles. In particular, I was messing with the styling of the shopping cart. As a result, all of the links in the Admin menu are now rendered as "#" for me, that is, nothing in the Dashboard works.

However, when I navigate directly to a path, it opens successfully. This seems a bit bizzare since I definitely have not changed any code since the last time it worked. 

Does anyone have any idea what may have caused this and how one could fix it?

**Comment by artforlife** [comment]
I was able to fix this by re-arranging the order in which the vendor JS files are listed within the template. After placing JQuery as the first script that is listed in the HEAD section, I noticed this problem disappear. 
The issue can be closed now. Perhaps it will be of help to others.

**Comment by solarissmoke** [comment]
In future, please use the [https://groups.google.com/forum/?fromgroups#!forum/django-oscar](mailing list) (rather than this issue tracker) for help with debugging your projects. Thanks!
