### ISSUE TITLE
Documentation [Error]

### ISSUE THREAD

**Issue by mykljohn** [django-oscar/django-oscar#2439]
Hi, just to let you know, there's an error in the Docs.

Note: In django 1.10 and above: make sure to replace MIDDLEWARE with MIDDLEWARE_CLASSES

Should be:

Note: In django 1.10 and above: make sure to replace **MIDDLEWARE_CLASSES** with **MIDDLEWARE**

**Comment by solarissmoke** [comment]
Thanks!
