### ISSUE TITLE
Incorrect context generation in `get_annotated_list` template tag

### ISSUE THREAD

**Issue by iuliuscaesar92** [django-oscar/django-oscar#2446]
Need to perform dict update instead of assigning to info dictionary here:

https://github.com/django-oscar/django-oscar/blob/bbb31690bd6c0ff384d52de5be673bf86e2da3a1/src/oscar/templatetags/category_tags.py#L46

**Comment by iuliuscaesar92** [comment]
Also need to append the copy of the dict into tuple instead of reference on the row below:
`annotated_categories.append((node, info.copy(),))`

**Comment by iuliuscaesar92** [comment]
Also this line:
`        if prev_depth is not None and node_depth < prev_depth:
            info['num_to_close'] = list(range(0, prev_depth - node_depth)) `
should be below the info.update(...) that i've mentioned before

**Comment by solarissmoke** [comment]
I've looked at this code, and don't see a problem. We are using exactly the same logic as django-treebeard (https://github.com/django-treebeard/django-treebeard/blob/master/treebeard/models.py#L570), and it seems to work correctly.

> Also need to append the copy of the dict into tuple instead

No - this is not how the method works. The code you are referring to is explicitly modifying the *previous* info object based on new information. Notice that just below that, a new `info` object is assigned, which is what then gets saved to the next row in the list.

Can you provide an example/failing test case that illustrates the problem?

**Comment by iuliuscaesar92** [comment]
@solarissmoke thank you for your patience, it was my misunderstanding of the way this code works, now I clearly see that. I will close this topic. There is no test case for that situation.
