### ISSUE TITLE
Digital product on demo site

### ISSUE THREAD

**Issue by julienfabre** [django-oscar/django-oscar#2456]
It is stated in the demo site work-in-progress ticket (https://github.com/django-oscar/django-oscar/pull/557) that it now includes digital products (in this case PDF downloads), however I can't seem to find them.
Is there any ressources (documentation, examples...) on how to set up digital products with Oscar?

**Comment by craigloftus** [comment]
This isn't an out-of-the-box feature of Oscar, but it is something that the framework provides all the hooks to achieve.

You would define product types (instances of `catalogue.ProductClass`) that do not requiring shipping or stock tracking.

Then you need to [customise your order processing](https://django-oscar.readthedocs.io/en/latest/howto/how_to_set_up_order_processing.html) to automatically ship (e.g., email a download link) for those product types.

**Comment by julienfabre** [comment]
Thank you for your insights.

It is specified in [the docs](https://django-oscar.readthedocs.io/en/latest/howto/how_to_set_up_order_processing.html#structure) that a `cronjob or celery task` should be used to process the order for digital products.

How would a cronjob be relevant in that case?

**Comment by craigloftus** [comment]
> It is specified in the docs that a cronjob or celery task should be used to process the order for
> digital products.

The use of a cronjob is really just a suggestion about a way to design the process to be resilient to delivery failures.

**Comment by solarissmoke** [comment]
Closing as this isn't a code issue. Feel free to carry on the conversation on slack or the mailing list.
