### ISSUE TITLE
CSRF verification failed. Request aborted. for  DEBUG = False

### ISSUE THREAD

**Issue by prabhatpankaj** [django-oscar/django-oscar#2459]
I am getting CSRF error while login or registration for DEBUG=False .

Forbidden (403)
CSRF verification failed. Request aborted.
More information is available with DEBUG=True.

I am using Django==1.11.5

someone please provide me the solution for this

**Comment by solarissmoke** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/django-oscar) or slack for support requests. You will probably also need to provide a bit more information to get some help... maybe start by checking that you have cookies enabled.
