### ISSUE TITLE
Vouchers - negative total

### ISSUE THREAD

**Issue by pisapapiros** [django-oscar/django-oscar#2463]
Hi Oscar colleagues,

I've started to use vouchers, it's a really nice feature, but there's something that doesn't get along with my project.

After applying a fixed discount bigger than the order price, the order.total_excl_tax is negative. I think it comes from the basket line model, calculating line_price_excl_tax_incl_discounts(). Is it intended to work like that? Does it only happen to me? It doesn't look good, I'd rather put a 0.00 there. 

Coupon:
![1-coupon](https://user-images.githubusercontent.com/3200229/30848473-83e768ce-a29f-11e7-8c54-4bc63e1b9cc3.png)
Basket pre-coupon
![2-basket-pre](https://user-images.githubusercontent.com/3200229/30848471-83cf57e8-a29f-11e7-8f72-df3db34c4f99.png)
Basket post-coupon
![3-basket-post](https://user-images.githubusercontent.com/3200229/30848472-83d02024-a29f-11e7-9b69-6495fcacfa4a.png)
Checkout preview
![4-checkout-preview](https://user-images.githubusercontent.com/3200229/30848470-83afc52c-a29f-11e7-84ca-8df898ba5aff.png)
Order details:
![5-order-details](https://user-images.githubusercontent.com/3200229/30848469-83acd4e8-a29f-11e7-8f8f-4e70e4cdb0dd.png)

**Comment by solarissmoke** [comment]
Related/possible duplicate: #1683

**Comment by benz3k3** [comment]
Hi @pisapapiros,

Looks OK to me. Cart total (inc. discounts) = Cart total (excl. discounts) - Discount. Cart total (inc. discounts) = 30 - 45 = -15.

**Comment by sasha0** [comment]
Right, it calculates absolute value, which becomes negative when you try to apply discount greater than order total. The most reliable approach would be to alter the logic locally - mb to limit maximum applied discount amount or do not allow order total to be negative.

**Comment by sasha0** [comment]
Closing, since this behavior is intended and can be customized locally in your project.
