### ISSUE TITLE
Individual product class template partials - mismatch in docs

### ISSUE THREAD

**Issue by qubitstream** [django-oscar/django-oscar#2469]
Unless I'm missing something, there seems to be an error in the doc:

[The documentation on product partials](http://django-oscar.readthedocs.io/en/releases-1.5/howto/how_to_customise_templates.html#overriding-individual-products-partials) says:
*Apart from overriding catalogue/partials/product.html to change the looks for all products, you can also override it for individual products by placing templates in **catalogue/detail-for-upc-%s.html** or **catalogue/detail-for-class-%s.html**, where %s is the product’s UPC or class’s slug, respectively*

However, looking at the source of [product_tags.py](https://github.com/django-oscar/django-oscar/blob/1.5/src/oscar/templatetags/product_tags.py), line 21, different template files are searched:

    names = ['catalogue/partials/product/upc-%s.html' % product.upc,
                 'catalogue/partials/product/class-%s.html'
                 % product.get_product_class().slug,
                 'catalogue/partials/product.html']

**Comment by solarissmoke** [comment]
The documentation is referring to the product *detail* view, for which the template selection happens here: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/views.py#L91

The template tag you're referring to is used in product *list* views.

The documentation could be made clearer though, and there doesn't seem to be any documentation for the list view partials - so I'll leave this open.

**Comment by qubitstream** [comment]
Oh, you're right of course. 

I agree that an addition to the docs wouldn't hurt for sure.
