### ISSUE TITLE
Release with working dependencies for django 1.11

### ISSUE THREAD

**Issue by whyscream** [django-oscar/django-oscar#2477]
Current oscar 1.5 (or git master) does not allow a clean install with django 1.11. There is only one django-haystack version (2.7.0.dev0) that supports django 1.11, and that version is disallowed in oscar's `setup.py`:

```
$ git clone git@github.com:django-oscar/django-oscar.git
$ cd django-oscar
$ git checkout 1.5
HEAD is now at 78bc24df5... Bump to 1.5.0
$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to src/django_oscar.egg-info/requires.txt
[...]
Processing dependencies for django-oscar==1.5
[...]
error: Django 1.11.6 is installed but Django<1.11 is required by set(['django-haystack'])
$ pip freeze
Babel==2.5.1
Django==1.11.6
django-extra-views==0.6.4
django-haystack==2.6.1
django-oscar==1.5
django-phonenumber-field==1.3.0
django-tables2==1.13.0
django-treebeard==4.1.2
django-widget-tweaks==1.4.1
factory-boy==2.9.2
Faker==0.8.6
funcsigs==1.0.2
ipaddress==1.0.18
mock==2.0.0
olefile==0.44
pbr==3.1.1
phonenumberslite==8.8.4
Pillow==4.3.0
pkg-resources==0.0.0
purl==1.3.1
python-dateutil==2.6.1
pytz==2017.2
six==1.11.0
sorl-thumbnail==12.4a1
text-unidecode==1.0
Unidecode==0.4.21
$
```

Can we get a Oscar release that allows the django-haystack 2.7.0.dev0 version please? A patch release for oscar 1.5 would be sufficient, no need for an immediate 1.6 release.

**Comment by whyscream** [comment]
This issue was also brought up by @maerteijn in https://github.com/django-oscar/django-oscar/commit/91655b049f1577b4650b7b28f7e8877a3742c25b

**Comment by whyscream** [comment]
See PRs https://github.com/django-oscar/django-oscar/pull/2478 for patch on 1.5 release branch, and https://github.com/django-oscar/django-oscar/pull/2479 for master branch.

**Comment by solarissmoke** [comment]
Oscar 1.5.1 has just been released, which fixes this issue.
