### ISSUE TITLE
Django 2.0 support ?

### ISSUE THREAD

**Issue by mmmcorpsvit** [django-oscar/django-oscar#2495]
Django 2.0 already on RC stage, will be drop support Python 2.* branch (2.* must die, i believe...)

1. are have any plans for upgrade and drop python 2.*?
2. why demo (sandbox) so primitive ? (i now do good point e-shop, will be glad if can be Demo with you help of course: https://github.com/mmmcorpsvit/sophoshop)
3. with translate some terrible... for example Ukraine language not working correct! (i from Ukraine, hello))) )
4. project more live or dead ?)

**Comment by solarissmoke** [comment]
>  Any plans for upgrade and drop python 2.*?

Yes, we're planning to support Django 2 soon. Pull requests are welcome if you have done any work on this. We will be supporting Django 1.11 for some time yet, so we can't drop Python 2 entirely, but may consider dropping it for the next major release of Oscar. Oscar is already fully Python 3 compatible, so there isn't really a problem here.

> why demo (sandbox) so primitive?

Pull requests for making the demo less primitive are very welcome. 

> With translate some terrible... for example Ukraine language not working correct!

Please feel free to update the translations on Transifex, and to make a PR if there is a problem in the way the language is defined.

**Comment by mmmcorpsvit** [comment]
1. Ukraine translate not work
i fix this problem, just delete folder uk_UA, please try, i newby in oscar and not enought good know github for doing pullrequests)
write about this problem there: https://github.com/django-oscar/django-oscar/issues/2465
some messages are still not translated in dashboard, after new year planed fix it too

2. too have same problem: https://github.com/django-haystack/django-haystack/issues/1519
will be good write about known isuues separate on main page

in any case, sorry my poor english, and big th for oscar!!!

**Comment by sasha0** [comment]
The issue tries to address Django 2.0 support, which @solarissmoke already responded to. Translation issue is a separate topic and there's already ticket for this - https://github.com/django-oscar/django-oscar/issues/2465.

Other generic questions can be addressed in mailing list or Slack group. Thanks.

**Comment by craigloftus** [comment]
@mmmcorpsvit I've just pushed my work so far on Django 2.0 support, #2496. We're blocked on an upstream issue and a couple of failing tests.
