### ISSUE TITLE
Filtering products in the catalogue

### ISSUE THREAD

**Issue by narnikgamarnikus** [django-oscar/django-oscar#2500]
Hello. Thanks for Oscar - this is a great solution!

How can I implement filters in a catalogue?
I want to provide users with a range field or checkbox field so they can filter products at a price. or some attributes.

I did not find anything in Oscar's documentation about this.
This is a fairly common practice, for this, I think, there should be some developments or best practices on how to implement it.

Thanks in advance!

**Comment by egorsmkv** [comment]
Hi, Vova!

This library https://github.com/carltongibson/django-filter sounds good to be the solution for your needs.

**Comment by sasha0** [comment]
In order to achieve this, you might need to tweak `SearchForm` and logic in the search handler.

Anyhow, for the support issues you can use mailing list or Slack. Thanks.
