### ISSUE TITLE
no such column: catalogue_productattributevalue.value_datetime

### ISSUE THREAD

**Issue by pandabo1985** [django-oscar/django-oscar#2525]
## the catalogue's migrations not apply all,why?
./manage.py migrate
Operations to perform:
  Apply all migrations: address, admin, analytics, auth, basket, catalogue, contenttypes, customer, flatpages, offer, order, partner, payment, promotions, reviews, sessions, shipping, sites, thumbnail, voucher, wishlists
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying address.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying catalogue.0001_initial... OK
  Applying analytics.0001_initial... OK
  Applying analytics.0002_auto_20140827_1705... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sites.0001_initial... OK
  Applying partner.0001_initial... OK
  Applying customer.0001_initial... OK
  Applying basket.0001_initial... OK
  Applying basket.0002_auto_20140827_1705... OK
  Applying order.0001_initial... OK
  Applying offer.0001_initial... OK
  Applying voucher.0001_initial... OK
  Applying basket.0003_basket_vouchers... OK
  Applying basket.0004_auto_20141007_2032... OK
  Applying basket.0005_auto_20150604_1450... OK
  Applying basket.0006_auto_20160111_1108... OK
  Applying basket.0007_slugfield_noop... OK
  _**Applying catalogue.0002_auto_20150217_1221... OK
  Applying catalogue.0003_data_migration_slugs... OK
  Applying catalogue.0004_auto_20150217_1710... OK
  Applying catalogue.0005_auto_20150604_1450... OK
  Applying catalogue.0006_auto_20150807_1725... OK
  Applying catalogue.0007_auto_20151207_1440... OK
  Applying catalogue.0008_auto_20160304_1652... OK
  Applying catalogue.0009_slugfield_noop... OK**_
  Applying customer.0002_auto_20150807_1725... OK
  Applying customer.0003_update_email_length... OK
  Applying flatpages.0001_initial... OK
  Applying offer.0002_auto_20151210_1053... OK
  Applying offer.0003_auto_20161120_1707... OK
  Applying order.0002_auto_20141007_2032... OK
  Applying order.0003_auto_20150113_1629... OK
  Applying order.0004_auto_20160111_1108... OK
  Applying order.0005_update_email_length... OK
  Applying partner.0002_auto_20141007_2032... OK
  Applying partner.0003_auto_20150604_1450... OK
  Applying partner.0004_auto_20160107_1755... OK
  Applying payment.0001_initial... OK
  Applying payment.0002_auto_20141007_2032... OK
  Applying payment.0003_auto_20160323_1520... OK
  Applying promotions.0001_initial... OK
  Applying promotions.0002_auto_20150604_1450... OK
  Applying reviews.0001_initial... OK
  Applying reviews.0002_update_email_length... OK
  Applying reviews.0003_auto_20160802_1358... OK
  Applying sessions.0001_initial... OK
  Applying shipping.0001_initial... OK
  Applying shipping.0002_auto_20150604_1450... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying thumbnail.0001_initial... OK
  Applying wishlists.0001_initial... OK
  Applying wishlists.0002_auto_20160111_1108... OK

**Comment by sasha0** [comment]
This should has been fixed in 1.5 already. If you already customized `ProductAttributeValue` model, you need to generate migrations locally. Thanks.

**Comment by solarissmoke** [comment]
Closing as this appears to be an issue with your local setup (if you have forked the catalogue app you need to create migrations to match upstream model changes). Please feel free to use the mailing list if you still have issues.
