### ISSUE TITLE
Support lost for "render_option" in Django 1.11

### ISSUE THREAD

**Issue by josh-atkins-dev** [django-oscar/django-oscar#2526]
I'm trying to work out why the default `AdvancedSelect` widget won't add the '`disabled`' attribute for values given in `disabled_values`.

[See line 268 of `oscar.forms.widgets`](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/forms/widgets.py#L268) showing how constructor can take disabled values.

That class redefines the method "`render_option`" in order to inject the markup ` disabled="disabled"` on any values present in `self.disabled_values`.

In [Django 1.11 Release Notes line 612](https://github.com/django/django/blob/bc95314ca6af0b5e993ae07fdc7d8e6166d3b8ca/docs/releases/1.11.txt#L612), looks like the `render_option` method has been removed, which I suspect might be why I cannot have `self.disabled_values` take effect.

Can someone confirm what I'm suggesting is correct?

**Comment by solarissmoke** [comment]
You're right - it is indeed broken.
