### ISSUE TITLE
Bug: account page shows wishlist menuitem when wishlists app is hidden

### ISSUE THREAD

**Issue by thijskramer** [django-oscar/django-oscar#2536]
If you add `wishlists` to the `OSCAR_HIDDEN_FEATURES` setting, all wishlist-related functionality should be hidden. 
Although the wishlist buttons are gone on all product related templates, the 'wishlists' navigation item is still present on `/accounts/profile/` and it's still possible to manage wishlists from there.

**Comment by sasha0** [comment]
Thanks for the report.

Already fixed by #2522.
