### ISSUE TITLE
IOERROR at /en-gb/checkout/preview/

### ISSUE THREAD

**Issue by ApsRajput** [django-oscar/django-oscar#2537]
I get a bug when testing on server which shows 
IOError at /en-gb/checkout/preview/

Request Method: | POST
-- | --
http://eemfashion.in/en-gb/checkout/preview/
1.11.4
IOError
[Errno 5] Input/output error
/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/console.py in write_message, line 23
/usr/bin/python
2.7.12
['/root/eem/sandbox',  '/usr/local/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/local/lib/python2.7/dist-packages/setuptools-33.1.1-py2.7.egg',  '/root/eem/src',  '/usr/lib/python2.7/dist-packages']
Thu, 28 Dec 2017 10:56:36 +0000

but at local it works properly

Any fixes

**Comment by sasha0** [comment]
Could you please provide the whole traceback?

Although per the message `/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/console.py in write_message, line 23` it might inability to write email by django.core.mail.backends.filebased.EmailBackend backend, which would be totally a local issue.

**Comment by ApsRajput** [comment]
Environment:


Request Method: POST
Request URL: http://eemfashion.in/en-gb/checkout/preview/

Django Version: 1.11.4
Python Version: 2.7.12
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.flatpages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django_extensions',
 'debug_toolbar',
 'apps.gateway',
 'widget_tweaks',
 'oscar',
 'oscar.apps.analytics',
 'oscar.apps.checkout',
 'oscar.apps.address',
 'oscar.apps.shipping',
 'oscar.apps.catalogue',
 'oscar.apps.catalogue.reviews',
 'oscar.apps.partner',
 'oscar.apps.basket',
 'oscar.apps.payment',
 'oscar.apps.offer',
 'oscar.apps.order',
 'oscar.apps.customer',
 'oscar.apps.promotions',
 'oscar.apps.search',
 'oscar.apps.voucher',
 'oscar.apps.wishlists',
 'oscar.apps.dashboard',
 'oscar.apps.dashboard.reports',
 'oscar.apps.dashboard.users',
 'oscar.apps.dashboard.orders',
 'oscar.apps.dashboard.promotions',
 'oscar.apps.dashboard.catalogue',
 'oscar.apps.dashboard.offers',
 'oscar.apps.dashboard.partners',
 'oscar.apps.dashboard.pages',
 'oscar.apps.dashboard.ranges',
 'oscar.apps.dashboard.reviews',
 'oscar.apps.dashboard.vouchers',
 'oscar.apps.dashboard.communications',
 'oscar.apps.dashboard.shipping',
 'haystack',
 'treebeard',
 'sorl.thumbnail',
 'django_tables2']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.http.ConditionalGetMiddleware',
 'django.middleware.common.CommonMiddleware',
 'oscar.apps.basket.middleware.BasketMiddleware']



Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/root/eem/src/oscar/apps/checkout/session.py" in dispatch
  71.             request, *args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/root/eem/src/oscar/apps/checkout/views.py" in post
  441.             return self.handle_place_order_submission(request)

File "/root/eem/src/oscar/apps/checkout/views.py" in handle_place_order_submission
  457.         return self.submit(**self.build_submission())

File "/root/eem/src/oscar/apps/checkout/views.py" in submit
  631.                 shipping_charge, billing_address, order_total, **order_kwargs)

File "/root/eem/src/oscar/apps/checkout/mixins.py" in handle_order_placement
  118.         return self.handle_successful_order(order)

File "/root/eem/src/oscar/apps/checkout/mixins.py" in handle_successful_order
  254.         self.send_confirmation_message(order, self.communication_type_code)

File "/root/eem/src/oscar/apps/checkout/mixins.py" in send_confirmation_message
  292.                                                event_type, **kwargs)

File "/root/eem/src/oscar/apps/customer/utils.py" in dispatch_order_messages
  41.             dispatched_messages = self.dispatch_anonymous_messages(email, messages)

File "/root/eem/src/oscar/apps/customer/utils.py" in dispatch_anonymous_messages
  50.             dispatched_messages['email'] = self.send_email_messages(email, messages), None

File "/root/eem/src/oscar/apps/customer/utils.py" in send_email_messages
  123.             email.send()

File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py" in send
  348.         return self.get_connection(fail_silently).send_messages([self])

File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/console.py" in send_messages
  36.                     self.write_message(message)

File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/console.py" in write_message
  23.         self.stream.write('%s\n' % msg_data)

Exception Type: IOError at /en-gb/checkout/preview/
Exception Value: [Errno 5] Input/output error

**Comment by sasha0** [comment]
Right, this is local issue - see my comment above. Thanks.

**Comment by ApsRajput** [comment]
Thanks for the concern @sasha0
Can provide the solution as well please

**Comment by sasha0** [comment]
Feel free to ask about support cases in the mailing list or Slack. Thanks.
