### ISSUE TITLE
Refactor Oscar Application to use Django AppConfig

### ISSUE THREAD

**Issue by pwalsh** [django-oscar/django-oscar#2544]
# Description

By Django 1.11.8 (probably earlier, I have not checked) `startapp` generates an `apps.py` for housing application config classes. Related, `INSTALLED_APPS` integration is now documented as `<appname>.apps.<AppnameConfig>`, referencing these classes and this location.

Oscar also has an application config class, and it generally lives in `app.py`. There is much crossover between Oscar's app class and Django's app config class.

Oscar can probably configure itself from Django app config classes, if the Oscar Application can be designed as a mixin on a Django app config. Some fields should change, for example `self.app_name` > `self.name`. 

Also, I wonder if Django's model loaders could enhance or even replace all the dynamic class loading stuff in Oscar?

**Comment by solarissmoke** [comment]
I think this would be a good improvement and should let us drop a lot of code around class loading etc. I had a quick look at it some time back and found that it will require a fair bit of work, and maintaining backward compatibility may be tricky.

Still think it's worth doing though if someone is able to put in the time.

**Comment by jwayodi** [comment]
I'm working on this, in this PR: #2633

**Comment by solarissmoke** [comment]
Fixed in #2633
