### ISSUE TITLE
Oscar dynamic class loading breaks with recent Django configuration conventions

### ISSUE THREAD

**Issue by pwalsh** [django-oscar/django-oscar#2546]
# Description

As noted in #2544 Django's recommended `INSTALLED_APPS` config is now `<appname>.apps.<AppnameConfig>`.

This completely breaks Oscar's dynamic class loading as Oscar expects the module name of a class being loaded to exactly match a module in `INSTALLED_APPS` ([ref.](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/core/loading.py#L97)).

This will become a significant issue as more and more people follow the newer, recommended way to configure Django `INSTALLED_APPS`.

**Comment by solarissmoke** [comment]
I think this will need to be addressed as part of a wider refactoring in #2544 that relies on a single app config to tell Oscar where to find stuff. @pwalsh would you be willing/able to work on this?

**Comment by pwalsh** [comment]
this is also related to https://github.com/django-oscar/django-oscar/issues/1345 which also talks about Django 1.7 class loading.

**Comment by pwalsh** [comment]
> @pwalsh would you be willing/able to work on this?

@solarissmoke this is a deep and extensive change, which, honestly, I think would be better suited for a core maintainer of Django Oscar. In the meantime, I'll collect notes from what I find in research in #2544

**Comment by sasha0** [comment]
> this is also related to #1345 which also talks about Django 1.7 class loading.

Any thoughts about the related topic #1345? Pleas share if any. Thanks.

**Comment by solarissmoke** [comment]
Fixed in #2633
