### ISSUE TITLE
webob in use, but not referenced in pip dependencies

### ISSUE THREAD

**Issue by T4m** [django-oscar/django-oscar#2547]
Hello,
I update django-oscar 1.4 to 1.5.1. webob is now used in /oscar/test/utils.py:6. But webob is not added to python dependencies, so it's not added to requirements with pip-compile.

**Comment by solarissmoke** [comment]
Webob is a dependency of [webtest](https://pypi.python.org/pypi/WebTest), which is part of the [test dependencies](https://github.com/django-oscar/django-oscar/blob/master/setup.py#L59-L70) for Oscar. 

It isn't listed in `requirements.txt` (which only lists development dependencies), but rather in `setup.py`. It looks like that is the issue you have. I think the way to resolve it is to run `setup.py test` after installation.

**Comment by sasha0** [comment]
It's dependency of external package - I don't see any issue here.

**Comment by solarissmoke** [comment]
So, T4m is right. We're using `webob` in `oscar.test` which is shipped as part of Oscar itself - i.e., projects should be able to use the tools provided there. I think we either need to add `webob` to `setup.py` or stop using it in `oscar.test`. We only use it in [one place](https://github.com/django-oscar/django-oscar/blob/b77d2cf8f6083875534dc116074d0c7575497e6e/src/oscar/test/utils.py#L6) and could easily drop it - I think this would be better than adding a dependency.

**Comment by sasha0** [comment]
Agreed. Let's drop it.

**Comment by sasha0** [comment]
Did you try to rework cookie tests without `bytes_`? It was not easily possible when I refactored tests and moved away from test client usage.

**Comment by solarissmoke** [comment]
I have an idea that I think should work - will give it a go over the weekend.
