### ISSUE TITLE
Allow indicating form errors on AddToBasketForm

### ISSUE THREAD

**Issue by jerzyk** [django-oscar/django-oscar#255]
On the product detail page, it is impossible to indicate an incorrect field on the add-to-basket form.

Every time, form is being recreated from scratch, loosing form validation data and error indicators.

**Comment by sasha0** [comment]
The best and simplest solution for this case would be basket form submission via AJAX. 
In addition to submission without page reload, it does not require any interim implementation, which could cause more complications, than value.

Hence, we'd continue further discussion in related issue #1352.
