### ISSUE TITLE
Django oscar got failed migration via using mysql as backend

### ISSUE THREAD

**Issue by saurabh-mishrr** [django-oscar/django-oscar#2554]
I am trying to use django with mysql and while I was trying to migrate it throws an error ie.

"mysql.connector.errors.DatabaseError: 1553 (HY000): Cannot drop index 'catalogue_productimage_product_id_display_order_2df78171_uniq': needed in a foreign key constraint"

**Comment by solarissmoke** [comment]
Please can you provide a full stack trace that shows which migration the error originates from.

**Comment by our-startup** [comment]
Operations to perform:
  Apply all migrations: address, admin, analytics, auth, basket, catalogue, contenttypes, customer, flatpages, offer, order, partner, payment, promotions, reviews, sessions, shipping, sites, thumbnail, voucher, wishlists
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying address.0001_initial... OK
  Applying address.0002_auto_20150927_1547... OK
  Applying address.0003_auto_20150927_1551... OK
  Applying address.0004_auto_20170226_1122... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying catalogue.0001_initial... OK
  Applying analytics.0001_initial... OK
  Applying analytics.0002_auto_20140827_1705... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sites.0001_initial... OK
  Applying partner.0001_initial... OK
  Applying customer.0001_initial... OK
  Applying basket.0001_initial... OK
  Applying basket.0002_auto_20140827_1705... OK
  Applying order.0001_initial... OK
  Applying offer.0001_initial... OK
  Applying voucher.0001_initial... OK
  Applying basket.0003_basket_vouchers... OK
  Applying basket.0004_auto_20141007_2032... OK
  Applying basket.0005_auto_20150604_1450... OK
  Applying basket.0006_auto_20160111_1108... OK
  Applying basket.0007_slugfield_noop... OK
  Applying catalogue.0002_auto_20150217_1221... OK
  Applying catalogue.0003_data_migration_slugs... OK
  Applying catalogue.0004_auto_20150217_1710... OK
  Applying catalogue.0005_auto_20150604_1450... OK
  Applying catalogue.0006_auto_20150807_1725... OK
  Applying catalogue.0007_auto_20151207_1440... OK
  Applying catalogue.0008_auto_20160304_1652... OK
  Applying catalogue.0009_slugfield_noop... OK
  Applying catalogue.0010_auto_20170420_0439... OK
  Applying catalogue.0011_auto_20170422_1355...Traceback (most recent call last):
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/django/base.py", line 176, in _execute_wrapper
    return method(query, args)
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/cursor.py", line 559, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/connection.py", line 494, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/connection.py", line 396, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1553 (HY000): Cannot drop index 'catalogue_productimage_product_id_display_order_2df78171_uniq': needed in a foreign key constraint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/app/projects/oscar/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 536, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 349, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 380, in _delete_composed_index
    self.execute(self._delete_constraint_sql(sql, model, constraint_names[0]))
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/app/projects/oscar/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/django/base.py", line 226, in execute
    return self._execute_wrapper(self.cursor.execute, query, new_args)
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/django/base.py", line 194, in _execute_wrapper
    utils.DatabaseError(err.msg), sys.exc_info()[2])
  File "/app/projects/oscar/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/django/base.py", line 176, in _execute_wrapper
    return method(query, args)
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/cursor.py", line 559, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/connection.py", line 494, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/app/projects/oscar/lib/python3.5/site-packages/mysql/connector/connection.py", line 396, in _handle_result
    raise errors.get_exception(packet)
django.db.utils.DatabaseError: Cannot drop index 'catalogue_productimage_product_id_display_order_2df78171_uniq': needed in a foreign key constraint

**Comment by solarissmoke** [comment]
What version of Django are you using?

**Comment by our-startup** [comment]
Babel==2.5.1
Django==1.11.9
django-appconf==1.0.2
django-compressor==2.2
django-extra-views==0.6.4
django-haystack==2.6.1
django-oscar==1.5.1
django-phonenumber-field==1.3.0
django-tables2==1.17.1
django-treebeard==4.2.0
django-widget-tweaks==1.4.1
factory-boy==2.9.2
Faker==0.8.8
mock==2.0.0
mysql-connector==2.1.6
pbr==3.1.1
phonenumberslite==8.8.8
Pillow==5.0.0
pip==9.0.1
purl==1.3.1
python-dateutil==2.6.1
pytz==2017.3
rcssmin==1.0.6
rjsmin==1.0.12
setuptools==38.4.0
six==1.11.0
sorl-thumbnail==12.4.1
text-unidecode==1.1
Unidecode==0.4.21
wheel==0.30.0

**Comment by our-startup** [comment]
I tried above installed package by replacing django to ==1.8.18, It gives me another error ie.


> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f67a83efa60>
> Traceback (most recent call last):
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/utils/autoreload.py", line 229, in wrapper
>     fn(*args, **kwargs)
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
>     autoreload.raise_last_exception()
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
>     six.reraise(*_exception)
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/utils/autoreload.py", line 229, in wrapper
>     fn(*args, **kwargs)
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django/apps/config.py", line 86, in create
>     module = import_module(entry)
>   File "/app/projects/oscar1.8/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django_tables2/__init__.py", line 2, in <module>
>     from .tables import Table, TableBase
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django_tables2/tables.py", line 15, in <module>
>     from . import columns
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django_tables2/columns/__init__.py", line 6, in <module>
>     from .emailcolumn import EmailColumn
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django_tables2/columns/emailcolumn.py", line 9, in <module>
>     from .linkcolumn import BaseLinkColumn
>   File "/app/projects/oscar1.8/lib/python3.5/site-packages/django_tables2/columns/linkcolumn.py", line 4, in <module>
>     from django.urls import reverse
> ImportError: No module named 'django.urls'

**Comment by our-startup** [comment]
Babel==2.5.1
**Django==1.11.9**
django-appconf==1.0.2
django-compressor==2.2
django-extra-views==0.6.4
django-haystack==2.6.1
django-oscar==1.5.1
django-phonenumber-field==1.3.0
django-tables2==1.17.1
django-treebeard==4.2.0
django-widget-tweaks==1.4.1
factory-boy==2.9.2
Faker==0.8.8
mock==2.0.0
**mysql-connector==2.1.6**
pbr==3.1.1
phonenumberslite==8.8.8
Pillow==5.0.0
pip==9.0.1
purl==1.3.1
python-dateutil==2.6.1
pytz==2017.3
rcssmin==1.0.6
rjsmin==1.0.12
setuptools==38.4.0
six==1.11.0
sorl-thumbnail==12.4.1
text-unidecode==1.1
Unidecode==0.4.21
wheel==0.30.0

**Comment by solarissmoke** [comment]
I cannot reproduce this in Django 1.11.9 with MySQL version 5.7 (migrations run just fine). I can only guess that the issue is either that you are running an older version of MySQL, or there is some issue with mysql-connector (in which case maybe try mysqlclient instead).

**Comment by our-startup** [comment]
I am also using mysql version 5.7 and mysql connector 2.1.6 (pip)

**Comment by our-startup** [comment]
![image](https://user-images.githubusercontent.com/33782726/34769964-70d7d67c-f625-11e7-8ac3-dc1cc2edcee6.png)

**Comment by our-startup** [comment]
![image](https://user-images.githubusercontent.com/33782726/34770010-a1bb8126-f625-11e7-9aae-66279b424706.png)

**Comment by solarissmoke** [comment]
I'd suggest you try with mysqlclient instead and see if that makes a difference.

**Comment by our-startup** [comment]
I am using same connector in different project with same django version and
its working fine.

**Comment by solarissmoke** [comment]
What makes you think the issue is with Oscar itself then, rather than with your particular project where it is failing?

**Comment by saurabh-mishrr** [comment]
I don't know. I'm just saying that I'm using same connector for different project and its working fine. Have you tried to connect with mysql?

**Comment by saurabh-mishrr** [comment]
I tried with postgreSQL and its working fine. But its not working with mysql. Still I am closing this issue.

**Comment by kooba** [comment]
I've experienced the same issue on `MySQL 5.7.20` with `mysql-connector-python 8.0.5` while upgrading from `1.4` to `1.5.1`. I first tried to switch to `mysqlclient` but there seems to be a slew of issues running it on python3 (I'm on 3.6)

Workaround that worked for me:
1. Drop foreign key:
```SQL
ALTER TABLE catalogue_productimage DROP FOREIGN KEY catalogue_productima_product_id_49474fe8_fk_catalogue_product_id;
```
2. Run migrations
3. Restore the key:
```SQL
ALTER TABLE catalogue_productimage ADD CONSTRAINT `catalogue_productima_product_id_49474fe8_fk_catalogue_product_id` FOREIGN KEY (`product_id`) REFERENCES `catalogue_product` (`id`);
```

**Comment by kooba** [comment]
I've opened PR with more permanent fix: https://github.com/django-oscar/django-oscar/pull/2587
