### ISSUE TITLE
My purchases

### ISSUE THREAD

**Issue by yn-coder** [django-oscar/django-oscar#2558]
I my current project of DO adaptation I got castumer's question about `Account\My purchases` page.

I can't share the current private code, but can create the new version for main DO project.

`Account\My purchases` page contain the list of client purchased products. It's an another view on order's history.

Do you think it's useful for base DO product?

**Comment by solarissmoke** [comment]
Specifically how would this be different from the order history view?

**Comment by yn-coder** [comment]
If client has several orders - how it could find some specific previously purchased product? What if client has hundred orders?

`My purchases` is a table like this

Date | Product | Quantity | Order |
------|----------|-----------|------------
01/06/17  | Fasteners | 200 items | 54-48s

**Comment by solarissmoke** [comment]
Personally I don't think this is different enough from the order history view to justify adding it to the core. I would prefer that we just make it easy enough to add extra views so that projects can enhance the accounts section with such features.

**Comment by sasha0** [comment]
> Personally I don't think this is different enough from the order history view to justify adding it to the core. 

Me too.

> I would prefer that we just make it easy enough to add extra views so that projects can enhance the accounts section with such features.

What currently preventing user from adding extra views?

**Comment by solarissmoke** [comment]
> What currently preventing user from adding extra views?

Overriding the template was a bit of a pain (you had to override everything just to add a tab) but was improved in #2556 .

@yn-coder I think we will close this as something better implemented at project level.
