### ISSUE TITLE
differentiate in value_option and value_option in product attribute values table

### ISSUE THREAD

**Issue by SanskarSans** [django-oscar/django-oscar#2564]
I could not understand the difference in between value_option and value_multi_option field that is in the product attribute values table. Can anyone clarify their purpose and distinction with simple example, please? I saw in the admin but got confused.

**Comment by solarissmoke** [comment]
option only allows one option to be selected for that attribute - e.g, you might use it for distinct options like hard disk memory. Multi option allows multiple options to be selected for that attribute, e.g., you might use it for the colour choices available for a product.

Please use the mailing list or slack if you have further questions that are not bugs/feature requests. Thanks.

**Comment by SanskarSans** [comment]
Sorry, I could not load the slack. I got The request could not be satisfied. So I asked here. I apologize for that. Thanks for so instant reply though.
