### ISSUE TITLE
Documentation is unclear how to run tests.

### ISSUE THREAD

**Issue by khink** [django-oscar/django-oscar#2568]
The documentation (http://django-oscar.readthedocs.io/en/releases-1.5/internals/contributing/running-tests.html says to run `$ py.test`.

    $ py.test
    -bash: py.test: command not found

Well, obviously you need to have `pytest` installed. Let's make a virtualenv:

    $ mkvirtualenv --python=python3 oscar-tests
    (oscar-tests) $ pip install pytest
    (oscar-tests) $ py.test
    Traceback (most recent call last):
    ...
    ImportError: No module named 'django'
    ERROR: could not load /Users/kees/Projects/django-oscar/tests/conftest.py
 
Well obviously, we need django and all other dependencies.

    (oscar-tests) $ pip install -r requirements.txt
    ...
    Could not find a version that satisfies the requirement transifex-client==0.13.0 (from -r requirements.txt (line 30)) (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.4, 0.4.1, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.2, 0.7.3, 0.8, 0.9, 0.9.1, 0.10, 0.11b0, 0.11b3, 0.11, 0.11.1b0, 0.12b0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5)
No matching distribution found for transifex-client==0.13.0 (from -r requirements.txt (line 30))

Not sure if that's bad, but let's continue:

    (oscar-tests) $ py.test
    ...
    ImportError: No module named 'django'
    ERROR: could not load /Users/kees/Projects/django-oscar/tests/conftest.py

Wait what? Oh, django dependency is declared only in setup.py, which i haven't installed.

    (oscar-tests) $ pip install .
    ...
    Successfully installed Babel-2.5.3 Faker-0.8.10 Unidecode-0.4.21 django-1.11.9 django-extra-views-0.9.0 django-haystack-2.6.1 django-oscar-1.6.dev0 django-phonenumber-field-1.3.0 django-tables2-1.16.0 django-treebeard-4.2.0 django-widget-tweaks-1.4.1 factory-boy-2.9.2 mock-2.0.0 pbr-3.1.1 phonenumberslite-8.8.9 pillow-5.0.0 purl-1.3.1 python-dateutil-2.6.1 pytz-2017.3 sorl-thumbnail-12.4.1 text-unidecode-1.1
    (oscar-tests) $ py.test
    ...
    INTERNALERROR> django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'

Okay, another dependency, let's just install:

    (oscar-tests) $ pip install psycopg2
    ...
    Successfully installed psycopg2-2.7.3.2
    (oscar-tests) $ py.test
    /Users/kees/Projects/django-oscar/src/oscar/defaults.py:3: RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
      from django.core.urlresolvers import reverse_lazy
    ================================================================================ test session starts ================================================================================
    platform darwin -- Python 2.7.10, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
    rootdir: /Users/kees/Projects/django-oscar, inifile: setup.cfg
    plugins: django-3.1.2
    collected 840 items / 33 errors

    ====================================================================================== ERRORS =======================================================================================
    _________________________________________________________________ ERROR collecting tests/functional/test_basket.py __________________________________________________________________
    ImportError while importing test module '/Users/kees/Projects/django-oscar/tests/functional/test_basket.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    tests/functional/test_basket.py:14: in <module>
        from oscar.test.utils import extract_cookie_value
    src/oscar/test/utils.py:6: in <module>
        from webob.compat import bytes_
    E   ImportError: No module named webob.compat
    ...
    E   ImportError: No module named 'django_webtest'
    ...
    E   ImportError: No module named 'webob'

At this point i'm thinking i'm missing something. I tried installing `pytest-django` to no avail.

**Comment by sasha0** [comment]
You need to run `make install` or `pip install -e .[test]` to install all depencies.

**Comment by khink** [comment]
Ah thanks! I've updated the doc in #2569
