### ISSUE TITLE
more one group of variants ?

### ISSUE THREAD

**Issue by mmmcorpsvit** [django-oscar/django-oscar#2574]
are possible use oscar for variants when need more by one group of variants?

for example, T_shirts:
colors: black, white, red
sizes: M, L, XL

and different price for every variant ? any plans ?

**Comment by solarissmoke** [comment]
It's not clear what you are asking here - can you provide a more detailed explanation of what you are trying to achieve? Oscar already allows you to add any number of variants to a product, which different pricing for each. If you need more flexibility you can also calculate the price dynamically in your pricing strategy.

**Comment by solarissmoke** [comment]
Closing due to lack of feedback - feel free to reopen if you can provide more details.
