### ISSUE TITLE
Stop relying on CDN for TinyMCE

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2581]
The CDN version of TinyMCE has been broken for the last week or so - see https://github.com/tinymce/tinymce/issues/4171 . This has broken the dashboard for any site that uses the default dashboard setup - and with our current setup there is no way to fix this other than to monkey-patch `dashboard/layout.html` and use a different CDN.

I think this highlights the risks of using a CDN where we cannot control the minor version of the package (there is no way to specify minor version for that CDN). The maintainers of TinyMCE offer a different CDN (cloud.tinymce.com) as an alternative, but this one requires you to sign up for an API key.

I think it would be better for Oscar to provide a local copy of TinyMCE to avoid such issues in future.

**Comment by ksiazkowicz** [comment]
It broke production for us too. +1

**Comment by CoffeeNight** [comment]
Broke my production too

**Comment by davidhiskett** [comment]
Also broke ours - they said a fix was ready to go on Friday but it still hasn't been updated

**Comment by fyrkant** [comment]
You should be able to install TinyMCE with npm and copy it over with gulp like you seem to do with bootstrap! Then you can lock the version in the package.json.

**Comment by solarissmoke** [comment]
@fyrkant yep, that's the plan. Thank you for fixing the issue upstream as well though,
