### ISSUE TITLE
Mark user as staff

### ISSUE THREAD

**Issue by yn-coder** [django-oscar/django-oscar#2583]
Because Admin app is unsupported, how can I mark user as staff in dashboard?

If no way - is should we improve the `/dashboard/users/` or `user-detail` page with new actions (mark as staff) available for superuser?

**Comment by solarissmoke** [comment]
Currently the only place to do this is though the admin (which works, even though the dashboard is in theory a replacement for it), or through the shell.

The dashboard has a number of limitations which need to be addressed as part of a wider conversation on the purpose/functionality of the dashboard.

**Comment by yn-coder** [comment]
@solarissmoke So I just enable Admin app back.

**Comment by solarissmoke** [comment]
Yes - you can do this through the admin or the shell.
