### ISSUE TITLE
Remove datetimepicker JS from frontend template

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2584]
Oscar's base frontend layout template includes [JS for the Bootstrap datetimepicker](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/layout.html#L86-L87) that we use in the dashboard. 

There are no core frontend views that use any date/time picker widgets, so I don't think these scripts should be in the template. If a project needs to use a datepicker on the front end then they can add them - but it seems like innecessary overhead to load them everywhere just in case?

**Comment by ashishnitinpatil** [comment]
Agreed, I've felt the pain of the datetimepicker not working at all in the dashboard and having to disable it anyway. I'll see if I can submit a PR for this.

AFAIK, all major browsers now support datetime fields by default and there is hardly a requirement to use a custom solution for a mainstream problem with default solutions.
