### ISSUE TITLE
Disable basket - buy immediately

### ISSUE THREAD

**Issue by yn-coder** [django-oscar/django-oscar#2620]
I have a store with few digital products and I sure my custumers buy only one of it each time.

So I do not have phisical shiping and do not need for basket - only `buy now` button.

How can I disable basket and do buying process in I click - immediately redirect user to order?

**Comment by solarissmoke** [comment]
You would need to implement this logic yourself by replacing the add-to-basket form with your own form/handlers that bypass the basket and process the purchase immediately. Please use the mailing list/slack if you need further help in developing this idea.
