### ISSUE TITLE
Release 1.5.2 on pypi but not tagged in github

### ISSUE THREAD

**Issue by maerteijn** [django-oscar/django-oscar#2649]
I see that Oscar 1.5.2 was released on [pypi](https://pypi.python.org/pypi/django-oscar/1.5.2), but I don't see the corresponding tag on [github](https://github.com/django-oscar/django-oscar/tags).

Could somebody (who knows which commit is the 1.5.2 release) tag this and push it for future reference?

**Comment by solarissmoke** [comment]
Here you go: https://github.com/django-oscar/django-oscar/releases/tag/1.5.2
