### ISSUE TITLE
Not able to access admin dashboard

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [django-oscar/django-oscar#2650]
Not receiving an email with the credentials

**Comment by solarissmoke** [comment]
Duplicate of #2531

**Comment by Jeyakumarrathnaselvi** [comment]
How to access admin dashboard to validate the features

**Comment by solarissmoke** [comment]
Your best bet is to fire up the sandbox locally.
https://django-oscar.readthedocs.io/en/latest/internals/sandbox.html#running-the-sandbox-locally
