### ISSUE TITLE
Offer Tracking for Stacked Offers

### ISSUE THREAD

**Issue by ad-65** [django-oscar/django-oscar#2652]
I was testing out the stacked offer tracking that will be included in v1.6 and came across what may be a problem. It looks like the `LineOfferConsumer` class might be tracking the applied offers incorrectly.

As an example, in the basket app when  `AbstractLine.consume()` runs it should mark a line as consumed using `LineOfferConsumer.consume()` and passing the applicable offer. I think it should be storing the offer that consumed the items regardless of if the offer was exclusive or not. However, if the offer is exclusive it doesn't store the offer that consumed the line items.

This is for a test basket with an offer that should be applied to all three items in the line:

```python
class Line(AbstractLine):

    def consume(self, quantity, offer=None):
        super(Line, self).consume(quantity, offer)
        print "offer------------------------->", offer
        print "exclusive--------------------->", offer.exclusive
        print "has_discount------------------>", self.has_discount
        print "quantity_with_discount-------->", self.quantity_with_discount
        print "has_offer_discount------------>", self.has_offer_discount(offer)
        print "quantity_with_offer_discount-->", self.quantity_with_offer_discount(offer)
```

Output:

```
offer-------------------------> Discount 123456
exclusive---------------------> True
has_discount------------------> True
quantity_with_discount--------> 3
has_offer_discount------------> False
quantity_with_offer_discount--> 0
```

If the offer is set to non-exclusive then the behavior is as expected:

```
offer-------------------------> Discount 123456
exclusive---------------------> False
has_discount------------------> True
quantity_with_discount--------> 3
has_offer_discount------------> True
quantity_with_offer_discount--> 3
```

I don't actually need stacked offers per se, I just need to know what offer was applied to the line as a whole. Maybe this is stored somewhere else when a whole line is consumed by the same offer?

**Comment by pjstevns** [comment]
I'll take a look at this asap.

The LineOfferConsumer interface could do with more extensive tests.
