### ISSUE TITLE
Sorting products in catalog

### ISSUE THREAD

**Issue by yn-coder** [django-oscar/django-oscar#2654]
How to sort products in catalog ?

In my custom version I've add the new `ordering` field to product ancestor.

How to apply sorting in original DO ? Is my branch is interesting for base DO ?

**Comment by okfish** [comment]
It's not obvious because it is in the search form, which used in catalogue views. See here https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/search/forms.py#L82

**Comment by yn-coder** [comment]
@okfish I mean default sorting in catalog brawse page.

**Comment by solarissmoke** [comment]
The catalogue view uses a search handler that is based on the handler used for search - see https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/search/forms.py#L144. So they same form is used to control ordering of products.

Please use the mailing list or slack if you need further help with this.
