### ISSUE TITLE
Variant product list is not showing to partners

### ISSUE THREAD

**Issue by nikksbagul** [django-oscar/django-oscar#2655]
I am login as partner and I want to update my variant product stock record. But product is not showing on  catalogue product list.

**Comment by solarissmoke** [comment]
The partner dashboard doesn't support child products - see the note in the documentation: http://django-oscar.readthedocs.io/en/releases-1.1/ref/apps/dashboard.html#permission-based-dashboard . This is a known issue - closing as duplicate of #675 .
