### ISSUE TITLE
Develop and publish a supported versions policy

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2675]
Oscar does not currently have a formal policy that defines which versions are officially supported for maintenance and security releases, and the period for which versions will be supported.

I think we should develop a policy so that it is clear which versions will receive security and data-loss fixes.

My initial proposal for discussion is as follows:

1. With effect from Oscar 2.0 we use [semantic versioning](https://semver.org/) for releases.

2. We make Oscar 1.6 an LTS release that is linked to Django 1.11, which means we patch data loss and security issues for as long as Django 1.11 is officially supported (until April 2020).

3. We aim to release a new LTS one year before the previous LTS reaches end of life (i.e., April 2019 for the next LTS), and so on going forward. This is the same approach as Django takes.

4. Any major release issued in between these is **not** considered and LTS, and will only receive data loss and security fixes for a period of 1 year after it is released. This means that we drop support for Oscar 1.5.x in August 2018.

**Comment by sasha0** [comment]
Agreed. Any other opinions @craigloftus @mvantellingen ?
