### ISSUE TITLE
i get this issue builtins.DeprecationWarning

### ISSUE THREAD

**Issue by robbiibadi** [django-oscar/django-oscar#2691]
i try to use django oscar, i install based on documentation, everything iis fine, but when i go to basket url
i get this issue:

DeprecationWarning: SettingBasketView.extraat the class level is now deprecated. SetBasketView.factory_kwargsinstead.

**Comment by solarissmoke** [comment]
This was fixed in https://github.com/django-oscar/django-oscar/pull/2689 . We will issue a release shortly.
