### ISSUE TITLE
Easier "Colors" option?

### ISSUE THREAD

**Issue by khink** [django-oscar/django-oscar#2699]
On March 2nd, i asked this on Slack:

> Kees Hink [2:56 PM]
> How would one model a catalogue where all Products of a certain ProductClass are available in all AttributeOptions, and at the same price? Does one have to add all variants manually?
> 
> To take the sandbox as an example: All “T-shirt” products are now available in all Colors, and they all cost the same. So when i add a new T-shirt product, i don’t want to have to add Variants for each individual Color: there might be 20, that’s a lot of work. 
> (For now let’s disregard the “T-shirt size” factor by saying the new product is a size L. But bonus points if there’s a way to also let the customer pick any size as well, without having to add these manually.)
> 
> Is there a shortcut here?
> 
> Kees Hink [3:24 PM]
> I think product.options does what i want. Small issues:
> - I don’t seem to be able to set that through the dashboard (need django-admin)
> - It displays a string input field instead of the desired “colors” dropdown
> But that’s just implementation details, the basics are there!

Now that i've implemented this (https://www.barriquewijnhandel.nl/catalogue/category/glitterfles_7/), i thought i'd report what i had to do to get it working:

- Fork Oscar catalogue
- Add Color model + migration
- Fork Oscar's basket app.
- Override Oscar's SimpleAddToBasketForm
- Modify the AddToBasketForm to show a choice widget instead of text
- Test that we can manage custom colors for adding a Color product to basket
- Use Color objects in add to basket form
- Customize dashboard catalogue nav: also manage colors
- Make Colors manageable in Oscar Dashboard

Is this something we want to make easier? If so, i could share the knowledge, or make a PR or something.

**Comment by solarissmoke** [comment]
@khink thanks for sharing this! A couple of thoughts:

I personally think that `Color` specifically is probably too project-specific for Oscar to implement in core. You are, however, describing a fairly common use case ("choice-based options") and I think it's worth exploring whether Oscar can make it easier to implement that.

That said, the bulk of the work you describe above was in adding a `Color` model and making it dashboard-editable (which for me is quite project-specific).

We have previously used a different approach and used a product attribute to store a list of colors for each product, and then used these to populate a choice widget for the options, just as you have described. The benefit for us with that was that no additional dashboard functionality had to be written to allow management of these choices (they are just attributes) - all we had to do we swap out the widget used to render the options field. 

Would this approach have worked for you?

**Comment by specialunderwear** [comment]
I think you, while it looks like they are all the same, they really are not, because the products have a unique ean and sku, and you want this information to be associated with those products for google or marketplaces.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests without open PR's attached.
