### ISSUE TITLE
BrowsableProductManager was never deprecated, complicating overrides to it and ProductManager

### ISSUE THREAD

**Issue by andirigible** [django-oscar/django-oscar#2756]
I'm failing to understand why `BrowsableProductManager` was never deprecated and/or removed. The docstrings suggest it could have been deprecated as early as Oscar 0.7. I realize that the vanilla Product model uses it, but why does it use `BrowsableProductManager` instead of `ProductManager().browsable()`? The way this currently works makes overriding the behavior unnecessarily complicated, since `BrowsableProductManager` doesn't inherit dynamically, so overriding BPM requires re-declaring it after overriding PM. Obviously, I could just set my Product's `browsable` manager to `ProductManager().browsable()`, but it seems like this should have been dealt with already.

This seems like something that has just been forgotten, since the docstrings don't appear to have been updated since at least 0.7. I will happily do the legwork, but if this setup is intentional, I'll leave it alone.

### Technical details

* Python version: 3.6
* Django version: 1.11
* Oscar version: 1.6

**Comment by solarissmoke** [comment]
> I'm failing to understand why BrowsableProductManager was never deprecated and/or removed.

It's just that nobody has found the time. Would be very happy if you are able to make a PR for this.

I would suggest that we:

- Leave `ProductManager` and `BrowsableProductManager` but make both deprecated.
- Stop using both managers in Oscar core - i.e., just use `ProductQuerySet.as_manager()` instead.

**Comment by andirigible** [comment]
I can do this over the weekend, certainly. I'm happy to help with such a great library :)
