### ISSUE TITLE
Release unidecode changes?

### ISSUE THREAD

**Issue by jaroel** [django-oscar/django-oscar#2767]
Hi,

Could we get 1.6.3 released with the unidecode changes from https://github.com/django-oscar/django-oscar/pull/2749 ?

This would allow us to run Wagtail and Oscar in the same Django install, without depending on a source checkout.

Thanks up front!

**Comment by craigloftus** [comment]
The changes in #2749 involve API changes so it wouldn't be straight forward to backport to 1.6.x

There is a corresponding change, wagtail/wagtail#4618, that was merged quite a while ago but doesn't seem to have been included in the recent releases. Note, the PR is just a version bump; there isn't actually a functional conflict.

**Comment by jaroel** [comment]
Ah yeah, that makes sense. I'll poke Wagtail :)

**Comment by jaroel** [comment]
As a Wagtail 2.2 release is close, I don't think we'll need to push forward.
