### ISSUE TITLE
Oscar Basket django.db.models RelatedObjectDoesNotExist : Line has no basket

### ISSUE THREAD

**Issue by rahulmohite228** [django-oscar/django-oscar#2770]
Django db error when updating basket line.

### Issue Summary

I have added extra fields in StockRecord model, same fields is added in basket line model.
i have saved the extra field in db and use it to calculate final total of basket line.

but due to no reason the following error is coming at update function

**django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: Line has no basket.**

Hope i got some help

**Comment by solarissmoke** [comment]
You will need to provide a bit more information for us to be able to help - specifically how you have changed both the StockRecord and basket Line models, and what your update function is doing.

**Comment by rahulmohite228** [comment]
```
#my stockrecord extended model

from oscar.apps.partner.abstract_models import AbstractPartner, AbstractStockRecord
class StockRecord(AbstractStockRecord):
    extra_field = models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)
from oscar.apps.partner.models import *
```
--------------------------------------------------------------------------------------------------------
```
#my basket line model
from oscar.apps.basket.abstract_models import AbstractLine, AbstractBasket
class Line(AbstractLine):
    extra_field = models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)
from oscar.apps.basket.models import *
```

This how i have extented the models, and i partner/strategy.py
```

class NoTax(object):
          def pricing_policy(self, product, stockrecord):
              if not stockrecord or stockrecord.price_excl_tax is None:
                 return UnavailablePrice()
            return FixedPrice(
                 currency=stockrecord.price_currency,
               excl_tax=stockrecord.price_excl_tax,
            extra_field=stockrecord.extra_field,
            tax=D('0.00'))
```
