### ISSUE TITLE
Editing child products in dashboard emits ValidationError

### ISSUE THREAD

**Issue by SrdjanCosicPrica** [django-oscar/django-oscar#2783]
### Issue Summary

First time creating a child product works fine but trying to edit and save the child product after it has been creating always emits the ValidationError "a child product can't have a product class".

I saw here that this was already found in a PR but the bug seems to still exists in 1.6.2
https://github.com/django-oscar/django-oscar/pull/1441#issuecomment-52473882
### Steps to Reproduce

1. Create Product Class
2. Add new Product in previously created product class
3. Add new Variant and press save
4. Edit Variant and press save

### Technical details

* Python version: 3.6.4
* Django version: 2.0.7
* Oscar version: 1.6.2

**Comment by solarissmoke** [comment]
I am not able to reproduce this issue on the sandbox site - creating and then editing a variant works fine. 

Are you sure that you have not overridden either the catalogue or dashboard apps? If so can you try and give us steps to reproduce in the [sandbox](http://django-oscar.readthedocs.io/en/latest/internals/sandbox.html)?

**Comment by SrdjanCosicPrica** [comment]
Yeah you were right. The Product model is overridden but it was in the save method so I did not notice it until I looked more closely. Pardon my ignorance, closing.
