### ISSUE TITLE
Problem with PostgreSQL when retrieving products

### ISSUE THREAD

**Issue by Vitalynx** [django-oscar/django-oscar#2787]
### Issue Summary

A bug when using PostgreSQL as DB backend.

An invalid query is being used to get products in the catalogue (both in dashboard and regular).
This stems from the **get_queryset** method in **ProductListView**: 

`queryset = Product.browsable.base_queryset()`

For now, I replaced it with `Product.objects.all()` to get it to work.

\lib\site-packages\oscar\templates\oscar\base.html, error at line 0

> column "catalogue_product.structure" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT "catalogue_product"."id", "catalogue_product"."struct... ^

Full query:

`SELECT "catalogue_product"."id", "catalogue_product"."structure", 
 "catalogue_product"."upc", "catalogue_product"."parent_id", 
 "catalogue_product"."title", "catalogue_product"."slug", 
 "catalogue_product"."description", "catalogue_product"."product_class_id", 
 "catalogue_product"."rating", "catalogue_product"."date_created", 
 "catalogue_product"."date_updated", "catalogue_product"."is_discountable", 
 COUNT("catalogue_productclass_options"."option_id") AS 
 "num_product_class_options", 
 COUNT("catalogue_product_product_options"."option_id") AS 
 "num_product_options", "catalogue_productclass"."id", 
 "catalogue_productclass"."name", "catalogue_productclass"."slug", 
 "catalogue_productclass"."requires_shipping", 
 "catalogue_productclass"."track_stock" FROM "catalogue_product" LEFT OUTER 
 JOIN "catalogue_productclass" ON ("catalogue_product"."product_class_id" = 
 "catalogue_productclass"."id") LEFT OUTER JOIN 
 "catalogue_productclass_options" ON ("catalogue_productclass"."id" = 
 "catalogue_productclass_options"."productclass_id") LEFT OUTER JOIN 
 "catalogue_product_product_options" ON ("catalogue_product"."id" = 
 "catalogue_product_product_options"."product_id") WHERE 
 "catalogue_product"."parent_id" IS NULL GROUP BY "catalogue_product"."id", 
 "catalogue_productclass"."id" ORDER BY "catalogue_product"."date_updated" 
 DESC  LIMIT 1`

### Steps to Reproduce

1. Run the server
2. Add a product (after adding arbitrary category, product type and partner)
3. Visit the homepage and get products (Menu: Browse Store > All products) or through the dashboard (Menu: Catalogue > Products)

This bug does not occur when retrieving other information, such as the product types, categories, ranges etc.

### Technical details

* Python version: 3.6.4
* Django version: 2.0.7
* Oscar version: 1.6.4.
* PostgreSQL version: 9.0.23.

**Comment by solarissmoke** [comment]
I can't reproduce this on the sandbox. I think your issue is that you are using an unsupported version of PostgreSQL. Django 1.11.x requires [PostgreSQL 9.3 or higher](https://docs.djangoproject.com/en/2.1/releases/1.11/#dropped-support-for-postgresql-9-2-and-postgis-2-0).

**Comment by Vitalynx** [comment]
You're right - after upgrading to 9.6 it works.
Thanks!
