### ISSUE TITLE
Lazy URL load for OSCAR_HOMEPAGE in defaults.py raises unhandled exception

### ISSUE THREAD

**Issue by havocbane** [django-oscar/django-oscar#2810]
### Issue Summary

We are seeing the error `'promotions' is not a registered namespace` in our log handling when the Oscar app urls are resolved. It looks like the default settings are lazy loading the promotion homepage for the `OSCAR_HOMEPAGE` setting: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/defaults.py#L8

Since we're not using the promotions app urls in our customized integration, we see this raise the unhandled exception above.

### Steps to Reproduce

We customize/override the order and payment apps, but otherwise included `oscar.get_core_apps` in our `INSTALLED_APPS` setting. In our urls.py, we did not add `url(r'', include(oscar.app.application.urls))`, and then finally this error is raised when the django app urls are resolved, quickly reproducible in a view that simply raises via `response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())` in django.core.handlers.exception.py

### Technical details

* Python version: 3.6.3
* Django version: 1.11.7
* Oscar version: 1.6.3

**Comment by solarissmoke** [comment]
I think the long term solution for this is in #2215 where we are pulling out the promotions app completely. Until then, the easiest workaround is to override that setting with something like: 
    
    OSCAR_HOMEPAGE = '/'

**Comment by sasha0** [comment]
Setting has been finally updated within the #2215 and will be available within the Oscar 2.0 release.
