### ISSUE TITLE
Documentation could mention the need for python header files (-dev package)

### ISSUE THREAD

**Issue by pedro-walter** [django-oscar/django-oscar#2816]
Hi folks,

First of all, awesome project. Trying it for the first time to see if it fits my needs (or if the customization is worth it).

While building the sandbox locally, uWSGI build failed because I didn't have the python header files installed. It complained that "Python.h" was not found. A simple "apt-get install python-dev" was enough for me.

Mentioning in the documentation that you need python header files to build the sandbox can be a good idea, since I'm not sure if everyone would quickly know that "Python.h not found" error is easily fixed installing the headers. Guess a quick google would find it, but hey, why not make it easier? ;)

**Comment by sasha0** [comment]
Hi.

Thanks for the report. Would you submit a PR for this?

Thanks.

**Comment by sasha0** [comment]
In fact, second paragraph of the page "Setting up the development environment" - https://django-oscar.readthedocs.io/en/releases-1.6/internals/contributing/development-environment.html#setting-up-the-development-environment already mentions about it:

> If using Ubuntu, the python-dev package is required for some packages to compile.

Although I added additional note to the sandbox page as well in the PR #2998.
