### ISSUE TITLE
DeprecationWarning in StoreAddressInline

### ISSUE THREAD

**Issue by veris-neerajdhiman** [django-oscar/django-oscar#2828]
### Issue Summary
I have enabled `Store` plugin in `Django-oscar` but When I am trying to create a Store I am getting this **DeprecationWarning**. 

`Setting StoreAddressInline.extra at the class level is now deprecated. Set StoreAddressInline.factory_kwargs instead.`

I am seeing that same issue was raised in #2688  and fix was released. But still I am getting this error SO don't know if that release have fixed the issue or this is different.

### Technical details

   - Python 3.6.3
   - django-extra-views==0.11.0
   - django-oscar==1.6.4

**Comment by solarissmoke** [comment]
It looks like the issue you are having is with [django-oscar-stores](https://github.com/django-oscar/django-oscar-stores) which is a separate app, and which is not currently compatible with Oscar 1.6. If you are able then a PR to that repo would be appreciated.

**Comment by veris-neerajdhiman** [comment]
@solarissmoke  I just opened a https://github.com/django-oscar/django-oscar-stores/pull/90 , have a look.
