### ISSUE TITLE
Product only added to SQL-table offer_rangeproduct if removed and added again

### ISSUE THREAD

**Issue by secretlifeof** [django-oscar/django-oscar#2830]
### Issue Summary

I use django-graphene (GraphQL) together with Oscar so I don't know how this behaves with the Oscar frontend.

I have added a range called LandingPage so that I can add products to my front-page.

```
query LandingPage {
  viewer {
    landingPage {
      edges {
        node {
          name
            includedProducts {
	      edges {
	        node {
		      title
		      images {
		      edges {
		         node {
		              original
		          }
		      }
		    }
		  }
	       }
	     }
	    }
          }
			
       }
   }
}

```
If I add and save the range "LandingPage", also checking that the products are in the range, the products are not added to the SQL-table offer_rangeproduct. But if I remove and add them again they get added to the table. Is it suppose to be like this?

I added a picture to show which section I mean.

<img width="1107" alt="screen shot 2018-09-26 at 17 14 54" src="https://user-images.githubusercontent.com/38684618/46089897-cf877a00-c1af-11e8-8a82-b45adf049832.png">

_As a side comment: I think Oscar works quite good together with a GraphQL-schema. Data gets extracted quite easily._

### Technical details

* Python version: 3.7.
* Django version: 2.08.
* Oscar version: 1.64.

**Comment by sasha0** [comment]
I believe the issue is not related directly with the Oscar itself, since Oscar does not have any raw SQL queries or etc.

**Comment by solarissmoke** [comment]
As noted above this seems to be happening at the database abstraction layer. If you can narrow this down to an issue with Oscar itself, as opposed to with django-graphene, please reopen this with additional details of how to reproduce this directly in Oscar.
