### ISSUE TITLE
RelatedObjectDoesNotExist at /en-gb/basket/ Line has no basket.

### ISSUE THREAD

**Issue by Matt-Deacalion** [django-oscar/django-oscar#2873]
### Issue Summary
`RelatedObjectDoesNotExist at /en-gb/basket/ Line has no basket.`
Occurs when updating a basket across multiple tabs. 

### Steps to Reproduce

The issue comes down to having the basket open in two tabs. To reproduce:

1. Add items to the basket and open the basket page in two tabs.
2. Remove an item from the basket in one of the tabs.
3. Try to update that same item in the other tab.

### Technical details

* Python version: 3.7.1
* Django version: 2.1
* Oscar version: 2.0dev0

**Comment by sasha0** [comment]
Ok, issue confirmed and address within PR #2976.
