### ISSUE TITLE
The application.urls on getting started/Building your own shop guide needs to be updated

### ISSUE THREAD

**Issue by harriebird** [django-oscar/django-oscar#2886]
### Issue Summary

The URLs guide on the "Building your own shop" needs to be updated. 
`    url(r'', include(application.urls)),`

### Steps to Reproduce

It's essential that you provide enough information for someone else to replicate the problem you're seeing. Simply describing something that's broken on your current project is not enough!

1. Visit https://django-oscar.readthedocs.io/
2. Visited the "Building your own shop"
3. Read and followed the instructions
4. Runned the project `python manage.py runserver`
5. The command produces `SyntaxError: invalid syntax`

### Technical details

* Python version: 3.6.6.
* Django version: 2.1.3.
* Oscar version: 1.6.4.

**Comment by solarissmoke** [comment]
Can you provide the stack trace for the error, and the code that you've copy-pasted? `SyntaxError` could be coming from anywhere.

**Comment by solarissmoke** [comment]
Closing due to lack of feedback - please reopen if you can provide a stack trace.
