### ISSUE TITLE
Notification body is rendered as plain text, but passed HTML in some cases

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2916]
### Issue Summary

The body for customer notifications are [rendered as plain text](https://github.com/django-oscar/django-oscar/blob/f2bb0fb73c83cb879fb2dec9184059dd96d814e0/src/oscar/templates/oscar/customer/notifications/detail.html#L29) in the detail view.

But we create notifications with HTML in the body - e.g., [for stock alerts](https://github.com/django-oscar/django-oscar/blob/f2bb0fb73c83cb879fb2dec9184059dd96d814e0/src/oscar/apps/customer/alerts/utils.py#L101).

The resulting notifications are rendered with escaped HTML such as `<a href="/catalogue/test-product_6/">test product</a> is back in stock`.

We need to either allow HTML in the body, or ensure we don't provide it. We already allow HTML in the subject so it seems silly not to allow it in the body.

**Comment by TravellerSam** [comment]
I can confirm this bug is still present in 3.0. Also, some strings are not translated (or translatable) in the same template.

<img width="1078" alt="Screenshot 2021-02-04 at 12 59 00" src="https://user-images.githubusercontent.com/872730/106890303-6900b800-66e9-11eb-8ce6-540eec6908e2.png">

**Comment by specialunderwear** [comment]
<img width="836" alt="image" src="https://github.com/django-oscar/django-oscar/assets/52858/a4259185-8100-4514-bf4d-72f98802d73a">
this has been fixed
