### ISSUE TITLE
make sandbox error  (python3) ubuntu machine

### ISSUE THREAD

**Issue by jramirezpr** [django-oscar/django-oscar#2943]
Following the tutorial for Sandbox on Ubuntu, 
`
$ git clone https://github.com/django-oscar/django-oscar.git
$ cd django-oscar
$ virtualenv oscar
$ source ./oscar/bin/activate
(oscar) $ make sandbox
`

gives me an error 

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-                                         rhzjrjd2/psycopg2/
Makefile:19: recipe for target 'install-python' failed
make: *** [install-python] Error 1
`
The sequence of commands before the error:

`
pip install -r requirements.txt
Collecting Werkzeug==0.14.1 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29                                         c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (3                                         22kB)
    100% |████████████████████████████████| 327kB 3.1MB/s
Collecting django-debug-toolbar==1.11 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/01/9a/3db232bd15882d90d3c5                                         3de1f34ce0a522327849593c9198899713267cfe/django_debug_toolbar-1.11-py2.py3-none-                                         any.whl (201kB)
    100% |████████████████████████████████| 204kB 2.1MB/s
Collecting django-extensions==2.1.5 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/bf/91/840de20b263525af1585                                         194eb8339a8f6d077f8b9698c80332d28f7a3200/django_extensions-2.1.5-py2.py3-none-an                                         y.whl (218kB)
    100% |████████████████████████████████| 225kB 3.2MB/s
Collecting psycopg2<2.8,>=2.7 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/63/54/c039eb0f46f9a9406b59                                         a638415c2012ad7be9b4b97bfddb1f48c280df3a/psycopg2-2.7.7.tar.gz (427kB)
    100% |████████████████████████████████| 430kB 3.5MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.                                         txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directo                                         ry
    containing pg_config to the $PATH or specify the full executable path with t                                         he
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyP                                         I
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

 `

**Comment by wooooodward** [comment]
```
mkdir oscar
cd oscar
git clone https://github.com/django-oscar/django-oscar.git
```

Then you have to checkout the [most recent release](https://github.com/django-oscar/django-oscar/releases).

`git checkout 05b14af`

Make virtual environment with python version < 3.7

```
python3.6 -m venv venv
source venv/bin/activate
```

Then use vim to edit the `requirements.txt` line `psycopg2>=2.7,<2.8 --no-binary psycopg2
` to `psycopg2-binary`

```
cd django-oscar
vim requirements.txt
```

Finally...

`make sandbox`

**Comment by jramirezpr** [comment]
@wooooodward Thank you, I will try that out.

**Comment by jramirezpr** [comment]
@wooooodward  update: I ran your solution, it seems to have worked! Couple of other issues that came up: something about not being able to run some wheels appeared, will try to reproduce error and add it to thread. Also, had to restart the make sandbox part because i did not have npm installed, (simple fix, but should be part of the tutorial or dependencies when django-oscar is installed). Anyways, thank you!

**Comment by hellobkrishna** [comment]
Hello, I'm new on this platform.
How to solve this issue!! when I use  make sandbox.

**(oscar) ubuntu@ip-172-xx-x-xx:~/django-oscar$** make sandbox
pip install -r requirements.txt
Collecting Werkzeug<1.1,>=1.0
 Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting django-debug-toolbar<2.3,>=2.2
 Using cached django_debug_toolbar-2.2-py3-none-any.whl (198 kB)
Collecting django-extensions<2.3,>=2.2
 Using cached django_extensions-2.2.9-py2.py3-none-any.whl (217 kB)
Collecting psycopg2-binary<2.9,>=2.8
 Using cached psycopg2_binary-2.8.5-cp35-cp35m-manylinux1_x86_64.whl (2.9 MB)
Collecting Pillow==7.1.2
 Using cached Pillow-7.1.2-cp35-cp35m-manylinux1_x86_64.whl (2.1 MB)
Collecting Whoosh==2.7.4
 Using cached Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)
Collecting django-environ==0.4.5
 Using cached django_environ-0.4.5-py2.py3-none-any.whl (21 kB)
Collecting django-redis==4.12.1
 Using cached django_redis-4.12.1-py3-none-any.whl (19 kB)
Collecting pysolr==3.8.1
 Using cached pysolr-3.8.1-py2.py3-none-any.whl (16 kB)
Collecting redis==3.5.3
 Using cached redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting requests==2.23.0
 Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting uWSGI==2.0.18
 Using cached uwsgi-2.0.18.tar.gz (801 kB)
Collecting whitenoise==5.1.0
 Using cached whitenoise-5.1.0-py2.py3-none-any.whl (19 kB)
Collecting flake8==3.8.2
 Using cached flake8-3.8.2-py2.py3-none-any.whl (72 kB)
Collecting flake8-debugger==3.2.1
 Using cached flake8-debugger-3.2.1.tar.gz (4.2 kB)
Collecting flake8-blind-except==0.1.1
 Using cached flake8-blind-except-0.1.1.tar.gz (2.5 kB)
Collecting isort==4.3.21
 Using cached isort-4.3.21-py2.py3-none-any.whl (42 kB)
Collecting pyprof2calltree==1.4.5
 Using cached pyprof2calltree-1.4.5.tar.gz (10 kB)
Collecting ipdb==0.13.2
 Using cached ipdb-0.13.2.tar.gz (14 kB)

ERROR: Could not find a version that satisfies the requirement ipython<7.16,>=7.12 (from -r requirements.txt (line 29)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0)
_ERROR: No matching distribution found for ipython<7.16,>=7.12 (from -r requirements.txt (line 29))
Makefile:19: recipe for target 'install-python' failed
make: *** [install-python] Error 1_
**(oscar) ubuntu@ip-172-xx-x-xx:~/django-oscar$**

**Comment by solarissmoke** [comment]
Looks like you're running Python 3.5 which is not supported by the latest version of iPython. Oscar's dependency should probably be pinned to 7.9.0 . Note however that Python 3.5 reaches end of life in September, and we will be dropping support for it after that.
