### ISSUE TITLE
Default 500 error template should not extend layout.html

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2971]
The current 500 error template in Oscar extends `error.html`, which in turn extends `500.html`. This is bad practise because it means that if you have an error in the parent template, then the 500 template will fail to render.

The 500 template should be standalone and not extend any other template.

**Comment by sasha0** [comment]
For simplicity, I'd just make `error.html` template standalone. What do you think?

**Comment by solarissmoke** [comment]
It's only the 500 template that I think needs to be standalone. 

I think it's fine and useful for 404 errors etc to extend `layout.html` - so that the user can still access navigation etc.
