### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by eugenzor** [django-oscar/django-oscar#2977]
Demo site: https://latest.oscarcommerce.com/en-gb/catalogue/
is not working:
![Selection_606](https://user-images.githubusercontent.com/3356454/55016116-ce1bfa80-4ff6-11e9-8e0f-41b7d4462007.png)

**Comment by solarissmoke** [comment]
@mvantellingen I think you're the only one who can fix this? MIgrations have failed to run after recent model changes.

**Comment by solarissmoke** [comment]
Fixed via #3126
