### ISSUE TITLE
Don't link to non-public products on front-end

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2979]
After the changes made in #2935, it is possible to generate front-end links to products that are not accessible from the front end - e.g, in the customer order history views. 

We need to change the behaviour such that if the product is not viewable we don't try to link to it from front-end views. Similarly we need to disable the ability to re-order a product if it is not viewable.

I came across this with the order history views but there may be other cases where the same issue applies.

**Comment by sasha0** [comment]
Didn't the PR #2985 address this issue?

**Comment by solarissmoke** [comment]
Yep. Fixed in #2985.
