### ISSUE TITLE
Make Benefit apply methods accept kwargs

### ISSUE THREAD

**Issue by fakhar362** [django-oscar/django-oscar#2982]
If one decides to use the `max_total_discount` or the `discount_amount` field available on `apply()` methods of `PercentageDiscountBenefit` and `AbsoluteDiscountBenefit`, you run into the issue that the other benefits of `FixedPriceBenefit` etc don't accept these **arguments** or **kwargs** in general, and because of this, in your overridden `apply_benefit()` method on `ConditionalOffer` you have to add in a conditional to check for the proxyclass of your Benefit to only add the additonal kwarg i.e. `max_total_discount` in case of `PercentageDiscountBenefit` or `AbsoluteDiscountBenefit`, so it would be beneficial if all apply methods to start accepting kwargs so one can go without adding in the additional checks for **proxy class** of `Benefit`

Came across this issue in our project where we decided to restrict the max discount per application of an offer, other people will also probably run into similar issues if they want to make use of the `max_total_discount` argument.

**Comment by sasha0** [comment]
Done in PR #2983.
