### ISSUE TITLE
Release a django 2.2 compatible version?

### ISSUE THREAD

**Issue by maerteijn** [django-oscar/django-oscar#3011]
Any sight, roadmap or ideas for a 1.7 or 2.0 version so we have a Django 2.2 compatible release?

**Comment by auvipy** [comment]
From the commit history, this should be possible from the master branch.

**Comment by solarissmoke** [comment]
I would like to cut a 2.0 release very soon - will discuss this with the other core team members early next week to see if we can agree to cut a release before the end of the month.

**Comment by maerteijn** [comment]
Ok sounds good, then I can release a new version of [oscarapi](https://github.com/django-oscar/django-oscar-api/) as well.

**Comment by auvipy** [comment]
At least the oscar==2.0a1 would be superb as well by the end of this month :)

**Comment by solarissmoke** [comment]
We released 2.0b1 yesterday. Will wait a couple of weeks for feedback/bug reports before making an RC. https://pypi.org/project/django-oscar/2.0b1/
