### ISSUE TITLE
Disable Debug Toolbar in Sandbox

### ISSUE THREAD

**Issue by johanovic** [django-oscar/django-oscar#3038]
I just tested Oscar for the first time. I created the sandbox locally and was about to conclude that it was too slow for me. I looked at the debug toolbar and realized it could not be the SQL (which is nice and fast). Actually it was the toolbar itself. I deactivated debug mode and realized that Oscar is fast. 

Hence my suggestion: disable the debug toolbar for the sandbox or document that it should be disabled if you want to test Oscar for speed.

0.02

**Comment by solarissmoke** [comment]
Thanks for this suggestion. I think disabling it completely would be a bit problematic, because we use the sandbox for development (which is itself maybe an issue...). Making a note in the documentation is a good idea though.

**Comment by sasha0** [comment]
> Thanks for this suggestion. I think disabling it completely would be a bit problematic, because we use the sandbox for development (which is itself maybe an issue...). 

Yes, totally. As a middle-term goal, I propose to spin-off a separate settings/env for development and leave sandbox to get acknowledge with the Oscar, play around etc. WDYT @solarissmoke ?

> Making a note in the documentation is a good idea though.

Ok, let's drop a note about that.
