### ISSUE TITLE
Unable to run dockerfile

### ISSUE THREAD

**Issue by bhuiyanmobasshir94** [django-oscar/django-oscar#3052]
Found a bug? Please fill out the sections below.

### Issue Summary
While building docker file through docker build command I got stuck  and got some warnings. Even while pulling docker image from docker hub couldn't run it at all. Want a doc for running docker image. Please help me out

**Comment by SmileyJames** [comment]
I can build the dockerfile and run the resulting image, without error.

**Comment by solarissmoke** [comment]
I've just tested running the docker file, and it works fine for me. Going to close this issue - if you are able to provide more specific details about what doesn't work for you / steps to reproduce the problem then we can look into it.
