### ISSUE TITLE
Add a Management Command for Copying notifications to database

### ISSUE THREAD

**Issue by shimulch** [django-oscar/django-oscar#3066]
Is there a management command to populate ``CommunicationEventType`` with existing templates?

If not it might be pretty handy. In our case we needed to provide our customer with ability to changing email content (At least minimum) without programmer's help. Oscar has great support for that. But we need to manually copy all the template to database. Would it be possible to create a management command to do that? 

Looking forward to hear from you guys, if you think it's a good idea, I can spend some time on it.

**Comment by specialunderwear** [comment]
Yes. https://gist.github.com/specialunderwear/f3386e92f0a5f8990a4772a08326f640

**Comment by shimulch** [comment]
@specialunderwear Thanks for that gist. But seems it does not support SMS templates.

**Comment by specialunderwear** [comment]
That should easy enough to fix ...

**Comment by sasha0** [comment]
Closing since it looks like all questions were addressed already.
