### ISSUE TITLE
The postal Code validation for Israel should also take 5 digit numbers

### ISSUE THREAD

**Issue by ckaalund** [django-oscar/django-oscar#3074]
In oscar.apps.address.abstract_models.AbstractAddress:

`'IL': r'^[0-9]{7}$',`

Should be:
`'IL': r'^([0-9]{5}|[0-9]{7})$',`

For more info: https://en.wikipedia.org/wiki/Postal_codes_in_Israel

**Comment by ckaalund** [comment]
But they are used by our customers. So sure I can just overwrite it, which we have. 

To me the key sentence in the wiki article is: "they continue to be widely used". As we are dealing with people and not machines, then what is official is to me not as important as what is used by our customers :)

**Comment by solarissmoke** [comment]
@ckaalund grateful if you can make a PR to address this.

**Comment by sasha0** [comment]
Or if you could quote working 5-digit postal code - that also would be helpful.

**Comment by sasha0** [comment]
Ok, found reference by myself of https://en.youbianku.com/Israel.

PR is coming as well.
