### ISSUE TITLE
ProductQuerySet.base_queryset() should not perform annotations

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#3075]
The annotations performed in [`base_queryset()`](https://github.com/django-oscar/django-oscar/blob/a5096da38a265925f768ec5ce5258e9b7b1a2d72/src/oscar/apps/catalogue/managers.py#L97-L98) are very expensive. 

We have a catalogue of 250,000 products, where loading the dashboard products list view takes about 6-7 seconds because of these annotations - despite the fact that they are not used anywhere in that view. Removing the annotation drops this to less than 0.5 seconds.

I propose that the base queryset should be just that - a base queryset without any annotations. The views that need to use options should add annotations when preparing their context. The same argument could actually apply for the prefetching being done here. I think we need to review all the places that `base_queryset()` is used, and whether it is more optimal to perform the prefetching at point of use.

**Comment by specialunderwear** [comment]
Hi solarissmoke, I have been doing a lot with the querysets these days and in this case I believe that the performance problem could be caused by your queryset not being sliced. It could be that your entire 250000 products are being returned annotated, which could cause the annotation to be very slow indeed because it performs a count. If done on a single page of objects, that would be harmless. Could you please turn on db logging and make sure that there is no query being performed that would return all the objects in your database?

The paginators are tricky and sometimes do not slice the queryset.

**Comment by solarissmoke** [comment]
@specialunderwear the query is being sliced. Here is the generated SQL for the problematic query - note the limit clause at the end:

```
SELECT ••• FROM "catalogue_product" LEFT OUTER JOIN "catalogue_productclass" ON ("catalogue_product"."product_class_id" = "catalogue_productclass"."id") LEFT OUTER JOIN "catalogue_productclass_options" ON ("catalogue_productclass"."id" = "catalogue_productclass_options"."productclass_id") LEFT OUTER JOIN "catalogue_product_product_options" ON ("catalogue_product"."id" = "catalogue_product_product_options"."product_id") WHERE "catalogue_product"."parent_id" IS NULL GROUP BY "catalogue_product"."id", "catalogue_productclass"."id" ORDER BY "catalogue_product"."date_updated" DESC LIMIT 20
```

This query takes 2,000ms. If the annotation is removed it takes 1.9ms and is reduced to:

```
SELECT ••• FROM "catalogue_product" LEFT OUTER JOIN "catalogue_productclass" ON ("catalogue_product"."product_class_id" = "catalogue_productclass"."id") WHERE "catalogue_product"."parent_id" IS NULL ORDER BY "catalogue_product"."date_updated" DESC LIMIT 20
```

I'm fairly certain that the annotation is problematic. The annotation appears to be happening before the `LIMIT` is applied in the database.

**Comment by specialunderwear** [comment]
Thanks solarissmoke, I think the group by makes that query slow. has_options is the only method that uses that info. I don't think has_options would be very hard to implement efficiently in a different way.

**Comment by specialunderwear** [comment]
Something like this would work, but not that this always returns all the options of product class and product in one go. That is not what the current options method does. At least it returns a queryset!
```
    def options(self):
        Option = self._meta.get_field("product_options").related_model
        return Option.objects.filter(
            models.Q(product=self) | models.Q(productclass=self.product_class_id or -1),
        ).distinct()

    @property
    def has_options(self):
        return self.options.exists()
```

**Comment by specialunderwear** [comment]
It is really fun to use the newest query features in django !!!
