### ISSUE TITLE
Removing a field on a model likely to result in import error in ModelForm

### ISSUE THREAD

**Issue by rik** [django-oscar/django-oscar#3078]
# Context
I'm moving the `Partner` foreign key from `StockRecord` to `Product`. 

# Steps to reproduce
1. Fork the Partner app
1. Add a custom `StockRecord` model without the partner field:
    ```py
    class StockRecord(AbstractStockRecord):
        partner = None
    ```
1. Run `./manage.py runserver`

# Error
When importing `StockRecordForm`, Django throws this error:
```pytb
Traceback (most recent call last):
  File "/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/site-packages/oscar/apps/dashboard/catalogue/apps.py", line 27, in ready
    'ProductListView')
  File "/site-packages/oscar/core/loading.py", line 31, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/site-packages/oscar/core/loading.py", line 99, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/site-packages/oscar/core/loading.py", line 133, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/site-packages/oscar/apps/dashboard/catalogue/views.py", line 25, in <module>
    ('ProductForm',
  File "/site-packages/oscar/core/loading.py", line 41, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/site-packages/oscar/core/loading.py", line 99, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/site-packages/oscar/core/loading.py", line 133, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 64, in <module>
    class StockRecordForm(forms.ModelForm):
  File "/site-packages/django/forms/models.py", line 266, in __new__
    raise FieldError(message)
```

[Code in Django](https://github.com/django/django/blob/858cfd74e958b63e81657e5a9fc5f751c19e8192/django/forms/models.py#L260-L267)

# Solutions/workaround?
For now, I'm going to keep a partner field but change it to a boolean to have a small storage overhead.

I wonder if there is anything Oscar could do to make it easier to remove fields on models.

**Comment by solarissmoke** [comment]
I'm not sure there is a lot that Oscar can do to help in this regard. If you want to remove a field that is used heavily in core, you will need to override and modify any code that depends on it. 

In this case the error is arising because `dashboard.catalogue.forms.StockRecordForm` depends on there being a `partner` field on the model. If you override that form not to do that, then you will not get an error. This isn't something that Oscar is going to be able to do for you though.

In this particular case I would suggest that it is easier and low-cost simply to have a single partner that all stock records are foreign keyed to, instead of trying to remove the field. You will run into a very large number of issues otherwise.

**Comment by rik** [comment]
I've tried overriding that Form but it is still throwing an error because `apps/dashboard/catalogue/forms.py` is still getting imported by `default_class_loader`.

**Comment by rik** [comment]
I'm wondering if there is a way to do something similar to `AbstractModels`. Have a blueprint for `ModelForm` in Oscar that only turns into a concrete form if there is no concrete version in the local project.

**Comment by maerteijn** [comment]
I think you are trying to do things that is not worth all the effort that is needed to make it work (and to keep it maintainable).

As solarissmoke pointed out: 
> In this particular case I would suggest that it is easier and low-cost simply to have a single partner that all stock records are foreign keyed to, instead of trying to remove the field.

Do that and override the form not to show the partner field (and set a default value for it).

> Have a blueprint for ModelForm in Oscar that only turns into a concrete form if there is no concrete version in the local project.

There is already. `get_class` and `get_classes` is doing that exactly. See the [Documentation](https://django-oscar.readthedocs.io/en/2.0.0/ref/core.html#dynamic-class-loading) and the source code of Oscar how it is used.

**Comment by rik** [comment]
Yeah, I'm moving away from removing that particular field and introduce another concept of Seller on Product. Thanks for the advices.

> > Have a blueprint for ModelForm in Oscar that only turns into a concrete form if there is no concrete version in the local project.
> 
> There is already. `get_class` and `get_classes` is doing that exactly. See the [Documentation](https://django-oscar.readthedocs.io/en/2.0.0/ref/core.html#dynamic-class-loading) and the source code of Oscar how it is used.

See my earlier comment  https://github.com/django-oscar/django-oscar/issues/3078#issuecomment-511375967 and the traceback, this does not work. Django raises an exception at import time.

This is not an issue for me anymore. I still think it can be annoying in other situations but if no one else expressed this issue, feel free to close it.
