### ISSUE TITLE
Wrong logic for getting all available statuses for Order and OrderLine.

### ISSUE THREAD

**Issue by dfirst** [django-oscar/django-oscar#3088]
Wrong logic for getting all available statuses for Order and OrderLine.
Wrong test case: django-oscar/tests/integration/order/test_models.py>LineStatusTests>test_all_statuses_class_method
In setup testcase it have:
`        Line.pipeline = {'A': ('B', 'C'),
                         'B': ('C',)}`
And in testcase it check:
`self.assertEqual(['A', 'B'], sorted(Line.all_statuses()))`
But should be:
`self.assertEqual(['A', 'B', 'C'], sorted(Line.all_statuses()))`
Same problem with order.

Please confirm if its a bug and i do PR.

**Comment by solarissmoke** [comment]
I think it's just a poorly written test rather than a bug in the functional code. The pipeline should be defined as:

    Line.pipeline = {
        'A': ('B', 'C'), 
        'B': ('C',)
        'C': (),
    }

**Comment by dfirst** [comment]
Ok but it happen in multiple testcases, that`s why i`m not sure is it a bug or feature.
Same issue for orders test case:
`{'PENDING': ('SHIPPED', 'CANCELLED'),
                          'SHIPPED': ('COMPLETE',)}`
And also same problem in orders dashboard testcases:
`{'A': ('B', 'C')}`

**Comment by solarissmoke** [comment]
It's neither a bug nor a feature - simply that the test pipelines defined in the tests are poorly defined.
