### ISSUE TITLE
slack workspace is down

### ISSUE THREAD

**Issue by othane** [django-oscar/django-oscar#3096]
Found a bug? Please fill out the sections below.

### Issue Summary

The link to the slack workspace in the README.rst does not seem to work ?

### Steps to Reproduce

In the README.rst there is a link to  https://slack.oscarcommerce.com/ .. if I visit the link it does not seem to work

### Technical details

NA

**Comment by maerteijn** [comment]
Thanks, updated the link in #3097

**Comment by rik** [comment]
Are there any instructions on how to request access to that Slack workspace?

**Comment by solarissmoke** [comment]
See https://github.com/django-oscar/django-oscar/pull/3097#issuecomment-516386953 - slack.oscarcommerce.com is what was triggering the invite. I think we need to ask @mvantellingen as a first step whether he can look into what is wrong there, and whether we need to host that service elsewhere.

**Comment by solarissmoke** [comment]
Please [use this form](https://forms.gle/Vpn2EnTjQ68C1jyG8) as an interim measure - we'll use it to process invites manually.

**Comment by solarissmoke** [comment]
This is fixed now.
