### ISSUE TITLE
Add date_updated field to basketline

### ISSUE THREAD

**Issue by mhoonjeon** [django-oscar/django-oscar#3140]
Logic behind this proposal:

It is very fairly common for customers to change and fiddle with basketlines(i.e change quantities), so I think adding `date_updated` field to AbstractBaskeLine would be good.

I know forking the basket app and overriding basketline is trivial, but the Line model having `date_updated` field as default would be more flexible. I think most people would like to use Oscar as it is and make changes only when it is absolutely necessary for forward-compatibility reasons.

The docstring even advises users to do this, if someone wants to order the basket lines like Amazon(=`Last modified on top`), which I presume would be the case for quite a number of people including myself.

Thanks.

**Comment by sasha0** [comment]
I don't have any objections, how about you @solarissmoke @craigloftus ?

**Comment by solarissmoke** [comment]
No objection here either. PR is welcome.
