### ISSUE TITLE
Invalid html when non public categories have subcategories that are public.

### ISSUE THREAD

**Issue by specialunderwear** [django-oscar/django-oscar#3160]
The ``category_tree`` template tag will render invalid html when a non public category has public categories.

This is because the category loop will skip to the next depth (because the children depth is greater and they are not filtered out) without opening a tag. This leads to too many closing tags.

The solution is ofcourse to filter out all children of non public categories. But that might be not so easy 😄

**Comment by solarissmoke** [comment]
I think this will be fixed by #3050

**Comment by specialunderwear** [comment]
Haha sorry no this is a bug in that code. We run that in production, sorry

**Comment by solarissmoke** [comment]
Closing as this is not an issue on master, but with PR #3050 where it's been addressed.
