### ISSUE TITLE
Exclusive with Count Condition not work anymore

### ISSUE THREAD

**Issue by prince-tanapong** [django-oscar/django-oscar#3162]
# Issue Summary

I create 2 offers with count condition, **Both are not exclusive**, After oscar version 2.0, It seem like it just apply only 1 offers not apply both anymore

### Steps to Reproduce
1. Create 2 offers like this 
![Screen Shot 2019-08-29 at 17 02 19](https://user-images.githubusercontent.com/8855366/63931190-01b7f080-ca7f-11e9-8e34-d93f01c3d102.png)

2. Only 1 offer apply
![Screen Shot 2019-08-29 at 17 06 09](https://user-images.githubusercontent.com/8855366/63931399-67a47800-ca7f-11e9-8989-988bd9cf5b05.png)

**Expected**
1. Should apply both offers if it does not exclusive.?

Note
I try to dig into the issue and  compare the load, I found out that, in condition.py they are some changed about is_satisfied like this image below

<img width="1606" alt="Screen Shot 2019-08-29 at 17 08 11" src="https://user-images.githubusercontent.com/8855366/63931528-a6d2c900-ca7f-11e9-8f08-24e6a7966516.png">

When I reverse code back it work like a charm, Any idea why you guy change that?

### Technical details

* Python version: 3.6.8
* Django version: 1.11.5
* Oscar version: 2.0.1.

**Comment by janfabry** [comment]
Indeed, this was changed in https://github.com/django-oscar/django-oscar/commit/c1c61ef5c5112068fbaeadf5714423becec8ba25#diff-008132744b4a8f62da8f13ae6286db70R49-R50, but only for `CountCondition`, not for `CoverageCondition` and `ValueCondition`, so I think this was an error.

**Comment by sasha0** [comment]
Or the reason could also be in the `Condition.can_apply_condition` method. As the author of the change, could you please suggest @pjstevns what was the motivation of the change?

**Comment by bruecksen** [comment]
Are there any news on this issue? Or could I help with something.

**Comment by solarissmoke** [comment]
@bruecksen it needs someone to spend a bit of time working out a fix - if you have time to do so that would be appreciated.
