### ISSUE TITLE
Missing French translation 

### ISSUE THREAD

**Issue by rik** [django-oscar/django-oscar#3169]
Some translations are missing in the package and in Transifex.

# Is public
```po
#: apps/catalogue/abstract_models.py:267
#, fuzzy
#| msgid "Is public?"
msgid "Is public"
msgstr "Est publique ?"

#: apps/catalogue/abstract_models.py:269
msgid "Show this product in search results and catalogue listings."
msgstr ""

#: templates/oscar/dashboard/catalogue/product_update.html:176
msgid "Drag images to re-order them. Space for additional images will appear when images are added."
msgstr ""
```

There might be more but that's what I've found so far.

**Comment by solarissmoke** [comment]
We update the package translation files manually once in a while. Same for Transifex at present (see #3029). We do need a better workflow for this.

**Comment by solarissmoke** [comment]
Transifex should now be up to date - I'll give it a few days before pulling back the translations from there in case you want to update/add any translations.

**Comment by rik** [comment]
Thanks! I've translated all of them!
