### ISSUE TITLE
Offer Consumed Many Times on Same Product

### ISSUE THREAD

**Issue by alexphelps** [django-oscar/django-oscar#3171]
### Issue Summary
The Offer Incentive type "Discount is percentage off of the products value" will multiply the discount value by the max affected items. For example, an Offer for 10% discount with max affected 5 items in the basket will result in a 50% discount on 1 product, instead of the expected 10% discount. 

### Steps to Reproduce
1. Create a new offer with incentive 10% discount and max affected items 5
2. The offer will apply itself 5 * 10% resulting in a 50% discount

![image](https://user-images.githubusercontent.com/674282/64397229-c3c45900-d08a-11e9-894f-df225f43a336.png)
![image](https://user-images.githubusercontent.com/674282/64397235-ccb52a80-d08a-11e9-92b8-205e60f7e481.png)
![image](https://user-images.githubusercontent.com/674282/64397257-d9d21980-d08a-11e9-8be8-46eb87462b6c.png)

![image](https://user-images.githubusercontent.com/674282/64397312-10a82f80-d08b-11e9-83fc-158b07c1f9a5.png)

### Technical details

Can reproduce on the Sandbox site with Oscar 2.0 
https://latest.oscarcommerce.com/
Example Offer - https://latest.oscarcommerce.com/en-gb/dashboard/offers/4/

**Comment by solarissmoke** [comment]
Thank you for reporting this @alexphelps , and @nasirhjafri for your PR! We will back-port this fix to the 2.0.x branch and issue a bugfix release soon.

**Comment by solarissmoke** [comment]
Fixed in version 2.0.2.
