### ISSUE TITLE
Review Oscar's communications - and possibly consolidate them into a single framework

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#319]
Oscar currently sends emails via the customer dispatcher and also has a notifications framework.  There are also a few places where emails are sent directly from views.

These components should be reviewed and possibly unified into a single communications framework.

**Comment by sasha0** [comment]
Perhaps we can move it to the separate application and see if it is flexible and customizable enough? WDYT @solarissmoke @mvantellingen ?

**Comment by solarissmoke** [comment]
Agreed - there is a case for refactoring the entire communications workflow. I think a good first step would be to make sure that all existing communications are sent through the Dispatcher?

**Comment by sasha0** [comment]
Yes, that would be a good step to start with.

**Comment by sasha0** [comment]
Having done with @samitnuk large refactoring on one of the projects, in order to have single and consistent backend for all kinds of notifications, now I find original idea even more useful.

**Comment by solarissmoke** [comment]
Fixed in #3260.
