### ISSUE TITLE
Reports autodiscovery

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#32]
We should have an autodiscovery script for reporting that works like the admin or Haystack autodiscovery.

It will need to loop through all the installled apps and looks for a file called reports.py, then register each reporting class.  This will allow the reporting dashboard to automatically show the available reports.

**Comment by sasha0** [comment]
I think this would bring unnecessary complications and would require additional setting for excluding report classes, which and not needed to import.

Thus, I think explicitly report classes designation in the `GeneratorRepository` is enough for now. It's also consistent (with shipping repository) and worked well for all this time.
