### ISSUE TITLE
Need username and password for frobshop example application running locally

### ISSUE THREAD

**Issue by archit1012** [django-oscar/django-oscar#3207]
Need username and password for frobshop example application running locally
for 
http://localhost:8000/admin/login/
and 
http://127.0.0.1:8000/dashboard/login/

below one are not working

username: superuser
email: superuser@example.com
password: testing

**Comment by solarissmoke** [comment]
I'm not able to reproduce this - the documented credentials work fine on a new sandbox instance, as they do on the [demo site](https://latest.oscarcommerce.com/). If this doesn't work for you, just create a new user with `manage.py createsuperuser`.

**Comment by xpat** [comment]
FYI, trying this for the first time in 2024 and getting the exact same problem:  The documented credentials are good for the sandbox but not for the frobshop on localhost.  Thumbs-up to the work-around: `manage.py createsuperuser `   .
