### ISSUE TITLE
notifications context processor query DB on every request

### ISSUE THREAD

**Issue by sir-sigurd** [django-oscar/django-oscar#3208]
This context processor

https://github.com/django-oscar/django-oscar/blob/f9ff1588c1b4719d3cae3e1f9f2a8806aa3d0cb7/src/oscar/apps/customer/notifications/context_processors.py#L6-L12

query DB on every request even when `num_unread_notifications` is not used. So I think it might make sense to either make it callable or rework it as template tag.

**Comment by craigloftus** [comment]
`num_unread_notifications` is used in `oscar/partials/nav_accounts.html` which is included in `layout.html`, so by default it is used on every view apart from the dashboard.

If you've overriden the templates and don't use the variable, then you can avoid the cost by just not including this context processor in your `TEMPLATES` setting.
