### ISSUE TITLE
Basket Save For Later not validating correctly

### ISSUE THREAD

**Issue by brianedelman** [django-oscar/django-oscar#3215]
Found a bug? Please fill out the sections below.

### Issue Summary

Working on an django-oscar project and I discovered that the "save for later" feature in the basket doesn't work as intended as far as I can tell. I was a registered user interacting with my cart and had 2 items in the cart. Pressing saved for later reloaded the page but the cart remained unchanged. A message was added that read "cart total is now X.XX." So it was trying to do something but failing.

Upon investigating line 159 of `oscar/apps/basket/views.py` uses `getattr` to check for 'save_for_later' which always returns false even if it should be true. 
```
if (hasattr(form, 'cleaned_data')
                    and getattr(form.cleaned_data, 'save_for_later', False)):
```
I changed it into `form.cleaned_data.get('save_for_later', False)` which works but then it creates a bug further down the line where there should only be 1 saved basket. Not sure what the intended behavior down the line is but could create a PR if someone weighs in on what the behavior of the whole save for later flow should be.

### Steps to Reproduce

1. Add multiple items to cart.
2. Click 'save for later' in basket.
3. Cart will not change, but message will be added.

### Technical details

* Python version: 3.6.2
django-oscar==2.0.2

**Comment by solarissmoke** [comment]
Thanks for reporting this. This is a regression [introduced in this commit](https://github.com/django-oscar/django-oscar/commit/cca43aa4d1b41833fabfa8aaf432df28f8b1e498#diff-64ea6af857bdaaee13f3fbc770586f95), and your proposed change to fix that looks correct. Would be great if you are able to make a PR to fix this!

> but then it creates a bug further down the line where there should only be 1 saved basket

It's not clear to me why this should happen - a saved basket is created with a different status to the active one, and this shouldn't cause any problems. Can you elaborate on what issue you run into?

**Comment by brianedelman** [comment]
@solarissmoke I made the change locally and then I hit an issue where oscar does a .get() to grab the saved basket. Maybe it was something I had done during testing that wouldn't normally be hit, but I had multiple saved baskets after I changed the line described in my original post and was unable to load any pages as a result. My solution at the time was to delete all saved baskets via the shell. I don't know exactly which line it was at this point, however, line 128-129 of the same file might possibly be it. 
```                
saved_basket = self.basket_model.saved.get(
                    owner=self.request.user)
```
There is only one other call like this in the same file and it pertains to ajax which my use case wasn't touching, I don't believe. Either way both of these could potentially fail. I wasn't sure what the intention was further down the line. Should there be multiple saved baskets or only ever one?

**Comment by solarissmoke** [comment]
There should only be one saved basket for any user - the [logic that creates/updates a saved basket](https://github.com/django-oscar/django-oscar/blob/a22f4991b036890b2d90839cd2c4a03e22258255/src/oscar/apps/basket/views.py#L226-L229) should enforce this (unless there's another bug elsewhere).
