### ISSUE TITLE
Dynamic Class Loading with Forked Dashboard App

### ISSUE THREAD

**Issue by derekjamescurtis** [django-oscar/django-oscar#3232]
### Issue Summary

When forking a dashboard app, dynamic class loading always fetches the original oscar classes when importing with **get_class('dashboard.package.module', 'TheClass')**, instead of getting our overridden class.

**However**, if using the app_label the import works correctly.  This results in any of the oscar dashboard code only loading the original oscar class, instead of the overridden classs.

#### 1. Fork one of the oscar apps and it's corresponding dashboard

```bash
# fork oscar catalogue and dashboard catalogue
./manage.py oscar_fork_app catalogue my_project
./manage.py oscar_fork_app catalogue_dashboard my_project
```

#### 2. Replace the oscar apps in INSTALLED_APPS

```python
# my_project/settings.py

INSTALLED_APPS = [
  ....
    'oscar',
    # 'oscar.catalogue'
    'my_project.catalogue.apps.CatalogueConfig',
    # 'oscar.dashboard.catalogue'
    'my_project.dashboard.catalogue.apps.CatalogueDashboardConfig'
```

#### 3. Add an additional model field to ProductClass

```python
# my_project/catalogue/models.py
from oscar.apps.catalogue.abstract_models import AbstractProductClass
from oscar.core.loading import is_model_registered
from django.db import models
from django.utils.translation import ugettext_lazy as _

__all__ = []

if not is_model_registered('catalogue', 'ProductClass'):
    class ProductClass(AbstractProductClass):
        my_special_field = models.BooleanField(
            _('My special field'),
            default=False,
            help_text='It's special yo'
        )
    __all__.append('ProductClass')

from oscar.apps.catalogue.models import *  # noqa isort:skip
```

#### 4. Extend the dashboard form

```python
from oscar.apps.dashboard.catalogue import forms as base_forms
from oscar.core.loading import get_model

ProductClass = get_model('catalogue', 'ProductClass')

class ProductClassForm(base_forms.ProductClassForm):
    class Meta:
        model = ProductClass
        fields = ['name', 'requires_shipping', 'my_special_field', 'track_stock', 'options', ]
```

#### 5. Run our migrations

```python
./manage.py makemigrations
./manage.py migrate
```

#### 6. Notice the original class loads when using get_class with 'dashboard.catalogue.forms'

```python
# ./manage.py shell
>>> from oscar.core.loading import get_class

>>> get_class('dashboard.catalogue.forms', 'ProductClassForm')
<class 'oscar.apps.dashboard.catalogue.forms.ProductClassForm'>

>>> get_class('catalogue_dashboard.forms', 'ProductClassForm')
<class 'my_project.dashboard.catalogue.forms.ProductClassForm'>
```

I expect that the first call to get_class would return the value of the second.  My current workaround is to also subclass the views that use the aforementioned form and then assign those views to the appconfig class in .ready(), replacing the originals.

### Technical details

* Python version: Python 3.7
* Django version: 2.2.1
* Oscar version: 2.0.3

### Additional Notes

I have also overridden the dashboard app, as I'm using the promotions app that was split from oscar.  I don't think it's relevant, but just in case it is, I've included it here.

```python
from django.apps import apps
from django.conf.urls import include, url
from django.urls import path
from oscar.apps.dashboard.apps import DashboardConfig as OscarDashboardConfig

class DashboardConfig(OscarDashboardConfig):
    def ready(self):
        super().ready()
        self.promotions_app = apps.get_app_config('oscar_promotions_dashboard')

    def get_urls(self):
        urls = super().get_urls()
        extra_urls = []
        extra_urls.append(url(r'^promotions/', include(self.promotions_app.urls[0])))
        urls.extend(self.post_process_urls(extra_urls))
        return urls
```

**Comment by solarissmoke** [comment]
You say you've overridden the dashboard app - can you show us how you've loaded that in `INSTALLED_APPS`. The behaviour you've described would occur if the main dashboard app hasn't been forked (but it should work if it has been forked).

**Comment by solarissmoke** [comment]
We've tested this, and everything works correctly provided that (a) the dashboard app is forked as well and (b) it's location relative to other dashboard apps is correct. It seems you are missing one of these issues. We've updated the documentation in #3238 to try to make this clearer.

As regards modifying the class loader to use the app label instead of the app name, this would definitely make things more straightforward and is something we're planning to look into - it would be a significant breaking change from Oscar's historic class loading (which previously wasn't dependent on Django's app configuration), so it's something we need to do with some care.

I'm going to close this issue, but feel free to reopen if you can demonstrate that there's still an issue after addressing the two points above.
