### ISSUE TITLE
Confusing output of `oscar_fork_app` management command

### ISSUE THREAD

**Issue by samitnuk** [django-oscar/django-oscar#3246]
Sample output of `oscar_fork_app`:

```bash
> ./manage.py oscar_fork_app order apps
Creating package apps/order

Creating admin.py

Creating app config

Creating models.py

Creating migrations folder

Replace the entry 'oscar.apps.order.apps.OrderConfig' with 'apps.order.apps.OrderConfig' in INSTALLED_APPS
```

But there is no entry like `'oscar.apps.order.apps.OrderConfig'` in `INSTALLED_APPS`.
Based on [Oscar docs](https://django-oscar.readthedocs.io/en/2.0.0/internals/getting_started.html#django-settings) there is only `'oscar.apps.order'`.

Probably instead of `app_config_class_path` here:
https://github.com/django-oscar/django-oscar/blob/e347ad9ed052e82eb275d3bb32500f3f5f225007/src/oscar/core/customisation.py#L122-L129
we should use `app_config.name`.

I can prepare a PR to change the current behavior. Please comment. Thanks.

**Comment by solarissmoke** [comment]
I would prefer that we update the documentation on setting up a project to use the explicit app configs in the settings (i.e., the `INSTALLED_APPS` should contain `oscar.apps.order.apps.OrderConfig`), which is the recommended approach by Django. This will then make the output of the command correct.

**Comment by samitnuk** [comment]
@solarissmoke Thanks!

I will create a PR to update the documentation then.
