### ISSUE TITLE
Writing to products attributes with Product.attr can lead to dataloss

### ISSUE THREAD

**Issue by specialunderwear** [django-oscar/django-oscar#3258]
### Issue Summary

Writing to products attributes with `product.attr` can lead to data loss

### Steps to Reproduce

Create a productclass with 3 attributes, the second one you create must be optional.
Create a product and do not fill the second optional attribute. Now write to the non-optional attributes with code like this:

        p = Product.objects.get(pk=4)
        p.attr.subtitle = "lama"
        p.attr.available = False
        p.attr.save()

One of the 2 attributes will not be updated because the attr object will not be intialized. During save it will encounter the second attribute which is not on the object and trigger initialization. Initialization will overwrite one of the 2 values written and reset it to whatever is in the database.

### Technical details

This problem occurs with all python versions and all oscar versions.

**Comment by specialunderwear** [comment]
As a workaround, before writing, just call
```
p.attr.initiate_attributes()
```

**Comment by solarissmoke** [comment]
@specialunderwear could you please supply a failing test for this? I tried the below but it passes, which suggests I'm not correctly replicating the situation you describe:

```python
def test_attributes_initialised_before_write(self):
    product_class = factories.ProductClassFactory()
    product_class.attributes.create(name='a1', code='a1', required=True)
    product_class.attributes.create(name='a2', code='a2', required=False)
    product_class.attributes.create(name='a3', code='a3', required=True)
    product = factories.ProductFactory(product_class=product_class)
    product.attr.a1 = "v1"
    product.attr.a3 = "v3"
    product.attr.save()

    product.refresh_from_db()
    product.attr.a1 = "v2"
    product.attr.a3 = "v6"
    product.attr.save()

    product.refresh_from_db()
    assert product.attr.a1 == "v2"
    assert product.attr.a3 == "v6"
```

**Comment by specialunderwear** [comment]
Unfortunately refresh_from_db is not enough to reset the attributes.
try:
```
product.attr.__dict__ = {}
```
