### ISSUE TITLE
Setting `required` on a ProductAttribute with type boolean is non-sensical

### ISSUE THREAD

**Issue by woutdp** [django-oscar/django-oscar#3282]
### Issue Summary
When a `ProductAttribute` with type `boolean` is set to `required=True`, it requires any underlying`ProductAttributeValue` to be set to `True`, otherwise the Product you're trying to create/change won't save in the dashboard. I don't think the `required` field makes sense for a boolean field in this case. A Boolean field could still be `False` but be required to be filled in as `False`. It's all a bit confusing. 

It makes sense purely on a form, where you might need to check a checkbox to submit the form. But in this case it's a field in a database that's required. 

### Steps to Reproduce
1. Go to dashboard
1. On any `ProductType` defined, add an Attribute with type `True / False` and set the `Required` field to `True`.
1. Create a new product with this `ProductType` and set the attribute on the product to `False`

The dashboard interface says it's required to be set to `True` and as such the option for `False` is not possible.

### Proposed solution
Don't allow `ProductAttribute`'s with type `boolean` to be set to `required=True`.

### Technical details
I've tested this on an older Python version. But couldn't find any reference of a fix for this in the latest version.

* Python version: `2.7.17`
* Django version: `1.11.23`
* Oscar version: `1.6.7 `

**Comment by solarissmoke** [comment]
Thanks for this - your proposed fix makes sense, PR welcome if you have time.
