### ISSUE TITLE
Language selection not appearing

### ISSUE THREAD

**Issue by maxlefou** [django-oscar/django-oscar#3285]
### Issue Summary
The language selector at the top-left doesn't appear. The user can't select any language, unlike in [the demo website](https://latest.oscarcommerce.com).

### Steps to Reproduce
1. Just install oscar normally
2. Use the following code to add additional languages in `settings.py`:
```
LANGUAGE_CODE = 'en-gb'

gettext_noop = lambda s: s
LANGUAGES = [
    ('af', gettext_noop('Afrikaans')),
    ('ar', gettext_noop('Arabic')),
    [...]
    ('zh-hans', gettext_noop('Simplified Chinese')),
    ('zh-hant', gettext_noop('Traditional Chinese')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

os.environ["LANGUAGE"] = 'en-gb'

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
```
3. Also copied the locale folder in the project just in case.

### Technical details
* Python version: 3.7.3
* Django version: 2.2.9
* Oscar version: 2.0.4

Changing the value of `LANGUAGE_CODE` in `settings.py` works. Only the selector form on the website doesn't.

I slightly hacked the template to force the language select form to appear no matter what. It appears now but there's no languages in the list at all.

I also noticed the url pattern is not `website/en-gb/catalogue` as it should be, but `website/catalogue`. Though, `urls.py` is correctly set:
```
from django.apps import apps
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include(apps.get_app_config('oscar').urls[0])),
]
```

I'm new to django so maybe I missed something? I haven't found anything relevant in the docs though...

**Comment by solarissmoke** [comment]
As you've noted, this is working fine on the sandbox site, so it's something missing on your project. From what you have posted I suspect you're missing `django.template.context_processors.i18n` from your template context processors.

**Comment by maxlefou** [comment]
Thanks alot for the quick reply. Indeed the context processor was missing. Now everything works like a charm! :) Closing up.

Though, while it works perfectly, unlike the sandbox site, the path doesn't become like `website/en-gb/catalogue`. Is it normal? (not a problem though since it still works that way)

**Comment by solarissmoke** [comment]
> Unlike the sandbox site, the path doesn't become like website/en-gb/catalogue

You're probably missing [`i18_patterns`](https://github.com/django-oscar/django-oscar/blob/master/sandbox/urls.py#L32-L33) in your URL configuration.
