### ISSUE TITLE
Issue with `apply` method of `MultibuyDiscountBenefit`

### ISSUE THREAD

**Issue by samitnuk** [django-oscar/django-oscar#3344]
### Issue Summary

`apply` method of `MultibuyDiscountBenefit` does not work as it should. With `Count` condition it makes all items in the basket FOC.

### Steps to Reproduce

Failed test in PR https://github.com/django-oscar/django-oscar/pull/3342

### Technical details

If in the test above we will have more than two items in the basket. E.g.
```python
add_product(self.basket, D('20'), 2)
add_product(self.basket, D('100'), 5)
```
 this loop will make 10_000 iterations:
https://github.com/django-oscar/django-oscar/blob/2429ad9e88e9a432dfa60aaca703d99860f85389/src/oscar/apps/offer/applicator.py#L33-L40

Suggested change to `apply` method, please review in PR https://github.com/django-oscar/django-oscar/pull/3343

**Comment by maziar-dandc** [comment]
was it not possible to just set max cart applications = 1 ?
