### ISSUE TITLE
Incorrect endblock in template `templates/oscar/partials/brand.html`

### ISSUE THREAD

**Issue by RamezIssac** [django-oscar/django-oscar#3354]
Just an incorrect endblock location.

Easily Visible here on master branch atm 
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/partials/brand.html

I believe it should be 
```

<div class="col-sm-7 h1">
    <a href="{{ homepage_url }}">
        {% block brand_title %}{{ shop_name }}{% endblock %}
    </a>
    <small> {{ shop_tagline }}</small>
</div>
```
_notice where the `{% endblock %}` tag_

Thanks for the nice work guys :)

**Comment by adarshraj365** [comment]
@RamezIssac  yes ! 
There is no need of  {% endblock %}
can i fix this ?
