### ISSUE TITLE
Potential dependency conflicts between django-oscar and django

### ISSUE THREAD

**Issue by NeolithEra** [django-oscar/django-oscar#3360]
Hi, as shown in the following full dependency graph of **_django-oscar_**, **_django-oscar_** requires **_django >=2.2,<3.1_** ， while the installed version of django (3.0.6) ，**_django-haystack 3.1.0_** requires **_django >=2.2_**.
According to Pip's “_first found wins_” installation strategy, **_django 3.0.6_** is the actually installed version.
Although the first found package version **_django 3.0.6_** just satisfies the later dependency constraint （**_django >=2.2_**), it will easily cause a build failure once the updated django-haystack introduces a higher version of django
According to the release history of **_django-haystack_**, it habitually upgrates **_django_** in its recent releases. For instance, **_django-haystack 2.7.0_** upgrated django’s constraint from **_>=1.8,<2.1 to >=1.11<2.1,_** ,**_django-haystack 2.8.0_** upgrated django’s constraint from **_>=1.11,<2.1 to >=1.11_**, and **_django-haystack 3.1.0_** upgrated django’s constraint from **_>=1.11 to >=2.2_**. 

### Dependency tree
```
django-oscar - 0.6.2
| +- django(install version:3.0.6 version range:>=2.2,<3.1)
| +- django-model-utils(install version:4.0.0 version range:*)
| | +- django(install version:3.0.6 version range:>=2.0.1)
| +- djangorestframework(install version:3.11.0 version range:>=3.3,<3.12)
| | +- django(install version:3.0.6 version range:>=1.11)
| +- django-haystack(install version:3.1.0 version range:>=3.1.0,<4.0.0)
| | +- django (install version:3.0.5 version range:>=2.2)
| | | +- asgiref (install version: version range:=3.2)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- netdiff(install version:0.7 version range:>=0.7.0,<0.8.0)
| +- openwisp-utils(install version:0.4.5 version range:>=0.4.3,<0.5.0) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Lose the version range of **_django_** to be **_>=2.2_**.
2.	Remove your direct dependency **_django_**, and use the **django** transitively introduced by **_django-haystack_**.
@codeinthehole  Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by solarissmoke** [comment]
@NeolithEra I'm not clear on what the issue here is?

> Lose the version range of django to be >=2.2.

Doing this would cause problems when the next release of Django becomes available, because Oscar will not have been tested with it, and yet advertises that it supports it. That Haystack does this seems to me an issue with Haystack.

> Remove your direct dependency django.

Depending on transient dependencies like this is a recipe for problems.

Moreover I don't see any conflict here. As it is currently Oscar requires Django `>=2.2,<3.1`, and Haystack requires `django>=2.2`. There is no conflict between these dependencies. 

By the time Haystack drops support for Django 2.2, Oscar will have added support for newer versions of Django - that is not going to happen for a long while.

**Comment by NeolithEra** [comment]
@solarissmoke Thanks for your feedback. 
An alternative solution is **_changing the version range of  **_django-haystack_** to be <=3.1.0_**, to avoid making pull requests again and again to update **_django_**. 
And maybe it is not an issue, if django-oscar always upgrades django-haystack in its new releases.
This is a warm prompt for the potential dependency conflicts between django-oscar and django.

**Comment by solarissmoke** [comment]
Thanks for the explanation. I don't think we have anything to worry about - Haystack is not frequently updated, and will not drop support for Django 2.2 until it is end of life, and at that point Oscar will also drop support for it, and update it's haystack dependency.
