### ISSUE TITLE
Documentation incorrect for custom Shop

### ISSUE THREAD

**Issue by pwalsh** [django-oscar/django-oscar#3371]
Found a bug? Please fill out the sections below.

### Issue Summary

The documentation at https://github.com/django-oscar/django-oscar/blob/master/docs/source/howto/how_to_disable_an_app_or_feature.rst#how-to-disable-an-apps-urls for customising the shop (specifically - disabling the dashboard), does not seem to be correct, and seems to be missing information/

### Steps to Reproduce

1. create a config.py at root of project
```
# myproject/config.py
from oscar.config import Shop
from oscar.core.application import OscarConfig

class MyShop(Shop):

    # Override the get_urls method to remove the URL configuration for the
    # dashboard app
    def get_urls(self):
        urls = super().get_urls()
        for urlpattern in urls[:]:
            if hasattr(urlpattern, 'app_name') and (urlpattern.app_name == 'dashboard'):
                urls.remove(urlpattern)
        return self.post_process_urls(urls)
```

2. Didn't do this part, as this seems outdated with how Django settings works nowadays:

```
# myproject/__init__.py
default_app_config = 'myproject.config.MyShop'
```

3. *not documented* - replaced `oscar.config.Shop` with `myproject.config.Shop` in `INSTALLED_APPS`

4. *not documented* - removed all Oscar dashboard apps (i.e.: `oscar.apps.dashboard.*`) from `INSTALLED_APPS`

Expected: server can run and dashboard is not bootstrapped

Actual: `LookupError: No installed app with label 'dashboard'.`
### Technical details

* Python version: 3.8.1
* Django version: 3.0.1
* Oscar version: c1cadba8f33b58fac2c87f374993c8b37a67bfa7

**Comment by pwalsh** [comment]
@solarissmoke @sasha0 

I guess, it makes sense. Removing the URLs requires the apps to be registered. So, in that case - how would I remove the dashboard completely (deregistering URLs is not a good solution as the code is still loaded - I simply don't want to load parts of Oscar that I don't want, like, the entire dashboard)

**Comment by solarissmoke** [comment]
Please post the full stack trace for the `LookupError`.

**Comment by pwalsh** [comment]
> Please post the full stack trace for the LookupError.

Not really a need. as per my comment in https://github.com/django-oscar/django-oscar/issues/3371#issuecomment-631378751 it is correct that there would be a LookupError - this is not really documentation to *disable an app* but rather to *disable an app's URLs* which is fine, just not what I want (as I don't want to load code I am not using, and the disable URLs approach requires "installing" the app to "find" the URLs to disable).

I will just modify the shop object more comprehensively, now I have checked the source, so, closing this for now.
