### ISSUE TITLE
Line.product should have a related_name argument 

### ISSUE THREAD

**Issue by jolob5l** [django-oscar/django-oscar#3372]
Hello, thank you for the framework, love it, but here're some thoughts

The product attribute of the AbstractLine model should have a related_name argument

For example, I want to count all the lines with some product

p = Product.objects.first()
p.orderitem_set.count()

I think it should be set by default
Let me know if I'm wrong, please, if I'm not, I'd like to contribute :)

**Comment by solarissmoke** [comment]
If a `related_name` is not explicitly specified, it defaults to [`FOO_set`](https://docs.djangoproject.com/en/3.0/topics/db/queries/#following-relationships-backward) where `FOO` is the source model name. So you can access the lines for any product with `p.line_set.all()`.
