### ISSUE TITLE
Performance Issue: _get_absolute_url() is taking long time with a lot of categories

### ISSUE THREAD

**Issue by FloridSleeves** [django-oscar/django-oscar#3373]
### Issue Summary
When using a new profiling tool PyLive to profile oscar, we find function _get_absolute_url() is taking a lot of time when there are thousands of categories. And time it takes is growing with the number of categories.

### Steps to Reproduce
1. Create thousands categories in sandbox
2. Load the page and it will become slower (2-3s to load main page when categories grows to 4000)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The category url does not change over time normally. And it's intensively used in nearly every product page twice (one in side bar, another in the drop-down list 'Browse Store').  So it's naturally that we use cache to cache the url result so we can reuse it over different page.

A simplest way is use Django cache to cache the generated url:
```
def _get_absolute_url(self, parent_slug=None):
    full_url = cache.get("pk="+str(self.pk))
    if full_url is None:
        full_url = reverse('catalogue:category', kwargs={
                'category_slug': self.get_full_slug(parent_slug=parent_slug),  'pk': self.pk
            })
    cache.set("pk="+str(self.pk), full_url)
    return full_url
```
When I test it out with PyLive to profile, it can improve the speed by 3x after cache all the urls.
### Technical details

* Python version: Python3.6.9
* Django version: 2.2.12
* Oscar version: 2.0
We use [PyLive](https://github.com/devopspp/pyliveupdate) for profiling.

**Comment by solarissmoke** [comment]
This was fixed in #2895 (Oscar 2.1)

**Comment by rik** [comment]
#2895 is already in Oscar 2.0 (see https://github.com/django-oscar/django-oscar/commit/4fa6709b9a5326d3f35acda97acabe0581d46adc tag details and https://github.com/django-oscar/django-oscar/commit/9da707eb9fe57af3635e4058d1153a3c81f9dfcc)

**Comment by solarissmoke** [comment]
Hmm OK, reopening to investigate further then. The caching was moved to `get_full_slug` so it's not immediately obvious to me why it should have had a performance impact.

**Comment by FloridSleeves** [comment]
Seems like #2895 solves the problem partly by cache the parent slug.
However, when there are a lot of categories, it still takes a long time to generate full url. And the _reverse()_ function in __get_absolute_url()_ is also expensive. In our profiling, it takes up to 40% of the total time for executing __get_absolute_url()_

**Comment by rik** [comment]
I think this issue might be because `oscar/catalogue/browse.html` displays [the whole category tree by default](https://github.com/django-oscar/django-oscar/blob/13a865eb95fccc02899ca62b814441f9cc432ba1/src/oscar/templates/oscar/catalogue/browse.html#L24). You should customise that template to restrict the depth that makes sense for your shop.

**Comment by FloridSleeves** [comment]
> I think this issue might be because `oscar/catalogue/browse.html` displays [the whole category tree by default](https://github.com/django-oscar/django-oscar/blob/13a865eb95fccc02899ca62b814441f9cc432ba1/src/oscar/templates/oscar/catalogue/browse.html#L24). You should customise that template to restrict the depth that makes sense for your shop.

Thanks for the confirmation and suggestion! I agree with your suggestion.
But I just wonder can we solve this problem directly in oscar to cache the generated url. Since in #2895 oscar already step out to optimize the performance when there are a lot of categories but partially solve this problem, we can cache the url so that we make no further hit on database. 

This does not have any negative effect when there is few categories but will help a lot when a lot of categories are added. Once the cache is warm up, it no longer need to access database to build such a category tree any more.

**Comment by rik** [comment]
I'll let the Oscar team decides if they want to cache `Category.get_absolute_url` as well. My opinion is that it is not an issue for most shops so there's no need for it in Oscar.

Remember, you can customise `Category` in your project to add this cache if you want.

**Comment by solarissmoke** [comment]
I tend to agree with @rik here. Being too aggressive with caching by default has potential to cause other problems and make debugging them harder. 

Also I don't think `get_absolute_url()` is the best place to do this caching. If you have a large category tree, you should probably do template caching in the places you render that tree in its entirety, which will be even more efficient than calling `get_absolute_url()` for thousands of categories (side note - would a tree containing thousands of categories really be usable/desirable to render all at once?). The respective templates in Oscar are easy to override.

**Comment by solarissmoke** [comment]
I think Oscar has an appropriate level of caching here - the default category tree in the templates is intended to be used for relatively small number of categories - if you have thousands then I cannot see a situation in which it would make sense to render the whole tree on every view like that - so projects with such structures would be expected to override the applicable templates.
