### ISSUE TITLE
Baskets can be stuck frozen

### ISSUE THREAD

**Issue by Larrik** [django-oscar/django-oscar#3382]
Found a bug? Please fill out the sections below.

### Issue Summary

If `self.handle_order_placement` has an exception besides `UnableToPlaceOrder`, the `restore_frozen_basket` method is never called.

### Steps to Reproduce

In my example, I overrode `OrderCreator.create_line_models` and had a rare error in there.

### Technical details

* Python version: 2.7.
* Django version: 1.11.
* Oscar version: 1.6.7.

###
I recognize this is not the latest version, and we're doing something a little outside of the norm. That said, `restore_frozen_basket` should probably be in a `finally` clause.

**Comment by solarissmoke** [comment]
Yeah, makes sense - we basically need to [duplicate this logic](https://github.com/django-oscar/django-oscar/blob/05e4594230013c50ddafdf7458d51fc4b71277b3/src/oscar/apps/checkout/views.py#L608-L616) in the try/except block for `handle_order_placement`.
