### ISSUE TITLE
Using existing shipping address submit button becomes "Saving..."

### ISSUE THREAD

**Issue by jayvdb** [django-oscar/django-oscar#3396]
When using an existing address in shipping_address.html, the submit button uses [`data-loading-text="{% trans 'Saving...' %}"`](https://github.com/django-oscar/django-oscar/blob/a75d6ee/src/oscar/templates/oscar/checkout/shipping_address.html#L42) in both branches of that `if`.

It feels a little odd to use "Saving..." here as a user because the address above it is already saved.

Maybe there is some other saving occurring at this point, but that isnt clear to the user given the context of the button text appearing after "Ship to this address" was pressed, and inside the frame around the shipping address.

I am not a UI person, so I dont have strong suggestions.  Other parts of the process use "Proceed"-based terminology, or "Submitting..", etc.  maybe that could be better.

**Comment by solarissmoke** [comment]
"Submitting..." sounds like an improvement. PR welcome if you have a few minutes.
