### ISSUE TITLE
Question: Would a PR for Django 2.2 compatibility in the 1.x branch be accepted?

### ISSUE THREAD

**Issue by khink** [django-oscar/django-oscar#3401]
### Issue Summary

We'd like to create a Django-Oscar 1.x version (based off 1.6.7) that supports Django 2.2. Would the maintainers be willing to accept a PR for this, and make a release?

### Background

We're in the process of upgrading our Django-Oscar+API-based application to a supported version of Django. Unfortunately, while 1.6.7 does support Django 2.1, it does not support 2.2.

So we are faced with a choice:

1. Upgrade to Django-Oscar 2
2. See if we can get Django-Oscar 1 to work with Django 2.2

It seems that the second option would require the least effort. We are expecting a lot of work from the Django-Oscar 2 upgrade, and the changes between Django 2.1 and 2.2 seem minor by comparison.

We'd like to know if the maintainers think that Oscar1.x + Django2.2 compatibility might be useful enough to cut a release. I'm also wondering why there is no such branch/release yet: There might be blocking issues that i'm not aware of, so i'm asking for insights as to what i might run in to. 

### Questions

1. Would a Oscar1.x + Django2.2 release be feasible?
2. Are you aware of blocking issues that make this hard to achieve?

**Comment by solarissmoke** [comment]
> Would a Oscar1.x + Django2.2 release be feasible?

Yes - happy to release this if you are prepared to do the work of making it compatible.

> Are you aware of blocking issues that make this hard to achieve?

I don't think there are any such issues. The reason it wasn't done is mainly one of capacity (i.e., the more active Oscar branches you maintain, the more work is involved), and we don't yet have an explicit [policy](https://github.com/django-oscar/django-oscar/issues/2675) on which versions are actively maintained other than the current one. If the community would benefit from 1.6.x supporting Django 2.2, and you can spend the time required on it, then let's do it. I would say however that 1.6.x is likely only to receive security patches after that.

**Comment by khink** [comment]
Thanks for your speedy reply.

I'm very happy to hear that such a release is feasible. We'll start work for a proper Django-Oscar release. 

> I would say however that 1.6.x is likely only to receive security patches after that.

Totally agreed. It's just that we can't free up the time for the Oscar 2 transition at the moment.

**Comment by jayvdb** [comment]
Fwiw, I have a Oscar 2.0.x on Django 3 branch , just backporting the Django 3 fixes, and has been in use for quite a while.  Likewise I could submit it to a Oscar 2.0 branch, if that is desirable.  It isnt as wild as #3403 - so understand if it isnt worth the support matrix effort.  We would be upgrading to 2.1 soon anyways, is the theory.

**Comment by solarissmoke** [comment]
https://pypi.org/project/django-oscar/1.6.8/
