### ISSUE TITLE
Sandbox - Module not found: 'oscar.apps.communication'

### ISSUE THREAD

**Issue by Benleroter** [django-oscar/django-oscar#3407]
Found a bug? Please fill out the sections below.

### Sandbox - Module not found: 'oscar.apps.communication'

Wanting to run the Sandbox app locally. Installed all as per instructions here: https://django-oscar.readthedocs.io/en/2.0.4/internals/sandbox.html

### Steps to Reproduce
$ sudo apt install python3-dev
$ git clone https://github.com/django-oscar/django-oscar.git
$ cd django-oscar
$ virtualenv --python=python3 oscar
$ source ./oscar/bin/activate
(oscar) $ pip3 install -r requirements.txt (see attached file)
(oscar) $ cd sandbox 
(oscar) $ sandbox
(oscar) $ python3 manage.py runserver
ModuleNotFoundError: No module named 'oscar.apps.communication'

[requirements.txt](https://github.com/django-oscar/django-oscar/files/4785864/requirements.txt)

I have checked the files 'django-oscar/src/oscar/apps/communication/apps.py' is present. I have run the whole process four times now with the same result.

### Technical details

Django 2.2.13
Python 3.8.2
oscar 2.0.4

**Comment by solarissmoke** [comment]
You are using incompatible versions of Oscar - cloning the sandbox from master of this repository (version 2.1b), and then installing Oscar version 2.0.4 in the requirements, which is the cause of your error. 

You have two options:

1. Clone the `releases/2.0` branch of the repository: `git clone https://github.com/django-oscar/django-oscar.git@releases/2.0`. 

2. Install the development version of Oscar (`pip install -e .` when in the root of the repository).

The `make sandbox` command does the second option for you (along with a bunch of other stuff).
