### ISSUE TITLE
place_order() is giving surcharges error

### ISSUE THREAD

**Issue by iamsobanjaved** [django-oscar/django-oscar#3464]
### Issue Summary

`OrderCreator().place_order(  order_number=number, user=user,  basket=basket, shipping_address=shipping_address,shipping_method=shipping_method,  shipping_charge=shipping_charge, billing_address=billing_address, total=total, surcharges=surcharges, **kwargs)`

This statement is giving following error.

`*** TypeError: Direct assignment to the reverse side of a related set is prohibited. Use surcharges.set() instead.`

### Technical details

* Python version: 3.5.2
* Django version: 2.2
* Oscar version: 2.1

**Comment by solarissmoke** [comment]
I think you'll need to provide more information here - specifically the *full* stack trace for the error, and any context in terms of methods that you have overridden in your project. The most likely issue is that you have overridden `create_order_model` and not updated it to handle the new `surcharges` argument.
