### ISSUE TITLE
Add ability to make wishlists public/shareable

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#3509]
The existing wishlist functionality in Oscar is incomplete - the models allow for wishlists to be "public" or "shared", but the UI does not allow for making a wishlist public/shared. 

1. *Public wishlists* - we should llow users to make wishlists "public" which means that they can share links to this with others. My feeling is that "public" in this case should still require the viewer to be logged-in, so that these views are not exposed to abuse and SEO implications. This should be relatvely straighforward to implement, and has a clear use case.

2. *Shared wishlists* - it seems the original intention behind this was to have lists that can collaboratively be managed by multiple users. The use case for this isn't clear to me, and I think needs elaboration before we can implement.

**Comment by Andruten** [comment]
I've implemented the public wishlist in a project and one of the requirements is public wishlists can be shared by link and email with people without account (some kind of influencers' wishlists). So public wishlists is a really interesting feature.

**Comment by joeyjurjens** [comment]
This has been implemented in #3905
