### ISSUE TITLE
Add SEO fields to product and category models and make editable in the dashboard

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#3510]
There are a few SEO components that we regularly find clients asking for the ability to control on product and category pages:

1. Meta title
2. Meta description
3. Slug

For products, slug, meta title and description are all auto-generated from the product title/description, with no option to override any of these. While this is fine a lot of the time, Oscar should provide the ability to override these.

For categories, meta title and description are also auto-generated from the product title/description, and there is no option to override.

I think we should have a "Search Engine Optimisation" tab on the dashboard edit views for both of these, which allow override of these parameters.

**Comment by SameeranB** [comment]
Hey @solarissmoke ,
Just wanted to confirm that we are talking about the `AbtractProduct` and `AbstractCategory` classes from `src/oscar/apps/catalogue/abstract_models.py` right?

Also, will this issue involve changes in the model and changes to the frontend (dashboard)?

**Comment by solarissmoke** [comment]
@SameeranB yes, but note that there is [already a PR](https://github.com/django-oscar/django-oscar/pull/3522) for this feature under review.

**Comment by SameeranB** [comment]
Aah... that's great. No issues... I'll look for some other issue to resolve.
