### ISSUE TITLE
Add "active" field to stock records

### ISSUE THREAD

**Issue by farooqaaa** [django-oscar/django-oscar#3569]
Currently the only way to temporarily disable a stock record is to delete it but you lose the SKU, price and stock details. If you want to reactivate it, you will need those details again.

This can be avoided by adding an "active" field to stock records. If it's set to true by default, it won't break anything and there's no need to modify or write a lot of new tests.

I am willing to implement this but want to discuss it first. How does this sound?

**Comment by solarissmoke** [comment]
My initial thoughts are that this can be achieved relatively easily at project level by forking the partner app - you would add an `active` field and then just customise your pricing strategy to exclude inactive records. That being the case, I am not sure that Oscar needs to do this itself as it adds complexity to the default implementation which most projects would not use.

**Comment by farooqaaa** [comment]
Yeah, that makes sense. Thanks!
