### ISSUE TITLE
3.0a Release Category Navigation

### ISSUE THREAD

**Issue by daniel-butler** [django-oscar/django-oscar#3570]
### Issue Summary

When adding more than one product category they are not treated as a nav-list. Below is an Every Day and Seasonal > Thanksgiving product category lists. 

This only happens when on XL Screen sizes

![image](https://user-images.githubusercontent.com/22578954/98894127-17da8280-2472-11eb-96c5-7b1cf8f020fa.png)

*The colors have been adjusted from the defaults

### Steps to Reproduce

pip install django-oscar==3.0a

### Technical details

* Python version: 3.8.6
* Django version: 3.1.3
* Oscar version: 3.0a

**Comment by solarissmoke** [comment]
I can't reproduce this on the sandbox - see https://latest.oscarcommerce.com/en-gb/catalogue/ where the categories are correctly separated. Are you sure you don't have some custom styling which is affecting this?

**Comment by daniel-butler** [comment]
That was the issue. Sorry about that. I changed the `page_inner` value from 30px to 15px which threw it off.
