### ISSUE TITLE
UnicodeEncodeError with render_product if generated template paths contain non-ascii characters

### ISSUE THREAD

**Issue by stanflow** [django-oscar/django-oscar#3578]
### Issue Summary

We're getting a UnicodeEncodeError at the /catalogue/-url. I hope this information is sufficient:

**Notice that the URL is wrong in the title of this issue. It should be just /catalogue/**

``
Exception Value: | 'ascii' codec can't encode character '\xe5' in position 136: ordinal not in range(128)
/home/*****/env/lib/python3.8/site-packages/django/template/loaders/filesystem.py in get_contents, line 23
``

``
home/*****/env/lib/python3.8/site-packages/oscar/templatetags/product_tags.py in render_product
...
template_ = select_template(names) 
``

**Local vars**:
``
names | ['oscar/catalogue/partials/product/upc-60 gsm Soft NW Hydrofob Grå -800.html',  'oscar/catalogue/partials/product/class-carriers.html',  'oscar/catalogue/partials/product.html']
``

### Steps to Reproduce

Unfortunately I don't know how reproduce this since I haven't been administrating the shop at all.

### Technical details

* Python version: 3.7.9
* Django version: 3.0
* Oscar version: 2.1

**Comment by solarissmoke** [comment]
The problem is that the UPC you have defined for this product contains non-Ascii characters (å) in this case - this is being passed to the template loader and failing. This is probably something that can be handled better in Oscar, but the quick fix for you is just to correct your UPC ("60 gsm Soft NW Hydrofob Grå -800" is not an actual product code - looks like someone has just pasted the product title into that field).

**Comment by stanflow** [comment]
@solarissmoke Yep. Poor administration of the shop. :) But some validation of the product code there makes sense. I guess.

**Comment by solarissmoke** [comment]
I looked into this a bit more, and discovered that by [default](https://docs.djangoproject.com/en/3.1/ref/templates/api/#django.template.Engine) Django's template engine uses a utf-8 charset - and when that is the case then having unicode characters in a template name doesn't cause any problems (you can verify this on the sandbox). 

The only way to trigger the error posted above seems to be configure a template engine with a different `file_charset`. I think that's quite an edge case, and not one worth fixing here. 

See also [this Django ticket](https://code.djangoproject.com/ticket/29817) for some related discussion.

**Comment by stanflow** [comment]
@solarissmoke As far as I know I'm just using the default Django template engine.
