### ISSUE TITLE
DateTimePickerInput setting initial value for empty fields

### ISSUE THREAD

**Issue by alstr** [django-oscar/django-oscar#3590]
### Issue Summary

I have found that when using a `DateTimePickerInput` in the dashboard, the field is always automatically initialised with the current date/time, even when it is not a required field, and even when editing an item where the field was saved empty.

This is not so much a problem when first creating an item, but when you go back to edit something later, unless you clear the default value it is saved with the current date. This could easily be overlooked and cause problems.

### Steps to Reproduce

1. Create a basic model that has an optional date field e.g. `optional_date = models.DateTimeField(blank=True, null=True)`.
2. Create a basic dashboard `CreateView` where the `form_class` is a `ModelForm` for the above model. Set the field widget to `DateTimePickerInput`.
2. Fill out the form. Notice the date field is auto-populated. Clear the field and save.
3. Create and go to the `UpdateView`. The date field is re-populated even though the field was saved as `None`.

### Technical details

- `django-oscar` v3.0a0
- Setting the initial value to empty when intialising the `ModelForm` does not work as the behaviour is caused by the line `'initialDate': new Date(new Date().setSeconds(0))` in `dashboard.js`. I have added my own JS workaround to remedy it, but the default behaviour seems a little confusing to me.

**Comment by solarissmoke** [comment]
Thanks - I think the fix is probably just not to set `defaultDate` in the datetimepicker configuration in JS. PR appreciated if you have time.
