### ISSUE TITLE
Refactor voucher creation in the dashboard to allow greater flexibility

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#3614]
### Issue Summary

The voucher app provides a very flexible implementation of voucher functionality, where multiple offers can be associated with a voucher. But the dashboard interface for managing vouchers hides this flexibility and only allows the creation of vouchers with a single offer. Meanwhile, on the offer side, only site-wide offers can be created and edited through the dashboard.

### Proposal

I propose to refactor the voucher functionality as follows:

1. Allow CRUD of all types of offer in the dashboard, making it easy to identify the type of the offer (site-wide, voucher, session, user). We can provide a tabbed interface to see the offers of each type. 

    (By default, session and user offers are not applied anywhere - a future enhancement would be to allow associating user offers with particular users/groups of users, instead of requiring projects to implement this themselves.)

2. Refactor the existing voucher creation functionality so that instead of creating a single offer on the fly, the administrator instead selects one or more existing offers (of type voucher) to add to the voucher. This allows the creation of complex vouchers with a combination of offers.

This provides a much more powerful and flexible interface to the voucher functionality that already exists.

**Comment by sasha0** [comment]
Agree.

**Comment by specialunderwear** [comment]
Yes that would be nice
