### ISSUE TITLE
sandbox need long time to load in localhost

### ISSUE THREAD

**Issue by TechComet** [django-oscar/django-oscar#3617]
* Python version: Run `python --version`.
Python 3.8.5

* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
Version: 3.1.5

* Oscar version: Look in your requirements.txt, or run `pip show django-oscar | grep Version`.
Version: 3.0b1

why home page for sandbox need long time to load in localhost?
Very slow to write cache

**Comment by solarissmoke** [comment]
This is because `django-debug-toolbar` is enabled on the sandbox by default - there is a note about this and how to disable it in the [documentation](https://django-oscar.readthedocs.io/en/3.0a/internals/sandbox.html#run-the-sandbox-locally).
