### ISSUE TITLE
Django date format settings ignored

### ISSUE THREAD

**Issue by krzysztofjeziorny** [django-oscar/django-oscar#3635]
Setting Django's [date format](https://docs.djangoproject.com/en/3.1/ref/settings/#date-format) to `%d.%m.%Y` (or any other with possible [strings](https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#std:templatefilter-date)) renders the `%` character, as in the list of the offers' restriction in the Dashboard.

<img width="325" alt="date formats" src="https://user-images.githubusercontent.com/872730/106893754-491fc300-66ee-11eb-9831-e529bb82efdc.png">

The `USE_L10N = True` setting is being ignored, showing the time in 12-hour format. When USE_L10N is True, the locale-dictated format has higher precedence and should be applied instead.
I'm in Austria (CET, language code `de-at`).

<img width="276" alt="date formats de" src="https://user-images.githubusercontent.com/872730/106893737-43c27880-66ee-11eb-9584-33c807c3ecd7.png">

It's not the browser language issue, as it's the same for an `en-us` and `de-de` versions of newest Firefox.

### Technical details

* Python version: 3.7.3
* Django version: 2.2.18
* Oscar version: 3.0

**Comment by solarissmoke** [comment]
I think you are confusing two different things. Django's `DATE_FORMAT` setting does not accept formatting that uses the `%` sign - the [link you provided](https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#std:templatefilter-date) shows all the available formatting options.

You've mixed it up with `DATE_INPUT_FORMATS` which uses a [different format entirely](https://docs.djangoproject.com/en/3.1/ref/settings/#date-input-formats).
