### ISSUE TITLE
account signup requires EMAIL_BACKEND in settings.py

### ISSUE THREAD

**Issue by JohnRomanski** [django-oscar/django-oscar#3636]
### Issue Summary

Doing a clean install and following the instructions in the docs, I got an error.

```[Errno 61] Connection refused```

it was after a bit of googling that I found the root cause and solution here, EMAIL_BACKEND is a prerequisite to the site functionality running.

https://groups.google.com/g/django-oscar/c/gc0vwdIoyQY/m/xtxvFaQyCgAJ
```
   EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
```

I would recommend adding this to the docs if it is in fact required to run.

### Steps to Reproduce

- remove the EMAIL_BACKEND directive from the settings.py
- attempt to signup for an account

### Technical details

* Python version: Python 3.9.1
* Django version: Version: 3.1.6
* Oscar version: Version: 3.0

**Comment by solarissmoke** [comment]
`EMAIL_BACKEND` is not required - it [defaults to the SMTP backend](https://docs.djangoproject.com/en/3.1/ref/settings/#email-backend). You will get a connection refused error if you have no local SMTP server set up. 

I don't think that is an Oscar-specific issue as it's how all Django projects would work out of the box. I'm sure there has been debate about changing Django's defaults, but I don't think it is an issue that Oscar needs to weigh in on.

**Comment by JohnRomanski** [comment]
Thanks for the great and immediate feedback. You are correct of course
```
EMAIL_BACKEND | 'django.core.mail.backends.smtp.EmailBackend'
```
Would it be appropriate to use `fail_silently` or to show a more meaningful error message?

**Comment by solarissmoke** [comment]
I don't think `fail_silently` would be an appropriate default, given that sending emails is an important activity performed by Oscar in several places and you'd probably want to know if something went wrong with that. 

Oscar could potentially catch any exception raised by the backend. I think the question here would be whether we can add any useful information that the original exception/trace doesn't contain. What was the full stack trace for the error you got?

**Comment by JohnRomanski** [comment]
Request Method: | POST
-- | --
http://127.0.0.1:8000/accounts/login/
3.1.6
ConnectionRefusedError
[Errno 61] Connection refused
/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py, line 831, in create_connection
/Users/john/Library/Caches/pypoetry/virtualenvs/discauction-demo-WPUZWD28-py3.9/bin/python
3.9.1
['/Users/john/src/django-oscar/frobshop',  '/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',  '/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9',  '/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',  '/Users/john/Library/Caches/pypoetry/virtualenvs/discauction-demo-WPUZWD28-py3.9/lib/python3.9/site-packages']
Thu, 04 Feb 2021 15:38:19 +0000

here is the FULL output
https://dpaste.com/A53WU4AXD

Yes, technically, I could spend time on this to read and parse the whole error message. The `[Errno 61] Connection refused` is a bit of a dead end for googling.

I was following the install instructions step by step. I don't think that it would be an issue to add a line to the doc including this information, when it's something that stopped me in my tracks as a first time user.

**Comment by glavery** [comment]
you can use `django.core.mail.backends.console.EmailBackend` for development

**Comment by JohnRomanski** [comment]
thanks @glavery, I did find the solution through googling. I just thought that this might be added to the docs, as it would have saved me an hour as a first time user.

SAFE to close this issue. Hopefully this will also help the next user who runs into this.
