### ISSUE TITLE
Warning: NullBooleanField is deprecated in Django 3.1

### ISSUE THREAD

**Issue by JohnRomanski** [django-oscar/django-oscar#3637]
### Issue Summary

NullBooleanField is deprecated in Django 3.1. Running any manage.py command throughs a non-critical warning.

```
WARNINGS:
catalogue.ProductAttributeValue.value_boolean: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use BooleanField(null=True) instead.
```

### Suggested solution

The fix seems pretty straightforward
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/abstract_models.py#L1043

```
-    value_boolean = models.NullBooleanField(_('Boolean'), blank=True, db_index=True)
+   value_boolean = models.BooleanField(_('Boolean'), blank=True, null=True, db_index=True)
```

But I am not sure of the impact to the migrations, etc. In my limited testing I have not yet been able to override and test this.

### Technical details

* Python version: Python 3.9.1
* Django version: Version: 3.1.6
* Oscar version: Version: 3.0

**Comment by ml394** [comment]
Hey @solarissmoke - just wondering if this has been included in an official release yet? I notice the new migration isn't in the repository for versions 3.0.1 and 3.0.2 and the non-critical warning still appears.

https://github.com/django-oscar/django-oscar/tree/3.0.2/src/oscar/apps/catalogue/migrations

- Python 3.8.5
- Django 3.1.9
- Oscar 3.0.2

**Comment by solarissmoke** [comment]
@ml394 it's part of 3.1 which is currently in beta.
