### ISSUE TITLE
No module named 'oscar.apps.customer.notifications' when installing in Django 3

### ISSUE THREAD

**Issue by serguitus** [django-oscar/django-oscar#3641]
Found a bug? Please fill out the sections below.

### Issue Summary

I'm trying to install django-oscar according to instructions in docs. after setting everything and trying to test site, I get a message "No module named 'oscar.apps.customer.notifications'" trying to access any page of the site after logging in

Thank you in advance for your help and hard work

### Steps to Reproduce

Just did a fresh install and started dev server. did login and got 500 on all pages

### Technical details

* Python version: 3.6.9
* Django version: 3.1.4
* Oscar version: 3.0

**Comment by solarissmoke** [comment]
You've used the instructions for version 2.6 of Oscar, while installing version 3.0 (`customer.notifications` was moved in Oscar 3). See also https://github.com/django-oscar/django-oscar/issues/3407#issuecomment-644688612 .

**Comment by serguitus** [comment]
Oops, Thank you for your fast answer. although I changed to instructions of v3.0 after a couple steps, I overlooked a change in context_processors.
Great job with Oscar!  I hope to do some contributions to the project in a near future. :-)
