### ISSUE TITLE
Add possibility to override voucher.utils.get_offer_name

### ISSUE THREAD

**Issue by bruecksen** [django-oscar/django-oscar#3652]
It would be nice to add the possibility to override the `get_offer_name` method to allow for a custom display name of the conditional offer. I found it not useful to add `Offer for voucher 'Voucher name'` as a default to this and would like to customize it without the need to override all Views which use this function.

**Comment by solarissmoke** [comment]
That function is going to be removed entirely as part of the changes in https://github.com/django-oscar/django-oscar/pull/3632

**Comment by bruecksen** [comment]
@solarissmoke ah super, thanks!
