### ISSUE TITLE
Load customer.history with get_class

### ISSUE THREAD

**Issue by Chadys** [django-oscar/django-oscar#3675]
### Issue Summary

All functions of customer.history are loaded by using direct import instead of `get_class`, making it very impractical to override.

### Steps to Reproduce

Use cases are for example if you want to change how the object are loaded when getting recently viewed products (I wanted to use search backend instead of DB), or if you want to change some properties of the oscar_history cookie (I wanted to set `samesite` to Lax). Not all use cases can be anticipated, hence this is a good candidate for a `get_class` encapsulation. I think, contrarily to its name, that `get_class` also works for module import, but history module could also be converted to a class with static methods, what would you prefer? I can do the pull request then.

### Technical details

* Python version: 3.9.1
* Django version: 3.1.6
* Oscar version: 3.0.0

**Comment by solarissmoke** [comment]
Thanks @Chadys - this should definitely be loaded dynamically. As you note `get_class` does in fact work with modules, but I think moving these functions to a class with static methods would be helpful and more extensible in future. PR would be appreciated.
