### ISSUE TITLE
Line referense depends on options order

### ISSUE THREAD

**Issue by Kudria** [django-oscar/django-oscar#3690]
Basket line referense depends on options order. This may lead to creation additioanal line instances while adding products with same options, instead of line.quantity increase.

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/basket/abstract_models.py#L360

This behaviour may not be an issue while using built-in forms and views, but it resulted in hard to find bug my project.

**Comment by solarissmoke** [comment]
Fixed in #3691.
