### ISSUE TITLE
Missing translation tag in e-mails

### ISSUE THREAD

**Issue by Anto59290** [django-oscar/django-oscar#3693]
### Issue Summary

When using Oscar in another language, some texts in the e-mails are not translated.

### Steps to Reproduce

- Configure oscar in any other language than English
- Make oscar send the reset password email
- You can see that in the email the CTA is still "Reset Password"

### Technical details

Source of the issue: 

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/communication/emails/commtype_password_changed_body.html#L20

This code is missing a "trans" tag.

Same issue in a few other places:

https://github.com/django-oscar/django-oscar/blob/master/src/oscar/templates/oscar/communication/emails/commtype_email_changed_body.html#L20

https://github.com/django-oscar/django-oscar/blob/1442cb734ec542459a31cbd9c174bf8817dcfeea/src/oscar/templates/oscar/communication/emails/commtype_password_reset_body.html#L20

**Comment by solarissmoke** [comment]
Thanks - PR to fix this would be appreciated if you have time.

**Comment by solarissmoke** [comment]
Fixed in https://github.com/django-oscar/django-oscar/commit/04cd6a4fc750db9310147d96776f06fe289269bf
