### ISSUE TITLE
Person's title translations giving confusing choices in other languages

### ISSUE THREAD

**Issue by krzysztofjeziorny** [django-oscar/django-oscar#3696]
The same translations of the English terms in address book's dropdown list of titles are causing confusion in other languages.

The original choices in English: 

https://github.com/django-oscar/django-oscar/blob/1a3372e1728d7b464693da6c78525ef4f13176a1/src/oscar/apps/address/abstract_models.py#L22

are being translated to a same term:  Miss/Mrs/Ms turns Frau/Frau/Frau in German or Mlle/Mme/Mme in French or Panna/Pani/Pani in Polish. It's impossible to differentiate the title chosen.

https://github.com/django-oscar/django-oscar/blob/1a3372e1728d7b464693da6c78525ef4f13176a1/src/oscar/locale/de/LC_MESSAGES/django.po#L45-L55

<img width="622" alt="Screenshot 2021-04-28 at 11 02 43" src="https://user-images.githubusercontent.com/872730/116380855-a5d5da00-a814-11eb-9065-9cdfc0df3801.png">

One can try it out with different languages in the address book in the [sandbox](https://latest.oscarcommerce.com/en-gb/accounts/addresses/add/).

I'd propose, instead of searching for direct translations, that could be difficult or awkward to use ("panna" in Polish or "Fräulein" in German for Miss are rather old-fashioned and not being used often), we leave just one term for a woman, hopefully it's sensible and inclusive to all in question.

**Comment by solarissmoke** [comment]
Hah, that's a fun one. 

I am inclined to suggest we go even further and remove the title field from the address forms entirely (we'd have to leave the field in the models in case projects want to use it). I agree with the [UK Government Design System](https://design-system.service.gov.uk/patterns/names/) advice on this:

> Avoid asking users for their title.
> 
> It’s extra work for them and you’re asking them to potentially reveal their gender and marital status, which they may not want to do.
> 
> It’s also hard to predict the range of titles your users will have. If you have to ask for someone’s title, use an optional text input not a select.

I don't think the title is really a useful/necessary field and a delivery address is perfectly usable without it.

**Comment by krzysztofjeziorny** [comment]
I think you're right. The current choices are also a little limited (for example I'd need also a 'company'), so it's better to remove it entirely.

**Comment by SakshiUppoor** [comment]
@solarissmoke May I work on this issue?

Also, I came across this property called `salutation`:
https://github.com/django-oscar/django-oscar/blob/27fe44a177b52aaa2299767ac7d879d3c130352d/src/oscar/apps/address/abstract_models.py#L319-L326

If `title` is removed from `salutation`, it becomes redundant as `name` property is serving the same purpose:
https://github.com/django-oscar/django-oscar/blob/27fe44a177b52aaa2299767ac7d879d3c130352d/src/oscar/apps/address/abstract_models.py#L328-L330

So, should all references to `salutation` be removed as well?

**Comment by solarissmoke** [comment]
@SakshiUppoor yes, please do. 

The only change required here is to remove the `title` from the address forms. We're not modifying the model itself - so that if projects still want to use the title they can. Thus properties such as `salutation` will also need to remain.
