### ISSUE TITLE
Feature request: Disable checkout preview step

### ISSUE THREAD

**Issue by denisvlr** [django-oscar/django-oscar#3719]
During checkout, it woud be great to be able to disable/skip the "preview" step.
After the user submits their payment info, the order is automatically validated, the user is redirected to the confirmation page.

Is it possible today?

Otherwise, could you suggest general guidance on how to implement it?
(I'm looking into implementing this on our project, and why not submit a PR if it makes sense).

**Comment by confuzeus** [comment]
You can implement this by playing around with the checkout app a little.

**Comment by solarissmoke** [comment]
This can be achieved by forking the `checkout` app and overriding the `PaymentDetailsView` to suit the workflow you want to handle - for example if `preview=True` you can redirect directly to another view.
