### ISSUE TITLE
Add is_ajax helper to utils.py

### ISSUE THREAD

**Issue by SaturnFromTitan** [django-oscar/django-oscar#3740]
Django 3.1 deprecated the `HttpRequest.is_ajax` method as it relies on a jQuery-specific way of signifying AJAX calls.

For most Oscar projects that's probably ok though, as they only use jQuery.

I see that in the current codebase `self.request.is_ajax()` was replaced by the less readable
```
self.request.headers.get('x-requested-with') == 'XMLHttpRequest'
```

I suggest adding a helper to `core/compat.py` to restore the old behaviour. Apart from readability that would enable oscar projects to check for AJAX requests in a consistent way with the built-in code.

I'm thinking of
```
def is_ajax(request):
    """
    Django 3.1 deprecated the  HttpRequest.is_ajax method as it relies on
    a jQuery-specific way of signifying AJAX calls.

    https://docs.djangoproject.com/en/3.1/releases/3.1/#id2
    """
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
```

I'm happy to submit a PR for this ✌️

**Comment by jwayodi** [comment]
@SaturnFromTitan This sounds like a good idea. Please make the PR, adding the helper to `core/utils.py` (`core/compat.py` is for stuff we ideally want to remove one day).
