### ISSUE TITLE
Event Handler extra kwargs arguments 

### ISSUE THREAD

**Issue by akash-vns** [django-oscar/django-oscar#3749]
i'm using the django-oscar from couple of months and found something need to be modify.

### Issue Summary 
In the EventHandler (of order  processing)  there is no way to send extra (kwargs) arguments ,
always need to copy whole function from where ever it's initiated and try to send extra data to EventHandler class.

 but it would be great to have something like Django generic views method  (```def get_form_kwargs()``` )  and pass the extra kwargs to EventHandler class.

I'm happy to submit a PR for this.

**Comment by solarissmoke** [comment]
PR welcome!

**Comment by akash-vns** [comment]
Helllo @solarissmoke 

as i mentioned the improvement,

i raise PR  for the same. (PR https://github.com/django-oscar/django-oscar/pull/3752)
it's passed all test cases and coverage the whole new mixin file (created in order app).

i'm contributing first time,
and i followed all steps that mentioned in oscar-contibution doc.

so , please guide me  what i have need to  do get the approval.

**Comment by solarissmoke** [comment]
Fixed in #3752.
