### ISSUE TITLE
No Paypal packages for paypal payment oscar > 3

### ISSUE THREAD

**Issue by Bastilla123** [django-oscar/django-oscar#3764]
Found a bug? Please fill out the sections below.

### Issue Summary

Both Packages what i know Django Oscar paypal and Django Oscar docdata are both not oscar > 3 compatible.

### Steps to Reproduce

Both Packages what i know Django Oscar paypal and Django Oscar docdata are both not oscar > 3 compatible. There are also in github from packages issues are open but since month not reactions from developers. So i think both packages are death...

In Django oscar docdata payment details html is not implemented so this package don't work.

Have anyone a solution for paypal payment for oscar > 3.

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Oscar version: Look in your requirements.txt, or run `pip show django-oscar | grep Version`.

**Comment by sasha0** [comment]
Please submit issues, relevant to the specific Oscar packages in the respective issue trackers, since the above is not relevant to the Oscar itself.
