### ISSUE TITLE
OrderFactory.date_placed is inconsistent with other fields

### ISSUE THREAD

**Issue by sephii** [django-oscar/django-oscar#3767]
### Issue Summary

Creating an order with `OrderFactory(date_placed=...)` doesn’t actually create the order with the given date, but creates the order and then assigns the given date without saving it. This is inconsistent with the other fields, and yields unexpected results.

I’ve noticed [this field is explicitly removed from the kwargs](https://github.com/django-oscar/django-oscar/blob/d076d04593acf2c6ff9423e94148bb491cad8bd9/src/oscar/test/factories/order.py#L87) so I guess there’s a reason to do it like that? If not, I suggest removing this special case.

### Steps to Reproduce

```python
order_line = OrderLineFactory(order__date_created=datetime.date(2020, 1, 1))
print(order_line.order.date_created)  # Shows 2020-01-01
print(OrderLine.objects.filter(order__date=datetime.date(2020, 1, 1))  # Doesn’t return anything
order_line.order.refresh_from_db()
print(order_line.order.date_created)  # Shows the current date
```

To get it working as expected, you need to first create the order, save it, and then set it as related object, which is kind of annoying:

```python
order = OrderFactory(date_created=datetime.date(2020, 1, 1))
order.save()
order_line = OrderLineFactory(order=order)
```

### Technical details

* Python version: 3.8.5
* Django version: 2.2.24
* Oscar version: 2.1.1

**Comment by solarissmoke** [comment]
Seems like this logic was created [at the same time](https://github.com/django-oscar/django-oscar/commit/4ac7e830bf0b7270b1400141120e586fabbe2dae) as the factory itself - I can't see any obvious reason why. Agree that we should drop it. PR welcome if you have time.

**Comment by sephii** [comment]
Sure, here you go. :) The tests seem to be passing, so I’m not sure why it was done like this in the first place.
