### ISSUE TITLE
IDEA: no need for automatic stock allocations with new order?

### ISSUE THREAD

**Issue by xplsek03** [django-oscar/django-oscar#3778]
My order processing pipelines presumes that when the order is placed ( _order.utils.place_order()_ ), no stockrecord allocations are made. Now the part of place_order method responsible for creating stockrecord allocation is:
```
for line in basket.all_lines():
    self.create_line_models(order, line)
    self.update_stock_records(line)
```
But shouldn't this kind of a functionality be project-agnostic - separated to its own method and put away from _place_order_? If project relies on _EventHandler_ with changing stock numbers, it has to be overriden. Or maybe there is a different way how to place order without allocations?
Thanks for opinion.

**Comment by Dihfahsih1** [comment]
@solarissmoke  please come and throw more light on this issue, i trust you in clarifying oscar issues with insightful explanations

**Comment by solarissmoke** [comment]
It is a bit of a nuisance that Oscar allocates stock by default, but doesn't by default clear or consuming those allocations. I think removing this default allocation completely is likely to cause problems for projects that rely on it, but I don't have an objection to making it easier to disable this by exposing a setting to turn it off. PR welcome if you have time.

**Comment by xplsek03** [comment]
Definitely will look into it when i have little free time.
