### ISSUE TITLE
ProductAttribute.code should be a unique field

### ISSUE THREAD

**Issue by odunybrad** [django-oscar/django-oscar#3785]
### Issue Summary

The product attribute should have a unique code. 
You can only assign one attribute with that code in the dashboard-product anyway. 

### Steps to Reproduce

1. In dashboard, go to `product-type` - `product attributes` page: _/dashboard/catalogue/product-type/1/update/_
2. Add two product attributes with the same name. (I use name att1 and type text.)
3. Save the form. Both attributes with the same code are saved and shown on the page. 
4. Go to one `dashboard/products` page for that product class, _/dashboard/catalogue/products/8/?upc=&title=shirt_, only one attribute name is shown on the form. 
5. Note that even I create attributes with different types, only one attribute of that code will be shown on the `dashboard/products` page. 

![Screen Shot 2021-10-14 at 11 30 32 AM](https://user-images.githubusercontent.com/11536831/137376274-b0b32263-f2cd-492e-bbef-dcd8fedfa802.png)

![Screen Shot 2021-10-14 at 11 30 14 AM](https://user-images.githubusercontent.com/11536831/137376244-875b59c7-7ced-40b4-b4da-690479c8ea0e.png)

#### Expected result:
* Give Exception when saving the attribute - "Duplicate product attributes code / attributes with this code already exists." 
* Enforce the `uniqueness` of `AbstractProductAttribute.code`. This is a SlugField. 
* Another way is to enforce the unique_together of (code, type), while the data retrieval part needs to be updated as well. 
* I can work on the PR for this issue, please let me know. 

#### Cause
Here have the assumption that `attribute.code` should be unique. 

```python
File: src/oscar/apps/dashboard/catalogue/forms.py
    def set_initial_attribute_values(self, product_class, kwargs):
        ...
        for attribute in product_class.attributes.all():
            try:
                value = instance.attribute_values.get(
                    attribute=attribute).value
            except exceptions.ObjectDoesNotExist:
                pass
            else:
                kwargs['initial']['attr_%s' % attribute.code] = value
```

### Technical details

* Python version: 3.9.7
* Django version: 3.2.7
* Oscar version: master

**Comment by joeyjurjens** [comment]
> We cannot globally enforce uniqueness of attribute codes, because Oscar permits reusing the same attribute code on different product types (and this can be useful to be able to do). I think the solution here would be to add validation on the formset for any given product class, to ensure that a code isn't repeated for that product class. PR welcome for this - note that it will be a bit messy to properly handle validation of deleted rows etc.

Can't we just add`unique_together = ('code', 'product_class',)` on the ProductAttribute model?

**Comment by solarissmoke** [comment]
No, for the reason I mentioned in my comment: Oscar permits reusing the same attribute code on different product types. Imagine you have 20 product types which all share one attribute - Oscar currently allows that and it is (from my experience) a common use case.

**Comment by joeyjurjens** [comment]
Not sure if I'm misunderstanding you, but I understand the reusing the same attribute code on multiple product types is common. However, if you add `unique_together = ('code', 'product_class',)` on the ProductAttribute model's Meta class, it prevents you from using the same code for the product type you're editing. You can still use the same code on other product types.

**Comment by solarissmoke** [comment]
My apologies, you're right and I misunderstood - `unique_together` as you describe would work.
