### ISSUE TITLE
Add support for secondary versions of the same product

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#379]
We need to support projects which sell new and second-hand versions of the same UPC.  

Since Oscar has a unique constraint on UPC, one way to do this would be to use the parent-child structure that is normally used for variant products.  We can have the new product be the parent, with its own stock record, and have the second-hand versions be variants.

This means the second-hand versions won't be visible when browsing which is good.

This may require some re-working of the product details page to show options correctly. 

Tasks:
- Render product detail page using radio buttons in a table to show variants, prices and availability.

**Comment by specialunderwear** [comment]
This can allready be done as proven here: https://latest.oscarcommerce.com/en-gb/catalogue/django-t-shirt_8/
