### ISSUE TITLE
Custom group prices

### ISSUE THREAD

**Issue by thecodeiot** [django-oscar/django-oscar#3797]
In a lot of ecommerce frameworks, customer group prices exists. Or even specific prices for a single user.

I think this can and should be a default feature in oscar.

Django groups already exists, so I guess this can be used for it.

Would this be something that can and may be implemented in oscar?

**Comment by opobla** [comment]
Hi! I'm facing the same problem here. Did you solve it somwhow?

**Comment by joeyjurjens** [comment]
closing all issues that look like they really are feature requests but don't have open PR's attached.
