### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [django-oscar/django-oscar#3822]
Hey there!

I belong to an open source security research community, and a member (@ktg9) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by solarissmoke** [comment]
Hey @JamieSlome thanks for reaching out. While we work on putting in place a security policy I'd be grateful if you (or @ktg9) could drop me an email (contact in my [Github profile](https://github.com/solarissmoke)) and we'll get on to it.

**Comment by JamieSlome** [comment]
@solarissmoke - just for reference, you can find the report here: https://huntr.dev/bounties/c6ed0ec6-bcad-41a4-8f9a-5b0db7859db6/

It is only visible to permissive maintainers 👍

**Comment by ktg9** [comment]
Hi @solarissmoke, did you have time to take a look at the report?

**Comment by ktg9** [comment]
Hi @solarissmoke , any update?

**Comment by Summer88** [comment]
Hi, 

may I ask if it is safe to setup a production site right now with latest stable?

Thanks, BR

**Comment by joeyjurjens** [comment]
Closing this issue because there wasn't really a vulnerability risk.
