### ISSUE TITLE
Offers / Free product benefit type.

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#383]
Example: ''Buy product X, get product Y for free" - the additional product needs to be added automatically to the basket.

Implementation idea:
- Use a signal raised when a basket qualitifies for a new offer.  Then look at the offer and see if it has a "post-qualify" action

**Comment by sasha0** [comment]
We'll need to implement custom benefit model and additional one, that will store product and quantity of benefit products.
The logic is simple, as suggested above - add benefit products to the basket/order with zero prices.

**Comment by sasha0** [comment]
I believe `MultibuyDiscountBenefit` almost satisfies the requirements, but not quite.

We could add a product range to the Benefit model and then accordingly alter basket with those products and provide them by zero price, as I already stated above.

Might not be the most common case, but would be interesting to see how far offer application capabilities can expand.

Would appreciate your thoughts too @django-oscar/core @pjstevns.

**Comment by pjstevns** [comment]
I've build this kind of functionality before.

- Using the offer module, adding a 'free' product is easy enough. Removing it however is suddenly introducing the kind of complexity to the involved Benefit that says 'code smell'.
- I'm maintaining a completely different approach in my current main webshop. It uses a separate model (ProductBundle) where when you add product-A you _can_ add product-B with a discount, or, if the discount is 100% it is added automatically. The state of the bundled products is added as a foreign key on the basket (and order) lines involved. It works, but it's also quite complex.
- A completely different approach I designed on an earlier project that had additional requirements beyond simple bundle-discounts. For that I used a BasketPolicy approach that facilitated stuff like:
 
 - if you buy A, B is added automatically. Remove A, B is also removed.
 - if you buy A, B is added automatically with discount. Remove A, B loses it's discount.
 - If you buy C, you are eligible to add A, and if you do B is added automatically. Remove C, A and B are also removed. 
etc...

It was proprietary code I don't have access to any more, but  using an approach orthogonal to conditional offers made life easier. I didn't have to muck around shoehorning functionality into the benefit applicator that didn't really fit, like automatically adding/removing products. 

At a minimum, you need a mechanism for keeping track of products that were added automatically and what condition triggered this. Once you have that, you can remove such products if the condition no longer applies.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
