### ISSUE TITLE
Some tests misusing assertTrue for comparisons

### ISSUE THREAD

**Issue by code-review-doctor** [django-oscar/django-oscar#3866]
`assertTrue` is not for comparing arguments, should use `assertEqual` for that.

The developer's intent of the test was to compare argument 1 with argument 2, which is not happening. Really what is happening is the test is passing because first argument is truthy. The correct method to use is assertEqual. [more details](https://codereview.doctor/features/python/best-practice/avoid-misusing-unittest-assert-true)

https://github.com/django-oscar/django-oscar/blob/c05353a76dfbb7ce0df744e97cf0e282c54cae56/tests/integration/catalogue/test_options.py#L35

I found this issue automatically, see other issues [here](https://codereview.doctor/django-oscar/django-oscar)

**Comment by specialunderwear** [comment]
Not that is not what is happening at all, in fact this test just has a really bad and invalid failure message. Thanks for pointing out a fault in the tests though.

**Comment by specialunderwear** [comment]
I've sent you a pull request to help you with this issue at: https://github.com/code-review-doctor/django-oscar/pull/6
