### ISSUE TITLE
Performance issue in cases where selecting strategy for product

### ISSUE THREAD

**Issue by pwalsh** [django-oscar/django-oscar#3875]
Found a bug? Please fill out the sections below.

### Issue Summary

In Oscar 2.1, Selecting a strategy for product in [`UseFirstStockRecord`](https://github.com/django-oscar/django-oscar/blob/2.1.0b0/src/oscar/apps/partner/strategy.py#L188) used to (correctly, for performance reasons) index on the related stock records for a product to get the first. This meant, of course, that the `prefetch_related` call to `stockrecords` on `Product` was used and no additional queries generated.

Now, in Oscar 3.1 [this was changed to use the queryset's `first` method](https://github.com/django-oscar/django-oscar/blob/3.1/src/oscar/apps/partner/strategy.py#L188), which unfortunately makes the prefetch invalid and causes a new query each time a product shows price info (for various reasons, this has a huge performance impact on my use case).

This change was introduced in [this commit](https://github.com/django-oscar/django-oscar/commit/3a826796d01e5cba345aa646dbc5c8ae466cbf4a), which also implemented the same pattern over various related queries, and therefore I assume has similar performance implications (but I haven't checked).

### Steps to Reproduce

Try to render a page with various snippets of pricing info for a collection of hundreds of products - use a tool like Django Debug Toolbar to see the query multiplication :)

### Technical details

* Python version: Run `python --version`: 3.10
* Django version: Look in your requirements.txt, or run `pip show django | grep Version` 3.2.12
* Oscar version: Look in your requirements.txt, or run `pip show django-oscar | grep Version`. 3.1

**Comment by specialunderwear** [comment]
Interesting, I would have thought that the [0] indexing was done because queryset.first() didn't exist at the time this was written.

**Comment by specialunderwear** [comment]
could you show us a screenshot of your usecase or add a url? I think it would be good to be able to replicate the scenario.

**Comment by pwalsh** [comment]
Hey @specialunderwear 

I don't have a public URL but you can see the docs for `prefetch_related` that this is the expected behaviour:

https://docs.djangoproject.com/en/4.0/ref/models/querysets/#prefetch-related

The "note" section clearly illustrates.

So, using `.first()` has negative performance implications with this change in Oscar - it means the optimization of prefetching the stock records is redundant, and that the query performance from that optimization is therefore no longer present).

**Comment by solarissmoke** [comment]
Hah, this is interesting. I too had just assumed that this was legacy code that was written before `first()` was introduced. I think we need to revert that commit, but also add docstrings explaining why it's done that way, as it's not immediately obvious.

**Comment by pwalsh** [comment]
@solarissmoke 

Yes, it is not obvious from the code, and a way to document it better would also be to emphasize where Oscar does `select_related` and `prefetch_related` queries - I assume there will be Oscar users who don't know the details of Django's ORM and won't be aware that any customization they may do to queries will make Oscar's use of `select_related` and `prefetch_related` redundant, impacting performance.

Also see the [docs](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#first) and the [implementation](https://github.com/django/django/blob/main/django/db/models/query.py#L862) for `.first()` - Because of the stuff around ordering, I would be careful about using it in Oscar to be honest - `first()` and `all()[0]` are *not* guaranteed to return the same instance due to how ordering may or may not be implemented.
