### ISSUE TITLE
When choosing a custom condition for your offer, it requires a range while it shouldn't

### ISSUE THREAD

**Issue by joeyjurjens** [django-oscar/django-oscar#3885]
When you are choosing a custom condition on your offer, it will throw an error if you do not select a range as well.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/7702200/156327295-b915ed75-48ea-4172-b1fb-98d8e67c674c.png">

However, the range is saved on the custom condition model so it should not be required.

### Steps to Reproduce
1. Create a custom condition, see [here](https://django-oscar.readthedocs.io/en/3.0.2/howto/how_to_create_a_custom_condition.html) how.
2. Create an offer and choose your custom condition without choosing a range, type and value.
3. Error should occur.

The logic in the the clean method of the ConditionForm seems wrong (line 127):
https://github.com/django-oscar/django-oscar/blob/23013a61a1f84517522c071bbeddb3fd3e841ee6/src/oscar/apps/dashboard/offers/forms.py#L126-L133

I think it should be like the BenefitForm does it:
https://github.com/django-oscar/django-oscar/blob/23013a61a1f84517522c071bbeddb3fd3e841ee6/src/oscar/apps/dashboard/offers/forms.py#L178-L191

Or is there any reason this is a requirement even when you choose a custom condition?

### Technical details

* Python version: Python 3.9.9
* Django version: Version: 3.2.9
* Oscar version: Version: 3.1

**Comment by jwayodi** [comment]
I think you are right that the validation is wrong, and should be like the one on the `BenefitForm`.
