### ISSUE TITLE
Large number of baskets makes Order Admin page slow to load

### ISSUE THREAD

**Issue by st8st8** [django-oscar/django-oscar#3888]
Found a bug? Please fill out the sections below.

### Issue Summary

A summary of the issue.

Our shop has a large number of baskets now.  This mean that the basket dropdown in the order admin page takes about a minute to load.

### Steps to Reproduce

Create 2000+ baskets, submit one order, and then view that order in Django Admin

Is there a way we should be purging baskets, can we add Select2 (or otherwise) or make this read only?

### Technical details
Python 3.9, Django 3.2, Oscar 3.1

**Comment by solarissmoke** [comment]
I think the simplest fix here is to change the basket to use a [raw id](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields) in the admin instead of a dropdown - PR welcome if you have time.

**Comment by st8st8** [comment]
I ended up making the basket read only in the admin - that works for me.  I've offered a PR to that effect....
