### ISSUE TITLE
App for enabling syndication with 3rd parties, eg Google's Product Search

### ISSUE THREAD

**Issue by AndrewIngram** [django-oscar/django-oscar#39]
Probably a more long-term idea, but it would potentially benefit most users of Oscar.

There are a number of price comparison sites which retailers can register their catalogue with, they usually operate on a cost-per-click basis, but google's one is free.

They can use a number of mechanisms, the most common being a feed or a programmatic API. I envisage a number of backends being available that build on one of these core mechanisms.

To understand the potential complexity, here's how it would work for Google via their API:
- Google removes any products after 30 days, this is presumably to prevent their search results becoming stale. To get around this, all active products would need to be resynced at least once every 30 days.
- Any time a product changes it would need to be resynced. This could be done as a periodic task (eg daily), or perhaps asynchronously using a message queue. In the past I've used a twice-daily cron task.
- Assuming we go with a cron task and because of the previous two points, for each product we'd need to keep track of the last-modified and last-syndicated dates of each product.
- The task runs, finds all the products that need to be synced and generates the required API calls. These calls can be quite slow, so it's best to sync batches of products in one call. There may be issues with large batches timing out, which would prevent syncing all products with just one call. In the past i've used batches of 50.
- We'd also need to keep track of any products that need to be removed (before their natural 30 day expiry), this may be because they've been physically deleted or because they're out of stock. Whilst Google is free, other providers charge per click, so paying for a customer who can't buy the product isn't ideal. With Google these products can be removed via the API.

The feed approach works similarly, but with hosting an XML feed of the changes at a URL rather than generating an API call. The catch is that there's no confirmation of a successful sync, so we wouldn't be able to accurately update the last-syndicated field. Because of this the feed may have to show ALL products, which isn't a good solution with a large catalogue.

Assuming Google is just one backend of many, we'd also need support for multiple backends running in tandem, possibly with each having their own models and cron tasks.

Other providers to investigate include Kelkoo, Pricerunner and Ciao.

If there's interest I can investigate this further.

**Comment by sasha0** [comment]
I think it's interesting idea, but rather for external Oscar application, not core. 

The fact that during all this time there were no attempts to implement this functionality (based on absence of submitted PRs), it does not prove presence of practical interest to this functionality.

If we reconsider this in the future - we can open a new task or re-open this one. Thanks.
