### ISSUE TITLE
Unable to access oscar on https://example.com:8443/oscar

### ISSUE THREAD

**Issue by jessicana** [django-oscar/django-oscar#3921]
### Issue Summary

I followed [this guide](https://worldoscar.org/knowledge-base/oscar-19-installation/?epkb_post_type_1=oscar-19-installation) and I managed to install the most recent version [oscar_emr19-66~1881.deb](https://sourceforge.net/projects/oscarmcmaster/files/Oscar%20Debian%2BUbuntu%20deb%20Package/oscar_emr19-66~1881.deb/download) on Ubuntu 22.04. After a successful installation, I was able to arrive at the below stages:

![image](https://user-images.githubusercontent.com/7415824/166155088-3adb7b18-7208-4830-9fe0-a80739b51847.png)

![image](https://user-images.githubusercontent.com/7415824/166154636-cd429909-6936-4df2-8343-83fc13d22124.png)

When I `run less /usr/share/oscar-emr/README.txt` , I got:

![image](https://user-images.githubusercontent.com/7415824/166154724-e6272921-de8c-4795-b4ce-a92bfd8e087a.png)

### The problem
When I visited https://[example.com](https://example.com:8443/oscar):8443/oscar I got:

![image](https://user-images.githubusercontent.com/7415824/166155558-da0b157a-87f4-48fb-9eee-d3dea6a6d078.png)

### Technical details
```
java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```

* Python version: When I run `python --version`, I got: `-bash: python: command not found`. But `pip3 --version` returned `pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)`
* Django version: When I run `pip show django | grep Version`, I got `WARNING: Package(s) not found: django`
* Oscar version: When I run `pip show django-oscar | grep Version`, I got `WARNING: Package(s) not found: django-oscar`

### Help needed
How can I fix my installation to get this up and running?

**Comment by solarissmoke** [comment]
You have got the wrong repository - this project is `django-oscar`, not related at all to the medical records software whose issue tracker is [here](https://oscaremr.atlassian.net/jira/software/c/projects/OSCAREMR/issues/?filter=allissues)
