### ISSUE TITLE
No existing catalan translations

### ISSUE THREAD

**Issue by rbetancourt27** [django-oscar/django-oscar#3924]
### Issue Summary

I need some catalan translations which don't exists

### Technical details

* Python version: 3.8
* Django version: 2.2
* Oscar version: 2.1

**Comment by viggo-devries** [comment]
Hey @rbetancourt27 thanks for doing this. We use Transifex to manage all translations.

https://www.transifex.com/projects/p/django-oscar/

Would you be so kind to sign up and add them to the Transifex project?

If you need any help please ask.

**Comment by rbetancourt27** [comment]
Hey @viggo-devries Is it needed the translations to be approved? When they're added must I close the pull request?

**Comment by viggo-devries** [comment]
hey @rbetancourt27 thank you very much for adding the translations!

I released Oscar 3.2 alpha today and they have been added to that release!

so you can install that version on your project and you should have the new translations added.

Please note that this is an alpha release and could have some issues still. A 3.2 final release should be here in a couple of weeks.
