### ISSUE TITLE
Image cropper

### ISSUE THREAD

**Issue by Bastilla123** [django-oscar/django-oscar#3949]
Found a bug? Please fill out the sections below.

Sometimes imaages are uploaded with different aspec ratio. In Listview now product tiles have different heights.

A summary of the issue.

Upload in dashboard in 2 different products different images with differend aspect ratios and then go to listview of products.
 
Solution

I think best solution is a cropper like this https://github.com/aneesh2usman/django_cropper_image where i can setup i fix aspect ratio.

Please insert a cropper in dashboard on product createview/updateview.

Thanks

**Comment by joeyjurjens** [comment]
This is a project specific problem and I don't think this should be added to the core of Oscar. You can change the way or rendering images in the templates, as that seems the thing you want to do.
