### ISSUE TITLE
Mismatch between AbsoluteDiscountBenefit and desctiprion in AbstractBenefit.TYPE_CHOICES 

### ISSUE THREAD

**Issue by ebottos94** [django-oscar/django-oscar#3955]
### As exposed in PR [#3952](https://github.com/django-oscar/django-oscar/pull/3954) :

According with the description in the class AbstractBenefit in file src/oscar/apps/offer/abstract_models.py in line 481, for the absolute discount the discount's logic is : "Discount is a fixed amount off of the product's value".

In the file src/oscar/apps/offer/benefits.py instead the logic in the class AbsoluteDiscountBenefit is developed as if the discount were "Discount is a fixed amount off of the total amount of the shopping".

### What do you want to do? Change the description or logic?

In PR [#3952](https://github.com/django-oscar/django-oscar/pull/3954) I've changed the logic, if this is not what you want to do I can open new PR to simply change the description of the Benefit.

Thanks

**Comment by specialunderwear** [comment]
We can't change the logic, because that would change working of the offer in existing sites. So please change the description. If you do need the different functionality, I suggest adding a new type of offer that implements that.

**Comment by samar-hassan** [comment]
Benefit description update here https://github.com/django-oscar/django-oscar/pull/3954
