### ISSUE TITLE
Redirect loop in ProductDetailView

### ISSUE THREAD

**Issue by hutchison** [django-oscar/django-oscar#3967]
### Issue Summary

I started a test project and included the oscar urls like this:
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app:shop/', include(apps.get_app_config('oscar').urls[0])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
But when I try to look up an example product I get into a redirect loop. I looked into `ProductDetailView` and the problem lies in `redirect_if_necessary()`
```
    def redirect_if_necessary(self, current_path, product):
        if self.enforce_parent and product.is_child:
            return HttpResponsePermanentRedirect(
                product.parent.get_absolute_url())

        # right here:
        if self.enforce_paths:
            expected_path = product.get_absolute_url()
            if expected_path != quote(current_path):
                return HttpResponsePermanentRedirect(expected_path)
```
Because the colon gets quoted to `%3A` I get into the redirect loop.

### Steps to Reproduce

1. start a new project and include django-oscar in the `urlpatterns` with a prefix that includes a colon, e.g.
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app:shop/', include(apps.get_app_config('oscar').urls[0])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
2. start the development server, add at least one product and try to view the details of the product
3. you should see a redirect loop

### Technical details

* Python version: Python 3.9.13
* Django version: 3.2.15
* Oscar version: 3.1.0

Here is a PR with a fix: https://github.com/django-oscar/django-oscar/pull/3966

**Comment by joeyjurjens** [comment]
Fixed in https://github.com/django-oscar/django-oscar/pull/4106
