### ISSUE TITLE
Need to break assumption that user is found at request.user

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#397]
Horrible requirement driven from downstream nasty B2B requirements.

Some projects need to be able to override which user is used in templates and business logic.  Some user's can 'masquerade' as other users which is like logging in as them but retaining some of their own privileges.  This makes things very complicated.

Ultimately, every view that uses `request.user` needs a method for loading the user instance so that it can be overridden.

**Comment by sasha0** [comment]
I personally has never seen any similar use-cases in my projects yet and achieving similar logic for B2B does not seem feasible without major customization. 

We can create a new issue when we want to continue discussion of the new B2B-related changes.
