### ISSUE TITLE
Adding Image option for products

### ISSUE THREAD

**Issue by HoseinPorazar** [django-oscar/django-oscar#3970]
For some products I need to get user entered  images( for instance I want to get user image for applying on T-Shirts)
I tried adding Options in basket/forms.py and catalogue> Abstract options but it didn't work
Can you please give a solution?

**Comment by joeyjurjens** [comment]
I don't think this is something we should implement in the oscar core.
Allowing users to upload files comes with a security risks and methods preventing such risks is likely platform specific.

You were on the right track though, you should start with extending the form and you should create a new model that stores the images to the basket line option I suppose, or add a new field on the basket line option that can take an image.

Anyways for now, I'm closing this as this should be implemented by the developers of the shop if they want to. If you have support questions you can ask so on Google Groups.
