### ISSUE TITLE
Huge load times for ecommerce site when having many products and categories

### ISSUE THREAD

**Issue by iSolorak** [django-oscar/django-oscar#3982]
Found a bug? Please fill out the sections below.

### Issue Summary

Oscar is having huge load times when a site has a lot of products and categories .

### Steps to Reproduce

For example the page I am currently handling has at least 80k products and 500 categories and it slows down the whole page . Even homepage where no product is shown ( yes the navigation bar and what is shown is optimized that's why the load time is not as huge as in ProductCategoryView ) . 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

* Python version: `3.8.6`.
* Django version: Django==3.2.7.
* Oscar version: django-oscar==3.1.
* Deployed using : nginx and uwsgi

**Comment by iSolorak** [comment]
It's not that the issue is fixed . Still trying to understand what's wrong . Meanwhile I've done some optimizations to my website , still slow . The optimizations were using some DJANGO REST API endpoints for navbar category set and URL's . I 've tried connecting to a remote database for more "" physical power "" ( More CPU , RAM dedicated  to Queries only ) still slow . I repeat the amount of products that my site contains is 81k products ( with variants ) and around 800 Categories. Yes wherever was appropriated I did use queries such as  select_related and prefetch_related. The question still remains the same . What is the maximum capacity for products and categories that oscar can handle

**Comment by joeyjurjens** [comment]
Hi @iSolorak, the numbers you mention (80k products and 500 categories) are quite a lot if you combine them together.

I've a few suggestions though;
**Cache the header / navigation menu**
Rendering the navigation menu with so many categories, is not ideal and should preferably be cached. This can simply be done by the Django template cache mechanism. In our sites, we cache for like 10/15 minutes and then after that the first user that comes on the site will have a slight delay but then it's cached again for 10/15 minutes.

You could also cache this with no time limit and remove the cache key once changes are made to a category, though I suggest the first one.

**Use elasticsearch** 
We use elasticsearch on our webshops and I think this would help you as well. We've got a site with around a million products and it runs smooth and the main reason is ElasticSearch.

There's a package for django-oscar: https://github.com/django-oscar/django-oscar-elasticsearch

** Implement caching **
If possibly, you can implement some sort of caching. Category pages (normally) don't change very often, same with detail pages of products. Though, I don't know much about this, so I'm not sure what to recommend. We use varnish, but that's quite some work to get right.

Also, I'm curious on what kind of database your webshop runs?

**Comment by specialunderwear** [comment]
YOu should be very very careful with the category_tree templatetag, only use it once on each page and render only to the depth you need. And make sure not to access item.category when looping through the items or you will make additional queries!

**Comment by specialunderwear** [comment]
.

**Comment by specialunderwear** [comment]
.

**Comment by iSolorak** [comment]
I am using postgresql

**Comment by iSolorak** [comment]
Also I do not understand why the issue was closed . Still having the same problem and I am eager to learn why it gets slower when having many products . Should I use more than one database ? Should I use remote database . I 've been searching for a while there is now answer anywhere .

**Comment by iSolorak** [comment]
@specialunderwear  @joeyjurjens
