### ISSUE TITLE
ProductSelect widget (dashboard.catalogue.widgets)

### ISSUE THREAD

**Issue by martinsrudzroga** [django-oscar/django-oscar#3993]
How to remove selected option or add empty value option if used without formsets?

**Comment by martinsrudzroga** [comment]
OK, found one solution

$("#id_parent").select2({
            placeholder: '----------',
            allowClear: true,
        });

**Comment by joeyjurjens** [comment]
Hi @martinsrudzroga, issues are not for support, so please next time refer to our Google Group: https://groups.google.com/g/django-oscar

To answer your questions though;

You could fork the dashboard catalogue app (see docs for forking) and override the `ProductSelect` class and override the build_attrs method something like this:

```python
    def build_attrs(self, *args, **kwargs):
        attrs = super().build_attrs(*args , **kwargs)
        attrs['data-placeholder'] = '------------'
        attrs['data-required'] = 'false'
        attrs['data-allow-clear'] = 'true'
        return attrs
```
