### ISSUE TITLE
Supported version 3.x

### ISSUE THREAD

**Issue by Chrescht** [django-oscar/django-oscar#3994]
Hi all,

according to the main page there is currently no supported 3.x version.
Is this correct?
Is there a roadmap for future versions?

Also, DataCash does not seem to be alive any more.
https://docs.oscarcommerce.com/en/latest/index.html

Many thanks

**Comment by specialunderwear** [comment]
That's right, we are working on the 3.2 release at the moment which will be an LTS release. Thanks for your report.
