### ISSUE TITLE
SearchHandler initialisation fails in Version 3.2a4

### ISSUE THREAD

**Issue by gwaidacher** [django-oscar/django-oscar#4003]
### Issue Summary

Wrong order in import of catalogue.search_handlers.py, line 8, Oscar Version 3.2a4:
```
SearchResultsPaginationMixin, SearchHandler,  = get_classes(
     'search.search_handlers', ('SearchHandler', 'SearchResultsPaginationMixin'))
```

### Steps to Reproduce

Initialisation of SearchHandler in apps/search/search_handlers.py:

`handler = SearchHandler(request.GET, request.get_full_path)`

results in:

`Error: object.__init__() takes exactly one argument (the instance to initialize)`

### Steps to fix:

see:  https://github.com/django-oscar/django-oscar/pull/4002

merge 1 commit into [django-oscar:master](https://github.com/django-oscar/django-oscar) from [gwaidacher:patch-1](https://github.com/gwaidacher/django-oscar/tree/patch-1)

### Technical details

* Python version: 3.9.2
* Django version: 3.2.16
* Oscar version: 3.2a4

**Comment by joeyjurjens** [comment]
Thanks for your report and PR! It has been merged
https://github.com/django-oscar/django-oscar/commit/cf40cdb81d4d65430309290dcb44db659f61b7ae
