### ISSUE TITLE
Unpublished products are still shown in offers

### ISSUE THREAD

**Issue by gwaidacher** [django-oscar/django-oscar#4054]
### Issue Summary

Offers show non-public products

### Steps to Reproduce

1. Create an Offer
2. Unpublish a product which is part of the offer (set product.is_public = False)
3.  The product is still shown in Offer List and Detail

### Technical details

* Python version: 3.9.2
* Django version: 3.2.16
* Oscar version: 3.2.0

**Comment by gwaidacher** [comment]
#4053 fixes this issue

**Comment by joeyjurjens** [comment]
#4053 merged
