### ISSUE TITLE
Configuring ranges does not allow excluding products through the UI

### ISSUE THREAD

**Issue by joeyjurjens** [django-oscar/django-oscar#4055]
The range model allows exclusion of specific products:
https://github.com/django-oscar/django-oscar/blob/151dc05395865ec0f51cdd45be9970a1bbea2f0c/src/oscar/apps/offer/abstract_models.py#L854

However, you can not configure those through the dashboard UI, while it's a pretty useful feature.

You can configure single included products, with the "Save and edit products" button;
<img width="349" alt="image" src="https://user-images.githubusercontent.com/7702200/220860699-86ca45f9-8e73-4648-b978-8a4b242c7708.png">

We could also allow users to exclude products in this view, though we would probably need to make the view UI a bit clearer here, as to me it already looks a bit clumsy.

A separate view would do as well, but it should inherit the logic from the edit products view, as the only difference should be that it saves the products in the `excluded_products` field rather than the `included_products` field

**Comment by gwaidacher** [comment]
Hi!

I added a table with the excluded_products, please check. If my changes are ok for you, I will try to add the missing tests.

**Comment by gwaidacher** [comment]
Hi, I have a working solution with tabs, with a second textfield for upcs and a separate file upload field
https://github.com/django-oscar/django-oscar/pull/4073

unfortunately the tests failed because the migrations (add 2nd fileuploadfield for excluded products) are not performed automatically - how can this be accomplished?

2nd question: how are translations for the new strings added?

**Comment by gwaidacher** [comment]
![image](https://user-images.githubusercontent.com/117359695/225294963-588ff622-58eb-4bd4-9435-648443f2a223.png)

**Comment by gwaidacher** [comment]
> However, you can not configure those through the dashboard UI, while it's a pretty useful feature.

Hi! Please have a a look at my PR, https://github.com/django-oscar/django-oscar/pull/4073 if it fits your requirements, I'll add the missing tests for the new functionality.

**Comment by gwaidacher** [comment]
added missing tests in #4073
