### ISSUE TITLE
Critical vulnerability idenfitied suggestion of a Private reporting

### ISSUE THREAD

**Issue by Sim4n6** [django-oscar/django-oscar#4086]
Hi,

I have identified a critical vulnerability in the latest codebase of django-oscar. 

I think reporting it publicly as an issue, is not correct. I suggest please that you enable the [GitHub's private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) for this repository. It would permit CVE assigning, private discussion, etc.

Otherwise, if you have a bug bounty program, I am wiling to share my report in there.

Thank you in advance.

**Comment by joeyjurjens** [comment]
Hi @Sim4n6 , excuse the somewhat late reply. Could you please send me an email regarding the vulnerability (contact on my github profile) or alternatively upload it to something like https://huntr.dev/?

The person who has admin rights on this repo is unavailable at the moment to enable the private vulnerability option, but we'll do so once he's back.

**Comment by Sim4n6** [comment]
No problem, I will write the details using the huntr platform.

**Comment by Sim4n6** [comment]
Report submitted https://huntr.dev/bounties/f0e67c54-e881-45ca-942a-aa7e4e6cee5e

**Comment by Sim4n6** [comment]
In case you have a bug bounty program or you consider I am eligible for a bounty please let me know. 

And please keep me posted regarding the activation of the GitHub Private Bounty reporting feature ...
