### ISSUE TITLE
the dashboard won't show the built-in fields after customisation: FieldError: Unknown field(s)

### ISSUE THREAD

**Issue by fluffbufff** [django-oscar/django-oscar#4103]
Found a bug? Please fill out the sections below.

### Issue Summary
I get: django.core.exceptions.FieldError: Unknown field(s) (markdown_reason, markdown, short_description, bestseller, is_new, out_of_stock, on_sale) specified for Product

### Steps to Reproduce

Using oscar_fork_app I forked:
1. catalogue: 
```
#/my_project/my_oscar_apps/catalogue/models.py
from django.db import models
from oscar.apps.catalogue.abstract_models import AbstractProduct

class Product(AbstractProduct):
    
    custom_field = models.TextField(blank=True)

from oscar.apps.catalogue.models import *  # noqa isort:skip

```
2. dashboard
3. catalogue_dashboard:
```
#/my_project/my_oscar_apps/dashboard/catalogue/forms.py
from oscar.apps.dashboard.catalogue import forms as base_forms


class ProductForm(base_forms.ProductForm):

    class Meta(base_forms.ProductForm.Meta):
        fields = [
            'title', 'upc', 'on_sale',
            'short_description', 'description',
            'out_of_stock', 'bestseller',
            'is_new', 'is_discountable', 'structure',
            'markdown', 'markdown_reason', 
           'custom_field'
        ]

```

I customised dashboard forms as per the [docs](https://django-oscar.readthedocs.io/en/stable/howto/how_to_customise_models.html?highlight=register%20models%20dashboard#customising-dashboard-forms)

My folder structure:
|____my_oscar_apps
| |______init__.py
| |______pycache__
| | |______init__.cpython-310.pyc
| |____dashboard
| | |____models.py
| | |______init__.py
| | |______pycache__
| | | |____models.cpython-310.pyc
| | | |____apps.cpython-310.pyc
| | | |______init__.cpython-310.pyc
| | |____apps.py
| | |____catalogue
| | | |____models.py
| | | |______init__.py
| | | |______pycache__
| | | | |____models.cpython-310.pyc
| | | | |____forms.cpython-310.pyc
| | | | |____apps.cpython-310.pyc
| | | | |______init__.cpython-310.pyc
| | | |____apps.py
| | | |____forms.py
| |____catalogue
| | |____migrations
| | | |____0005_auto_20230513_2113.py
| | | |______init__.py
| | | |______pycache__
| | | | |______init__.cpython-310.pyc
| | |____models.py
| | |______init__.py
| | |______pycache__
| | | |____models.cpython-310.pyc
| | | |____admin.cpython-310.pyc
| | | |____apps.cpython-310.pyc
| | | |______init__.cpython-310.pyc
| | |____apps.py
| | |____admin.py

The error occurs when I makemigrations/migrate/runserver

**Comment by joeyjurjens** [comment]
Hi @fluffbufff , it seems like you've copied the example of the docs without altering it.

You've only added the "custom_field" as new field. But you're adding `markdown_reason, markdown, short_description, bestseller, is_new, out_of_stock, on_sale` to your fields, but those fields do not exist. They're added to the docs for demonstration, on how it would work if you added new fields.

So what you would need to do is add the original fields + your new field(s). Eg:
```python
from oscar.apps.dashboard.catalogue import forms as base_forms

class ProductForm(base_forms.ProductForm):
    class Meta(base_forms.ProductForm.Meta):
        fields = ['title', 'upc', 'description', 'is_public', 'is_discountable', 'structure', 'slug', 'meta_title', 'meta_description', 'custom_field']
```

Alternatively you can append your own field as a list to the original meta class fields like this:
```python
from oscar.apps.dashboard.catalogue import forms as base_forms

class ProductForm(base_forms.ProductForm):
    class Meta(base_forms.ProductForm.Meta):
        fields = base_forms.ProductForm.Meta.fields + ["custom_field"]
```
