### ISSUE TITLE
Differently priced product options

### ISSUE THREAD

**Issue by em-ex** [django-oscar/django-oscar#4109]
Hi,
Thank you all for putting all this effort into this extremely useful project! 

Not sure if this is appropriate place to post, but the official [Oscar Slack "inviter"](https://slack.oscarcommerce.com/) doesn't seem to work anymore and Google Groups search wasn't particularly fruitful. This must be super easy for skilled devs, but I'm struggling to find an optimal approach to the following catalogue setup.

Using Oscar 3.2, I created a custom product importer class which fetches product data from a third-party source (via REST API) and adds two types of products into Oscar. For one of them - the `tea` product class - there's a requirement to have a 'packed weight' option for customer to choose from (rendered as a regular drop-down selector on the front-end). 

Purchasable packages are 10 g and 50 g, although sometimes there's also a "brick" option available for some sorts of tea, which can have an arbitrary weight, usually 250 g and more.  All three options must be tied to the same product StockRecord. 

I extract the 10 g price from the third-party product data and use it to calculate prices for 50 g and brick, if it exists. 

_But where do I define these prices for each option?_ 
And how do I allow "brick" option only for certain products?

Product variants seem like an overkill for this, and trying to define weight attribute (which, I assume, should go along with some custom strategy, although I haven't gotten this far) I always seem to run into issues _after_ the first tea is successfully added:

```python
    tea_product = self._create_product(
        structure='standalone',
        product=product,
        groups=inventory['menu'].groups
    )

    weight_group = AttributeOptionGroup.objects.create(name='Packed weight')
    
    AttributeOption.objects.get_or_create(
        group=weight_group,
        option='10 g'
    )
    AttributeOption.objects.get_or_create(
        group=weight_group,
        option='50 g'
    )
    ProductAttribute.objects.create(
        product_class=tea_product.product_class,
        name='Weight',
        code='weight',
        type='option',
        option_group=weight_group
    )
```
If I use `ProductAttribute.objects.create(`) it expectedly fails on uniqueness:
> UNIQUE constraint failed: catalogue_productattribute.code, catalogue_productattribute.product_class_id

If I use `ProductAttribute.objects.get_or_create()` it fails with:
> UNIQUE constraint failed: catalogue_productattribute.code, catalogue_productattribute.product_class_id
> oscar.apps.catalogue.models.ProductAttribute.DoesNotExist: ProductAttribute matching query does not exist.

Please advise

**Comment by viggo-devries** [comment]
maybe try

ProductAttribute.objects.create(
        product_class=tea_product.product_class,
        code='weight',
        defaults={'name':'Weight',
        'type':'option',
        'option_group':weight_group
    )

**Comment by viggo-devries** [comment]
but I think you have corrupted your database because you used .create, there are probably now multiple product attributes with the same code on 1 productclass

.create does not run validation, that's probably why this has happened.

**Comment by em-ex** [comment]
Thank you for taking time to look into this, Viggo!
I'm flushing all tables in my DB before each import, but might've overlooked something along the way. I need to take a closer look at this after I'm done converting my HTML template into Oscar template
