### ISSUE TITLE
Voucher offer is only applied to one single product in the basket

### ISSUE THREAD

**Issue by kevinrenskers** [django-oscar/django-oscar#4147]
### Issue Summary

When creating a voucher offer without "max affected items" set, it is still only applied to one single item in the basket.

### Steps to Reproduce

I used the sandbox (https://latest.oscarcommerce.com/en-gb/dashboard) to create a new Voucher Offer that applied to all items, gives a $2 discount, and doesn't set a max affected items value.

![Screenshot 2023-08-07 at 17 15 13](https://github.com/django-oscar/django-oscar/assets/229384/b90ed17d-016a-4d98-98e4-05a3b4adaaf7)

I then created a voucher set with some vouchers. I added some items to my cart, and applied one of the vouchers.

The problem is that the total discount is only $2, whereas I would expect it to be $2 per item? After all, I didn't set "max affected items" to 1.

![Screenshot 2023-08-07 at 17 15 23](https://github.com/django-oscar/django-oscar/assets/229384/a4a475bc-4877-4186-b182-4db5984902bb)

### Technical details

* Python version: 3.10.
* Django version: 3.2.20.
* Oscar version: 3.2.

**Comment by samar-hassan** [comment]
This benefit's description was a bit misleading, I have updated the description here https://github.com/django-oscar/django-oscar/pull/3954. The discount is applied on the basket's total instead of applying on each product price.
