### ISSUE TITLE
A voucher offer is alway saved as a site offer

### ISSUE THREAD

**Issue by kevinrenskers** [django-oscar/django-oscar#4148]
### Issue Summary

Whenever I want to create or edit a voucher offer, it is always saved as a site offer.

### Steps to Reproduce

Whenever I create a new voucher offer, it actually gets saved as a site offer, when I press save on step 4.

1. Create a new voucher offer:

![Screenshot 2023-08-07 at 17 25 02](https://github.com/django-oscar/django-oscar/assets/229384/99fc8347-92cd-4894-87d8-b69a7f35e501)

2. On step 4 its type is still "Voucher":

![Screenshot 2023-08-07 at 17 25 48](https://github.com/django-oscar/django-oscar/assets/229384/09e4d84e-5937-4528-a788-83d30cdd3795)

3. But when saving, the type changes to "Site offer".

![Screenshot 2023-08-07 at 17 25 55](https://github.com/django-oscar/django-oscar/assets/229384/4aeee6af-490c-4206-a87a-ee0bb07943ca)

The only way to make it into a Voucher offer is to edit this offer in the database, I can't do it via the dashboard at all. Editing a voucher offer also turns it into a site offer upon saving.

On the Oscar sandbox site it does work. The biggest difference I can spot is that I have 3 offer types:

![Screenshot 2023-08-07 at 17 29 14](https://github.com/django-oscar/django-oscar/assets/229384/e33e9699-9ca1-457d-bb9c-95e31ffcda6d)

But the sandbox only has two:

![Screenshot 2023-08-07 at 17 30 03](https://github.com/django-oscar/django-oscar/assets/229384/16c53be4-4421-437e-8698-b5bc3fc0f82c)
 
### Technical details

* Python version: 3.10.
* Django version: 3.2.20.
* Oscar version: 3.2.

**Comment by samar-hassan** [comment]
Hi @kevinrenskers ,

I added User specific offer in sandbox.
`
OSCAR_OFFERS_IMPLEMENTED_TYPES = [
    "SITE",
    "VOUCHER",
    "USER"
]`

But the offer type didn't change when I followed your steps to reproduce. Kindly let us know any other details that could help us reproduce this issue.

Thanks.

**Comment by samar-hassan** [comment]
While testing this, I added User specific offer in sandbox too, as mentioned earlier. Hence, the difference of 3 or 2 offer types isn't what's causing this. Is there any other change you made in the offer views?

<img width="879" alt="image" src="https://github.com/django-oscar/django-oscar/assets/88422175/d353fa5e-ba53-496f-aaa7-55eb89688823">

**Comment by kevinrenskers** [comment]
I don't think so, no. I really have no idea what's going on.

But we're in the process of migrating away from Oscar to a custom-built store, so feel free to close this issue since it's not reproducible and I seem to be the only one with this problem.
