### ISSUE TITLE
Django 4.2 Support

### ISSUE THREAD

**Issue by christopappas** [django-oscar/django-oscar#4149]
### Feature Request

Hi there,

A bit new to django-oscar here. I noticed in the code there is support for django 4.2, but it hasn't come out in an official release. I'm not sure if this counts as an official feature request, but wanted to raise it, as The People™️ (me, and likely many others) want this :) 

In the meantime, if there is an official release schedule you could point me to, that would also be very helpful!

Thank you for your time,
Chris

**Comment by srivardhan-rathore** [comment]
Ya, Please the Release the New Update that supports Django 4.2

**Comment by viggo-devries** [comment]
Just release the Alpha: https://github.com/django-oscar/django-oscar/releases/tag/3.2.1a
please test it out and let me know if you find any issues.
