### ISSUE TITLE
Offer's slug doesn't support unicode

### ISSUE THREAD

**Issue by alnuaimi94** [django-oscar/django-oscar#4152]
I gotten error when I visited offers page.
I'm use Arabic language.![image](https://github.com/django-oscar/django-oscar/assets/96056894/ab15cff6-536e-4bfb-82fd-7752abf06cef)

**Comment by alnuaimi94** [comment]
I fixed that by edit offer detail path from:

'python
path("<slug:slug>/", self.detail_view.as_view(), name="detail"),
'

To:

'python
path("<str:slug>/", self.detail_view.as_view(), name="detail"),
'

**Comment by specialunderwear** [comment]
You can make this work by configuring the following setting:
```
OSCAR_SLUG_ALLOW_UNICODE = True
```

**Comment by alnuaimi94** [comment]
> You can make this work by configuring the following setting:
> 
> ```
> 
> OSCAR_SLUG_ALLOW_UNICODE = True
> 
> ```
> 
> 
> 
> That fixed here: https://github.com/django-oscar/django-oscar/pull/1995
> 
> 
> 
> Hmm I think your issue is a bit different.

It's work only with product slug
