### ISSUE TITLE
Code too complex; So much unlogical

### ISSUE THREAD

**Issue by Bastilla123** [django-oscar/django-oscar#4162]
Hello i like this product very much but there are soooo much things in code which are not good, unlogical.

1. I have till yet no idea why you map url in apps.py which makes muuuuch more work then to use normal url.py. I see no advantage
2. Why you use not normal models.py and define models normal. Why you use a abstract class?
3. There are sooo much unlogical code. For example checkout/shipping-method/ there you post choose method. Why you not get this with get parameter? Strategy and Prices in partner this is a absolut blackhole why this code so is insert. 

For a beginner which have no experience with your product he has no chance to understand this code.

My wish was that you in next release you don't insert more feature. Please clean up code make it simpler and more readable..

Last thing you don't insert a complete integration of shipping methods and payment gateway in your product and link only to third level packages. To implement checkout process complete is not a easy task. This is unnecessary effort. Please integrate a standard paypal integration which works out of the box because i think near 100% of all customer want that paypal is activate...

P.S. i know several developer how tells me that i should forget django oscar and take another webshop framework which are easier to customize

**Comment by specialunderwear** [comment]
For a beginner, I think it would be very instructive to read the manual and try to determine which features correspond to the thing you don't understand. You might learn something.
