### ISSUE TITLE
variant: how to inherit some of the parent fields

### ISSUE THREAD

**Issue by Chrescht** [django-oscar/django-oscar#4190]
I am looking to setup a model for wine, and I'm wondering how to efficiently set up the variants.
There is a new variant every year having the same
- name
- wine type (red, rosé, white, ..)
but different
- grape varieties (cépage in French)
- price
- vintage

This is not an urgent oscar issue but I hope it's still is a valid question because of the parent inheritance.

**Technical details**

- Python version: 3.10.12
- Django version: 4.2.6
- Oscar version: 3.2.2

**Comment by viggo-devries** [comment]
Hi Christian,

The children inherit the attribute values from the parent.

If you fill these out in parent products and leave them empty in the child products they should appear on the detail page / in the filters.

**Comment by Chrescht** [comment]
Ok, perfect, thanks @viggo-devries 
I take it for the grape variety, since it's not a trivial attribute, I have to add a custom one?
E.g. it's several types of percentages adding up to 100%.

**Comment by viggo-devries** [comment]
You can add the “grape variety” attribute and fill it out on every child, if it’s filled it on the child it doesn’t look at it’s parents attribute value.

This way you can “override” the parents attributes

**Comment by specialunderwear** [comment]
Hi the issue reporter is for issues, if you need help please ask elsewhere.

**Comment by Chrescht** [comment]
A little harsh but I get it :-)
I did ask in the Google group but got no replies.
