### ISSUE TITLE
Promotions / Enhancements

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#424]
_Promotions could do with a round of enhancements.  This ticket is a work in progress to gather notes on things to do._

Notes:
- There is a `banner.html` template that doesn't seem to be used.  Also there's JS trying to initialise it.

Tasks:
- [ ] Make product lookups use AJAX and autocomplete in single product and multi-product dashboard forms
- [ ] Add support for banners
- [ ] Add support for countdown blocks
- [ ] Ensure promotions render correctly in sidebars
- [ ] Add support for tabbed blocks
- [ ] Review templates to ensure there isn't duplication that could be solved with partials.

**Comment by sasha0** [comment]
Closing this, since promotions being extracted into the separate package in terms of #2215
