### ISSUE TITLE
Must shown the Option value instead of Option code in thank you page showed products.

### ISSUE THREAD

**Issue by svandeneertwegh** [django-oscar/django-oscar#4263]
Found a bug? Please fill out the sections below.

### Issue Summary
When you are on the '/checkout/thank-you/' page, you see a list of products you bought. Normally when you used an option, the product name has '( option='optionvalue') in the string.
Problem is that the option= must be the option.value and not option.code.

For example on the basket page it does show good but only on the summary/thankyou page it does this issue.

### Technical details

* Python version: 3.11.8.
* Django version: 4.2.7.
* Oscar version: 3.2.4.

**Comment by SarthakNikhal** [comment]
Can I work on this issue?

**Comment by svandeneertwegh** [comment]
You may.
