### ISSUE TITLE
Styles/themes and Bootstrap5

### ISSUE THREAD

**Issue by aruytehno** [django-oscar/django-oscar#4300]
There is a suggestion to add support for themes/templates for quick styling of the project. Hours of searching on the Internet and on GitHub did not give quick results. Out of the box, there is only the usual template example of a store. Yes, this is a great solution for the team, but for those who want to deploy their own project in sollo, it can cause insurmountable difficulties. This could significantly increase oscar's popularity. Especially with the introduction of Bootstrap 5.

**Comment by GOUTHAM-2002** [comment]
Can i work on this ?

**Comment by samar-hassan** [comment]
@aruytehno @GOUTHAM-2002 please see if you can write a proposal for this feature before working on it, to make it more clear.
