### ISSUE TITLE
How to setup Featured Products in django-oscar

### ISSUE THREAD

**Issue by arunk** [django-oscar/django-oscar#4326]
Hi,
I'm asking this here, since the django-oscar Google Group appears to be inactive and full of spam. I'm trying to figure out the right way to add functionality to my django-oscar site so that certain Products can be flagged as Featured on the site. But I can't seem to find any existing field in the models that allow me to do this? So is the only way to achieve this by using a custom model and adding a featured boolean field to the model? Or am I missing something? I have tried going through the docs and the code, but haven't been able to find this field anywhere. Yet it seems like a fairly obvious field that should be required by most e-commerce setups.

Thanks,
arun

**Comment by samar-hassan** [comment]
Hi @arunk, you can use product attributes to store this information. You can also create a range containing the featured products. Ranges have their own pages in oscar as well.

**Comment by arunk** [comment]
Ok thanks @samar-hassan, I'll take a look at Product Attributes and Ranges.
