### ISSUE TITLE
Track product views to see most interested for example

### ISSUE THREAD

**Issue by svandeneertwegh** [django-oscar/django-oscar#4356]
Is there an option that the oscar saves a view accessed from a product so that we can analyse products and also show in the system what the latest 10 most viewed products are for example.

### Issue Summary

It currently only works with per user (with COOKIES)

### Technical details

* **3.11.10** Python version: Run `python --version`.
* **4.2.13**  Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* **4.0a1**   Oscar version: Look in your requirements.txt, or run `pip show django-oscar | grep Version`.

**Comment by joeyjurjens** [comment]
You mean?
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/signals.py#L3

https://django-oscar.readthedocs.io/en/3.1/ref/signals.html#product-viewed

**Comment by svandeneertwegh** [comment]
@joeyjurjens many thanks!
