### ISSUE TITLE
Featured checkbox

### ISSUE THREAD

**Issue by svandeneertwegh** [django-oscar/django-oscar#4358]
I would like to suggest a 'featured' checkbox on the first tab of an product editing.
So we can query on that, and show it to the people?

**Comment by joeyjurjens** [comment]
There are basically already two solutions for this;
1. Create a category "Featured" and add your product to this
2. Create a range with the products you want to feature. Ranges have a RangeDetailView: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/views.py#L55

**Comment by svandeneertwegh** [comment]
Hm. i thought to make a checkbox named "Featured?" in the product update options.

**Comment by svandeneertwegh** [comment]
I dont want to influence the categories with this

**Comment by joeyjurjens** [comment]
The beauty of oscar is, that you can fork an app and extend it to your liking. So also add extra fields to models. I personally don't think a featured checkbox should be added into the core. Did you try ranges? To see if that meets your needs?

**Comment by svandeneertwegh** [comment]
Yes. I will do that with a fork.
