### ISSUE TITLE
Price Range Facet No Longer Works After Update to 3.2.5

### ISSUE THREAD

**Issue by dismine** [django-oscar/django-oscar#4375]
### Issue Summary

After updating Django Oscar to version 3.2.5, the price range facet in search results stopped working correctly and shows "no matches" for all queries. This issue seems to stem from a discrepancy between the facet field name expected by Oscar and the field name generated by Haystack/Solr.

Here's the relevant configuration from `OSCAR_SEARCH_FACETS`:

```python
OSCAR_SEARCH_FACETS = {
    "fields": OrderedDict(
        [  
            ("product_class", {"name": _("Type"), "field": "product_class"}),
            ("rating", {"name": _("Rating"), "field": "rating"}),
        ]
    ),
    "queries": OrderedDict(
        [
            (
                "price_range",
                {
                    "name": _("Price range"),
                    "field": "price",
                    "queries": [
                        (_("0 to 250"), "[0 TO 250]"),
                        (_("250 to 500"), "[250 TO 500]"),
                        (_("500 to 1000"), "[500 TO 1000]"),
                        (_("1000 to 2000"), "[1000 TO 2000]"),
                        (_("2000+"), "[2000 TO *]"),
                    ],
                },
            ),
        ]
    ),
}
```

Upon investigating, I found that Haystack always generates a `price_exact` field for faceting, while Oscar expects the field to be `price`. When I switch to `price_exact` in `OSCAR_SEARCH_FACETS`, the reverse issue occurs — now the queries return results for `price`, but the context data preparation breaks in the final stage.

Example facet response:

```python
{'start_offset': 0, 'result_class': <class 'haystack.models.SearchResult'>, 'end_offset': 1, 'facets': {'product_class': {}, 'rating_exact': {}}, 'narrow_queries': {'price:([0 TO 250])'}, 'query_facets': [('price_exact', '[0 TO 250]'), ('price_exact', '[250 TO 500]'), ('price_exact', '[500 TO 1000]'), ('price_exact', '[1000 TO 2000]'), ('price_exact', '[2000 TO *]')]}
```

Example Solr request:

```
/solr/pshop-en/select/?q=(is_public:(true)+AND+structure:("standalone"+OR+"parent"))&fl=*+score&df=text&start=0&rows=1&spellcheck=true&spellcheck.collate=true&spellcheck.count=1&facet=on&facet.field=product_class&facet.field=rating_exact&facet.query=price_exact:[0+TO+250]&facet.query=price_exact:[250+TO+500]&facet.query=price_exact:[500+TO+1000]&facet.query=price_exact:[1000+TO+2000]&facet.query=price_exact:[2000+TO+*]&fq=django_ct:(catalogue.product)&fq=price:([0+TO+250])&wt=json
```

### Debugging

I believe the issue is related to how the `FacetMunger` class processes facet queries. Specifically, the mismatch between the `price` field in Oscar's search facets and the `price_exact` field generated by Haystack/Solr causes the final stage of context data preparation to fail.

Snippet from `FacetMunger`:
```python
def munge_query_facet(self, key, facet, clean_data):
    clean_data[key] = {"name": facet["name"], "results": []}
    # Loop over the queries in OSCAR_SEARCH_FACETS rather than the returned
    # facet information from the search backend.
    for field_value, query in facet["queries"]:
        field_name = facet["field"]
        is_faceted_already = field_name in self.selected_facets

        match = "%s:%s" % (field_name, query)
        if match not in self.facet_counts["queries"]: # Always not match because price_exact instead of price!!!
            # This query was not returned
            datum = {
                "name": field_value,
                "count": 0,
                "show_count": True,
                "disabled": True,
            }
        else:
            count = self.facet_counts["queries"][match]
            datum = {
                "name": field_value,
                "count": count,
                "show_count": not is_faceted_already,
                "disabled": count == 0 and not is_faceted_already,
                "selected": False,
            }
            if query in self.selected_facets.get(field_name, []):
                # Selected
                datum["selected"] = True
                datum["show_count"] = True
                url = self.base_url.remove_query_param("selected_facets", match)
                datum["deselect_url"] = self.strip_pagination(url)
            else:
                url = self.base_url.append_query_param("selected_facets", match)
                datum["select_url"] = self.strip_pagination(url)
        clean_data[key]["results"].append(datum)
```
#### Related Issue:
Even if the price range is disabled, Oscar doesn't filter out old `selected_facets` parameters from URLs. This can result in broken queries that trigger a Solr error:

```
HTTP 400: Invalid Number: [250 to 500] for field price_exact
```

This can happen if old URLs (e.g., from search indexing bots) still contain parameters related to previously valid facets, leading to unwanted Solr errors.

### Technical details

* Python version: 3.10.12.
* Django version: 4.2.16.
* Oscar version: 3.2.5.
* Haystack version: 3.3.0.
* Solr version: 9.6.

**Comment by gwaidacher** [comment]
Hi!

see https://github.com/django-oscar/django-oscar/pull/4187/files

I restored `field_name = "%s_exact" % facet["field"]` in `munge_query_facet` and the price_range reappered in my shop

**Comment by gwaidacher** [comment]
I sent a PR #4376 but the tests did not pass:

`INTERNALERROR>     THUMBNAIL_STORAGE = settings.STORAGES['default']['BACKEND']`
`INTERNALERROR> AttributeError: 'Settings' object has no attribute 'STORAGES'`

don't know how to fix that

**Comment by gwaidacher** [comment]
fyi #4376 was merged into master.

**Comment by joeyjurjens** [comment]
fixed in; https://github.com/django-oscar/django-oscar/pull/4376
