### ISSUE TITLE
Review use of HTTP in email templates

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#442]
The logic around whether to use 'http' or 'https' in templates is messy and spread around in several places.  Might be better to use a templatetag to consolidate.

**Comment by MatthewWilkes** [comment]
As the reset urls can only be used once by virtue of their tokens changing after use, I don't think this is so severe.

It looks like the password reset email sending gets its instruction to use https (or not) from the standard Django auth implementation, which passes on the state of the request that requests the reset, so we don't have that in other contexts; we'd have to duplicate the logic.

My (personal) opinion is that as there's no privilege escalation that can happen here. Protecting `store/password-reset/…` is just part of configuring TLS on your site. It'll only impact people that whitelist URLs inside the store as being HTTPS only *and* include the profile edit page but not the password reset page.

I'd say this is closable, as it's such a minor edge case, compared to the original ticket.

**Comment by maikhoepfel** [comment]
Thanks for having a look!
