### ISSUE TITLE
Rework promotions dashboard

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#465]
Needs some attention.  Things like:
- The breadcrumbs have inconsistent capitalisation
- Tabbed blocks need implementing
- Countdowns need implementing
- The process for picking products needs to use search, not dropdowns
- The HTML editor is terrible for creating links within the text

**Comment by sasha0** [comment]
Closing this, since promotions are being extracted into the separate package in terms of #2215
