### ISSUE TITLE
Review catalogue/stock import commands

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#486]
I think they are probably just misleading these days.  Need to either 
1. rewrite them to be universally useful
2. drop them

Nb, the sandbox still uses them to populate the site.
@gissues:{"order":28.571428571428562,"status":"backlog"}

**Comment by solarissmoke** [comment]
It is very difficult to make the importer "universal" because projects could have their own catalogue models. I think it's useful to have the importer there for people to see how they might import stuff themselves, but would leave it at that.
