### ISSUE TITLE
ImportError: Could not import settings 'frobshop.settings' (Is it on sys.path?): No module named oscar

### ISSUE THREAD

**Issue by nikolaysm** [django-oscar/django-oscar#494]
Someone tell me what could be the problem?

**Comment by thepythonist99** [comment]
Hi, I ran into that same problem and I figured out a step that was absent in the [getting started](http://django-oscar.readthedocs.org/en/latest/getting_started.html) part.
So I ran $ python setup.py install and everything worked well.
