### ISSUE TITLE
Anonymous checkout: email should be checked against registered customers

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#525]
When doing an anonymous checkout, it's possible to enter an email address that belongs to a registered user. This can easily happen with form fields pre-filled by the browser. 

I suggest validating against the existing user email addresses and, if it fails, suggesting that the user enter his password or request a new one.

I consider this a minor issue and just put it here to not forget.

**Comment by sasha0** [comment]
Closing since email check was already added to the `GatewayForm` some time ago.
