### ISSUE TITLE
Order status pipelines need docs

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#542]
Motivation:
- https://groups.google.com/forum/?fromgroups=#!topic/django-oscar/RILldxUBj2g
- https://groups.google.com/forum/?fromgroups=#!searchin/django-oscar/status/django-oscar/jbEzUGJ57g4/owY4SouAr-AJ
- https://groups.google.com/forum/?fromgroups=#!searchin/django-oscar/status/django-oscar/ZYXjif4VbvM/mM6DeMpqw9IJ

Detailed docs are required on how to implement a order processing pipeline.

Here's some user stories to consider
### Example 1

The site takes payment at checkout and so an order is created with a single payment event.  At this stage, all lines have status 'pending'

An admin can then use the dashboard to:
- Mark a subset of 'pending' lines as 'shipped'
- Mark a subset of 'shipped' lines as 'returned' (This could trigger an automatic refund)
### Example 2

The site takes only pre-authorises at checkout and so an order is created with a single payment event.  At this stage, all lines have status 'pending'

An admin can then use the dashboard to:
- Mark a subset of 'pending' lines as 'shipped'.  Before the shipping event is recorded, payment is attempted for the total of the selected lines plus any shipping costs (for the whole order) if this is the first batch to ship.
- Mark a subset of 'shipped' lines as 'returned' (This could trigger an automatic refund)
### Tasks
- [x] Correct the docs on the difference between line and order statuses
- [x] Add ability to manually set an order status in the order dashboard

**Comment by sasha0** [comment]
All should has been covered already. Note about difference between line and order statuses can be found in "Defining the order pipeline" chapter of "Getting started" doc.
