### ISSUE TITLE
Reviews app needs a thorough going over

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#590]
It has been messy for a while.  It was tidied up briefly by @codeinthehole as part of the 0.5 release push but there are still lots of things to sort out.
- Tidy up the review detail template and link it back into the main templates as a permanlink
- Make URL names consistent with rest of Oscar
- Make template names consistent with rest of Oscar
- When browsing reviews, the drop-down doesn't show the right value after it has been submitted. 
- I don't think the voting handling should be on the vote detail view.  These actions could be handled on a separate view class.

Possible feature: allow a 'manufacturer' response for negative reviews.  I suppose these would need to be added through the dashboard but should be relatively simple to implement.  See https://groups.google.com/forum/?fromgroups=#!topic/django-oscar/7kK33gdHB8c

**Comment by specialunderwear** [comment]
closing all issues that are no requests that don't have PR's attached.
