### ISSUE TITLE
[Blakey] Better support for dynamic pricing

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#599]
_WIP progress ticket to gather requirements to make Oscar work better with Tangent's internal Blakey product._

Things to improve:
- Support for products whose price is calculated at runtime using an external service.
- Support for product classes where the price is a function of the quantity (so you can't adjust the quantity on the basket page).
- Need to disable the quantity changing functionality on the basket page as this can change the price.

**Comment by jmound** [comment]
Any details about how to do this? Product price calculated at runtime via external service sounds relevant to me.

**Comment by lionaneesh** [comment]
Is there any documentation available on how to do this?

**Comment by kapil019** [comment]
Hi @codeinthehole How i can use dynamic pricing?
