### ISSUE TITLE
Using django-appconf to handle oscar's default settings

### ISSUE THREAD

**Issue by elbaschid** [django-oscar/django-oscar#606]
I just came across this project [jezdez/django-appconf](https://github.com/jezdez/django-appconf) that is used in [jezdez/django-compressor](https://github.com/jezdez/django-compressor) to handle the default configurations. Looking through the documentation this could be a pretty nice way of handling the config details in `default.py`. It seems like a good fit and I thought I put it up here for discussion. I can put up a branch with with a sample implementation for Oscar if this is worth investigating.

**Comment by sasha0** [comment]
I'm not sure if we still need to include additional external dependency for the default settings, which we had no issues with yet. What do you think @solarissmoke @craigloftus @mvantellingen ?

**Comment by solarissmoke** [comment]
It's not clear to me what the advantage of this appconf app is over what we currently do?

**Comment by sasha0** [comment]
It allows to put application-specific settings as `AppConf` class constants without prefix, which will be automatically added and allows to organize project settings in a certain way - https://github.com/django-compressor/django-compressor/blob/develop/compressor/conf.py#L10-L133.

I don't see significant improvements it could bring, but add external dependency. Hence, I personally don't find it essential to change how application settings organized. If we decide to revise them in the future - we can open a new issue. Thanks.
