### ISSUE TITLE
Would larger product images be better for mobile viewing?

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#643]
Quoting from https://groups.google.com/forum/?fromgroups=#!topic/django-oscar/7kK33gdHB8c

> Smaller devices would benefit from larger pictures 
> - See the mobile size for this Zurb Foundation template: http://foundation.zurb.com/page-templates4/store.html 
> - This is not a suggestion to switch the front-end Framework
> - These images respond well to browser resizing: http://teegallery.com
> - This site has a simple design and features: https://www.inventables.com

Is there an improvement we can make here by changing the image sizes?

**Comment by sasha0** [comment]
I believe we'd allow to control thumbnails size in the settings, rather than hardcoding into the templates. Thus, to be address during thumbnails revision in the #1408.
