### ISSUE TITLE
Font Awesome doesn't load

### ISSUE THREAD

**Issue by arturobermejo** [django-oscar/django-oscar#649]
- font-awesome.less
  @fontAwesomePath: '/static/oscar/fonts';
- dashboard.css
  @font-face {
  font-family: 'FontAwesome';
  src: url('/static/oscar/fonts/fontawesome-webfont.eot');
  src: url('/static/oscar/fonts/fontawesome-webfont.eot?#iefix') ....
  font-weight: normal;
  font-style: normal;
  }

This assume that my STATIC_ROOT is '/static/', then doesn't work when I change to another thing, for example /site_media/static/. Maybe it should be:

@fontAwesomePath: '../fonts';

**Comment by Abishek05** [comment]
I am facing this issue in production. Navbar fonts are not loading in production but works in local server.
So am i supposed to change the `@font-face src:url` ? 

change
```
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=3.2.1');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=3.2.1') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff?v=3.2.1') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=3.2.1') format('truetype'), url('../fonts/fontawesome-webfont.svg#fontawesomeregular?v=3.2.1') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
to 

```
@font-face {
  font-family: 'FontAwesome';
  src: url('/oscar/fonts/fontawesome-webfont.eot?v=3.2.1');
  src: url('/oscar/fonts/fontawesome-webfont.eot?#iefix&v=3.2.1') format('embedded-opentype'), url('/oscar/fonts/fontawesome-webfont.woff?v=3.2.1') format('woff'), url('/oscar/fonts/fontawesome-webfont.ttf?v=3.2.1') format('truetype'), url('/oscar/fonts/fontawesome-webfont.svg#fontawesomeregular?v=3.2.1') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by makspll** [comment]
The link to the solution doesn't exist anymore, facing the same issue when offline compression is on.
