### ISSUE TITLE
Template redundancy in dashboard

### ISSUE THREAD

**Issue by maiksprenger** [django-oscar/django-oscar#654]
A quick glance at dashboard views shows there's a bit of duplication in templates and views that should be easy to reduce with employing one level of template inheritance and using PageTitleMixin. Quite similar to what happened in https://github.com/tangentlabs/django-oscar/commit/c3a546100b7c523012bd747c6bf9a3d18414c05e, really.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
