### ISSUE TITLE
Non abstract Benefit model with unique proxy_class is hard to modify or extend

### ISSUE THREAD

**Issue by riklaunim** [django-oscar/django-oscar#685]
offer/Benefit is a non abstract model so it can't be overridden/extended by overriding the application and making some new migrations for locally changed Benefit model. Second problem is unique proxy_class which prevents adding more than one Voucher with custom proxy_class (and  I have to set them as... Benefit is not abstract).

I've make manual migration to remove the unique from proxy_class and now I can use multiple vouchers with a proxy class ("most expensive for free") for different product sets with no problems. So the question is why Benefit model is done as it is? Why it is non-abstract and why proxy_class is unique?

**Comment by maikhoepfel** [comment]
I found time to make a PR in #1940

**Comment by maikhoepfel** [comment]
FYI, you can use @specialunderwear's [mean class hack](https://gist.github.com/specialunderwear/9d917ddacf3547b646ba) to remove the uniqueness constraint until my PR is merged.

**Comment by ckepper** [comment]
Why does the unique constraint still apply to the Condition class? Can it be removed from this one as well?

**Comment by sasha0** [comment]
@ckepper let's create a new issue for this.
