### ISSUE TITLE
OSCAR_REQUIRED_ADDRESS_FIELDS in default: city is line4

### ISSUE THREAD

**Issue by raimonesteve** [django-oscar/django-oscar#713]
City in address model is line4 field. Not required in address form:

https://github.com/raimonesteve/django-oscar/commit/5177c9443b995ef3c28f1d047ce8c0a530b2af1c

**Comment by Tyrdall** [comment]
@codeinthehole Can you also change it in the docs? https://github.com/django-oscar/django-oscar/blob/master/docs/source/ref/settings.rst#oscar_required_address_fields

**Comment by SalahAdDin** [comment]
Was this pull request merged?

**Comment by sasha0** [comment]
@Tyrdall please open new issue for your request. Thanks.
