### ISSUE TITLE
Allow fine-grained control of Country order in dropdowns

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#720]
This is related to https://github.com/tangentlabs/django-oscar/pull/699

We should change the `is_highlighted` field of the `AbstractCountry` model to be an integer field so that the order that countries appear in dropdowns can be controlled.  At the moment, countries can be "highlighted" so that they appear first but this might not be right in some circumstances.  Eg, if both Canada and the USA are hightlighted, Canada will always come first when you might want the US first.

Changing the field to an integer will provide more fine-grained control.  

We should also change the address forms (in checkout and accounts) to set the initial country to the first result (rather than the blank `---------` option).

**Comment by NerdPraise** [comment]
Based on this, how does one then make a country instance the default country for both useraddress, shippingaddress and partneraddress
