### ISSUE TITLE
Make sure that checkout always shows options to login/or type in email first

### ISSUE THREAD

**Issue by mmoravcik** [django-oscar/django-oscar#721]
At the moment, once email address is set, checkout is skipping the login option and goes straight to the shipping address details

We need to keep this step in, with pre populated email address

**Comment by MARUTHESH** [comment]
I just added OSCAR_ALLOW_ANON_CHECKOUT = True in my setting.py file, even after it redirects me to the login page when I click Proceed to Checkout button, I don't understand what is wrong with this, someone please help me out.
