### ISSUE TITLE
How can I enable faceted search with django-oscar ? [ Documentation missing ]

### ISSUE THREAD

**Issue by yugaljindle** [django-oscar/django-oscar#749]
I am very new to Oscar, I have been trying to use the builtin support for faceted search for my Oscar project but I have no clue (can't find any documentation).

I have : 
- My elastic search running at port 9200
- Haystack settings :

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    },
}
- I was able to index my catalogue successfully with `python manage.py rebuild_index`

But my /search/ page still lists only categories to click through. I digged in deeper into the views.py in search app (from oscar) and found its MultiFacetedSearchView is rendering 'search/results.html'

And 'search/results.html' seems to be looping over categories and rendering categories only. Nothing related to faceted search.

I don't know if i am missing something or what ?
How should I enable faceted search for my catelogue ? [ If its a 1 step process ]
Even if its not a 1 step process, then can you link me to some code snippets or documentation ( I was enable to find any ) ?

**Comment by kishan3** [comment]
HI guys I am working on Products listing using django oscar. There are some filters(ex. year, price range etc) I want to apply them to products lists. Can I use facets for this functionality ??

**Comment by aef-** [comment]
StackOverflow/Google Groups are better places to ask these types of questions but check out:
http://django-oscar.readthedocs.org/en/latest/ref/settings.html?highlight=oscar_search_facet#oscar-search-facets
and
https://github.com/django-oscar/django-oscar/blob/master/sites/sandbox/deploy/solr/schema.xml#L148
