### ISSUE TITLE
Replace WYSIWYG editor

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#757]
Oscar currently uses the bootstrap-wysiwyg HTML editor.  However, this is causing a number of problems.  

For example, it doesn't support IE7 which is a requirement for lots of Tangent projects (sadly).

Related tickets:
- https://github.com/tangentlabs/django-oscar/issues/730
- https://github.com/tangentlabs/django-oscar/issues/344

**Comment by elipavlov** [comment]
Hello.
There is any resolutions for this issue?
As I understand CKEditor didn't be integrated.

**Comment by solarissmoke** [comment]
Yes - see the commit that closed this issue. We switched to using TinyMCE.
