### ISSUE TITLE
Reviews reworking

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#774]
Reviews is messy and needs some attention.  Here are some notes:
- [x] We don't need to two forms for anon and normal users.  This could be more elegantly solved with a single form taking the user as the first `__init__` arg.
- [x] Needless validation logic in model `save` method
- [x] Voting should be in its own views, not mingled with the review detail view (I think).
- [x] Voting methods should be on the review model directly.
- [x] Some methods should be properties.

**Comment by sasha0** [comment]
Voting methods are already in the review model directly, which was the last outstanding item.
