### ISSUE TITLE
Offers incentives don't require a value

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#778]
While trying to recreate #703, I managed to create incentives without a value. 
![screenshot from 2013-08-02 09 45 33](https://f.cloud.github.com/assets/509427/899871/22099302-fb50-11e2-9871-1b1a50d04742.png)

It seems to work only for the two percentage-based incentive types.

**Comment by sasha0** [comment]
Closing, since per 8fa4e093b32ea154ee7a966ee9b4e4e3b11a2efa it's not available to create percentage discount benefits any more.
