### ISSUE TITLE
It's hard to add extra context variables into emails

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#783]
Example: I want to have a setting for a contact phone number that I can use in all email templates.  

One potential solution would be to use template context processors but these only work if you use a `RequestContext` instance.  The `get_messages` method within uses a normal `Context` instance which is correct as the request won't always be available when messages are sent from offline processes.

Not sure on the best approach.  Maybe another settings of context variables for email templates.

**Comment by Habu-Kagumba** [comment]
Was a solution ever found for this? @codeinthehole

**Comment by sasha0** [comment]
Should definitely be part of #319.

**Comment by solarissmoke** [comment]
This will be addressed in #2591.

**Comment by kevinrenskers** [comment]
I'm sorry to be commenting on such an old issue, but how exactly has this been addressed? I see the code where the email is sent, with the extra context: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/checkout/mixins.py#L267-L278. But when I create an email template in the database with the code `ORDER_PLACED` and I want to use new context values.. how do I actually extend the context?
