### ISSUE TITLE
Improve score handling for ratings

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#798]
http://www.evanmiller.org/how-not-to-sort-by-average-rating.html

I don't see why this shouldn't be used. Python implementation suggested here: https://gist.github.com/mattdennewitz/226309

**Comment by solarissmoke** [comment]
Closing on the basis that we don't do any sort of ranking by ratings any more in core. `TopScoredReviewsManager` related logic was dropped in Oscar 1.2. Projects that wish to incorporate ratings can override `analytics.scores.Calculator`.
