### ISSUE TITLE
Oscar's docs need a glossary

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#800]
I'm sick of explaining what a fulfilment partner is.

**Comment by 9gix** [comment]
@codeinthehole I'm still confused with one of the sentences in the fulfilment partner reference. "[Many Oscar deployments will only have one fulfillment partner.](http://django-oscar.readthedocs.org/en/latest/ref/apps/partner.html#oscar.apps.partner.abstract_models.AbstractPartner)". I'm not sure why this is true. Who is the one **usually** being the fulfilment partner? Is it **usually** the shop owner themselves? 
Then why not giving a default value for the fulfilment partner then? (i.e. the "owner" being the instance of fulfilment partner).
