### ISSUE TITLE
ShippingMethodView should be a FormView

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#808]
At the moment, the checkout `ShippingMethodView` is a `TemplateView` which overrides the `post` method and looks for a certain posted param to determine which shipping method is selected.  

I think this would be better as a standard Django `FormView` as:
- More conventional, easier to understand
- Easier to extend by supplying a custom form class
- Easier to hook into the success action (eg using `form_valid`)

**Comment by sasha0** [comment]
@codeinthehole Done, PR #1781

**Comment by sasha0** [comment]
Fixed in #1781.
