### ISSUE TITLE
URL fields need a rethink

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#824]
There are model and form fields that handle internal as well as external URLs.  They need reviewing and possibly deleting.

Notes:
- Content blocks can only link to internal pages - we should use a different type of field for this (one that doesn't allow external URLs).
- Need to ensure we are correctly using (or not using) `verify_exists`

**Comment by sasha0** [comment]
* promotion models use `ExtendedURLField` which already does have internal URL validator.
* `verify_exists` argument support was dropped in Oscar 1.5.
