### ISSUE TITLE
Extend basket view to use default shipping address

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#827]
The basket summary view attempts to look up a default shipping method so an indicative order total can be displayed.  The checkout allows the method to be changed later on though.

At the basket stage, we don't know the user's chosen shipping address so we don't pass it.  However, Oscar does have a concept of default shipping address.  We should extend the basket view to pass the user's default shipping address (if one is known).

**Comment by naringas** [comment]
> pass where ?

right here https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/shipping/methods.py#L33
how would I calculate the shipping charge, without knowing the address?
