### ISSUE TITLE
Text input fields are often too wide

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#851]
See for example the wishlist line form:

![image](https://f.cloud.github.com/assets/80975/1225959/8ea0ed14-2777-11e3-8baa-0aa2ac0e3ea8.png)

The quantity field is too wide.  This is tricky to change within the Django form declarations since any `size` attribute gets clobbered by a `width=206px` setting in the LESS files. 

Can we adjust the LESS so that we can manually control input sizes?

**Comment by sasha0** [comment]
Already fixed by fcddaececf4d30fa8588f72812338e551efea056.
