### ISSUE TITLE
Wishlists: merge list/detail pages

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#852]
Tangent's UX team has suggested it would be better to merge the wishlist list and detail pages that currently sit within the accounts section.  The page would still be a list view but would also show the contents of each wishlist in a table underneath.  This would streamline things nicely.

**Comment by sasha0** [comment]
I don't think it now tangible improvement at the current state. Nowadays it's already common practice to build interactive UI for this use-case on top of ReactJS/VueJS/etc and RESTful API, rather than on top of classic views. WDYT @solarissmoke @mvantellingen @craigloftus ?

**Comment by solarissmoke** [comment]
I have a different opinion and feel that Oscar should provide a set of working "classic" views. I don't think it is good for the project if we expect a developer to have to implement the whole dashboard themselves using an API (unless we are going to provide a working base dashboard built on React/Vue/etc). So I'd leave this open.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
