### ISSUE TITLE
Wishlists: remove from account section

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#853]
Wishlist probably don't belong in the customer account section.  Better to have them sit along side the basket in terms of site nav and breadcrumbs.  This would require a new link to the wishlist to appear in the top header of the page.  This link to your wishlist should only appear if you actually have one.

**Comment by sasha0** [comment]
I think it can still remain as is for now - it's not supposed to be used so often, as mini basket widget.
