### ISSUE TITLE
Decide if reviews should exist without products

### ISSUE THREAD

**Issue by maikhoepfel** [django-oscar/django-oscar#862]
There's an [unresolved discussion](https://groups.google.com/forum/#!msg/django-oscar/1gur_QmbgzY/W2_MOW906cMJ) about whether reviews should be deleted when the product is deleted. This issue has been added to track it.

If it is decided that reviews can live on their own, it should be ensured that the dashboard handles that case okay. The related issue #836 has been fixed now.

**Comment by sasha0** [comment]
I also personally don't see reason why to keep reviews after product removal.
