### ISSUE TITLE
Checkout address handling

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#886]
There are a few minor issues around address handling in the checkout that need addressing.  These mainly arise when shipping to two different territories where the address form is different for each one.
- It should be possible to edit the list of address book addresses shown.  Eg when shipping within US, only show US addresses
- Editing an existing address should use a similar form to the shipping address form.  Eg customisation to the main shipping address form should be reflected on the user address form too.

**Comment by sasha0** [comment]
> It should be possible to edit the list of address book addresses shown. Eg when shipping within US, only show US addresses

It can be easily customized in `ShippingAddressView.get_available_addresses` method which user addresses to display in the current checkout session.

> Editing an existing address should use a similar form to the shipping address form. Eg customisation to the main shipping address form should be reflected on the user address form too.

User address and shipping address forms inherit the same base address form, which also requires mandatory address fields to be defined (per `OSCAR_REQUIRED_ADDRESS_FIELDS` setting). Thus, if both models have the same custom field - we can just add it to the setting. At the same time, forms also allow to specify fields per form, which allows to use fields, specific only for shipping or user address model which also provides enough of flexibility.

Ultimately, both minor issues can be easily addressed by customization, which should be sufficient for now.
