### ISSUE TITLE
Namespace Oscar's request attributes

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#979]
See https://groups.google.com/d/msgid/django-oscar/527FF90A.1030303%40tangentsnowball.com.au

The `strategy` attribute that Oscar sets clashes with python-social-auth which also tries to set the same attribute.  We should use a `oscar` namespace dict/namedtuple to house the strategy and, later, the basket instances.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
