### ISSUE TITLE
Better RTL support

### ISSUE THREAD

**Issue by alinik** [django-oscar/django-oscar#986]
The default templates does not support right to left language correctly.
in most cases adding {% if LANGUAGE_BIDI %}dir="rtl"{% endif %} to html tag.
but sometimes need more work.

**Comment by pwalsh** [comment]
I think the focus should go into getting the dashboard with RTL support, using whatever tricks bootstrap provides to do it. 

The frontend templates are less interesting in my opinion - my general perspective is that they are at best a point of reference for doing your own frontends for Oscar.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests that don't have PR's attached.
