### ISSUE TITLE
Clarify how Braintree payments are integrated

### ISSUE THREAD

**Issue by DrMeers** [django-oscar/django-oscar#995]
`how_to_integrate_payment.rst` states "This is the type of payment source used (eg PayPal, DataCash, BrainTree)", however I cannot find any other references to "Braintree" in the repository. I can see plenty of other "django-oscar-paypal/stripe/eway/etc" repositories, but no `django-oscar-braintree` -- has Braintree support been integrated yet?

**Comment by psychok7** [comment]
Are there any updates regarding Braintree integration??

**Comment by maikhoepfel** [comment]
Not that I'm aware of, no. This seems to be confusing, so I removed any mention of BrainTree in https://github.com/django-oscar/django-oscar/commit/effdc77b92caefa8f56cb5ae10a4c8b1eb1e663a. 

If this is a necessary requirement for you, you are free to write your own extension, or we're happy to explore options. In that case, please get in touch.
